package totah.lab.prometheus.neural;

import java.util.List;
import java.util.Objects;
import totah.lab.prometheus.molecular.Molecule;
import totah.lab.prometheus.numerics.DirectionalSecondOrderJet;
import totah.lab.prometheus.variational.ParameterVector;
import totah.lab.prometheus.variational.QuantumCoordinates;
import totah.lab.prometheus.variational.force.GeneralMolecularSpaceWarp;

/** Fused all-nucleus/all-Cartesian differential-SWCT graph for the general Slater-Jastrow state. */
public final class GeneralSlaterJastrowDirectionalEvaluator {
    public Evaluation evaluate(Molecule molecule,ParameterVector parameters,QuantumCoordinates coordinates){Objects.requireNonNull(molecule);Objects.requireNonNull(parameters);Objects.requireNonNull(coordinates);if(coordinates.particles().size()!=molecule.electrons().value())throw new IllegalArgumentException("electron count mismatch");for(int i=0;i<coordinates.particles().size();i++){var expected=i<molecule.spin().alphaElectrons()?totah.lab.prometheus.variational.SpinProjection.ALPHA:totah.lab.prometheus.variational.SpinProjection.BETA;if(coordinates.particles().get(i).spin()!=expected)throw new IllegalArgumentException("electrons must be ordered alpha then beta");}int ne=coordinates.particles().size(),nn=molecule.nuclei().size(),spatial=3*ne,directions=6*nn,orbitals=Math.max(molecule.spin().alphaElectrons(),molecule.spin().betaElectrons());if(parameters.values().size()!=orbitals+1)throw new IllegalArgumentException("general state parameter count mismatch");double[][] weights=new double[ne][nn];double[] divergence=new double[3*nn];for(int i=0;i<ne;i++)for(int a=0;a<nn;a++){var w=GeneralMolecularSpaceWarp.weight(molecule,coordinates.particles().get(i),a);weights[i][a]=w.value();for(int axis=0;axis<3;axis++)divergence[3*a+axis]+=w.derivative(axis);}
        DirectionalSecondOrderJet[][] electron=new DirectionalSecondOrderJet[ne][3];for(int i=0;i<ne;i++){var e=coordinates.particles().get(i);double[] v={e.xBohr(),e.yBohr(),e.zBohr()};for(int axis=0;axis<3;axis++){double[] tangent=new double[directions];for(int a=0;a<nn;a++)tangent[total(a,axis)]=weights[i][a];electron[i][axis]=DirectionalSecondOrderJet.spatialVariable(v[axis],spatial,3*i+axis,tangent);}}
        DirectionalSecondOrderJet[][] nuclei=new DirectionalSecondOrderJet[nn][3];for(int a=0;a<nn;a++){var p=molecule.nuclei().get(a).position().inBohr();double[] v={p.x(),p.y(),p.z()};for(int axis=0;axis<3;axis++){double[] tangent=new double[directions];tangent[total(a,axis)]=1;tangent[bare(a,axis)]=1;nuclei[a][axis]=DirectionalSecondOrderJet.variable(v[axis],spatial,tangent);}}
        DirectionalSecondOrderJet alpha=determinant(matrix(molecule,parameters,electron,nuclei,0,molecule.spin().alphaElectrons(),spatial,directions),spatial,directions),beta=determinant(matrix(molecule,parameters,electron,nuclei,molecule.spin().alphaElectrons(),molecule.spin().betaElectrons(),spatial,directions),spatial,directions);DirectionalSecondOrderJet j=DirectionalSecondOrderJet.constant(0,spatial,directions);double b=parameters.values().getLast();for(int i=0;i<ne;i++)for(int k=i+1;k<ne;k++){var r=distance(electron[i][0].subtract(electron[k][0]),electron[i][1].subtract(electron[k][1]),electron[i][2].subtract(electron[k][2]));double cusp=coordinates.particles().get(i).spin()==coordinates.particles().get(k).spin()?.25:.5;j=j.add(r.multiply(cusp).divide(r.multiply(b).add(1)));}DirectionalSecondOrderJet psi=alpha.multiply(beta).multiply(j.exp());
        DirectionalSecondOrderJet potential=DirectionalSecondOrderJet.constant(0,spatial,directions);for(int i=0;i<ne;i++)for(int a=0;a<nn;a++)potential=potential.add(distance(electron[i][0].subtract(nuclei[a][0]),electron[i][1].subtract(nuclei[a][1]),electron[i][2].subtract(nuclei[a][2])).reciprocal().multiply(-molecule.nuclei().get(a).charge().atomicNumber()));for(int i=0;i<ne;i++)for(int k=i+1;k<ne;k++)potential=potential.add(distance(electron[i][0].subtract(electron[k][0]),electron[i][1].subtract(electron[k][1]),electron[i][2].subtract(electron[k][2])).reciprocal());for(int a=0;a<nn;a++)for(int c=a+1;c<nn;c++)potential=potential.add(distance(nuclei[a][0].subtract(nuclei[c][0]),nuclei[a][1].subtract(nuclei[c][1]),nuclei[a][2].subtract(nuclei[c][2])).reciprocal().multiply(molecule.nuclei().get(a).charge().atomicNumber()*molecule.nuclei().get(c).charge().atomicNumber()));
        double[] dPsi=new double[directions],dLap=new double[directions],dPotential=new double[directions];for(int d=0;d<directions;d++){dPsi[d]=psi.directionalDerivative(d);dLap[d]=psi.laplacianDirectionalDerivative(d,spatial);dPotential[d]=potential.directionalDerivative(d);}return new Evaluation(psi.value(),psi.laplacian(spatial),potential.value(),dPsi,dLap,dPotential,divergence,1,1);
    }
    private static DirectionalSecondOrderJet[][] matrix(Molecule molecule,ParameterVector p,DirectionalSecondOrderJet[][] e,DirectionalSecondOrderJet[][] n,int offset,int count,int spatial,int directions){DirectionalSecondOrderJet[][] m=new DirectionalSecondOrderJet[count][count];for(int i=0;i<count;i++)for(int o=0;o<count;o++){DirectionalSecondOrderJet value=DirectionalSecondOrderJet.constant(0,spatial,directions);for(int a=0;a<n.length;a++){var x=e[offset+i][0].subtract(n[a][0]);var y=e[offset+i][1].subtract(n[a][1]);var z=e[offset+i][2].subtract(n[a][2]);var r=distance(x,y,z);value=value.add(polynomial(o,x,y,z,r,spatial,directions).multiply(r.multiply(-p.values().get(o)).exp()).multiply(molecule.nuclei().get(a).charge().atomicNumber()));}m[i][o]=value;}return m;}
    private static DirectionalSecondOrderJet polynomial(int o,DirectionalSecondOrderJet x,DirectionalSecondOrderJet y,DirectionalSecondOrderJet z,DirectionalSecondOrderJet r,int spatial,int directions){return switch(o%10){case 0->DirectionalSecondOrderJet.constant(1,spatial,directions);case 1->x;case 2->y;case 3->z;case 4->r;case 5->x.multiply(y);case 6->x.multiply(z);case 7->y.multiply(z);case 8->x.multiply(x).add(y.multiply(y)).add(z.multiply(z));default->x.multiply(x).subtract(y.multiply(y));};}
    private static DirectionalSecondOrderJet determinant(DirectionalSecondOrderJet[][] input,int spatial,int directions){int n=input.length;if(n==0)return DirectionalSecondOrderJet.constant(1,spatial,directions);var a=new DirectionalSecondOrderJet[n][n];for(int i=0;i<n;i++)a[i]=input[i].clone();var det=DirectionalSecondOrderJet.constant(1,spatial,directions);int sign=1;for(int k=0;k<n;k++){int pivot=k;for(int i=k+1;i<n;i++)if(Math.abs(a[i][k].value())>Math.abs(a[pivot][k].value()))pivot=i;if(Math.abs(a[pivot][k].value())<1e-14)throw new IllegalArgumentException("singular Slater determinant");if(pivot!=k){var row=a[k];a[k]=a[pivot];a[pivot]=row;sign=-sign;}var q=a[k][k];det=det.multiply(q);for(int i=k+1;i<n;i++){var factor=a[i][k].divide(q);for(int c=k+1;c<n;c++)a[i][c]=a[i][c].subtract(factor.multiply(a[k][c]));}}return det.multiply(sign);}
    private static DirectionalSecondOrderJet distance(DirectionalSecondOrderJet x,DirectionalSecondOrderJet y,DirectionalSecondOrderJet z){return x.multiply(x).add(y.multiply(y)).add(z.multiply(z)).sqrt();}
    public static int total(int nucleus,int axis){return 6*nucleus+axis;}public static int bare(int nucleus,int axis){return 6*nucleus+3+axis;}
    public record Evaluation(double value,double electronicLaplacian,double potential,double[] valueDirectionalDerivatives,double[] laplacianDirectionalDerivatives,double[] potentialDirectionalDerivatives,double[] warpDivergence,int directionalAdPasses,int stateTraversals){public Evaluation{valueDirectionalDerivatives=valueDirectionalDerivatives.clone();laplacianDirectionalDerivatives=laplacianDirectionalDerivatives.clone();potentialDirectionalDerivatives=potentialDirectionalDerivatives.clone();warpDivergence=warpDivergence.clone();}@Override public double[] valueDirectionalDerivatives(){return valueDirectionalDerivatives.clone();}@Override public double[] laplacianDirectionalDerivatives(){return laplacianDirectionalDerivatives.clone();}@Override public double[] potentialDirectionalDerivatives(){return potentialDirectionalDerivatives.clone();}@Override public double[] warpDivergence(){return warpDivergence.clone();}}
}
