package totah.lab.prometheus.numerics;

import java.util.List;

/** Fixed SPD preconditioners used by the locked matrix-free SR experiment. */
public final class FixedPreconditioners {
    private FixedPreconditioners(){ }
    public static Preconditioner identity(int dimension){return new Preconditioner(){public int dimension(){return dimension;}public double[] apply(double[] residual){return residual.clone();}public String identity(){return "NONE";}};}
    public static Preconditioner diagonal(double[] diagonal){double[] copy=diagonal.clone();for(double value:copy)if(!(value>0))throw new IllegalArgumentException("positive diagonal required");return new Preconditioner(){public int dimension(){return copy.length;}public double[] apply(double[] residual){double[] result=new double[copy.length];for(int i=0;i<result.length;i++)result[i]=residual[i]/copy[i];return result;}public String identity(){return "DIAGONAL";}};}
    public static Preconditioner blocks(int dimension,List<Block> blocks){List<Block> copy=List.copyOf(blocks);boolean[] seen=new boolean[dimension];for(Block block:copy){for(int i=block.start;i<block.end;i++){if(i<0||i>=dimension||seen[i])throw new IllegalArgumentException("invalid block partition");seen[i]=true;}}for(boolean value:seen)if(!value)throw new IllegalArgumentException("blocks must cover dimension");return new Preconditioner(){public int dimension(){return dimension;}public double[] apply(double[] residual){double[] result=new double[dimension];for(Block block:copy){double[] rhs=new double[block.end-block.start];System.arraycopy(residual,block.start,rhs,0,rhs.length);double[] solved=solve(block.matrix,rhs);System.arraycopy(solved,0,result,block.start,solved.length);}return result;}public String identity(){return "BLOCK_BY_WAVEFUNCTION_COMPONENT";}};}
    public record Block(int start,int end,double[][] matrix){public Block{matrix=copy(matrix);if(end<=start||matrix.length!=end-start)throw new IllegalArgumentException("block dimensions disagree");for(double[] row:matrix)if(row.length!=matrix.length)throw new IllegalArgumentException("square block required");}@Override public double[][] matrix(){return copy(matrix);}}
    private static double[] solve(double[][] matrix,double[] rhs){int n=rhs.length;double[][] a=new double[n][n+1];for(int i=0;i<n;i++){System.arraycopy(matrix[i],0,a[i],0,n);a[i][n]=rhs[i];}for(int p=0;p<n;p++){int selected=p;for(int r=p+1;r<n;r++)if(Math.abs(a[r][p])>Math.abs(a[selected][p]))selected=r;double[] swap=a[p];a[p]=a[selected];a[selected]=swap;if(Math.abs(a[p][p])<1e-15)throw new IllegalArgumentException("singular preconditioner block");for(int r=p+1;r<n;r++){double factor=a[r][p]/a[p][p];for(int c=p;c<=n;c++)a[r][c]-=factor*a[p][c];}}double[] x=new double[n];for(int r=n-1;r>=0;r--){double value=a[r][n];for(int c=r+1;c<n;c++)value-=a[r][c]*x[c];x[r]=value/a[r][r];}return x;}
    private static double[][] copy(double[][] matrix){double[][] result=new double[matrix.length][];for(int i=0;i<matrix.length;i++)result[i]=matrix[i].clone();return result;}
}
