from pathlib import Path
import json,copy,hashlib
root=Path('software/modules/athena/src/main/resources/totah/lab/athena/system/rules')
m=json.loads(next((root/'groups-f08-v1').glob('*.json')).read_text());d=json.loads(m['parameters']['definition']['value'])
p=Path('software/qualification/scientific-rule-knowledge-audit-20261004/reference/wwpdb-xray.txt');refs=[{'kind':'SOURCE','namespace':'athena.foundation','id':str(p),'version':hashlib.sha256(p.read_bytes()).hexdigest()}]
rid='ATHENA.GROUP.ALPHA_PEPTIDE_LINK.SOURCE_CONNECTIVITY'
d.update(groupId=rid,patternId=rid+'/pattern',query='[N;!a]-[C;!a;X4;+0]-[C;!a;X3;+0](=[O;X1;+0])-[N;!a;X3;+0]-[C;!a;X4;+0]-[C;!a;X3;+0](=[O;X1;+0])',memberQueryIndices=list(range(8)),roles={'N1':[0],'CA1':[1],'C1':[2],'O1':[3],'N2':[4],'CA2':[5],'C2':[6],'O2':[7]},sourceReferences=refs,negativeCoverageVersion=rid+'/negative/1',occurrenceExclusions=[])
d['requiredState'].update(hydrogenElements=['C','N','O'],hydrogenRoles=[{'role':'C1','count':0},{'role':'O1','count':0},{'role':'O2','count':0}],roleHeavyDegree={'C1':3,'O1':1,'O2':1})
d['limitations']=['Exact supplied alpha-amino-carbonyl / neutral amide / alpha-carbon-carbonyl connectivity; no sequence name, L/D, stereochemistry, trans preference or biological validity inferred.','Glycine, substituted alpha carbons, proline-like N-ring substitution, and cyclic peptide connectivity are not excluded. Non-alpha backbones and charged/resonance-alternate peptide bonds need separately defined roles, not silent normalization.']
m.update(ruleId=rid,limitations=d['limitations']);m['negativeCoverage']['version']=d['negativeCoverageVersion'];m['parameters']['definition']['value']=json.dumps(d,sort_keys=True,separators=(',',':'));m['scientificSources']=[{'locator':str(p),'sha256':refs[0]['version'],'citation':'wwPDB X-ray validation guide, chirality/planarity section, peptide omega definition (snapshot lines1954-1958). Exact source peptide roles required; residue names alone do not establish connectivity.'}]
out=root/'peptide-geometry-v1';out.mkdir(exist_ok=True);(out/(rid+'.rule.json')).write_text(json.dumps(m,indent=2)+'\n')
group=copy.deepcopy(m)
parent=json.loads((root/'cysteine-backbone-b06/ATHENA.SULF.CYSTEINE_BACKBONE_ATTRIBUTION.rule.json').read_text());geometry=parent['parameters']['geometryManifest']
m=copy.deepcopy(group);m.update(ruleId='ATHENA.VAL.PEPTIDE_OMEGA.SOURCE_ALPHA_LINK',profile='ATHENA_PEPTIDE_OMEGA_V1',implementationId='athena.peptide-geometry',implementationVersion='1',family='VALIDATOR',tier='V12',measurementsProduced={'continuousGeometry':'athena-continuous-geometry/1'},requiredChemistry=['Verified exact source alpha-peptide group roles with authoritative H/charge/mapping'],requiredGeometry=['Complete finite common-frame selected CA1-C1-N2-CA2 torsion'])
m['parameters']={'sourceManifest':{'value':json.dumps(group,sort_keys=True,separators=(',',':')),'unit':'policy','definition':'qualified source-role definition'},'geometryManifest':geometry,'cisTransToleranceDegrees':{'value':'30.0','unit':'degree','definition':'Pinned wwPDB X-ray guide peptide planarity: deviation more than30 degrees from0/180'}}
m['negativeCoverage']={'version':'ATHENA.VAL.PEPTIDE_OMEGA.SOURCE_ALPHA_LINK/negative/1','requirements':['EXACT_SOURCE_ROLE_TUPLE','ALL_CORRESPONDENCES_AGREE','FINITE_COMMON_FRAME_TORSION'],'incompleteStatus':'UNKNOWN_INCONCLUSIVE','supportedDomain':'Exact supplied source alpha-peptide selected tuple only','scope':'One explicitly requested CA1-C1-N2-CA2 tuple; not complete protein absence'}
m['limitations']=['Selected source alpha-peptide omega only; not a universal backbone validator.','CIS_WINDOW: absolute omega<=30; TRANS_WINDOW: 180-absolute omega<=30; otherwise TWISTED_OUTSIDE_WINDOWS. Classification proposition is outside both windows, not biological invalidity.','No cis-Pro rejection, preference, energy, causality or empirical probability. Missing role/coordinate/plane scope remains inconclusive. Raw torsion is preserved independently.']
(out/(m['ruleId']+'.rule.json')).write_text(json.dumps(m,indent=2)+'\n')
# Separately named consecutive-amide source identity for the pinned backbone n->pi* screen.
p=Path('software/qualification/advanced-rule-research-design-20261004/reference/L20.html')
ng=copy.deepcopy(group);nd=json.loads(ng['parameters']['definition']['value']);nrid='ATHENA.GROUP.ADJACENT_ALPHA_BACKBONE_AMIDES.SOURCE_CONNECTIVITY'
nd.update(groupId=nrid,patternId=nrid+'/pattern',query=nd['query']+'-[N;!a;X3;+0]',memberQueryIndices=list(range(9)),negativeCoverageVersion=nrid+'/negative/1')
nd['roles']['N3']=[8];nd['requiredState']['hydrogenRoles'].append({'role':'C2','count':0});nd['requiredState']['roleHeavyDegree']['C2']=3
nd['sourceReferences'].append({'kind':'SOURCE','namespace':'athena.foundation','id':str(p),'version':hashlib.sha256(p.read_bytes()).hexdigest()})
nd['limitations']=['Adjacent neutral source amides on an explicit alpha-backbone path; cyclic/proline/glycine contexts allowed.','Not arbitrary disconnected ligand carbonyls, sulfur donors, beta-backbones, or normalized charged amide resonance depictions. Identity alone implies no n-to-pi-star interaction.']
ng.update(ruleId=nrid,limitations=nd['limitations']);ng['negativeCoverage']['version']=nd['negativeCoverageVersion'];ng['parameters']['definition']['value']=json.dumps(nd,sort_keys=True,separators=(',',':'))
ng['scientificSources'].append({'locator':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'citation':'Bartlett et al., Nature Chemical Biology 2010, n-to-pi-star interactions in proteins; Fig2a and Methods: consecutive backbone carbonyl operational geometry. DOI10.1038/nchembio.406; pinned PMC2921280.'})
(out/(nrid+'.rule.json')).write_text(json.dumps(ng,indent=2)+'\n')
nm=copy.deepcopy(m);nm.update(ruleId='ATHENA.INT.N_PI_STAR.ADJACENT_BACKBONE_CANDIDATE',profile='ATHENA_N_PI_BACKBONE_V1',tier='G07',family='INTERACTION',scientificSources=ng['scientificSources'],requiredGeometry=['Complete finite common-frame O1-C2 distance and O1-C2-O2 angle; independently attributed acceptor substituent plane'],requiredChemistry=['Verified adjacent source backbone-amide roles and all correspondence alternatives'])
nm['parameters']={'sourceManifest':{'value':json.dumps(ng,sort_keys=True,separators=(',',':')),'unit':'policy','definition':'Explicit adjacent-alpha-backbone-amide source identity'},'geometryManifest':geometry,'maximumDistanceAngstrom':{'value':'3.2','unit':'angstrom','definition':'Pinned L20 Fig2a operational screen'},'minimumAngleDegrees':{'value':'99.0','unit':'degree','definition':'Pinned L20 Fig2a O(previous)-C(next)-O(next) inclusive lower bound'},'maximumAngleDegrees':{'value':'119.0','unit':'degree','definition':'Pinned L20 Fig2a inclusive upper bound'}}
nm['negativeCoverage']={'version':nm['ruleId']+'/negative/1','supportedDomain':'Exact selected adjacent source backbone amides only','requirements':['EXACT_SOURCE_ROLE_TUPLE','ALL_CORRESPONDENCES_AGREE','FINITE_COMMON_FRAME_DISTANCE_ANGLE'],'scope':'Selected O1,C2,O2,CA2,N3; no whole-system absence','incompleteStatus':'UNKNOWN_INCONCLUSIVE'}
nm['limitations']=['Geometric candidate within published operational backbone screen, not orbital donation, stabilization, affinity or causality.','Distance<=3.2 A and99<=O1-C2-O2 angle<=119 degrees. Outside this window means absent for this screen only; the paper explicitly discusses possible interactions outside it.','Acceptor-carbon out-of-substituent-plane geometry is retained independently; unavailable plane geometry is not fabricated and does not change the distance/angle screen.','No extrapolation to arbitrary ligand carbonyls, sulfur donors, amide resonance alternatives or other backbones.']
(out/(nm['ruleId']+'.rule.json')).write_text(json.dumps(nm,indent=2)+'\n')
# A cyclic dipeptide reuses N1 as N3: represent that alias explicitly, not as two query atoms.
cg=copy.deepcopy(ng);cd=json.loads(cg['parameters']['definition']['value']);cid='ATHENA.GROUP.CYCLIC_DIPEPTIDE.ADJACENT_AMIDES.SOURCE_CONNECTIVITY'
cd.update(groupId=cid,patternId=cid+'/pattern',query='[N;!a;X3;+0]1-[C;!a;X4;+0]-[C;!a;X3;+0](=[O;X1;+0])-[N;!a;X3;+0]-[C;!a;X4;+0]-[C;!a;X3;+0](=[O;X1;+0])-1',memberQueryIndices=list(range(8)),negativeCoverageVersion=cid+'/negative/1')
cd['roles']['N3']=[0];cg.update(ruleId=cid);cg['negativeCoverage']['version']=cd['negativeCoverageVersion'];cg['parameters']['definition']['value']=json.dumps(cd,sort_keys=True,separators=(',',':'));(out/(cid+'.rule.json')).write_text(json.dumps(cg,indent=2)+'\n')
cm=copy.deepcopy(nm);cm['ruleId']='ATHENA.INT.N_PI_STAR.CYCLIC_DIPEPTIDE_CANDIDATE';cm['parameters']['sourceManifest']['value']=json.dumps(cg,sort_keys=True,separators=(',',':'));cm['negativeCoverage']['version']=cm['ruleId']+'/negative/1';(out/(cm['ruleId']+'.rule.json')).write_text(json.dumps(cm,indent=2)+'\n')
