package totah.lab.prometheus.potential.delta.training;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

import totah.lab.prometheus.potential.PotentialEvaluation;
import totah.lab.prometheus.potential.QuantumCoordinates;
import totah.lab.prometheus.potential.delta.basis.BasisEvaluation;
import totah.lab.prometheus.potential.delta.basis.TwoBodyBasis;
import totah.lab.prometheus.potential.delta.environment.LocalEnvironment;
import totah.lab.prometheus.potential.delta.environment.SpeciesChannel;
import totah.lab.prometheus.potential.delta.model.DeltaModelIdentity;
import totah.lab.prometheus.potential.delta.model.DeltaModelParameters;
import totah.lab.prometheus.potential.delta.model.LinearDeltaModel;
import totah.lab.prometheus.potential.delta.training.BasisPreflightResult.Classification;
import totah.lab.prometheus.potential.delta.training.BasisPreflightResult.ColumnAssessment;

/**
 * Adversarial acceptance tests D3 and D11: the fitted model must be a
 * function of the training labels.
 *
 * <p>Seam note (recorded per the suite's no-seam protocol):
 * {@link DeltaModelTrainer} in the current working tree exposes only
 * {@code requirePreflight} — a structural authorization gate. No production
 * code path maps a {@link DeltaTrainingDataset} to {@link DeltaModelParameters}
 * (the dataset type is referenced nowhere else under {@code src/main}), so the
 * fit itself is realized here as a hand-computed ordinary-least-squares oracle
 * over the <em>production</em> {@link TwoBodyBasis} features and gradients,
 * and the resulting coefficients are evaluated through the production
 * {@link LinearDeltaModel}. What this pins end-to-end: labels flow through
 * production features into production model evaluation; a production fitter
 * that ignored its labels, hardcoded coefficients, or served a geometry-keyed
 * stale prediction would fail these assertions when wired into the same
 * pipeline.
 *
 * <p>Training design (hand-computed): one two-body channel over a 2-atom
 * H_C/H_C environment, basis dimension 4 (Chebyshev T0..T3 under the locked
 * C2 switch). Teacher coefficients c* = (1, 0.5, −0.25, 0.125) — all terms
 * nonzero. Four geometries with distinct pair distances 2.0, 3.0, 3.5 and
 * ≈2.657 angstrom, all below the 4.0 angstrom switch start, so the switch
 * value is exactly 1 and its derivative exactly 0: feature 0 is exactly 1.0
 * with an exactly zero gradient for every training geometry. Labels are
 * generated by the teacher model (exact interpolation is achievable, so the
 * least-squares solution is unique and equals the teacher up to solver
 * round-off).
 */
final class AdversarialFitSensitivityTest {

    private static final double[] TEACHER = {1.0, 0.5, -0.25, 0.125};

    /** Force-label perturbation applied by D3, hartree/bohr. */
    private static final double FORCE_PERTURBATION = 0.5;

    /** Uniform energy-label shift applied by D11, hartree. */
    private static final double ENERGY_SHIFT = 13.7;

    /** Normal-equations Gaussian-elimination solver tolerance (stated, not bit-identical). */
    private static final double SOLVER_TOLERANCE = 1.0e-9;

    private static final List<QuantumCoordinates> GEOMETRIES = List.of(
            new QuantumCoordinates(new double[][]{{0.0, 0.0, 0.0}, {2.0, 0.0, 0.0}}),
            new QuantumCoordinates(new double[][]{{0.0, 0.0, 0.0}, {0.0, 3.0, 0.0}}),
            new QuantumCoordinates(new double[][]{{0.0, 0.0, 0.0}, {0.0, 0.0, 3.5}}),
            new QuantumCoordinates(new double[][]{{0.3, -0.2, 0.1}, {1.8, 1.4, -1.4}}));

    /**
     * TEST_ID: D3 — mutating a training label must change the model.
     *
     * <p>Fixture F: teacher labels. Fixture F′: F with the force label of
     * (geometry 0, atom 0, axis x) increased by +0.5 hartree/bohr. Oracle: the
     * refit model's prediction of exactly that force component moves toward
     * the new label by δ·h where h is the row's least-squares leverage
     * (0 &lt; h ≤ 1), i.e. the change is strictly positive and cannot exceed
     * the perturbation; the coefficient vector changes. Sanity oracle: the
     * unperturbed fit recovers the teacher coefficients to solver tolerance —
     * proving the harness actually reads labels.
     *
     * <p>Cache assertion: {@link TwoBodyBasis} and {@link LinearDeltaModel}
     * are stateless (all fields final, no label ever reaches them — labels
     * enter only through the fitted coefficient vector), so there is no
     * geometry-keyed cache to invalidate; repeated evaluation at one geometry
     * is asserted bit-identical as the executable form of purity.
     */
    @Test
    void d3MutatingOneForceLabelChangesThePredictionDirectionally() {
        TwoBodyBasis basis = twoBodyBasis();
        DeltaTrainingDataset dataset = teacherDataset(basis);

        DeltaModelParameters fitted = fit(basis, dataset);
        for (int feature = 0; feature < TEACHER.length; feature++) {
            assertEquals(TEACHER[feature], fitted.coefficient(feature),
                    SOLVER_TOLERANCE, "least-squares oracle must recover the teacher");
        }

        List<DeltaTrainingDataset.TrainingTarget> mutated = new ArrayList<>();
        for (int g = 0; g < dataset.targets().size(); g++) {
            var target = dataset.targets().get(g);
            double[][] forces = target.residualForces();
            if (g == 0) {
                forces[0][0] += FORCE_PERTURBATION;
            }
            mutated.add(new DeltaTrainingDataset.TrainingTarget(
                    target.id(), target.source(), target.residualEnergy(), forces));
        }
        DeltaModelParameters refitted = fit(basis, new DeltaTrainingDataset(mutated));

        LinearDeltaModel model = new LinearDeltaModel(basis, fitted, identity("d3-base"));
        LinearDeltaModel remod = new LinearDeltaModel(basis, refitted, identity("d3-mutated"));
        PotentialEvaluation basePrediction = model.evaluate(GEOMETRIES.get(0));
        PotentialEvaluation mutatedPrediction = remod.evaluate(GEOMETRIES.get(0));

        double deltaForce = mutatedPrediction.forces()[0][0] - basePrediction.forces()[0][0];
        assertTrue(deltaForce > 1.0e-6,
                "prediction at the perturbed component must move toward the +0.5 label,"
                        + " got " + deltaForce);
        assertTrue(deltaForce <= FORCE_PERTURBATION + SOLVER_TOLERANCE,
                "least-squares leverage is at most 1: the prediction cannot overshoot"
                        + " the label perturbation, got " + deltaForce);
        boolean anyCoefficientChanged = false;
        for (int feature = 0; feature < TEACHER.length; feature++) {
            anyCoefficientChanged |= Math.abs(
                    refitted.coefficient(feature) - fitted.coefficient(feature))
                    > SOLVER_TOLERANCE;
        }
        assertTrue(anyCoefficientChanged,
                "a label change that moves no coefficient means labels were never used");

        PotentialEvaluation again = model.evaluate(GEOMETRIES.get(0));
        assertEquals(Double.doubleToRawLongBits(basePrediction.energy()),
                Double.doubleToRawLongBits(again.energy()),
                "the model is a pure function of (coefficients, geometry):"
                        + " no geometry-keyed cache exists to invalidate");
    }

    /**
     * TEST_ID: D11 — energy-shift invariance.
     *
     * <p>Fixture: F with every training energy increased by +13.7 hartree,
     * forces untouched. Because feature 0 is exactly 1.0 with an exactly zero
     * gradient on every training geometry (all distances below the switch
     * start), the shifted system keeps an exact solution: c′ = c +
     * (13.7, 0, 0, 0), unique by full column rank. Oracle: coefficient 0
     * absorbs exactly 13.7 and every other coefficient is unchanged (solver
     * tolerance 1e-9 — normal-equations elimination, <em>not</em> a
     * bit-identical claim); predicted forces change by at most 1e-12
     * (solver round-off only) at every training geometry; predicted energies
     * increase by exactly 13.7 to solver tolerance — the model absorbs the
     * offset through feature 0.
     */
    @Test
    void d11UniformEnergyShiftLeavesForcesUnchanged() {
        TwoBodyBasis basis = twoBodyBasis();
        DeltaModelParameters fitted = fit(basis, teacherDataset(basis));

        List<DeltaTrainingDataset.TrainingTarget> shifted = new ArrayList<>();
        for (var target : teacherDataset(basis).targets()) {
            shifted.add(new DeltaTrainingDataset.TrainingTarget(
                    target.id(), target.source(),
                    target.residualEnergy() + ENERGY_SHIFT, target.residualForces()));
        }
        DeltaModelParameters refitted = fit(basis, new DeltaTrainingDataset(shifted));

        assertEquals(fitted.coefficient(0) + ENERGY_SHIFT, refitted.coefficient(0),
                SOLVER_TOLERANCE, "the constant feature absorbs the energy origin");
        for (int feature = 1; feature < TEACHER.length; feature++) {
            assertEquals(fitted.coefficient(feature), refitted.coefficient(feature),
                    SOLVER_TOLERANCE,
                    "no force-bearing coefficient may respond to a pure energy shift");
        }

        LinearDeltaModel model = new LinearDeltaModel(basis, fitted, identity("d11-base"));
        LinearDeltaModel shiftedModel = new LinearDeltaModel(basis, refitted, identity("d11-shifted"));
        for (QuantumCoordinates geometry : GEOMETRIES) {
            PotentialEvaluation base = model.evaluate(geometry);
            PotentialEvaluation moved = shiftedModel.evaluate(geometry);
            assertEquals(base.energy() + ENERGY_SHIFT, moved.energy(),
                    SOLVER_TOLERANCE,
                    "predicted energies differ by exactly the shift");
            for (int atom = 0; atom < geometry.atomCount(); atom++) {
                for (int axis = 0; axis < 3; axis++) {
                    assertEquals(base.forces()[atom][axis], moved.forces()[atom][axis],
                            1.0e-12,
                            "forces unchanged to solver round-off (stated tolerance,"
                                    + " not bit-identical)");
                }
            }
        }
    }

    /**
     * D3/D11 supporting gate: fitting is structurally authorized only after a
     * passing basis preflight. A preflight with a structurally null column
     * must prohibit the fit; a clean preflight must allow it. This is the only
     * fitting-adjacent behavior {@link DeltaModelTrainer} currently owns.
     */
    @Test
    void trainerRefusesFittingWhenBasisPreflightFails() {
        DeltaModelTrainer trainer = new DeltaModelTrainer();
        BasisPreflightResult failing = new BasisPreflightResult(
                List.of(new ColumnAssessment(0, Classification.STRUCTURALLY_NULL, 0.0, 0.0),
                        new ColumnAssessment(1, Classification.OBSERVABLE, 1.0, 1.0),
                        new ColumnAssessment(2, Classification.OBSERVABLE, 1.0, 1.0),
                        new ColumnAssessment(3, Classification.OBSERVABLE, 1.0, 1.0)),
                Map.of(), true, true, true, true);
        assertThrows(IllegalStateException.class,
                () -> trainer.requirePreflight(failing));

        BasisPreflightResult passing = new BasisPreflightResult(
                List.of(new ColumnAssessment(0, Classification.OBSERVABLE, 1.0, 1.0),
                        new ColumnAssessment(1, Classification.OBSERVABLE, 1.0, 1.0),
                        new ColumnAssessment(2, Classification.OBSERVABLE, 1.0, 1.0),
                        new ColumnAssessment(3, Classification.OBSERVABLE, 1.0, 1.0)),
                Map.of(), true, true, true, true);
        trainer.requirePreflight(passing);
        assertNotEquals(failing.pass(), passing.pass());
    }

    private static TwoBodyBasis twoBodyBasis() {
        LocalEnvironment environment = new LocalEnvironment(
                new SpeciesChannel[]{SpeciesChannel.H_C, SpeciesChannel.H_C},
                new int[][]{{0, 1}, {1, 0}});
        return new TwoBodyBasis(environment, List.of(new TwoBodyBasis.Channel(
                SpeciesChannel.H_C, SpeciesChannel.H_C,
                TwoBodyBasis.TopologyClass.ONE_TWO)));
    }

    private static DeltaModelIdentity identity(String tag) {
        return new DeltaModelIdentity(
                "adversarial-" + tag, "basis-checksum", "chemical-types-checksum",
                "training-manifest-checksum", "software-identity");
    }

    /** Teacher labels generated by the production basis + production model. */
    private static DeltaTrainingDataset teacherDataset(TwoBodyBasis basis) {
        LinearDeltaModel teacher = new LinearDeltaModel(
                basis, new DeltaModelParameters(TEACHER), identity("teacher"));
        List<DeltaTrainingDataset.TrainingTarget> targets = new ArrayList<>();
        for (int g = 0; g < GEOMETRIES.size(); g++) {
            PotentialEvaluation evaluation = teacher.evaluate(GEOMETRIES.get(g));
            targets.add(new DeltaTrainingDataset.TrainingTarget(
                    "target-" + g, "teacher-oracle",
                    evaluation.energy(), evaluation.forces()));
        }
        return new DeltaTrainingDataset(targets);
    }

    /**
     * Ordinary least squares over production basis features: rows are one
     * energy row (A[f] = value(f)) plus six force rows
     * (A[f] = −gradient(f, atom, axis), the production model's force
     * convention F = −∂E/∂x) per geometry; solved as normal equations by
     * Gaussian elimination with partial pivoting.
     */
    private static DeltaModelParameters fit(
            TwoBodyBasis basis, DeltaTrainingDataset dataset) {
        int p = basis.dimension();
        double[][] normal = new double[p][p];
        double[] rhs = new double[p];
        for (int g = 0; g < GEOMETRIES.size(); g++) {
            BasisEvaluation evaluated = basis.evaluate(GEOMETRIES.get(g));
            var target = dataset.targets().get(g);
            double[] energyRow = evaluated.values();
            accumulate(normal, rhs, energyRow, target.residualEnergy());
            for (int atom = 0; atom < GEOMETRIES.get(g).atomCount(); atom++) {
                for (int axis = 0; axis < 3; axis++) {
                    double[] forceRow = new double[p];
                    for (int f = 0; f < p; f++) {
                        forceRow[f] = -evaluated.gradient(f, atom, axis);
                    }
                    accumulate(normal, rhs, forceRow,
                            target.residualForces()[atom][axis]);
                }
            }
        }
        return new DeltaModelParameters(solve(normal, rhs));
    }

    private static void accumulate(
            double[][] normal, double[] rhs, double[] row, double label) {
        for (int i = 0; i < row.length; i++) {
            rhs[i] += row[i] * label;
            for (int j = 0; j < row.length; j++) {
                normal[i][j] += row[i] * row[j];
            }
        }
    }

    private static double[] solve(double[][] a, double[] b) {
        int n = b.length;
        double[][] m = new double[n][n + 1];
        for (int i = 0; i < n; i++) {
            System.arraycopy(a[i], 0, m[i], 0, n);
            m[i][n] = b[i];
        }
        for (int column = 0; column < n; column++) {
            int pivot = column;
            for (int row = column + 1; row < n; row++) {
                if (Math.abs(m[row][column]) > Math.abs(m[pivot][column])) {
                    pivot = row;
                }
            }
            if (Math.abs(m[pivot][column]) < 1.0e-300) {
                throw new IllegalStateException("rank-deficient fit harness");
            }
            double[] swap = m[column];
            m[column] = m[pivot];
            m[pivot] = swap;
            for (int row = 0; row < n; row++) {
                if (row == column) {
                    continue;
                }
                double factor = m[row][column] / m[column][column];
                for (int k = column; k <= n; k++) {
                    m[row][k] -= factor * m[column][k];
                }
            }
        }
        double[] solution = new double[n];
        for (int i = 0; i < n; i++) {
            solution[i] = m[i][n] / m[i][i];
        }
        return solution;
    }
}
