package totah.lab.prometheus.variational;

import static org.junit.jupiter.api.Assertions.*;
import java.util.List;
import org.junit.jupiter.api.Test;
import totah.lab.prometheus.molecular.*;
import totah.lab.prometheus.neural.GeneralSlaterJastrowState;

final class GeneralMolecularMatrixFreeSrOptimizerTest {
    @Test void generalStateFeedsBoundedBlockMatrixFreeSr(){Molecule h=new Molecule("H",List.of(new NuclearCenter(0,"H",new NuclearCharge(1),new CartesianPosition(0,0,0,LengthUnit.BOHR))),new MolecularCharge(0),new ElectronCount(1),new SpinSector(1,0,2));var state=GeneralSlaterJastrowState.cuspInitialized(h);List<QuantumCoordinates> points=List.of(c(.4,0,0),c(.8,.1,0),c(1.2,-.1,.2),c(1.8,.2,-.1));GeneralMolecularSampleSource source=consumer->{for(var point:points)consumer.accept(1.0,point);};var config=new GeneralMolecularMatrixFreeSrOptimizer.Configuration(.01,1e-2,.05,2,100,1e-10,1e-12);var result=new GeneralMolecularMatrixFreeSrOptimizer().oneIteration(state,new GeneralMolecularCoulombHamiltonian(h),source,config);assertEquals("BLOCK_PRECONDITIONED_MATRIX_FREE_SR",result.optimizer());assertEquals(points.size(),result.initialStateEvaluations());assertTrue(result.streamedOperatorPasses()>0);assertTrue(result.relativeTrueResidual()<1e-10);}

    @Test void covarianceRegressionIsSymmetricAfterAllMeansAreInitialized()throws Exception{Molecule molecule=new Molecule("covariance-regression",List.of(new NuclearCenter(0,"O",new NuclearCharge(8),new CartesianPosition(0,0,0,LengthUnit.BOHR)),new NuclearCenter(1,"H",new NuclearCharge(1),new CartesianPosition(1.7,0,0,LengthUnit.BOHR)),new NuclearCenter(2,"H",new NuclearCharge(1),new CartesianPosition(-.4,1.6,0,LengthUnit.BOHR))),new MolecularCharge(0),new ElectronCount(10),new SpinSector(5,5,1));var state=GeneralSlaterJastrowState.cuspInitialized(molecule);var source=new GeneralMolecularImportanceBatches(molecule,64,4,101,32);var method=GeneralMolecularMatrixFreeSrOptimizer.class.getDeclaredMethod("statistics",GeneralSlaterJastrowState.class,GeneralMolecularCoulombHamiltonian.class,GeneralMolecularSampleSource.class);method.setAccessible(true);Object statistics=method.invoke(null,state,new GeneralMolecularCoulombHamiltonian(molecule),source);var accessor=statistics.getClass().getDeclaredMethod("covariance");accessor.setAccessible(true);double[][] covariance=(double[][])accessor.invoke(statistics);for(int i=0;i<covariance.length;i++)for(int j=0;j<covariance.length;j++)assertEquals(covariance[i][j],covariance[j][i],1e-15,"covariance must not depend on mean initialization order");}

    @Test void directWavefunctionSamplesAreNotMultipliedByPsiSquaredAgain()throws Exception{Molecule h=new Molecule("direct-weight-regression",List.of(new NuclearCenter(0,"H",new NuclearCharge(1),new CartesianPosition(0,0,0,LengthUnit.BOHR))),new MolecularCharge(0),new ElectronCount(1),new SpinSector(1,0,2));var state=GeneralSlaterJastrowState.cuspInitialized(h);List<QuantumCoordinates> points=List.of(c(.4,0,0),c(1.8,0,0));DirectWavefunctionSampleSource source=consumer->{for(var point:points)consumer.accept(1,point);};var method=GeneralMolecularMatrixFreeSrOptimizer.class.getDeclaredMethod("statistics",GeneralSlaterJastrowState.class,GeneralMolecularCoulombHamiltonian.class,GeneralMolecularSampleSource.class);method.setAccessible(true);Object statistics=method.invoke(null,state,new GeneralMolecularCoulombHamiltonian(h),source);var accessor=statistics.getClass().getDeclaredMethod("weightSum");accessor.setAccessible(true);assertEquals(2.0,(double)accessor.invoke(statistics),0);}
    private static QuantumCoordinates c(double x,double y,double z){return new QuantumCoordinates(List.of(new QuantumCoordinates.ParticleCoordinate(0,x,y,z,SpinProjection.ALPHA)));}
}
