package totah.lab.gaia.pocket;

public enum PocketMetricType {
    FPOCKET_SCORE,
    FPOCKET_DRUGGABILITY,
    P2RANK_PROBABILITY,
    VOLUME,
    TOTAL_SASA,
    POLAR_SASA,
    APOLAR_SASA,
    ALPHA_SPHERE_COUNT,
    MEAN_LOCAL_HYDROPHOBIC_DENSITY,
    MEAN_ALPHA_SPHERE_RADIUS,
    MEAN_ALPHA_SPHERE_SOLVENT_ACCESS,
    APOLAR_ALPHA_SPHERE_PROPORTION,
    HYDROPHOBICITY_SCORE,
    VOLUME_SCORE,
    POLARITY_SCORE,
    CHARGE_SCORE,
    POLAR_ATOM_PROPORTION,
    ALPHA_SPHERE_DENSITY,
    ALPHA_SPHERE_MAX_DISTANCE,
    FLEXIBILITY
}
