#!/usr/bin/env python3
"""Resolve cautious authoritative names for the fixed 12-protein panel."""
from __future__ import annotations
import argparse,csv,hashlib,json
from pathlib import Path
DATE='2026-08-01'
def fasta(p):
 d={};n=None
 for l in p.read_text().splitlines():
  if l.startswith('>'):n=l[1:].split()[0];d[n]=''
  else:d[n]+=l.strip()
 return d
def rec(**x):return x
def main():
 ap=argparse.ArgumentParser();ap.add_argument('phase1',type=Path);a=ap.parse_args();root=a.phase1;seq=fasta(root/'cluster_representatives.fasta');meta={x['sequence_id']:x for x in csv.DictReader((root/'cluster_representatives_metadata.csv').open())}
 rows=[
 rec(sequence_id='HUMAN_METTL7B',cluster='reference',biohub_id='',original='Human METTL7B reference',upi='',uniprot='Q6UX53',refseq='NP_689850.2',ensembl='ENSP00000377796.3 (ENSG00000170439.8)',gene='TMT1B (synonym METTL7B)',name='Thiol S-methyltransferase TMT1B',alts='Methyltransferase-like protein 7B; METTL7B',organism='Homo sapiens',taxid='9606',status='reviewed',level='UniProt evidence at protein level (PE=1); experimentally characterized enzyme',source='UniProtKB/Swiss-Prot',url='https://www.uniprot.org/uniprotkb/Q6UX53/entry',confidence='very high',relation='confirmed human reference',notes='Reviewed record; current HGNC/UniProt nomenclature uses TMT1B, with METTL7B retained as a synonym.'),
 rec(sequence_id='HUMAN_METTL7A',cluster='reference',biohub_id='',original='Human METTL7A reference',upi='',uniprot='Q9H8H3',refseq='NP_054752.3; XP_054227679.1',ensembl='ENSP00000331787.4 and alternate Ensembl isoforms (ENSG00000185432.13)',gene='TMT1A (synonym METTL7A)',name='Thiol S-methyltransferase TMT1A',alts='Methyltransferase-like protein 7A; METTL7A',organism='Homo sapiens',taxid='9606',status='reviewed',level='UniProt evidence at protein level (PE=1); experimentally characterized enzyme',source='UniProtKB/Swiss-Prot',url='https://www.uniprot.org/uniprotkb/Q9H8H3/entry',confidence='very high',relation='confirmed human reference',notes='Reviewed record; current HGNC/UniProt nomenclature uses TMT1A, with METTL7A retained as a synonym; multiple transcript/isoform cross-references exist.'),
 rec(sequence_id='CLUSTER_01_REP',cluster='1',biohub_id='60ee18447dcd7b69207b93fac7add250',original='Methyltransferase like 7A',upi='UPI001336417D',uniprot='A0A665WN80',refseq='',ensembl='ENSENLP00000045549',gene='METTL7A (Ensembl); LOC115044110 (UniProt source model)',name='Methyltransferase-like protein 7A',alts='',organism='Echeneis naucrates',taxid='173247',status='unreviewed; predicted',level='Automated UniProtKB/TrEMBL and Ensembl gene-model annotation',source='UniProtKB/TrEMBL; Ensembl',url='https://www.uniprot.org/uniprotkb/A0A665WN80/entry',confidence='moderate',relation='predicted TMT1A/METTL7A ortholog',notes='Exact-sequence cross-references agree on METTL7A-family identity; no reviewed organism-specific record or experimental confirmation.'),
 rec(sequence_id='CLUSTER_02_REP',cluster='2',biohub_id='d3f8d432b47105d4d408d7a544c4c5d1',original='Thiol methyltransferase 1A',upi='UPI00072EA7D3',uniprot='A0A3B3VHP7',refseq='XP_014912494',ensembl='ENSPLAP00000024526',gene='TMT1A (UniProt); METTL7A (Ensembl); LOC106962540 (RefSeq)',name='Thiol methyltransferase 1A',alts='Methyltransferase-like protein 7A',organism='Poecilia latipinna',taxid='48699',status='unreviewed; predicted',level='Concordant automated UniProtKB, RefSeq, and Ensembl annotation',source='UniProtKB/TrEMBL; RefSeq; Ensembl',url='https://www.uniprot.org/uniprotkb/A0A3B3VHP7/entry',confidence='high for family/orthology; low for experimental function',relation='predicted TMT1A ortholog',notes='Exact sequence maps to all three records. TMT1A is a database gene name, not evidence of experimental characterization in this species.'),
 rec(sequence_id='CLUSTER_03_REP',cluster='3',biohub_id='634f16f7e0f298727b395874854a8741',original='Thiol S-methyltransferase TMT1B-like isoform X2',upi='UPI002417A50C',uniprot='',refseq='XP_054922304',ensembl='',gene='LOC126522293',name='Thiol S-methyltransferase TMT1B-like isoform X2',alts='',organism='Dermacentor andersoni',taxid='34620',status='predicted',level='Automated RefSeq eukaryotic gene model',source='NCBI RefSeq via UniParc exact-sequence cross-reference',url='https://www.ncbi.nlm.nih.gov/protein/XP_054922304',confidence='moderate',relation='predicted TMT1B-like family member; orthology not curated',notes='No active UniProtKB record. “Isoform X2” is a predicted gene-model label; LOC126522293 is not a curated gene symbol.'),
 rec(sequence_id='CLUSTER_04_REP',cluster='4',biohub_id='25d6052c0b963947285f3248b0b22cea',original='Thiol methyltransferase 1B',upi='UPI001E250006',uniprot='A0A2J8UI78',refseq='',ensembl='ENSPPYP00000005271',gene='TMT1B',name='Thiol methyltransferase 1B',alts='Methyltransferase-like protein 7B',organism='Pongo abelii',taxid='9601',status='unreviewed; predicted',level='Concordant UniProtKB/TrEMBL and Ensembl orthology annotation',source='UniProtKB/TrEMBL; Ensembl',url='https://www.uniprot.org/uniprotkb/A0A2J8UI78/entry',confidence='high for predicted orthology; not experimentally confirmed',relation='predicted TMT1B ortholog',notes='Near-identical to human TMT1B, but the orangutan record remains unreviewed.'),
 rec(sequence_id='CLUSTER_05_REP',cluster='5',biohub_id='ad419820f1badd42f0016b7bec28ddff',original='Methyltransferase-like protein 7B like protein',upi='UPI001F953EA1',uniprot='A0A8T0EV01',refseq='XP_055945248',ensembl='XP_055945248.1 (Ensembl Metazoa cross-reference)',gene='HNY73_014948 (assembly locus); LOC129975965 (RefSeq locus)',name='Thiol S-methyltransferase TMT1B-like',alts='Methyltransferase-like protein 7B-like protein',organism='Argiope bruennichi',taxid='94029',status='unreviewed; predicted',level='Automated UniProtKB/TrEMBL, RefSeq, EMBL-WGS, and Ensembl Metazoa models',source='RefSeq preferred name; UniProtKB/TrEMBL exact-sequence record',url='https://www.ncbi.nlm.nih.gov/protein/XP_055945248',confidence='moderate',relation='predicted TMT1B-like family member; orthology not curated',notes='No recognized curated gene symbol or reviewed recommended name beyond a TMT1B/METTL7B-like prediction. HNY73_014948 and LOC129975965 are model/locus identifiers, not stable functional gene symbols.'),
 rec(sequence_id='CLUSTER_06_REP',cluster='6',biohub_id='d3acc3886c78e1b1530b8faec6521c9f',original='Thiol S-methyltransferase TMT1A-like isoform X1',upi='UPI001E670011',uniprot='',refseq='XP_069156275',ensembl='XP_045594782.1 (Ensembl Metazoa; alternate older model)',gene='LOC138350019',name='Thiol S-methyltransferase TMT1A-like isoform X1',alts='Methyltransferase-like protein 7A (older model XP_045594782)',organism='Procambarus clarkii',taxid='6728',status='predicted',level='Automated RefSeq model; conflicting/updated model identifiers',source='NCBI RefSeq via UniParc exact-sequence cross-reference',url='https://www.ncbi.nlm.nih.gov/protein/XP_069156275',confidence='moderate',relation='predicted TMT1A-like family member; orthology not curated',notes='No active UniProtKB record. XP_069156275 is current; XP_045594782 is inactive in RefSeq although an Ensembl Metazoa cross-reference remains. Isoform X1 and LOC138350019 are model-derived.'),
 rec(sequence_id='CLUSTER_07_REP',cluster='7',biohub_id='fcbe733928010358c3534b015bfdc240',original='Methyltransferase-like protein 7A isoform X2',upi='UPI0011E4F9CD',uniprot='A0A8B8MUV1',refseq='XP_030513876; XP_048137187',ensembl='',gene='LOC115727734',name='Putative methyltransferase-like protein 7A isoform X2',alts='Methyltransferase-like protein 7A isoform X2',organism='Rhodamnia argentea',taxid='178133',status='unreviewed; predicted',level='Automated UniProtKB/TrEMBL and two active RefSeq gene models',source='UniProtKB/TrEMBL; RefSeq',url='https://www.uniprot.org/uniprotkb/A0A8B8MUV1/entry',confidence='moderate',relation='predicted METTL7A-family member; orthology not curated',notes='The exact sequence maps to two active RefSeq accessions, likely assembly/model redundancy. LOC115727734 is a predicted locus; “isoform X2” is not independently curated.'),
 rec(sequence_id='CLUSTER_08_REP',cluster='8',biohub_id='2b38c3ca9b3dde5182055862f3ce5e7e',original='S-adenosyl-L-methionine-dependent methyltransferases superfamily protein family protein',upi='',uniprot='',refseq='',ensembl='IMG/M identifier 639590277',gene='',name='S-adenosyl-L-methionine-dependent methyltransferase superfamily protein',alts='',organism='unresolved metagenomic/IMG source',taxid='',status='unresolved; model-derived',level='Generic automated family annotation in supplied IMG/M-linked BioHub record',source='BioHub/IMG-M supplied identifier',url='639590277',confidence='low',relation='generic SAM-dependent methyltransferase; orthology unresolved',notes='No UniParc, active UniProtKB, RefSeq, or organism-level stable record was resolved. No gene symbol can be assigned; structural pocket similarity does not justify METTL7 naming.'),
 rec(sequence_id='CLUSTER_09_REP',cluster='9',biohub_id='16d838091a6d42a721687bbd31cf29bb',original='ubiE/COQ5 methyltransferase family domain-containing protein',upi='',uniprot='',refseq='',ensembl='MGYP001207546228',gene='',name='ubiE/COQ5 methyltransferase family domain-containing protein',alts='Generic methyltransferase domain-containing protein',organism='unresolved metagenomic source',taxid='',status='unresolved; predicted',level='Automated MGnify/metagenomic family annotation',source='MGnify identifier supplied by BioHub',url='https://www.ebi.ac.uk/metagenomics/',confidence='moderate for ubiE/COQ5 family; low for organism/function',relation='other SAM-dependent methyltransferase; not resolved as METTL7 ortholog',notes='No active UniProtKB/RefSeq record or organism-level assignment. The MGYP identifier did not resolve through the current public protein endpoint on the date checked; the original identifier is preserved.'),
 rec(sequence_id='CLUSTER_10_REP',cluster='10',biohub_id='0f48266b04e5451f4167d5c5e98e4fc3',original='Thiol S-methyltransferase METTL7B-like',upi='UPI00189A43A9',uniprot='',refseq='XP_037579802',ensembl='XP_037579802.1 (Ensembl Metazoa cross-reference)',gene='LOC119462532',name='Thiol S-methyltransferase TMT1B-like',alts='Thiol S-methyltransferase METTL7B-like',organism='Dermacentor silvarum',taxid='543639',status='predicted',level='Automated RefSeq and Ensembl Metazoa gene model',source='NCBI RefSeq via UniParc exact-sequence cross-reference',url='https://www.ncbi.nlm.nih.gov/protein/XP_037579802',confidence='moderate',relation='predicted TMT1B-like family member; orthology not curated',notes='No active UniProtKB record and no recognized curated gene symbol or recommended name beyond TMT1B/METTL7B-like. LOC119462532 is a predicted locus identifier.'),
 ]
 # Exact-sequence audit: BioHub MD5 equals sequence and UniParc sequence where available.
 for x in rows:
  s=seq[x['sequence_id']];md5=hashlib.md5(s.encode()).hexdigest();ok=(not x['biohub_id'] or md5==x['biohub_id'])
  if x['upi']:
   d=json.loads((root/'raw'/f"{x['upi']}.json").read_text());ok=ok and d['sequence']['value']==s
  x['sequence_identity_verification']='exact sequence/MD5 verified' if ok else 'FAILED'
  x['date_checked']=DATE
 fields={'sequence_id':'sequence_id','cluster':'biohub_cluster','biohub_id':'biohub_representative_identifier','original':'original_supplied_annotation','upi':'uniparc_identifier','uniprot':'active_uniprotkb_accession','refseq':'refseq_protein_accession','ensembl':'ensembl_or_species_genome_identifier','gene':'gene_symbol_or_locus','name':'recommended_protein_name','alts':'alternative_names','organism':'organism','taxid':'taxonomy_id','status':'annotation_status','level':'evidence_level','source':'source_database','url':'source_url_or_stable_identifier','date_checked':'date_checked','relation':'identity_interpretation','sequence_identity_verification':'sequence_identity_verification','confidence':'confidence','notes':'ambiguity_notes'}
 with (root/'representative_name_resolution.csv').open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(fields.values()));w.writeheader();w.writerows([{fields[k]:v for k,v in x.items()} for x in rows])
 lines=['# Authoritative name resolution for BioHub representatives','',f'Checked: {DATE}','','Names are assigned from exact-sequence database cross-references. Reviewed UniProtKB names take precedence; otherwise organism-specific RefSeq/Ensembl or current unreviewed UniProt records are reported explicitly as predictions. Pocket similarity was not used to assign names or symbols.','','## Important conclusions','','- Cluster 5 (*Argiope bruennichi*) has **no recognized curated gene symbol or reviewed name beyond a TMT1B/METTL7B-like prediction**. `HNY73_014948` and `LOC129975965` are automated locus identifiers.','- Cluster 10 (*Dermacentor silvarum*) likewise has **no recognized curated gene symbol or reviewed name beyond TMT1B/METTL7B-like**. `LOC119462532` is a predicted RefSeq locus.','- Clusters 3 and 6 resolve to active RefSeq predicted models but have no active UniProtKB record.','- Cluster 7 maps to one active unreviewed UniProt record and two active RefSeq accessions for the same sequence; the duplication is reported rather than silently choosing one RefSeq model.','- Clusters 8 and 9 remain generic/metagenomic proteins without organism-level authoritative naming.','','## Resolution table','','| Cluster | Organism | Best current protein name | Gene symbol | Accession | Status | Confidence |','|---|---|---|---|---|---|---|']
 for x in rows:
  acc=x['uniprot'] or x['refseq'] or x['ensembl'] or x['biohub_id'];lines.append(f"| {x['cluster']} | {x['organism']} | {x['name']} | {x['gene'] or 'none assigned'} | {acc} | {x['status']} | {x['confidence']} |")
 lines += ['','## Ambiguity notes','']
 for x in rows:lines.append(f"- **{x['sequence_id']}** — {x['notes']} Sequence audit: {x['sequence_identity_verification']}. Source: {x['url']}.")
 (root/'representative_name_resolution.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':main()
