from pathlib import Path
import copy,json,hashlib
root=Path('software/modules/athena/src/main/resources/totah/lab/athena/system/rules');q=Path(__file__).resolve().parent;out=root/'met-phe-survey-v1';out.mkdir(exist_ok=True)
write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n');canon=lambda v:json.dumps(v,sort_keys=True,separators=(',',':'))
files={'THIOETHER':root/'groups-foundation-v1/ATHENA.GROUP.THIOETHER.rule.json','CARBON_RING':root/'groups-b01/ATHENA.GROUP.AROMATIC.rule.json'};pins=json.loads((q/'SOURCE_PINS.json').read_text())
for p in files.values():pins[str(p)]=hashlib.sha256(p.read_bytes()).hexdigest()
write(q/'SOURCE_PINS.json',pins);refs=[{'kind':'SOURCE','namespace':'athena.g03.source','id':p,'version':h}for p,h in pins.items()];sci=[{'locator':p,'sha256':h,'citation':'Pinned source Met/Phe survey convention and exact bounded source/geometry contract; no energy, cysteine or chalcogen-O extension.'}for p,h in pins.items()];sources={}
for name,p in files.items():
 m=json.loads(p.read_text());d=json.loads(m['parameters']['definition']['value']);id='ATHENA.G03.SOURCE.'+name;m.update(ruleId=id,profile='ATHENA_GROUP_SOURCE_H_V4',implementationVersion='4',tier='G03_SOURCE_CONTEXT',qualification='NOT_EVALUATED');d.update(schema='athena-group-definition/2',groupId=id,patternId=id+'/pattern',occurrenceExclusions=[],negativeCoverageVersion=id+'/negative/1',sourceReferences=refs)
 d['requiredState']['hydrogenElements']=['C','N','O','S'];d['requiredState']['aromaticity']=True;d['requiredState']['hydrogenConsistencyQueries']={str(i):f'[*;H{i}]'for i in range(5)};d['supportedDomain']['elements']=['C','N','O','S'];m['parameters']['definition']['value']=canon(d);m['negativeCoverage']['version']=d['negativeCoverageVersion'];m['scientificSources']=sci;m['measurementsProduced']={'source-identities':'athena-group-identities/2'};sources[id]=m;write(out/(id+'.rule.json'),m)
m=json.loads((root/'source-fragment-parent-v1/ATHENA.A08.UNIQUE_LARGEST_HEAVY_SOURCE_COMPONENT.rule.json').read_text());g=json.loads(json.loads((root/'cysteine-backbone-b06/ATHENA.SULF.CYSTEINE_BACKBONE_ATTRIBUTION.rule.json').read_text())['parameters']['geometryManifest']['value']);id='ATHENA.G03.SOURCE_MET_PHE_SURVEY_CONTACT';m.update(family='INTERACTION',ruleId=id,profile='ATHENA_G03_MET_PHE_SURVEY_V1',implementationId='athena.met-phe-survey');m['parameters']={k:{'value':canon(v),'unit':'policy','definition':'Exact source identity or unchanged qualified mixed geometry.'}for k,v in [('sources',sources),('geometry',g)]};m['parameters']['maximumDistanceAngstrom']={'value':'7.0','unit':'angstrom','definition':'Inclusive selected survey-contact convention from L04; not an energy or affinity cutoff.'};m['scientificSources']=sci;m['requiredChemistry']=['Exact source-labelled chemically verified MET/PHE contexts, complete ordinary source state, authoritative H/charge/aromaticity/NONE and unique correspondence'];m['requiredGeometry']=['Qualified finite source SD-centroid distance, unique six-carbon plane and nonzero SD-centroid vector'];m['measurementsProduced']={'payload':'unchanged continuous mixed geometry/3 report','sourceRoles':'exact source residue and graph role attribution','distanceAngstrom':'raw SD-centroid distance, separate from chemistry eligibility'};m['limitations']=['Selected source Met/Phe survey-contact convention only; no energy, favorability, occupancy, cysteine, sulfonium or chalcogen-O assertion.','No angle/bond-length or isotope-composition inference; same nominal mass for identical carbon isotope descriptors.','No current-policy activation or production authority.'];m['negativeCoverage']={'version':id+'/coverage/1','scope':'EXACT_SELECTED_SOURCE_PAIR_ONLY','requirements':['EXACT_SOURCE_IDENTITIES','COMPLETE_SOURCE_COMPONENTS','INDEPENDENT_SOURCE_SCOPE','QUALIFIED_SELECTED_GEOMETRY','CURRENT_POLICY_AUTHORITY'],'incompleteStatus':'UNKNOWN_INCONCLUSIVE','supportedDomain':'Exact bounded Met/Phe source contexts in one immutable state; no system-wide negative.'};write(out/(id+'.rule.json'),m)
