package totah.lab.mettl7.triage;

public enum NextAction {
    REJECT_LOW_INFORMATION,
    KEEP_AS_NEGATIVE_CONTROL,
    TEST_DIRECT_BINDING_A_B,
    TEST_PRODUCTIVE_TURNOVER_A_B,
    TEST_APO_SAM_SAH_BINDING,
    TEST_COVALENCY_FIRST,
    TEST_AS_A_SELECTIVE_PROSPECT,
    TEST_AS_B_SELECTIVE_PROSPECT
}
