# Metadata assembly only; all chemistry and qualification execute in Java.
from pathlib import Path
import json,hashlib
q=Path('software/qualification/athena-scientific-rules-20261004');base=Path('software/modules/athena/src/main/resources/totah/lab/athena/system/rules');out=base/'scientific';out.mkdir(exist_ok=True)
requirements=['EXPLICIT_PARTNER_SCOPE','EXPLICIT_CONNECTIVITY','UNAMBIGUOUS_CHEMICAL_MAPPING','SUPPORTED_CHEMICAL_DOMAIN','FORMAL_STATE_COVERAGE','PERCEPTION_ENUMERATION_COMPLETE','SEARCH_ENUMERATION_COMPLETE','FINITE_GEOMETRY']
def source(path,citation):return dict(locator=str(path),sha256=hashlib.sha256(Path(path).read_bytes()).hexdigest(),citation=citation)
patterns={'alcohol':'[O;H1;+0]-[C;X4]','carbonyl':'[O;X1;+0]=[C;+0]','ammonium':'[N+;X4]','carboxylate':'[O-]-[C](=[O])'}
rows=[('HYDRO','HYDROPHOBIC','ATHENA.HYDROPHOBIC.CONTACT','Neutral carbon with C/H-only source neighbors; complete mapped neutral-carbon eligibility across selected partners. Charged carbon remains unsupported.'),('HBOND','HBOND','ATHENA.HBOND.DIRECTIONAL','Neutral aliphatic alcohol donors/acceptors and carbonyl oxygen acceptors; explicit donor H and single D-H bond; neutral C/H/O-only scope for a complete negative. Other donor/acceptor classes remain unsupported.'),('PIPI','PI_STACKING','ATHENA.PI_STACKING.GEOMETRY','Isolated six-member neutral carbocyclic aromatic rings with source aromaticity corroboration; every aromatic atom covered for a negative. Fused/heteroaromatic/other rings remain unsupported.'),('CATPI','PI_CATION','ATHENA.PI_CATION.GEOMETRY','Supported tetra-coordinate ammonium cations and isolated six-carbon neutral aromatic rings; all charged and aromatic sites accounted for; no universal amine-plane guard.'),('SALT','SALT_BRIDGE','ATHENA.SALT_BRIDGE.PROXIMITY','Supported tetra-coordinate ammonium and carboxylate groups with explicit formal charges and source protonation; every nonzero-charge site accounted for. Other charged motifs remain unsupported.')]
index=[]
for old,family,rule,domain in rows:
 m=json.loads((base/f'INT.{old}.001--ATHENA_NATIVE_{family}.rule.json').read_text());m.update(schema='athena-rule/2',ruleId=rule,profile='ATHENA_SCIENTIFIC_V1',version='1.0.0',implementationId='athena.scientific',implementationVersion='1',tier='bounded-scientific-definition',requiredCapabilities=['DISTANCE_QUERIES'])
 m['negativeCoverage']=dict(version='athena-negative-coverage/1',supportedDomain=domain,requirements=requirements,scope='EXPLICIT_PARTNERS_ONLY',incompleteStatus='UNKNOWN_INCONCLUSIVE')
 m['requiredChemistry']=['Candidate-local validated MolecularGraph correspondence and explicit source topology','Existing injected OCL sanitizer/SMARTS matcher, with backend evidence',domain]
 m['measurementsProduced']={'raw':'Existing native candidate geometry before threshold classification','candidateSupported':'Candidate-local source chemistry proof, independent of negative coverage','negativeCoverage':'All eight versioned obligations; booleans with missing-requirement reasons','perceptionProvenance':'Original component, sanitizer, patterns and backend method/version evidence'}
 for role,query in patterns.items():m['parameters']['pattern.'+role]=dict(value=query,unit='policy',definition='OCL SMARTS; query:0 is the role anchor; carboxylate retains full query atom membership. No independent matcher.')
 m['scientificSources']=[source('software/qualification/athena-rule-definitions-review-20261004/DESIGN.txt','User-approved Athena definitions and primary-literature source map; operational criteria, not affinity calibration')]
 m['referenceArtifacts']=[source('software/modules/athena/src/main/java/totah/lab/athena/system/rules/AthenaScientificRules.java','Athena domain and negative-coverage implementation'),source('software/modules/athena/src/main/java/totah/lab/athena/interaction/InteractionMeasurements.java','Unchanged legacy measurement authority')]
 for path in ['software/modules/athena/src/main/java/totah/lab/athena/system/rules/RuleAnalyzers.java','software/modules/athena/src/main/java/totah/lab/athena/system/rules/RuleManifest.java','software/modules/athena/src/main/java/totah/lab/athena/system/rules/RuleRegistry.java','software/modules/daedalus/src/main/java/totah/lab/daedalus/system/RuleExecutionPipeline.java','software/modules/athena-openchemlib/src/main/java/totah/lab/athena/design/backend/ocl/OclMolecularBackend.java','software/modules/athena-openchemlib/src/main/java/totah/lab/athena/design/backend/ocl/OclGraphMapper.java']:
  m['referenceArtifacts'].append(source(path,'Pinned registry/evaluation/orchestration or existing OCL implementation; no external scientific authority substitution'))
 m['limitations']=['Qualified only in the stated chemical domain and explicit partner scope; no universal chemistry completeness claim.','A supported positive does not imply complete coverage. ABSENT_FALSE requires every negativeCoverage obligation.','No binding energy, potency, inhibition, physical coupling or METTL7 interpretation.','Historical measurements lacking candidate-local eligibility/coverage cannot be reused as /2 evidence; collect new attributed measurements from the same immutable state.','Legacy detector algorithms, profile bytes and certificates remain unchanged; external references are not production authorities.']
 if family=='PI_CATION':m['limitations'].append('Scientific geometry does not apply the legacy AMINE <=30-degree guard; raw guard geometry remains retained.')
 name=rule+'.rule.json';(out/name).write_text(json.dumps(m,indent=2)+'\n');index.append(name)
(out/'index.txt').write_text('\n'.join(index)+'\n')
schema=json.loads((base/'manifest.schema.json').read_text());schema['$id']='athena-rule/2';schema['properties']['schema']={'const':'athena-rule/2'};schema['required'].append('negativeCoverage')
schema['properties']['negativeCoverage']={'type':'object','additionalProperties':False,'required':['version','supportedDomain','requirements','scope','incompleteStatus'],'properties':{'version':{'const':'athena-negative-coverage/1'},'supportedDomain':{'type':'string','minLength':1},'requirements':{'const':requirements},'scope':{'const':'EXPLICIT_PARTNERS_ONLY'},'incompleteStatus':{'const':'UNKNOWN_INCONCLUSIVE'}}}
(out/'manifest.schema.json').write_text(json.dumps(schema,indent=2)+'\n')
print('5 opt-in Athena scientific manifests; legacy manifest resources untouched')
