package totah.lab.prometheus.validation;

import java.io.IOException;
import java.lang.management.ManagementFactory;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;

import totah.lab.prometheus.neural.GeometryConditionedHydrogenMoleculeState;
import totah.lab.prometheus.variational.DifferentiableStateEvaluation;
import totah.lab.prometheus.variational.HydrogenMoleculeHamiltonian;
import totah.lab.prometheus.variational.HydrogenMoleculeImportanceBatches;
import totah.lab.prometheus.variational.ParameterVector;
import totah.lab.prometheus.variational.QuantumCoordinates;
import totah.lab.prometheus.variational.force.AnalyticDifferentialSwctForceEstimator;
import totah.lab.prometheus.variational.force.HydrogenMoleculeSpaceWarp;
import totah.lab.prometheus.variational.force.HydrogenMoleculeSpaceWarpForceEstimator;

/** One-shot locked analytic differential-SWCT equivalence and performance experiment. */
public final class AnalyticDifferentialSwctExperiment {
    private static final double[] RADII={1,1.4,3};
    private static final ParameterVector PARAMETERS=new ParameterVector(List.of(.8576772116910546,.11919655001255025,-.06709570692540537,.04370894911240642,-.32732397143757097,.21519667708138937,-.06386208428749664,.04232059707741613,.017563345336565027,-.12118637444956007,.11444052280585346,.26554487072063354,.19811737981250818,.07860098998305089,-.2778578205251936,-.16701609069702947,.07580798604963333,-.15755013283163458,.22812063643399538,-.1453261891402233));
    private AnalyticDifferentialSwctExperiment() { }

    public static void main(String[] args)throws IOException{if(args.length!=2)throw new IllegalArgumentException("protocol and output directories required");Path protocol=Path.of(args[0]),output=Path.of(args[1]);verifyProtocol(protocol);Files.createDirectories(output);if(Files.exists(output.resolve("ANALYTIC_DIFFERENTIAL_SWCT_DECISION.json")))throw new IllegalStateException("one-shot evidence exists");
        List<OracleRow> oracle=new ArrayList<>();boolean oraclePass=true;for(double radius:RADII){OracleRow row=oracle(radius);oracle.add(row);oraclePass&=row.passes;}
        List<ComparisonRow> comparisons=new ArrayList<>();List<PerformanceRow> performance=new ArrayList<>();String classification;
        if(!oraclePass)classification="ANALYTIC_DIFFERENTIAL_SWCT_NOT_EQUIVALENT";else{for(double radius:RADII){BenchmarkResult result=benchmark(radius);comparisons.add(result.comparison);performance.addAll(result.performance);}boolean equivalent=comparisons.stream().allMatch(ComparisonRow::passes);boolean faster=equivalent&&comparisons.stream().allMatch(ComparisonRow::faster);classification=!equivalent?"ANALYTIC_DIFFERENTIAL_SWCT_NOT_EQUIVALENT":faster?"ANALYTIC_DIFFERENTIAL_SWCT_EQUIVALENT_AND_FASTER":"ANALYTIC_DIFFERENTIAL_SWCT_EQUIVALENT_NOT_FASTER";}
        write(output.resolve("SWCT_DERIVATIVE_ORACLE.csv"),oracleCsv(oracle));write(output.resolve("SWCT_EQUIVALENCE.csv"),comparisonCsv(comparisons));write(output.resolve("SWCT_PERFORMANCE.csv"),performanceCsv(performance));write(output.resolve("SWCT_EXACT_SCALARS.jsonl"),exactJsonl(classification,oracle,comparisons));
        write(output.resolve("ANALYTIC_DIFFERENTIAL_SWCT_DECISION.json"),String.format(Locale.ROOT,"{\"classification\":\"%s\",\"oracle_passes\":%s,\"performance_executed\":%s,\"historical_evidence_modified\":false}%n",classification,oraclePass,oraclePass));
        write(output.resolve("ANALYTIC_DIFFERENTIAL_SWCT_FINAL_REPORT.md"),report(classification,oracle,comparisons));write(output.resolve("SOFTWARE_ENVIRONMENT.txt"),environment());checksums(output,List.of("SWCT_DERIVATIVE_ORACLE.csv","SWCT_EQUIVALENCE.csv","SWCT_PERFORMANCE.csv","SWCT_EXACT_SCALARS.jsonl","ANALYTIC_DIFFERENTIAL_SWCT_DECISION.json","ANALYTIC_DIFFERENTIAL_SWCT_FINAL_REPORT.md","SOFTWARE_ENVIRONMENT.txt"));}

    private static OracleRow oracle(double radius){var state=new GeometryConditionedHydrogenMoleculeState(radius,PARAMETERS);var h=new HydrogenMoleculeHamiltonian(radius);var batches=batches(2000,radius);List<NumericalContribution> numerical=numericalTrace(state,h,batches);List<AnalyticDifferentialSwctForceEstimator.Contribution> analytic=new ArrayList<>();new AnalyticDifferentialSwctForceEstimator().evaluate(state,h,batches,analytic::add);if(numerical.size()!=analytic.size())return new OracleRow(radius,numerical.size(),analytic.size(),Double.POSITIVE_INFINITY,Double.POSITIVE_INFINITY,Double.POSITIVE_INFINITY,Double.POSITIVE_INFINITY,0,false);
        List<Double> local=new ArrayList<>(),bare=new ArrayList<>(),log=new ArrayList<>(),base=new ArrayList<>();for(int i=0;i<numerical.size();i++){var n=numerical.get(i);var a=analytic.get(i);local.add(Math.abs(a.totalLocalEnergyDerivative()-n.totalDerivative));bare.add(Math.abs(a.bareLocalEnergyDerivative()-n.bareDerivative));log.add(Math.abs(a.logJacobianStateDerivative()-n.logDerivative));base.add(Math.abs(a.baseForce()-n.base));}
        local.sort(Double::compare);bare.sort(Double::compare);log.sort(Double::compare);base.sort(Double::compare);double fraction=Math.min(fraction(local,5e-4),Math.min(fraction(bare,5e-4),fraction(base,5e-4)));boolean pass=max(log)<=2e-5&&max(local)<=5e-3&&max(bare)<=5e-3&&max(base)<=5e-3&&fraction>=.999;return new OracleRow(radius,numerical.size(),analytic.size(),max(local),max(bare),max(log),max(base),fraction,pass);}

    private static BenchmarkResult benchmark(double radius){var state=new GeometryConditionedHydrogenMoleculeState(radius,PARAMETERS);var h=new HydrogenMoleculeHamiltonian(radius);var batches=batches(72000,radius);List<PerformanceRow> rows=new ArrayList<>();List<HydrogenMoleculeSpaceWarpForceEstimator.Result> numerical=new ArrayList<>();List<AnalyticDifferentialSwctForceEstimator.Result> analytic=new ArrayList<>();for(int replay=0;replay<3;replay++){long heap=usedHeap(),cpu=cpuTime(),alloc=allocatedBytes(),start=System.nanoTime();var n=new HydrogenMoleculeSpaceWarpForceEstimator().evaluate(state,h,batches);long wall=System.nanoTime()-start;rows.add(new PerformanceRow(radius,"NUMERICAL",replay,wall,cpuDelta(cpu),allocationDelta(alloc),Math.max(heap,usedHeap()),n.stateEvaluations(),n.localEnergyEvaluations(),0));numerical.add(n);heap=usedHeap();cpu=cpuTime();alloc=allocatedBytes();start=System.nanoTime();var a=new AnalyticDifferentialSwctForceEstimator().evaluate(state,h,batches);wall=System.nanoTime()-start;rows.add(new PerformanceRow(radius,"ANALYTIC",replay,wall,cpuDelta(cpu),allocationDelta(alloc),Math.max(heap,usedHeap()),a.stateTraversals(),a.localEnergyEvaluations(),a.directionalGraphPasses()));analytic.add(a);}
        var n=numerical.getFirst();var a=analytic.getFirst();boolean replay=numerical.stream().allMatch(x->same(n,x))&&analytic.stream().allMatch(x->same(a,x));double forceDiff=Math.abs(a.forceHartreePerBohr()-n.forceHartreePerBohr()),varianceDiff=Math.abs(a.forceEstimatorVarianceHartree2PerBohr2()-n.forceEstimatorVarianceHartree2PerBohr2());double nSe=Math.sqrt(n.forceEstimatorVarianceHartree2PerBohr2()/n.configurations()),aSe=Math.sqrt(a.forceEstimatorVarianceHartree2PerBohr2()/a.configurations()),seRelative=nSe==0?(aSe==0?0:Double.POSITIVE_INFINITY):Math.abs(aSe-nSe)/nSe;long nMedian=median(rows,"NUMERICAL"),aMedian=median(rows,"ANALYTIC");boolean equivalent=forceDiff<=5e-5&&varianceDiff<=Math.max(5e-5,.005*n.forceEstimatorVarianceHartree2PerBohr2())&&seRelative<=.005&&replay;boolean faster=a.stateTraversals()<=a.configurations()&&aMedian<=.8*nMedian&&rows.stream().filter(x->x.implementation.equals("ANALYTIC")).allMatch(x->x.peakHeapBytes<(1L<<30));return new BenchmarkResult(new ComparisonRow(radius,n.forceHartreePerBohr(),a.forceHartreePerBohr(),forceDiff,n.forceEstimatorVarianceHartree2PerBohr2(),a.forceEstimatorVarianceHartree2PerBohr2(),varianceDiff,nSe,aSe,seRelative,n.stateEvaluations(),a.stateTraversals(),nMedian,aMedian,(double)nMedian/aMedian,replay,equivalent,faster),rows);}

    private static List<NumericalContribution> numericalTrace(GeometryConditionedHydrogenMoleculeState state,HydrogenMoleculeHamiltonian h,HydrogenMoleculeImportanceBatches batches){List<NumericalContribution> result=new ArrayList<>();double radius=h.bondLengthBohr(),step=HydrogenMoleculeSpaceWarpForceEstimator.DIFFERENCE_STEP_BOHR;var plusState=state.atGeometry(radius+step);var minusState=state.atGeometry(radius-step);var plusH=new HydrogenMoleculeHamiltonian(radius+step);var minusH=new HydrogenMoleculeHamiltonian(radius-step);batches.forEachBatch(batch->batch.forEach(point->{QuantumCoordinates c=point.coordinates();DifferentiableStateEvaluation center=state.evaluateWithDerivatives(c);double psi=center.value().real();if(!Double.isFinite(psi)||Math.abs(psi)<1e-14)return;double local=local(center,psi,h,c);var pw=HydrogenMoleculeSpaceWarp.transform(c,radius,step);var mw=HydrogenMoleculeSpaceWarp.transform(c,radius,-step);var pe=plusState.evaluateWithDerivatives(pw.coordinates());var me=minusState.evaluateWithDerivatives(mw.coordinates());double total=(local(pe,pe.value().real(),plusH,pw.coordinates())-local(me,me.value().real(),minusH,mw.coordinates()))/(2*step);double log=(Math.log(Math.abs(pe.value().real()))+.5*Math.log(pw.jacobian())-Math.log(Math.abs(me.value().real()))-.5*Math.log(mw.jacobian()))/(2*step);var pf=plusState.evaluateWithDerivatives(c);var mf=minusState.evaluateWithDerivatives(c);double bare=(local(pf,pf.value().real(),plusH,c)-local(mf,mf.value().real(),minusH,c))/(2*step);double base=-total-2*local*log;result.add(new NumericalContribution(total,bare,log,base));}));return result;}
    private static double local(DifferentiableStateEvaluation e,double psi,HydrogenMoleculeHamiltonian h,QuantumCoordinates c){return -.5*e.coordinateLaplacian().value().real()/psi+h.potential(c);}
    private static HydrogenMoleculeImportanceBatches batches(int count,double radius){return new HydrogenMoleculeImportanceBatches(count,radius,1.15,1009,512);}
    private static boolean same(HydrogenMoleculeSpaceWarpForceEstimator.Result a,HydrogenMoleculeSpaceWarpForceEstimator.Result b){return Double.doubleToRawLongBits(a.forceHartreePerBohr())==Double.doubleToRawLongBits(b.forceHartreePerBohr())&&Double.doubleToRawLongBits(a.forceEstimatorVarianceHartree2PerBohr2())==Double.doubleToRawLongBits(b.forceEstimatorVarianceHartree2PerBohr2());}
    private static boolean same(AnalyticDifferentialSwctForceEstimator.Result a,AnalyticDifferentialSwctForceEstimator.Result b){return Double.doubleToRawLongBits(a.forceHartreePerBohr())==Double.doubleToRawLongBits(b.forceHartreePerBohr())&&Double.doubleToRawLongBits(a.forceEstimatorVarianceHartree2PerBohr2())==Double.doubleToRawLongBits(b.forceEstimatorVarianceHartree2PerBohr2());}
    private static double fraction(List<Double> values,double tolerance){return (double)values.stream().filter(x->x<=tolerance).count()/values.size();}private static double max(List<Double> values){return values.getLast();}
    private static long median(List<PerformanceRow> rows,String implementation){List<Long> values=rows.stream().filter(x->x.implementation.equals(implementation)).map(x->x.wallNanos).sorted().toList();return values.get(1);}
    private static long usedHeap(){Runtime r=Runtime.getRuntime();return r.totalMemory()-r.freeMemory();}
    private static long cpuTime(){var bean=ManagementFactory.getOperatingSystemMXBean();return bean instanceof com.sun.management.OperatingSystemMXBean os?os.getProcessCpuTime():-1;}
    private static long cpuDelta(long before){long now=cpuTime();return before<0||now<0?-1:now-before;}
    private static long allocatedBytes(){var bean=ManagementFactory.getThreadMXBean();return bean instanceof com.sun.management.ThreadMXBean thread&&thread.isThreadAllocatedMemorySupported()?thread.getThreadAllocatedBytes(Thread.currentThread().threadId()):-1;}
    private static long allocationDelta(long before){long now=allocatedBytes();return before<0||now<0?-1:now-before;}
    private static String oracleCsv(List<OracleRow> rows){StringBuilder out=new StringBuilder("radius,numerical_count,analytic_count,max_total_derivative_error,max_bare_derivative_error,max_log_error,max_base_error,fraction_within_primary_tolerance,passes\n");for(var r:rows)out.append(String.format(Locale.ROOT,"%.1f,%d,%d,%.17g,%.17g,%.17g,%.17g,%.17g,%s%n",r.radius,r.numericalCount,r.analyticCount,r.maxTotal,r.maxBare,r.maxLog,r.maxBase,r.fractionWithin,r.passes));return out.toString();}
    private static String comparisonCsv(List<ComparisonRow> rows){StringBuilder out=new StringBuilder("radius,numerical_force,analytic_force,force_difference,numerical_variance,analytic_variance,variance_difference,numerical_se,analytic_se,se_relative_difference,numerical_traversals,analytic_traversals,numerical_median_wall_ns,analytic_median_wall_ns,speedup,replay_bitwise,equivalent,faster\n");for(var r:rows)out.append(String.format(Locale.ROOT,"%.1f,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%d,%d,%d,%d,%.17g,%s,%s,%s%n",r.radius,r.numericalForce,r.analyticForce,r.forceDifference,r.numericalVariance,r.analyticVariance,r.varianceDifference,r.numericalSe,r.analyticSe,r.seRelativeDifference,r.numericalTraversals,r.analyticTraversals,r.numericalMedianWall,r.analyticMedianWall,r.speedup,r.replayBitwise,r.passes,r.faster));return out.toString();}
    private static String performanceCsv(List<PerformanceRow> rows){StringBuilder out=new StringBuilder("radius,implementation,replay,wall_ns,cpu_ns,allocated_bytes,peak_observed_heap_bytes,state_traversals,local_energy_evaluations,directional_ad_passes\n");for(var r:rows)out.append(String.format(Locale.ROOT,"%.1f,%s,%d,%d,%d,%d,%d,%d,%d,%d%n",r.radius,r.implementation,r.replay,r.wallNanos,r.cpuNanos,r.allocatedBytes,r.peakHeapBytes,r.stateTraversals,r.localEnergyEvaluations,r.directionalPasses));return out.toString();}
    private static String exactJsonl(String classification,List<OracleRow> oracle,List<ComparisonRow> comparisons){StringBuilder out=new StringBuilder();scalar(out,"classification_code",classification.hashCode(),"dimensionless");for(var r:oracle){scalar(out,"R"+r.radius+"_oracle_max_base_error",r.maxBase,"hartree/bohr");}for(var r:comparisons){scalar(out,"R"+r.radius+"_numerical_force",r.numericalForce,"hartree/bohr");scalar(out,"R"+r.radius+"_analytic_force",r.analyticForce,"hartree/bohr");scalar(out,"R"+r.radius+"_speedup",r.speedup,"dimensionless");}return out.toString();}
    private static void scalar(StringBuilder out,String field,double value,String units){out.append(String.format(Locale.ROOT,"{\"field\":\"%s\",\"units\":\"%s\",\"raw_ieee754_bits\":\"0x%016x\",\"hex_float\":\"%s\",\"decimal\":\"%.17g\"}%n",field,units,Double.doubleToRawLongBits(value),Double.toHexString(value),value));}
    private static String report(String classification,List<OracleRow> oracle,List<ComparisonRow> comparisons){StringBuilder out=new StringBuilder("# Analytic Differential SWCT Final Report\n\nClassification: `").append(classification).append("`\n\n");for(var r:oracle)out.append(String.format(Locale.ROOT,"- R=%.1f oracle: %s; max base error %.9g%n",r.radius,r.passes?"PASS":"FAIL",r.maxBase));for(var r:comparisons)out.append(String.format(Locale.ROOT,"- R=%.1f: force difference %.9g Ha/bohr; traversal %d -> %d; median speedup %.3fx; equivalent=%s%n",r.radius,r.forceDifference,r.numericalTraversals,r.analyticTraversals,r.speedup,r.passes));out.append("\nThe frozen numerical estimator is the scientific reference. No H2 state, estimator definition, sample, or historical evidence was changed. Nuclear antisymmetry and zero transverse components follow exactly from the centered scalar bond-coordinate construction; this experiment does not claim a general molecular vector-force implementation.\n");return out.toString();}
    private static String environment(){return "java.version="+System.getProperty("java.version")+"\njava.vendor="+System.getProperty("java.vendor")+"\nos.name="+System.getProperty("os.name")+"\nos.arch="+System.getProperty("os.arch")+"\navailable.processors="+Runtime.getRuntime().availableProcessors()+"\n";}
    private static void verifyProtocol(Path directory)throws IOException{for(String line:Files.readAllLines(directory.resolve("PROTOCOL_SHA256"))){String[] f=line.trim().split("\\s+",2);if(f.length!=2||!sha(directory.resolve(f[1])).equals(f[0]))throw new IllegalStateException("protocol checksum mismatch");}}
    private static void write(Path path,String text)throws IOException{try(FileChannel channel=FileChannel.open(path,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE)){ByteBuffer bytes=StandardCharsets.UTF_8.encode(text);while(bytes.hasRemaining())channel.write(bytes);channel.force(true);}}
    private static void checksums(Path directory,List<String> names)throws IOException{StringBuilder out=new StringBuilder();for(String name:names)out.append(sha(directory.resolve(name))).append("  ").append(name).append('\n');write(directory.resolve("SHA256SUMS"),out.toString());}
    private static String sha(Path path)throws IOException{try{MessageDigest d=MessageDigest.getInstance("SHA-256");try(var in=Files.newInputStream(path)){byte[] b=new byte[8192];int n;while((n=in.read(b))>=0)d.update(b,0,n);}return HexFormat.of().formatHex(d.digest());}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
    private record NumericalContribution(double totalDerivative,double bareDerivative,double logDerivative,double base){}
    private record OracleRow(double radius,long numericalCount,long analyticCount,double maxTotal,double maxBare,double maxLog,double maxBase,double fractionWithin,boolean passes){}
    private record PerformanceRow(double radius,String implementation,int replay,long wallNanos,long cpuNanos,long allocatedBytes,long peakHeapBytes,long stateTraversals,long localEnergyEvaluations,long directionalPasses){}
    private record ComparisonRow(double radius,double numericalForce,double analyticForce,double forceDifference,double numericalVariance,double analyticVariance,double varianceDifference,double numericalSe,double analyticSe,double seRelativeDifference,long numericalTraversals,long analyticTraversals,long numericalMedianWall,long analyticMedianWall,double speedup,boolean replayBitwise,boolean passes,boolean faster){}
    private record BenchmarkResult(ComparisonRow comparison,List<PerformanceRow> performance){}
}
