package totah.lab.prometheus.validation;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;

import totah.lab.prometheus.numerics.FixedPreconditioners;
import totah.lab.prometheus.numerics.Preconditioner;
import totah.lab.prometheus.numerics.StreamingCovarianceOperator;

/** One-shot execution of the locked E5 solver-convergence study. */
public final class MatrixFreeSrSolverConvergenceExperiment {
    private MatrixFreeSrSolverConvergenceExperiment(){}

    public static void main(String[] args)throws IOException{
        if(args.length!=3)throw new IllegalArgumentException("protocol, frozen E4 results, and output directories required");Path protocol=Path.of(args[0]),predecessor=Path.of(args[1]),output=Path.of(args[2]);verifyManifest(protocol.resolve("PROTOCOL_SHA256"),protocol);verifyManifest(predecessor.resolve("SHA256SUMS"),predecessor);Files.createDirectories(output);if(Files.exists(output.resolve("MATRIX_FREE_SR_SOLVER_CONVERGENCE_DECISION.json")))throw new IllegalStateException("one-shot evidence exists");
        var control=MatrixFreeSrExperiment.frozenSolverControl();double[][] damped=damped(control.covariance(),control.damping());double[] rhs=negate(control.matrixFreeGradient()),denseDelta=solve(damped,negate(control.denseGradient()));Spectrum spectrum=spectrum(damped);boolean spd=spectrum.minimum>0;
        List<Preconditioner> preconditioners=List.of(FixedPreconditioners.identity(20),FixedPreconditioners.diagonal(control.diagonal()),FixedPreconditioners.blocks(20,control.blocks()));List<Row> rows=new ArrayList<>();List<String> traceNames=new ArrayList<>();
        for(Preconditioner preconditioner:preconditioners)for(var mode:SolverConvergencePcg.Mode.values()){
            var operator=new StreamingCovarianceOperator(20,control.source(),control.damping());long start=System.nanoTime();var result=new SolverConvergencePcg().solve(operator,preconditioner,rhs,mode);long wall=System.nanoTime()-start;double max=maxDifference(result.solution(),denseDelta),rms=rmsDifference(result.solution(),denseDelta),denseDecrease=quadratic(control.denseGradient(),denseDelta,damped),candidateDecrease=quadratic(control.denseGradient(),result.solution(),damped),decreaseError=Math.abs(denseDecrease-candidateDecrease),relative=result.trueResidual()/norm(rhs);var replayOperator=new StreamingCovarianceOperator(20,control.source(),control.damping());var replay=new SolverConvergencePcg().solve(replayOperator,preconditioner,rhs,mode);boolean deterministic=bitwise(result,replay);boolean pass=result.converged()&&!result.breakdown()&&relative<=1e-12&&max<=1e-9&&rms<=2e-10&&decreaseError<=1e-10&&deterministic;rows.add(new Row(preconditioner.identity(),mode.name(),result.iterations(),result.operatorApplications(),result.recursiveResidual(),result.trueResidual(),relative,result.residualGap(),result.maximumConjugacyLoss(),max,rms,decreaseError,wall,deterministic,result.breakdown(),pass));String traceName="TRACE_"+preconditioner.identity()+"_"+mode.name()+".csv";write(output.resolve(traceName),traceCsv(result.trace(),norm(rhs)));traceNames.add(traceName);
        }
        boolean blockPass=rows.stream().anyMatch(r->r.preconditioner.equals("BLOCK_BY_WAVEFUNCTION_COMPONENT")&&r.passes),allPass=preconditioners.stream().allMatch(p->rows.stream().anyMatch(r->r.preconditioner.equals(p.identity())&&r.passes)),anyBreakdown=rows.stream().anyMatch(Row::breakdown);boolean inherited=Files.readString(predecessor.resolve("MATRIX_FREE_SR_DECISION.json")).contains("\"operator_equivalent\":true")&&Files.readString(predecessor.resolve("MATRIX_FREE_SR_DECISION.json")).contains("\"scaling_passes\":true");String classification=!spd||anyBreakdown?"MATRIX_FREE_SR_SOLVER_CORRECTNESS_DEFECT":allPass?"GENERAL_MATRIX_FREE_SR_SOLVER_CONVERGENCE_QUALIFIED":blockPass&&inherited?"BLOCK_PRECONDITIONED_MATRIX_FREE_SR_QUALIFIED":"MATRIX_FREE_SR_TIGHT_TOLERANCE_LIMIT_CONFIRMED";
        List<String> hypotheses=hypotheses(rows);write(output.resolve("SOLVER_CONVERGENCE_RESULTS.csv"),rowsCsv(rows));write(output.resolve("SR_SYSTEM_CONDITIONING.json"),String.format(Locale.ROOT,"{\"minimum_eigenvalue\":%.17g,\"maximum_eigenvalue\":%.17g,\"condition_number\":%.17g,\"spd\":%s,\"damping\":%.17g}%n",spectrum.minimum,spectrum.maximum,spectrum.maximum/spectrum.minimum,spd,control.damping()));write(output.resolve("SOLVER_CONVERGENCE_DIAGNOSIS.md"),report(classification,rows,spectrum,hypotheses,inherited));write(output.resolve("MATRIX_FREE_SR_SOLVER_CONVERGENCE_DECISION.json"),decision(classification,hypotheses,blockPass,allPass,spd,inherited));write(output.resolve("SOFTWARE_ENVIRONMENT.txt"),environment());List<String> names=new ArrayList<>(List.of("SOLVER_CONVERGENCE_RESULTS.csv","SR_SYSTEM_CONDITIONING.json","SOLVER_CONVERGENCE_DIAGNOSIS.md","MATRIX_FREE_SR_SOLVER_CONVERGENCE_DECISION.json","SOFTWARE_ENVIRONMENT.txt"));names.addAll(traceNames);checksums(output,names);
    }

    private static List<String> hypotheses(List<Row> rows){List<String> out=new ArrayList<>();for(String p:List.of("NONE","DIAGONAL","BLOCK_BY_WAVEFUNCTION_COMPONENT")){Row base=find(rows,p,"BASELINE_RECURSIVE_PCG"),truth=find(rows,p,"PCG_TRUE_RESIDUAL"),comp=find(rows,p,"PCG_TRUE_RESIDUAL_COMPENSATED");if(!base.passes&&truth.passes&&base.residualGap>0)out.add("RECURSIVE_RESIDUAL_DRIFT:"+p);if(!truth.passes&&comp.passes)out.add("FLOATING_POINT_REDUCTION_LIMIT:"+p);if(Math.max(base.conjugacyLoss,Math.max(truth.conjugacyLoss,comp.conjugacyLoss))>1e-10)out.add("KRYLOV_CONJUGACY_LOSS:"+p);}boolean block=rows.stream().anyMatch(r->r.preconditioner.equals("BLOCK_BY_WAVEFUNCTION_COMPONENT")&&r.passes),other=rows.stream().anyMatch(r->!r.preconditioner.equals("BLOCK_BY_WAVEFUNCTION_COMPONENT")&&r.passes);if(block&&!other)out.add("STRUCTURED_PRECONDITIONING_REQUIRED");if(out.isEmpty())out.add("NO_SINGLE_DIAGNOSTIC_CAUSE_ESTABLISHED");return List.copyOf(out);}
    private static Row find(List<Row> rows,String p,String mode){return rows.stream().filter(r->r.preconditioner.equals(p)&&r.mode.equals(mode)).findFirst().orElseThrow();}
    private static boolean bitwise(SolverConvergencePcg.Result a,SolverConvergencePcg.Result b){if(a.iterations()!=b.iterations()||a.operatorApplications()!=b.operatorApplications()||a.converged()!=b.converged())return false;if(Double.doubleToRawLongBits(a.trueResidual())!=Double.doubleToRawLongBits(b.trueResidual()))return false;double[] x=a.solution(),y=b.solution();for(int i=0;i<x.length;i++)if(Double.doubleToRawLongBits(x[i])!=Double.doubleToRawLongBits(y[i]))return false;return true;}
    private static String traceCsv(List<SolverConvergencePcg.Trace> traces,double rhsNorm){StringBuilder o=new StringBuilder("iteration,recursive_residual,true_residual,true_relative_residual,residual_gap\n");for(var t:traces)o.append(String.format(Locale.ROOT,"%d,%.17g,%.17g,%.17g,%.17g%n",t.iteration(),t.recursiveResidual(),t.trueResidual(),t.trueResidual()/rhsNorm,t.residualGap()));return o.toString();}
    private static String rowsCsv(List<Row> rows){StringBuilder o=new StringBuilder("preconditioner,solver,iterations,operator_applications,recursive_residual,true_residual,true_relative_residual,residual_gap,max_A_conjugacy_loss,max_update_error,rms_update_error,predicted_decrease_error,wall_ns,deterministic_replay,breakdown,passes\n");for(var r:rows)o.append(String.format(Locale.ROOT,"%s,%s,%d,%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%d,%s,%s,%s%n",r.preconditioner,r.mode,r.iterations,r.applications,r.recursiveResidual,r.trueResidual,r.trueRelativeResidual,r.residualGap,r.conjugacyLoss,r.maxUpdateError,r.rmsUpdateError,r.decreaseError,r.wallNanos,r.deterministic,r.breakdown,r.passes));return o.toString();}
    private static String report(String classification,List<Row> rows,Spectrum spectrum,List<String> hypotheses,boolean inherited){StringBuilder o=new StringBuilder("# Matrix-Free SR Solver-Convergence Diagnosis\n\nClassification: `").append(classification).append("`\n\nThe E4 negative result remains unchanged. The covariance operator, H2 state, damping, target, and gates were not altered.\n\n- damped minimum eigenvalue: ").append(String.format(Locale.ROOT,"%.8g",spectrum.minimum)).append("\n- damped maximum eigenvalue: ").append(String.format(Locale.ROOT,"%.8g",spectrum.maximum)).append("\n- spectral condition number: ").append(String.format(Locale.ROOT,"%.8g",spectrum.maximum/spectrum.minimum)).append("\n- inherited E4 operator/scaling gates: ").append(inherited).append("\n\n## Solver results\n\n");for(var r:rows)o.append(String.format(Locale.ROOT,"- %s / %s: iterations=%d, true relative residual=%.3g, residual gap=%.3g, max update error=%.3g, A-conjugacy loss=%.3g, pass=%s%n",r.preconditioner,r.mode,r.iterations,r.trueRelativeResidual,r.residualGap,r.maxUpdateError,r.conjugacyLoss,r.passes));o.append("\n## Supported diagnoses\n\n");for(String h:hypotheses)o.append("- `").append(h).append("`\n");o.append("\nNo scientific model or target changed.\n");return o.toString();}
    private static String decision(String classification,List<String> hypotheses,boolean block,boolean all,boolean spd,boolean inherited){String quoted=hypotheses.stream().map(x->"\""+x+"\"").reduce((a,b)->a+","+b).orElse("");return String.format(Locale.ROOT,"{\"classification\":\"%s\",\"block_qualified\":%s,\"all_preconditioners_have_passing_variant\":%s,\"system_spd\":%s,\"e4_operator_and_scaling_inherited\":%s,\"supported_diagnoses\":[%s]}%n",classification,block,all,spd,inherited,quoted);}

    private static Spectrum spectrum(double[][] source){double[][] a=copy(source);int n=a.length;for(int sweep=0;sweep<100*n*n;sweep++){int p=0,q=1;double max=0;for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)if(Math.abs(a[i][j])>max){max=Math.abs(a[i][j]);p=i;q=j;}if(max<1e-15)break;double angle=.5*Math.atan2(2*a[p][q],a[q][q]-a[p][p]),c=Math.cos(angle),s=Math.sin(angle);for(int k=0;k<n;k++){if(k==p||k==q)continue;double kp=a[k][p],kq=a[k][q];a[k][p]=a[p][k]=c*kp-s*kq;a[k][q]=a[q][k]=s*kp+c*kq;}double pp=a[p][p],qq=a[q][q],pq=a[p][q];a[p][p]=c*c*pp-2*s*c*pq+s*s*qq;a[q][q]=s*s*pp+2*s*c*pq+c*c*qq;a[p][q]=a[q][p]=0;}double min=Double.POSITIVE_INFINITY,max=Double.NEGATIVE_INFINITY;for(int i=0;i<n;i++){min=Math.min(min,a[i][i]);max=Math.max(max,a[i][i]);}return new Spectrum(min,max);}
    private static double[][] damped(double[][] source,double lambda){double[][] out=copy(source);for(int i=0;i<out.length;i++)out[i][i]+=lambda;return out;}private static double[][] copy(double[][] source){double[][] out=new double[source.length][];for(int i=0;i<out.length;i++)out[i]=source[i].clone();return out;}
    private static double[] solve(double[][] matrix,double[] rhs){int n=rhs.length;double[][] a=new double[n][n+1];for(int i=0;i<n;i++){System.arraycopy(matrix[i],0,a[i],0,n);a[i][n]=rhs[i];}for(int p=0;p<n;p++){int selected=p;for(int r=p+1;r<n;r++)if(Math.abs(a[r][p])>Math.abs(a[selected][p]))selected=r;double[] swap=a[p];a[p]=a[selected];a[selected]=swap;for(int r=p+1;r<n;r++){double factor=a[r][p]/a[p][p];for(int c=p;c<=n;c++)a[r][c]-=factor*a[p][c];}}double[] x=new double[n];for(int r=n-1;r>=0;r--){double v=a[r][n];for(int c=r+1;c<n;c++)v-=a[r][c]*x[c];x[r]=v/a[r][r];}return x;}
    private static double quadratic(double[] g,double[] x,double[][] a){double[] ax=apply(a,x);return dot(g,x)+.5*dot(x,ax);}private static double[] apply(double[][] a,double[] x){double[] y=new double[x.length];for(int i=0;i<y.length;i++)for(int j=0;j<x.length;j++)y[i]+=a[i][j]*x[j];return y;}private static double dot(double[] a,double[] b){double s=0;for(int i=0;i<a.length;i++)s+=a[i]*b[i];return s;}private static double norm(double[] x){return Math.sqrt(dot(x,x));}private static double[] negate(double[] x){double[] y=x.clone();for(int i=0;i<y.length;i++)y[i]=-y[i];return y;}private static double maxDifference(double[] a,double[] b){double m=0;for(int i=0;i<a.length;i++)m=Math.max(m,Math.abs(a[i]-b[i]));return m;}private static double rmsDifference(double[] a,double[] b){double s=0;for(int i=0;i<a.length;i++){double d=a[i]-b[i];s+=d*d;}return Math.sqrt(s/a.length);}
    private static void verifyManifest(Path manifest,Path directory)throws IOException{for(String line:Files.readAllLines(manifest)){if(line.isBlank())continue;String[] f=line.trim().split("\\s+",2);if(f.length!=2||!sha(directory.resolve(f[1])).equals(f[0]))throw new IllegalStateException("checksum mismatch: "+line);}}
    private static void write(Path path,String value)throws IOException{try(FileChannel channel=FileChannel.open(path,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE)){ByteBuffer buffer=StandardCharsets.UTF_8.encode(value);while(buffer.hasRemaining())channel.write(buffer);channel.force(true);}}
    private static void checksums(Path directory,List<String> names)throws IOException{StringBuilder out=new StringBuilder();for(String name:names)out.append(sha(directory.resolve(name))).append("  ").append(name).append('\n');write(directory.resolve("SHA256SUMS"),out.toString());}
    private static String sha(Path path)throws IOException{try{MessageDigest digest=MessageDigest.getInstance("SHA-256");try(var input=Files.newInputStream(path)){byte[] buffer=new byte[8192];int count;while((count=input.read(buffer))>=0)digest.update(buffer,0,count);}return HexFormat.of().formatHex(digest.digest());}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
    private static String environment(){return "java.version="+System.getProperty("java.version")+"\njava.vendor="+System.getProperty("java.vendor")+"\nos.name="+System.getProperty("os.name")+"\nos.arch="+System.getProperty("os.arch")+"\navailable.processors="+Runtime.getRuntime().availableProcessors()+"\n";}
    private record Spectrum(double minimum,double maximum){}private record Row(String preconditioner,String mode,int iterations,int applications,double recursiveResidual,double trueResidual,double trueRelativeResidual,double residualGap,double conjugacyLoss,double maxUpdateError,double rmsUpdateError,double decreaseError,long wallNanos,boolean deterministic,boolean breakdown,boolean passes){}
}
