package totah.lab.prometheus.validation;

import java.io.IOException;
import java.lang.management.ManagementFactory;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;

import totah.lab.prometheus.neural.GeometryConditionedHydrogenMoleculeState;
import totah.lab.prometheus.numerics.FixedPreconditioners;
import totah.lab.prometheus.numerics.LinearOperator;
import totah.lab.prometheus.numerics.PreconditionedConjugateGradientSolver;
import totah.lab.prometheus.numerics.Preconditioner;
import totah.lab.prometheus.numerics.StreamingCovarianceOperator;
import totah.lab.prometheus.variational.HydrogenMoleculeHamiltonian;
import totah.lab.prometheus.variational.HydrogenMoleculeImportanceBatches;
import totah.lab.prometheus.variational.ParameterVector;

/** One-shot matrix-free SR equivalence, preconditioning, and scaling experiment. */
public final class MatrixFreeSrExperiment {
    private static final double[] RADII={.8,1,1.2,1.4,1.6,2,3,4,6};private static final double LAMBDA=1e-3;
    private static final ParameterVector PARAMETERS=new ParameterVector(List.of(.8576772116910546,.11919655001255025,-.06709570692540537,.04370894911240642,-.32732397143757097,.21519667708138937,-.06386208428749664,.04232059707741613,.017563345336565027,-.12118637444956007,.11444052280585346,.26554487072063354,.19811737981250818,.07860098998305089,-.2778578205251936,-.16701609069702947,.07580798604963333,-.15755013283163458,.22812063643399538,-.1453261891402233));
    private MatrixFreeSrExperiment(){ }

    static SolverControl frozenSolverControl(){
        DenseStats dense=denseStats();MatrixFreeStats matrixFree=matrixFreeStats();
        return new SolverControl(dense.gradient,dense.covariance,matrixFree.gradient,
                matrixFree.diagonal,matrixFree.blocks,matrixFree.source,LAMBDA);
    }

    public static void main(String[] args)throws IOException{if(args.length!=2)throw new IllegalArgumentException("protocol and output directories required");Path protocol=Path.of(args[0]),output=Path.of(args[1]);verify(protocol);Files.createDirectories(output);if(Files.exists(output.resolve("MATRIX_FREE_SR_DECISION.json")))throw new IllegalStateException("one-shot evidence exists");long denseStart=System.nanoTime();DenseStats dense=denseStats();double[] denseDelta=negate(solve(dense.covariance,dense.gradient,LAMBDA));long denseWall=System.nanoTime()-denseStart;long mfStart=System.nanoTime();MatrixFreeStats mf=matrixFreeStats();long mfSetupWall=System.nanoTime()-mfStart;
        var operator=new StreamingCovarianceOperator(20,mf.source,LAMBDA);List<ProductRow> products=products(operator,dense.covariance);List<SolveRow> solves=new ArrayList<>();for(Preconditioner p:preconditioners(mf)){solves.add(solveRow(p,operator,mf.gradient,denseDelta,dense.covariance));}
        boolean productsPass=products.stream().allMatch(ProductRow::passes),solvesPass=solves.stream().allMatch(SolveRow::passes);boolean replay=replay(mf,denseDelta,solves);
        List<ScalingRow> scaling=new ArrayList<>();boolean solverStable=true;try{for(int p:new int[]{64,256,1024})scaling.addAll(scale(p));}catch(RuntimeException exception){solverStable=false;write(output.resolve("SCALING_FAILURE.txt"),exception.toString()+"\n");}
        boolean scalable=solverStable&&scaling.stream().filter(r->r.implementation.equals("MATRIX_FREE_BLOCK")).allMatch(r->r.converged&&r.wallNanos<600_000_000_000L&&r.peakHeapBytes<(1L<<30));boolean structured=solves.stream().filter(r->r.preconditioner.equals("BLOCK_BY_WAVEFUNCTION_COMPONENT")).findFirst().map(block->solves.stream().filter(r->r.preconditioner.equals("NONE")).findFirst().map(none->block.iterations<none.iterations||block.wallNanos<none.wallNanos).orElse(false)).orElse(false);
        String classification=!productsPass||!solvesPass?"MATRIX_FREE_SR_NOT_EQUIVALENT":!replay?"MATRIX_FREE_SR_CORRECTNESS_DEFECT":!solverStable?"MATRIX_FREE_SR_SOLVER_INSTABILITY":scalable&&structured?"MATRIX_FREE_SR_EQUIVALENT_AND_SCALABLE":"MATRIX_FREE_SR_EQUIVALENT_NOT_BENEFICIAL";
        write(output.resolve("SR_OPERATOR_EQUIVALENCE.csv"),productCsv(products));write(output.resolve("SR_SOLVER_COMPARISON.csv"),solveCsv(solves,denseWall,mfSetupWall));write(output.resolve("SR_SCALING.csv"),scalingCsv(scaling));write(output.resolve("SR_EXACT_SCALARS.jsonl"),exactScalars(classification,products,solves));write(output.resolve("MATRIX_FREE_SR_DECISION.json"),String.format(Locale.ROOT,"{\"classification\":\"%s\",\"operator_equivalent\":%s,\"updates_equivalent\":%s,\"deterministic_replay\":%s,\"structured_preconditioning_beneficial\":%s,\"scaling_passes\":%s,\"dense_control_wall_ns\":%d,\"matrix_free_setup_wall_ns\":%d}%n",classification,productsPass,solvesPass,replay,structured,scalable,denseWall,mfSetupWall));write(output.resolve("MATRIX_FREE_SR_FINAL_REPORT.md"),report(classification,products,solves,scaling,denseWall,mfSetupWall,structured));write(output.resolve("SOFTWARE_ENVIRONMENT.txt"),environment());checksums(output,List.of("SR_OPERATOR_EQUIVALENCE.csv","SR_SOLVER_COMPARISON.csv","SR_SCALING.csv","SR_EXACT_SCALARS.jsonl","MATRIX_FREE_SR_DECISION.json","MATRIX_FREE_SR_FINAL_REPORT.md","SOFTWARE_ENVIRONMENT.txt"));}

    private static DenseStats denseStats(){int p=20;double[][] covariance=new double[p][p];double[] gradient=new double[p];for(double radius:RADII){Raw raw=raw(radius,true,true);for(int i=0;i<p;i++){gradient[i]+=raw.gradient[i]/RADII.length;for(int j=0;j<p;j++)covariance[i][j]+=raw.covariance[i][j]/RADII.length;}}return new DenseStats(gradient,covariance);}
    private static MatrixFreeStats matrixFreeStats(){int p=20;double[] gradient=new double[p],diagonal=new double[p];double[][][] blocks=new double[5][4][4];double[][] means=new double[RADII.length][p],norms=new double[RADII.length][];for(int r=0;r<RADII.length;r++){Raw raw=raw(RADII[r],false,true);means[r]=raw.mean;norms[r]=new double[]{raw.norm};for(int i=0;i<p;i++){gradient[i]+=raw.gradient[i]/RADII.length;diagonal[i]+=raw.diagonal[i]/RADII.length;}for(int b=0;b<5;b++)for(int i=0;i<4;i++)for(int j=0;j<4;j++)blocks[b][i][j]+=raw.blocks[b][i][j]/RADII.length;}
        StreamingCovarianceOperator.CenteredObservationSource source=consumer->{for(int r=0;r<RADII.length;r++){final int radiusIndex=r;double radius=RADII[r],norm=norms[r][0];var state=new GeometryConditionedHydrogenMoleculeState(radius,PARAMETERS);batches(radius).forEachBatch(batch->batch.forEach(point->{var e=state.evaluateWithGeometryDerivatives(point.coordinates()).stateEvaluation();double psi=e.value().real();if(!Double.isFinite(psi)||Math.abs(psi)<1e-14)return;double weight=point.weight()*psi*psi/norm/RADII.length;double[] centered=new double[20];for(int i=0;i<20;i++)centered[i]=e.parameterGradient().derivatives().get(i).real()/psi-means[radiusIndex][i];consumer.accept(weight,centered);}));}};
        for(int i=0;i<p;i++)diagonal[i]+=LAMBDA;List<FixedPreconditioners.Block> blockList=new ArrayList<>();for(int b=0;b<5;b++){for(int i=0;i<4;i++)blocks[b][i][i]+=LAMBDA;blockList.add(new FixedPreconditioners.Block(4*b,4*b+4,blocks[b]));}return new MatrixFreeStats(gradient,diagonal,blockList,source);}
    private static Raw raw(double radius,boolean full,boolean structured){int p=20;var state=new GeometryConditionedHydrogenMoleculeState(radius,PARAMETERS);var h=new HydrogenMoleculeHamiltonian(radius);Moments m=new Moments(p,full,structured);batches(radius).forEachBatch(batch->batch.forEach(point->{var e=state.evaluateWithGeometryDerivatives(point.coordinates()).stateEvaluation();double psi=e.value().real();if(!Double.isFinite(psi)||Math.abs(psi)<1e-14)return;double q=point.weight()*psi*psi,local=-.5*e.coordinateLaplacian().value().real()/psi+h.potential(point.coordinates());double[] o=new double[p];for(int i=0;i<p;i++)o[i]=e.parameterGradient().derivatives().get(i).real()/psi;m.norm+=q;m.energy+=q*local;for(int i=0;i<p;i++){m.o[i]+=q*o[i];m.oe[i]+=q*o[i]*local;m.diagonalRaw[i]+=q*o[i]*o[i];if(full)for(int j=0;j<p;j++)m.oo[i][j]+=q*o[i]*o[j];}if(structured)for(int b=0;b<5;b++)for(int i=0;i<4;i++)for(int j=0;j<4;j++)m.blocksRaw[b][i][j]+=q*o[4*b+i]*o[4*b+j];}));double energy=m.energy/m.norm;double[] mean=new double[p],gradient=new double[p],diagonal=new double[p];double[][] covariance=full?new double[p][p]:null;double[][][] blocks=new double[5][4][4];for(int i=0;i<p;i++){mean[i]=m.o[i]/m.norm;gradient[i]=2*(m.oe[i]/m.norm-mean[i]*energy);diagonal[i]=m.diagonalRaw[i]/m.norm-mean[i]*mean[i];if(full)for(int j=0;j<p;j++)covariance[i][j]=m.oo[i][j]/m.norm-mean[i]*(m.o[j]/m.norm);}if(structured)for(int b=0;b<5;b++)for(int i=0;i<4;i++)for(int j=0;j<4;j++)blocks[b][i][j]=m.blocksRaw[b][i][j]/m.norm-mean[4*b+i]*mean[4*b+j];return new Raw(m.norm,mean,gradient,diagonal,covariance,blocks);}
    private static List<Preconditioner> preconditioners(MatrixFreeStats mf){return List.of(FixedPreconditioners.identity(20),FixedPreconditioners.diagonal(mf.diagonal),FixedPreconditioners.blocks(20,mf.blocks));}
    private static List<ProductRow> products(StreamingCovarianceOperator operator,double[][] covariance){List<double[]> vectors=List.of(unit(20),alternating(20),hashed(20));List<ProductRow> rows=new ArrayList<>();for(int k=0;k<vectors.size();k++){double[] explicit=matrixApply(covariance,vectors.get(k),LAMBDA),actual=operator.apply(vectors.get(k));double max=0,square=0;for(int i=0;i<20;i++){double error=Math.abs(actual[i]-explicit[i]);max=Math.max(max,error);square+=error*error;}double rms=Math.sqrt(square/20);rows.add(new ProductRow(k,max,rms,max<=1e-11&&rms<=2e-12));}return rows;}
    private static SolveRow solveRow(Preconditioner preconditioner,StreamingCovarianceOperator operator,double[] gradient,double[] denseDelta,double[][] covariance){double[] rhs=negate(gradient);long heap=usedHeap(),cpu=cpuTime(),start=System.nanoTime();var result=new PreconditionedConjugateGradientSolver().solve(operator,preconditioner,rhs,new PreconditionedConjugateGradientSolver.Configuration(200,1e-12,1e-14));long wall=System.nanoTime()-start;double max=0,square=0;for(int i=0;i<20;i++){double error=Math.abs(result.solution()[i]-denseDelta[i]);max=Math.max(max,error);square+=error*error;}double rms=Math.sqrt(square/20),denseDecrease=quadratic(gradient,denseDelta,covariance),actualDecrease=quadratic(gradient,result.solution(),covariance);boolean pass=result.converged()&&max<=1e-9&&rms<=2e-10&&Math.abs(denseDecrease-actualDecrease)<=1e-10&&result.relativeResidual()<=1e-12;return new SolveRow(preconditioner.identity(),result.iterations(),result.operatorApplications(),result.absoluteResidual(),result.relativeResidual(),max,rms,denseDecrease,actualDecrease,Math.abs(denseDecrease-actualDecrease),wall,cpuDelta(cpu),Math.max(heap,usedHeap()),operator.counters().streamedPasses(),pass);}
    private static boolean replay(MatrixFreeStats mf,double[] denseDelta,List<SolveRow> original){var operator=new StreamingCovarianceOperator(20,mf.source,LAMBDA);List<SolveRow> replay=new ArrayList<>();for(Preconditioner p:preconditioners(mf))replay.add(solveRow(p,operator,mf.gradient,denseDelta,denseStats().covariance));for(int i=0;i<original.size();i++){SolveRow a=original.get(i),b=replay.get(i);if(a.iterations!=b.iterations||a.operatorApplications!=b.operatorApplications||Double.doubleToRawLongBits(a.absoluteResidual)!=Double.doubleToRawLongBits(b.absoluteResidual)||Double.doubleToRawLongBits(a.maxUpdateError)!=Double.doubleToRawLongBits(b.maxUpdateError))return false;}return true;}

    private static List<ScalingRow> scale(int p){int n=4096,block=16;Synthetic source=new Synthetic(p,n);long explicitBytes=8L*p*p;double[][] explicit=null;long explicitWall=-1;if(p<=256){long start=System.nanoTime();explicit=source.dense(LAMBDA);explicitWall=System.nanoTime()-start;}else{explicit=new double[p][p];long start=System.nanoTime();matrixApply(explicit,hashed(p),0);explicitWall=System.nanoTime()-start;}double[] diagonal=source.diagonal(LAMBDA);List<FixedPreconditioners.Block> blocks=source.blocks(block,LAMBDA);double[] rhs=hashed(p);List<ScalingRow> rows=new ArrayList<>();for(Preconditioner preconditioner:List.of(FixedPreconditioners.identity(p),FixedPreconditioners.diagonal(diagonal),FixedPreconditioners.blocks(p,blocks))){var operator=new StreamingCovarianceOperator(p,source::forEach,LAMBDA);long heap=usedHeap(),start=System.nanoTime();var result=new PreconditionedConjugateGradientSolver().solve(operator,preconditioner,rhs,new PreconditionedConjugateGradientSolver.Configuration(200,1e-12,1e-14));long wall=System.nanoTime()-start;double explicitError=Double.NaN;if(p<=256){double[] dense=solveRegularizedAlready(explicit,rhs);explicitError=maxDifference(dense,result.solution());}long candidateBytes=8L*(8L*p+(long)(p/block)*block*block);rows.add(new ScalingRow(p,n,"MATRIX_FREE_"+preconditioner.identity(),result.iterations(),result.operatorApplications(),result.relativeResidual(),wall,Math.max(heap,usedHeap()),candidateBytes,explicitBytes,explicitWall,explicitError,result.converged()&&(p>256||explicitError<=1e-9)));}return rows;}
    private static double quadratic(double[] g,double[] delta,double[][] s){double[] a=matrixApply(s,delta,LAMBDA);return dot(g,delta)+.5*dot(delta,a);}
    private static double[] solve(double[][] s,double[] rhs,double lambda){double[][] a=copy(s);for(int i=0;i<a.length;i++)a[i][i]+=lambda;return solveRegularizedAlready(a,rhs);}
    private static double[] solveRegularizedAlready(double[][] matrix,double[] rhs){int n=rhs.length;double[][] a=new double[n][n+1];for(int i=0;i<n;i++){System.arraycopy(matrix[i],0,a[i],0,n);a[i][n]=rhs[i];}for(int p=0;p<n;p++){int selected=p;for(int r=p+1;r<n;r++)if(Math.abs(a[r][p])>Math.abs(a[selected][p]))selected=r;double[] swap=a[p];a[p]=a[selected];a[selected]=swap;if(Math.abs(a[p][p])<1e-15)throw new IllegalArgumentException("singular dense control");for(int r=p+1;r<n;r++){double factor=a[r][p]/a[p][p];for(int c=p;c<=n;c++)a[r][c]-=factor*a[p][c];}}double[] x=new double[n];for(int r=n-1;r>=0;r--){double value=a[r][n];for(int c=r+1;c<n;c++)value-=a[r][c]*x[c];x[r]=value/a[r][r];}return x;}
    private static double[] matrixApply(double[][] matrix,double[] vector,double lambda){double[] out=new double[vector.length];for(int i=0;i<out.length;i++){for(int j=0;j<out.length;j++)out[i]+=matrix[i][j]*vector[j];out[i]+=lambda*vector[i];}return out;}
    private static double[][] copy(double[][] source){double[][] out=new double[source.length][];for(int i=0;i<out.length;i++)out[i]=source[i].clone();return out;}
    private static double[] negate(double[] x){double[] out=x.clone();for(int i=0;i<out.length;i++)out[i]=-out[i];return out;}private static double dot(double[] a,double[] b){double sum=0;for(int i=0;i<a.length;i++)sum+=a[i]*b[i];return sum;}private static double maxDifference(double[] a,double[] b){double max=0;for(int i=0;i<a.length;i++)max=Math.max(max,Math.abs(a[i]-b[i]));return max;}
    private static double[] unit(int p){double[] v=new double[p];v[0]=1;return v;}private static double[] alternating(int p){double[] v=new double[p];for(int i=0;i<p;i++)v[i]=(i%2==0?1:-1)/Math.sqrt(p);return v;}private static double[] hashed(int p){double[] v=new double[p];for(int i=0;i<p;i++)v[i]=Math.sin((i+1)*12.9898+78.233);return v;}
    private static HydrogenMoleculeImportanceBatches batches(double radius){return new HydrogenMoleculeImportanceBatches(2500,radius,1.15,43,512);}
    private static long usedHeap(){Runtime r=Runtime.getRuntime();return r.totalMemory()-r.freeMemory();}private static long cpuTime(){var b=ManagementFactory.getOperatingSystemMXBean();return b instanceof com.sun.management.OperatingSystemMXBean os?os.getProcessCpuTime():-1;}private static long cpuDelta(long before){long now=cpuTime();return before<0||now<0?-1:now-before;}
    private static String productCsv(List<ProductRow> rows){StringBuilder o=new StringBuilder("vector,max_error,rms_error,passes\n");for(var r:rows)o.append(String.format(Locale.ROOT,"%d,%.17g,%.17g,%s%n",r.vector,r.maxError,r.rmsError,r.passes));return o.toString();}
    private static String solveCsv(List<SolveRow> rows,long denseWall,long setupWall){StringBuilder o=new StringBuilder("preconditioner,iterations,operator_applications,absolute_residual,relative_residual,max_update_error,rms_update_error,dense_predicted_decrease,matrix_free_predicted_decrease,decrease_error,wall_ns,cpu_ns,peak_heap_bytes,cumulative_streamed_passes,passes,dense_control_wall_ns,matrix_free_setup_wall_ns\n");for(var r:rows)o.append(String.format(Locale.ROOT,"%s,%d,%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%d,%d,%d,%d,%s,%d,%d%n",r.preconditioner,r.iterations,r.operatorApplications,r.absoluteResidual,r.relativeResidual,r.maxUpdateError,r.rmsUpdateError,r.denseDecrease,r.actualDecrease,r.decreaseError,r.wallNanos,r.cpuNanos,r.peakHeapBytes,r.streamedPasses,r.passes,denseWall,setupWall));return o.toString();}
    private static String scalingCsv(List<ScalingRow> rows){StringBuilder o=new StringBuilder("P,N,implementation,iterations,operator_applications,relative_residual,wall_ns,peak_heap_bytes,candidate_storage_bytes,explicit_covariance_bytes,explicit_control_wall_ns,explicit_update_max_error,passes\n");for(var r:rows)o.append(String.format(Locale.ROOT,"%d,%d,%s,%d,%d,%.17g,%d,%d,%d,%d,%d,%.17g,%s%n",r.p,r.n,r.implementation,r.iterations,r.applications,r.residual,r.wallNanos,r.peakHeapBytes,r.candidateBytes,r.explicitBytes,r.explicitWallNanos,r.explicitError,r.converged));return o.toString();}
    private static String exactScalars(String classification,List<ProductRow> products,List<SolveRow> solves){StringBuilder o=new StringBuilder();for(var r:products)scalar(o,"operator_vector_"+r.vector+"_max_error",r.maxError,"dimensionless");for(var r:solves){scalar(o,r.preconditioner+"_relative_residual",r.relativeResidual,"dimensionless");scalar(o,r.preconditioner+"_max_update_error",r.maxUpdateError,"dimensionless");}return o.toString();}
    private static void scalar(StringBuilder o,String field,double value,String units){o.append(String.format(Locale.ROOT,"{\"field\":\"%s\",\"units\":\"%s\",\"raw_ieee754_bits\":\"0x%016x\",\"hex_float\":\"%s\",\"decimal\":\"%.17g\"}%n",field,units,Double.doubleToRawLongBits(value),Double.toHexString(value),value));}
    private static String report(String classification,List<ProductRow> products,List<SolveRow> solves,List<ScalingRow> scaling,long denseWall,long setupWall,boolean structured){StringBuilder o=new StringBuilder("# Matrix-Free SR Final Report\n\nClassification: `").append(classification).append("`\n\n- Dense control construction+solve: ").append(denseWall).append(" ns\n- Matrix-free initial statistics: ").append(setupWall).append(" ns\n- Operator equivalence: ").append(products.stream().allMatch(ProductRow::passes)).append("\n- Structured preconditioning beneficial: ").append(structured).append("\n\n");for(var r:solves)o.append(String.format(Locale.ROOT,"- %s: %d iterations, %d operator applications, relative residual %.3g, max update error %.3g, pass=%s%n",r.preconditioner,r.iterations,r.operatorApplications,r.relativeResidual,r.maxUpdateError,r.passes));o.append("\nNo H2 optimization or scientific target changed. Synthetic scaling tests storage/solver behavior only.\n");return o.toString();}
    private static String environment(){return "java.version="+System.getProperty("java.version")+"\njava.vendor="+System.getProperty("java.vendor")+"\nos.name="+System.getProperty("os.name")+"\nos.arch="+System.getProperty("os.arch")+"\navailable.processors="+Runtime.getRuntime().availableProcessors()+"\n";}
    private static void verify(Path d)throws IOException{for(String line:Files.readAllLines(d.resolve("PROTOCOL_SHA256"))){String[] f=line.trim().split("\\s+",2);if(f.length!=2||!sha(d.resolve(f[1])).equals(f[0]))throw new IllegalStateException("protocol checksum mismatch");}}
    private static void write(Path p,String text)throws IOException{try(FileChannel c=FileChannel.open(p,StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE)){ByteBuffer b=StandardCharsets.UTF_8.encode(text);while(b.hasRemaining())c.write(b);c.force(true);}}
    private static void checksums(Path d,List<String> names)throws IOException{StringBuilder o=new StringBuilder();for(String n:names)o.append(sha(d.resolve(n))).append("  ").append(n).append('\n');write(d.resolve("SHA256SUMS"),o.toString());}private static String sha(Path p)throws IOException{try{MessageDigest d=MessageDigest.getInstance("SHA-256");try(var in=Files.newInputStream(p)){byte[] b=new byte[8192];int n;while((n=in.read(b))>=0)d.update(b,0,n);}return HexFormat.of().formatHex(d.digest());}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}

    private record DenseStats(double[] gradient,double[][] covariance){}private record MatrixFreeStats(double[] gradient,double[] diagonal,List<FixedPreconditioners.Block> blocks,StreamingCovarianceOperator.CenteredObservationSource source){}
    record SolverControl(double[] denseGradient,double[][] covariance,double[] matrixFreeGradient,
            double[] diagonal,List<FixedPreconditioners.Block> blocks,
            StreamingCovarianceOperator.CenteredObservationSource source,double damping){}
    private record Raw(double norm,double[] mean,double[] gradient,double[] diagonal,double[][] covariance,double[][][] blocks){}
    private static final class Moments{double norm,energy;final double[] o,oe,diagonalRaw;final double[][] oo;final double[][][] blocksRaw;Moments(int p,boolean full,boolean blocks){o=new double[p];oe=new double[p];diagonalRaw=new double[p];oo=full?new double[p][p]:null;blocksRaw=blocks?new double[5][4][4]:null;}}
    private record ProductRow(int vector,double maxError,double rmsError,boolean passes){}private record SolveRow(String preconditioner,int iterations,int operatorApplications,double absoluteResidual,double relativeResidual,double maxUpdateError,double rmsUpdateError,double denseDecrease,double actualDecrease,double decreaseError,long wallNanos,long cpuNanos,long peakHeapBytes,long streamedPasses,boolean passes){}
    private record ScalingRow(int p,int n,String implementation,int iterations,int applications,double residual,long wallNanos,long peakHeapBytes,long candidateBytes,long explicitBytes,long explicitWallNanos,double explicitError,boolean converged){}

    private static final class Synthetic{final int p,n;final double[] mean;Synthetic(int p,int n){this.p=p;this.n=n;mean=new double[p];for(int s=0;s<n;s++)for(int i=0;i<p;i++)mean[i]+=feature(s,i)/n;}void forEach(StreamingCovarianceOperator.ObservationConsumer c){double w=1.0/n;for(int s=0;s<n;s++){double[] x=new double[p];for(int i=0;i<p;i++)x[i]=feature(s,i)-mean[i];c.accept(w,x);}}double[] diagonal(double lambda){double[] d=new double[p];forEach((w,x)->{for(int i=0;i<p;i++)d[i]+=w*x[i]*x[i];});for(int i=0;i<p;i++)d[i]+=lambda;return d;}List<FixedPreconditioners.Block> blocks(int size,double lambda){List<double[][]> matrices=new ArrayList<>();for(int start=0;start<p;start+=size){int width=Math.min(size,p-start);matrices.add(new double[width][width]);}forEach((w,x)->{for(int b=0;b<matrices.size();b++){double[][] m=matrices.get(b);int start=b*size;for(int i=0;i<m.length;i++)for(int j=0;j<m.length;j++)m[i][j]+=w*x[start+i]*x[start+j];}});List<FixedPreconditioners.Block> out=new ArrayList<>();for(int b=0;b<matrices.size();b++){double[][] m=matrices.get(b);for(int i=0;i<m.length;i++)m[i][i]+=lambda;out.add(new FixedPreconditioners.Block(b*size,b*size+m.length,m));}return out;}double[][] dense(double lambda){double[][] m=new double[p][p];forEach((w,x)->{for(int i=0;i<p;i++)for(int j=0;j<p;j++)m[i][j]+=w*x[i]*x[j];});for(int i=0;i<p;i++)m[i][i]+=lambda;return m;}private static double feature(int s,int i){double independent=unit(mix((((long)s)<<32)^(i&0xffffffffL)));double block=.12*unit(mix((((long)s)<<32)^((i/16+1L)*0x9e3779b97f4a7c15L)));return independent+block;}private static long mix(long z){z=(z^(z>>>30))*0xbf58476d1ce4e5b9L;z=(z^(z>>>27))*0x94d049bb133111ebL;return z^(z>>>31);}private static double unit(long bits){return 2*((bits>>>11)*0x1.0p-53)-1;}}
}
