package totah.lab.prometheus.variational;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import totah.lab.prometheus.molecular.GeneralMolecularCoulombHamiltonian;
import totah.lab.prometheus.neural.GeneralSlaterJastrowState;
import totah.lab.prometheus.numerics.FixedPreconditioners;
import totah.lab.prometheus.numerics.StreamingCovarianceOperator;
import totah.lab.prometheus.numerics.TrueResidualPreconditionedConjugateGradientSolver;

/** General-state adapter for the frozen BLOCK-preconditioned matrix-free SR family. */
public final class GeneralMolecularMatrixFreeSrOptimizer {
    public Result oneIteration(GeneralSlaterJastrowState state,GeneralMolecularCoulombHamiltonian hamiltonian,GeneralMolecularSampleSource samples,Configuration config){Objects.requireNonNull(state);Objects.requireNonNull(hamiltonian);Objects.requireNonNull(samples);Objects.requireNonNull(config);Statistics s=statistics(state,hamiltonian,samples);int p=state.parameters().values().size();List<FixedPreconditioners.Block> blocks=new ArrayList<>();for(int start=0;start<p;start+=config.blockSize()){int end=Math.min(p,start+config.blockSize()),n=end-start;double[][] matrix=new double[n][n];for(int i=0;i<n;i++)for(int j=0;j<n;j++)matrix[i][j]=s.covariance[start+i][start+j];for(int i=0;i<n;i++)matrix[i][i]+=config.damping();blocks.add(new FixedPreconditioners.Block(start,end,matrix));}
        boolean direct=samples instanceof DirectWavefunctionSampleSource;var operator=new StreamingCovarianceOperator(p,consumer->samples.forEach((weight,coordinates)->{var e=state.evaluateWithLocalEnergy(coordinates,hamiltonian);double psi=e.derivatives().value().real();double[] centered=new double[p];for(int i=0;i<p;i++)centered[i]=e.derivatives().parameterGradient().derivatives().get(i).real()/psi-s.mean[i];consumer.accept((direct?weight:weight*psi*psi)/s.weightSum,centered);}),config.damping());double[] rhs=s.gradient.clone();for(int i=0;i<p;i++)rhs[i]=-rhs[i];var solve=new TrueResidualPreconditionedConjugateGradientSolver().solve(operator,FixedPreconditioners.blocks(p,blocks),rhs,new TrueResidualPreconditionedConjugateGradientSolver.Configuration(config.maxSolverIterations(),config.relativeTolerance(),config.absoluteTolerance()));if(!solve.converged())throw new IllegalStateException("general BLOCK matrix-free SR failed true-residual gate");List<Double> next=new ArrayList<>(state.parameters().values());for(int i=0;i<p;i++){double update=Math.max(-config.maxAbsoluteUpdate(),Math.min(config.maxAbsoluteUpdate(),config.learningRate()*solve.solution()[i]));next.set(i,next.get(i)+update);}return new Result(state.withParameters(new ParameterVector(next)),s.energy,solve.relativeTrueResidual(),operator.counters().streamedPasses(),s.evaluations,"BLOCK_PRECONDITIONED_MATRIX_FREE_SR");}
    private static Statistics statistics(GeneralSlaterJastrowState state,GeneralMolecularCoulombHamiltonian h,GeneralMolecularSampleSource samples){int p=state.parameters().values().size();Mutable m=new Mutable(p);boolean direct=samples instanceof DirectWavefunctionSampleSource;samples.forEach((weight,c)->{var e=state.evaluateWithLocalEnergy(c,h);double psi=e.derivatives().value().real(),w=direct?weight:weight*psi*psi,local=e.localEnergy().orElseThrow().totalHartree();double[] o=new double[p];for(int i=0;i<p;i++)o[i]=e.derivatives().parameterGradient().derivatives().get(i).real()/psi;m.weight+=w;m.energy+=w*local;for(int i=0;i<p;i++){m.o[i]+=w*o[i];m.oe[i]+=w*o[i]*local;for(int j=0;j<p;j++)m.oo[i][j]+=w*o[i]*o[j];}m.evaluations++;});if(!(m.weight>0))throw new IllegalArgumentException("empty/zero molecular sample source");double energy=m.energy/m.weight;double[] mean=new double[p],gradient=new double[p];double[][] covariance=new double[p][p];for(int i=0;i<p;i++){mean[i]=m.o[i]/m.weight;gradient[i]=2*(m.oe[i]/m.weight-mean[i]*energy);}for(int i=0;i<p;i++)for(int j=0;j<p;j++)covariance[i][j]=m.oo[i][j]/m.weight-mean[i]*mean[j];return new Statistics(energy,m.weight,mean,gradient,covariance,m.evaluations);}
    public record Configuration(double learningRate,double damping,double maxAbsoluteUpdate,int blockSize,int maxSolverIterations,double relativeTolerance,double absoluteTolerance){public Configuration{if(!(learningRate>0)||!(damping>0)||!(maxAbsoluteUpdate>0)||blockSize<1||maxSolverIterations<1||!(relativeTolerance>0)||!(absoluteTolerance>0))throw new IllegalArgumentException("invalid general SR configuration");}}
    public record Result(GeneralSlaterJastrowState state,double initialEnergyHartree,double relativeTrueResidual,long streamedOperatorPasses,long initialStateEvaluations,String optimizer){}
    private record Statistics(double energy,double weightSum,double[] mean,double[] gradient,double[][] covariance,long evaluations){}
    private static final class Mutable{double weight,energy;long evaluations;final double[] o,oe;final double[][] oo;Mutable(int p){o=new double[p];oe=new double[p];oo=new double[p][p];}}
}
