package totah.lab.prometheus.variational;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.OptionalDouble;

import totah.lab.prometheus.identity.CanonicalHashing;
import totah.lab.prometheus.molecular.GeneralMolecularCoulombHamiltonian;
import totah.lab.prometheus.neural.GeneralSlaterJastrowState;

/** Bounded, read-only scale-readiness diagnostics for a general molecular sample stream. */
public final class GeneralMolecularSamplingDiagnostics {
    public Result evaluate(GeneralSlaterJastrowState state,GeneralMolecularCoulombHamiltonian hamiltonian,GeneralMolecularSampleSource samples){Objects.requireNonNull(state);Objects.requireNonNull(hamiltonian);Objects.requireNonNull(samples);List<Observation> values=new ArrayList<>();StringBuilder replay=new StringBuilder();samples.forEach((weight,coordinates)->{var evaluated=state.evaluateWithLocalEnergy(coordinates,hamiltonian);double psi=evaluated.derivatives().value().real(),effective=weight*psi*psi,energy=evaluated.localEnergy().orElseThrow().totalHartree();values.add(new Observation(weight,effective,energy));replay.append(Long.toHexString(Double.doubleToRawLongBits(weight))).append(':').append(Long.toHexString(Double.doubleToRawLongBits(effective))).append(':').append(Long.toHexString(Double.doubleToRawLongBits(energy))).append('\n');});if(values.isEmpty())throw new IllegalArgumentException("empty diagnostic sample stream");int finite=(int)values.stream().filter(Observation::finite).count();double weightSum=values.stream().mapToDouble(Observation::effectiveWeight).sum();if(!(weightSum>0)||!Double.isFinite(weightSum))throw new IllegalArgumentException("invalid effective diagnostic weights");double weightSquares=values.stream().mapToDouble(v->v.effectiveWeight()*v.effectiveWeight()).sum(),mean=values.stream().mapToDouble(v->v.effectiveWeight()*v.localEnergy()).sum()/weightSum,variance=values.stream().mapToDouble(v->v.effectiveWeight()*square(v.localEnergy()-mean)).sum()/weightSum;List<Observation> tails=new ArrayList<>(values);tails.sort(Comparator.comparingDouble((Observation v)->v.effectiveWeight()*square(v.localEnergy()-mean)).reversed());double denominator=weightSum*variance;return new Result("DETERMINISTIC_HALTON_IMPORTANCE",OptionalDouble.empty(),"NOT_APPLICABLE_NO_MARKOV_PROPOSALS",values.size(),finite,min(values,true),max(values,true),min(values,false),max(values,false),max(values,false)/weightSum,weightSum*weightSum/weightSquares,weightSum*weightSum/weightSquares/values.size(),mean,variance,minEnergy(values),weightedQuantile(values,weightSum,.01),weightedQuantile(values,weightSum,.50),weightedQuantile(values,weightSum,.99),maxEnergy(values),denominator==0?0:tail(tails,Math.max(1,(int)Math.ceil(values.size()*.01)),mean)/denominator,denominator==0?0:tail(tails,Math.max(1,(int)Math.ceil(values.size()*.05)),mean)/denominator,correlation(values,1),correlation(values,2),CanonicalHashing.sha256Hex(replay.toString()));}
    private static double weightedQuantile(List<Observation> input,double total,double probability){List<Observation> sorted=new ArrayList<>(input);sorted.sort(Comparator.comparingDouble(Observation::localEnergy));double target=probability*total,sum=0;for(Observation value:sorted){sum+=value.effectiveWeight;if(sum>=target)return value.localEnergy;}return sorted.getLast().localEnergy;}
    private static double correlation(List<Observation> values,int lag){double mean=values.stream().mapToDouble(Observation::localEnergy).average().orElseThrow(),numerator=0,left=0,right=0;for(int i=lag;i<values.size();i++){double a=values.get(i-lag).localEnergy-mean,b=values.get(i).localEnergy-mean;numerator+=a*b;left+=a*a;right+=b*b;}double denominator=Math.sqrt(left*right);return denominator==0?0:numerator/denominator;}
    private static double tail(List<Observation> values,int count,double mean){double result=0;for(int i=0;i<count;i++){Observation value=values.get(i);result+=value.effectiveWeight*square(value.localEnergy-mean);}return result;}
    private static double min(List<Observation> values,boolean raw){return values.stream().mapToDouble(v->raw?v.rawWeight:v.effectiveWeight).min().orElseThrow();}
    private static double max(List<Observation> values,boolean raw){return values.stream().mapToDouble(v->raw?v.rawWeight:v.effectiveWeight).max().orElseThrow();}
    private static double minEnergy(List<Observation> values){return values.stream().mapToDouble(Observation::localEnergy).min().orElseThrow();}
    private static double maxEnergy(List<Observation> values){return values.stream().mapToDouble(Observation::localEnergy).max().orElseThrow();}
    private static double square(double value){return value*value;}
    private record Observation(double rawWeight,double effectiveWeight,double localEnergy){boolean finite(){return Double.isFinite(rawWeight)&&Double.isFinite(effectiveWeight)&&Double.isFinite(localEnergy)&&rawWeight>0&&effectiveWeight>=0;}}
    public record Result(String samplingMode,OptionalDouble acceptanceRate,String acceptanceStatus,int samples,int finiteSamples,double rawWeightMinimum,double rawWeightMaximum,double effectiveWeightMinimum,double effectiveWeightMaximum,double maximumNormalizedWeight,double effectiveSampleSize,double effectiveSampleFraction,double localEnergyMean,double localEnergyVariance,double localEnergyMinimum,double localEnergyQ01,double localEnergyMedian,double localEnergyQ99,double localEnergyMaximum,double topOnePercentVarianceFraction,double topFivePercentVarianceFraction,double lagOneOrderingCorrelation,double lagTwoOrderingCorrelation,String deterministicReplayHash){public Result{Objects.requireNonNull(samplingMode);Objects.requireNonNull(acceptanceRate);Objects.requireNonNull(acceptanceStatus);Objects.requireNonNull(deterministicReplayHash);if(samples<1||finiteSamples<0||finiteSamples>samples)throw new IllegalArgumentException("invalid diagnostic counts");}public String csv(){return String.format(Locale.ROOT,"%s,%s,%s,%d,%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%s",samplingMode,acceptanceRate.isPresent()?Double.toString(acceptanceRate.getAsDouble()):"NA",acceptanceStatus,samples,finiteSamples,rawWeightMinimum,rawWeightMaximum,effectiveWeightMinimum,effectiveWeightMaximum,maximumNormalizedWeight,effectiveSampleSize,effectiveSampleFraction,localEnergyMean,localEnergyVariance,localEnergyMinimum,localEnergyQ01,localEnergyMedian,localEnergyQ99,localEnergyMaximum,topOnePercentVarianceFraction,topFivePercentVarianceFraction,lagOneOrderingCorrelation,lagTwoOrderingCorrelation,deterministicReplayHash);}}
}
