-- Throwaway schema for integration tests, cloned from the live DDL of
-- totah_lab_db (docking.* plus test copies of the public-side
-- targets/pipeline_runs, with artifacts' foreign keys adjusted to point
-- inside this schema). Rerunnable: drops itself first.
DROP SCHEMA IF EXISTS docking_test CASCADE;
CREATE SCHEMA docking_test;

CREATE TYPE docking_test.pocket_source AS ENUM (
    'FPOCKET', 'P2RANK', 'MANUAL', 'IMPORTED', 'BIOHUB'
);

CREATE SEQUENCE docking_test.receptor_id_seq;
CREATE SEQUENCE docking_test.structure_id_seq;
CREATE SEQUENCE docking_test.residue_id_seq;
CREATE SEQUENCE docking_test.pocket_id_seq;
CREATE SEQUENCE docking_test.pocket_residue_id_seq;
CREATE SEQUENCE docking_test.pocket_atom_id_seq;

-- Test copy of public.targets (inside this schema).
CREATE TABLE docking_test.targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    uniprot_id varchar(255) NOT NULL,
    CONSTRAINT targets_uniprot_unique UNIQUE (uniprot_id)
);

-- Test copy of public.pipeline_runs (inside this schema).
CREATE TABLE docking_test.pipeline_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    end_time timestamp(6),
    start_time timestamp(6),
    status varchar(255) NOT NULL
);

CREATE TABLE docking_test.artifacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    filename varchar(255) NOT NULL,
    label varchar(255) NOT NULL,
    storage_location varchar(1024) NOT NULL,
    pipeline_run_id bigint NOT NULL
        REFERENCES docking_test.pipeline_runs (id),
    target_id bigint NOT NULL
        REFERENCES docking_test.targets (id)
);

CREATE TABLE docking_test.receptor (
    id bigint NOT NULL DEFAULT nextval('docking_test.receptor_id_seq')
        PRIMARY KEY,
    target_name varchar(100),
    pdb_file text,
    pdbqt_file text,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    uniprot_id varchar(20),
    protein_name varchar(255),
    gene_name varchar(50),
    organism varchar(100),
    CONSTRAINT receptor_uniprot_id_unique UNIQUE (uniprot_id)
);

CREATE TABLE docking_test.structure (
    id bigint NOT NULL DEFAULT nextval('docking_test.structure_id_seq')
        PRIMARY KEY,
    receptor_id bigint NOT NULL
        REFERENCES docking_test.receptor (id) ON DELETE CASCADE,
    source varchar(20) NOT NULL,
    source_accession varchar(100),
    chain varchar(10),
    model_number integer,
    preparation_state varchar(20) NOT NULL DEFAULT 'RAW',
    parent_structure_id bigint
        REFERENCES docking_test.structure (id) ON DELETE RESTRICT,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    artifact_id bigint NOT NULL
        REFERENCES docking_test.artifacts (id) ON DELETE RESTRICT,
    chosen_pocket_id bigint,
    CONSTRAINT structure_model_number_check
        CHECK (model_number IS NULL OR model_number > 0),
    CONSTRAINT structure_not_own_parent_check
        CHECK (parent_structure_id IS NULL OR parent_structure_id <> id),
    CONSTRAINT structure_preparation_state_check
        CHECK (preparation_state IN ('RAW', 'CLEANED', 'PROTONATED', 'PDBQT')),
    CONSTRAINT structure_source_check
        CHECK (source IN ('PDB', 'ALPHAFOLD', 'BIOHUB', 'UPLOADED', 'GENERATED'))
);

CREATE TABLE docking_test.residue (
    id bigint NOT NULL DEFAULT nextval('docking_test.residue_id_seq')
        PRIMARY KEY,
    structure_id bigint NOT NULL
        REFERENCES docking_test.structure (id) ON DELETE CASCADE,
    chain varchar(10) NOT NULL,
    residue_number integer NOT NULL,
    insertion_code varchar(1) NOT NULL DEFAULT '',
    residue_name varchar(3) NOT NULL,
    CONSTRAINT residue_structure_position_unique
        UNIQUE (structure_id, chain, residue_number, insertion_code)
);

CREATE TABLE docking_test.pocket (
    id bigint NOT NULL DEFAULT nextval('docking_test.pocket_id_seq')
        PRIMARY KEY,
    receptor_id bigint
        REFERENCES docking_test.receptor (id) ON DELETE CASCADE,
    pocket_number integer,
    fpocket_file text,
    volume float8,
    druggability_score float8,
    structure_id bigint NOT NULL
        REFERENCES docking_test.structure (id) ON DELETE RESTRICT,
    source docking_test.pocket_source NOT NULL,
    artifact_id bigint NOT NULL
        REFERENCES docking_test.artifacts (id) ON DELETE RESTRICT,
    score float8,
    probability float8,
    CONSTRAINT pocket_structure_source_number_unique
        UNIQUE (structure_id, source, pocket_number)
);

CREATE TABLE docking_test.pocket_residue (
    id bigint NOT NULL DEFAULT nextval('docking_test.pocket_residue_id_seq')
        PRIMARY KEY,
    pocket_id bigint NOT NULL
        REFERENCES docking_test.pocket (id),
    chain char(1) NOT NULL,
    residue_number integer NOT NULL,
    residue_name varchar(3),
    residue_id bigint NOT NULL
        REFERENCES docking_test.residue (id) ON DELETE CASCADE,
    CONSTRAINT pocket_residue_membership_unique
        UNIQUE (pocket_id, residue_id),
    CONSTRAINT pocket_residue_uk
        UNIQUE (pocket_id, chain, residue_number)
);

CREATE TABLE docking_test.pocket_alpha_sphere (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pocket_id bigint NOT NULL
        REFERENCES docking_test.pocket (id) ON DELETE CASCADE,
    sphere_index integer NOT NULL,
    center_x float8 NOT NULL,
    center_y float8 NOT NULL,
    center_z float8 NOT NULL,
    radius float8 NOT NULL,
    CONSTRAINT pocket_alpha_sphere_unique
        UNIQUE (pocket_id, sphere_index),
    CONSTRAINT pocket_alpha_sphere_coords_finite
        CHECK (
            center_x <> 'Infinity'::float8
            AND center_x <> '-Infinity'::float8
            AND center_y <> 'Infinity'::float8
            AND center_y <> '-Infinity'::float8
            AND center_z <> 'Infinity'::float8
            AND center_z <> '-Infinity'::float8
        ),
    CONSTRAINT pocket_alpha_sphere_radius_positive
        CHECK (radius > 0 AND radius <> 'Infinity'::float8)
);

CREATE INDEX pocket_alpha_sphere_pocket_idx
    ON docking_test.pocket_alpha_sphere (pocket_id);

CREATE TABLE docking_test.pocket_shape_descriptor (
    pocket_id bigint PRIMARY KEY
        REFERENCES docking_test.pocket (id) ON DELETE CASCADE,
    point_count integer NOT NULL,
    radius_of_gyration float8 NOT NULL,
    extent_major float8 NOT NULL,
    extent_middle float8 NOT NULL,
    extent_minor float8 NOT NULL,
    elongation float8 NOT NULL,
    flatness float8 NOT NULL,
    h0 float8 NOT NULL,
    h1 float8 NOT NULL,
    h2 float8 NOT NULL,
    h3 float8 NOT NULL,
    h4 float8 NOT NULL,
    h5 float8 NOT NULL,
    h6 float8 NOT NULL,
    h7 float8 NOT NULL,
    h8 float8 NOT NULL,
    h9 float8 NOT NULL,
    h10 float8 NOT NULL,
    h11 float8 NOT NULL,
    descriptor_version integer NOT NULL
);

CREATE TABLE docking_test.pocket_atom (
    id bigint NOT NULL DEFAULT nextval('docking_test.pocket_atom_id_seq')
        PRIMARY KEY,
    pocket_residue_id bigint NOT NULL
        REFERENCES docking_test.pocket_residue (id),
    atom_name varchar(8),
    x float8,
    y float8,
    z float8,
    element varchar(4),
    coords cube
);
