from pathlib import Path
import copy,hashlib,json
root=Path('software/modules/athena/src/main/resources/totah/lab/athena/system/rules');q=Path('software/qualification/foundation-supportable-pass-20261007/p07');out=root/'zn-source-features-v1';out.mkdir(exist_ok=True)
write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n');canon=lambda v:json.dumps(v,sort_keys=True,separators=(',',':'))
pins=json.loads((q/'SOURCE_PINS.json').read_text());refs=[{'kind':'SOURCE','namespace':'athena.p07.source','id':p,'version':h}for p,h in pins.items()]
sci=[{'locator':p,'sha256':h,'citation':'Exact bounded RDKit source-pattern identity and explicit OCL transfer; no zinc binding or coordination assertion.'}for p,h in pins.items()]
base=json.loads((root/'groups-foundation-v1/ATHENA.GROUP.THIOETHER.rule.json').read_text());original=json.loads(base['parameters']['definition']['value']);sources={};features={}
for (line,n) in zip((q/'bounded-queries.tsv').read_text().splitlines(),[2,5,6,5,4,6,6]):
 name,query=line.split('\t');id='ATHENA.P07.SOURCE.'+name.upper();m=copy.deepcopy(base);m.update(ruleId=id,profile='ATHENA_GROUP_SOURCE_H_V4',implementationVersion='4',tier='P07_SOURCE_PATTERN');d=copy.deepcopy(original);d.update(schema='athena-group-definition/2',groupId=id,patternId=id+'/pattern',query=query,memberQueryIndices=list(range(n)),roles={f'q{i}':[i] for i in range(n)},occurrenceExclusions=[],negativeCoverageVersion=id+'/negative/1',sourceReferences=refs,limitations=['Literal original source-feature branch; no zinc-binding role or interaction assertion.','Whole-component neutral/source-scope eligibility is imposed independently by the P07 composing leaf.'])
 d['requiredState']={'graphCompleteness':True,'formalCharge':True,'aromaticity':True,'hydrogenElements':['C','N','O','S','P'],'hydrogenRoles':[],'roleHeavyDegree':{},'hydrogenConsistencyQueries':{str(i):f'[*;H{i}]'for i in range(5)}};d['supportedDomain']={'elements':['C','N','O','S','P'],'unsupportedQueries':[],'coveredAtomQuery':''};m['parameters']['definition']['value']=canon(d);m['negativeCoverage']['version']=d['negativeCoverageVersion'];m['limitations']=d['limitations'];m['scientificSources']=sci;m['measurementsProduced']={'source-pattern-identities':'athena-group-identities/2'};sources[id]=m;features.setdefault(name.split('_')[0],[]).append(id);write(out/(id+'.rule.json'),m)
m=json.loads((root/'source-fragment-parent-v1/ATHENA.A08.UNIQUE_LARGEST_HEAVY_SOURCE_COMPONENT.rule.json').read_text());id='ATHENA.P07.RDKIT_ZNBINDER_SOURCE_FEATURES_NEUTRAL_HEAVY';m.update(ruleId=id,profile='ATHENA_P07_ZN_SOURCE_FEATURES_V1',implementationId='athena.zn-source-features');m['parameters']={k:{'value':canon(v),'unit':'policy','definition':'Exact bounded source-pattern branches; retain original feature identity and every query correspondence.'}for k,v in [('sources',sources),('features',features)]};m['scientificSources']=sci;m['requiredChemistry']=['Complete selected neutral heavy C/N/O/S/P component; independent original source scope, charge, source-H consistency, aromaticity and explicit NONE','Seven pinned group/4 branches; original names and overlapping OR branch union remain explicit'];m['measurementsProduced']={'payload':'existing exact state snapshot','sourceFeatureOccurrences':'six original source feature identities with branch attribution and query-index correspondences'};m['limitations']=['Advisory source-pattern identities only; no actual zinc binding, coordination, affinity or role-catalog broadening.','No explicit-H target, normalization, inferred H, weighted center, default activation or production authority.','Negatives are original-feature-specific within the one complete selected eligible component.'];m['negativeCoverage']={'version':id+'/coverage/1','scope':'EXACT_SELECTED_COMPLETE_COMPONENT_PER_ORIGINAL_FEATURE','requirements':['COMPLETE_SOURCE_STATE','INDEPENDENT_SOURCE_SCOPE','ALL_OR_BRANCHES_EXHAUSTIVE','CURRENT_POLICY_AUTHORITY'],'incompleteStatus':'UNKNOWN_INCONCLUSIVE','supportedDomain':'Neutral heavy C/N/O/S/P source component; both ZnBinder6 branches required for negative coverage.'};write(out/(id+'.rule.json'),m)
