"""Pinned synthetic RDKit reference annotations for tests only; never a production source producer."""
from pathlib import Path
from rdkit import Chem,rdBase
import csv,json,re,hashlib
q=Path(__file__).resolve().parent;source=Path('software/qualification/scientific-rule-knowledge-audit-20261004/reference/rdkit--Data__BaseFeatures.fdef');queries=dict(re.findall(r'^DefineFeature (ZnBinder\d) (.+)$',source.read_text(),re.M));rows=[]
for file in [q/'REFERENCE_PANEL.tsv',q/'expanded-reference/REFERENCE_PANEL.tsv']:
 for row in list(csv.DictReader(file.open(),delimiter='\t'))+([{'id':'cyclic_phosphoryl_symmetry','smiles':'CP1(=O)OCO1'}] if file.name=='REFERENCE_PANEL.tsv' and file.parent==q else []):
  params=Chem.SmilesParserParams();params.removeHs=False;m=Chem.MolFromSmiles(row['smiles'],params);assert m is not None
  atoms=[{'id':'a'+str(a.GetIdx()),'element':a.GetSymbol(),'charge':a.GetFormalCharge(),'aromatic':a.GetIsAromatic(),'hydrogens':a.GetTotalNumHs(includeNeighbors=False)}for a in m.GetAtoms()]
  bonds=[{'first':b.GetBeginAtomIdx(),'second':b.GetEndAtomIdx(),'order':'AROMATIC'if b.GetIsAromatic()else str(b.GetBondType())}for b in m.GetBonds()]
  rows.append({**row,'atoms':atoms,'bonds':bonds,'expectedOriginalFeatureCounts':{name:len(m.GetSubstructMatches(Chem.MolFromSmarts(query),uniquify=True))for name,query in queries.items()},'admitted':all(a['element']!='H'and a['charge']==0 for a in atoms)})
out=Path('software/modules/daedalus/src/test/resources/p07-source-features');out.mkdir(exist_ok=True);p=out/'fixtures.json';p.write_text(json.dumps({'provenance':'Synthetic source graphs and H annotations generated by pinned-version RDKit as independent reference fixtures; not observed molecules, production source evidence, zinc binding or scientific authority. Coordinates in Java fixtures are arbitrary indices and unused.','rdkitVersion':rdBase.rdkitVersion,'sourceSha256':hashlib.sha256(source.read_bytes()).hexdigest(),'cases':rows},indent=2)+'\n');print(rdBase.rdkitVersion,len(rows),hashlib.sha256(p.read_bytes()).hexdigest())
