package totah.lab.athena.system.rules;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import java.nio.charset.StandardCharsets;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.athena.system.rules.EventPayload.*;

/** Hand-authored source-text controls, not a deposited structure or empirical dataset. */
class SourceSiteMetadataLexicalTest {
    static com.fasterxml.jackson.databind.node.ObjectNode plan(){var p=JSON.createObjectNode();p.put("schema","athena-source-site-metadata-plan/1");p.put("definition",SourceSiteMetadata.DEFINITION);var s=p.putObject("state");s.set("state",JSON.valueToTree(new totah.lab.mnemosyne.ScientificReference(totah.lab.mnemosyne.ScientificReference.Kind.CONTEXT,"fixture","source","1")));for(var k:List.of("stateSha256","chemicalSha256","coordinateSha256","correspondenceSha256"))s.put(k,"0".repeat(64));p.putObject("source");p.putObject("sourceProtocol");p.put("blockOrdinal",0);p.put("blockName","test");p.putArray("correspondence");return p;}
    static com.fasterxml.jackson.databind.node.ObjectNode parse(String source)throws Exception{return SourceSiteMetadata.extract(source.getBytes(StandardCharsets.UTF_8),plan(),Map.of());}
    static String sites(String occupancy,String b,String alt,String model){return "data_test\nloop_\n_atom_site.id\n_atom_site.occupancy\n_atom_site.B_iso_or_equiv\n_atom_site.label_alt_id\n_atom_site.pdbx_PDB_model_num\n1 "+occupancy+" "+b+" "+alt+" "+model+"\n";}
    static String relations(){return "loop_\n_atom_sites_alt.id\nA\nB\nloop_\n_atom_sites_alt_ens.id\nE\nloop_\n_atom_sites_alt_gen.ens_id\n_atom_sites_alt_gen.alt_id\nE A\n";}
    @ParameterizedTest @ValueSource(strings={"0","-0","1.0",".00","1.20e-2","1.2(3)","-1","1.5","?",".","'?'","'.'","\"?\"","\".\"","'text value'"}) void exactTokensAndMissingness(String token)throws Exception {
        String source=sites(token,"20.00","A","1");var f=parse(source).path("atomSiteRows").get(0).path("fields").path("_atom_site.occupancy");assertEquals(token.equals("?")?"MISSING_QUESTION":token.equals(".")?"INAPPLICABLE_DOT":"EXPLICIT",f.path("state").asText());var bytes=source.getBytes(StandardCharsets.UTF_8);assertEquals(token,new String(Arrays.copyOfRange(bytes,f.path("valueSpan").get(0).intValue(),f.path("valueSpan").get(1).intValue()),StandardCharsets.UTF_8));
    }
    @Test void omittedIsNotDefaultOrPlaceholder()throws Exception{var f=parse("data_test\n_atom_site.id 1\n").path("atomSiteRows").get(0).path("fields");assertEquals(JSON.readTree("{\"state\":\"OMITTED\"}"),f.get("_atom_site.occupancy"));assertEquals("OMITTED",f.path("_atom_site.pdbx_PDB_model_num").path("state").asText());}
    @Test void quotedNullsAreTextAndDiagnosedNumericOnly()throws Exception{var r=parse(sites("'?'","'.'","'?'","'1'"));assertEquals(2,r.path("diagnostics").findValuesAsText("code").stream().filter(x->x.startsWith("NONNUMERIC")).count());assertEquals("EXPLICIT",r.path("atomSiteRows").get(0).path("fields").path("_atom_site.label_alt_id").path("state").asText());}
    @Test void caseLookupPreservesOriginalItemBytes()throws Exception{String s="data_test\n_ATOM_SITE.ID 1\n_ATOM_SITE.OCCUPANCY 0\n";var f=parse(s).path("atomSiteRows").get(0).path("fields").path("_atom_site.occupancy");assertEquals("_ATOM_SITE.OCCUPANCY",s.substring(f.path("itemSpan").get(0).intValue(),f.path("itemSpan").get(1).intValue()));}
    @ParameterizedTest @ValueSource(strings={"\n","\r\n"}) void semicolonDetailsAndByteOffsets(String newline)throws Exception{String s=(sites("0.5","10","A","1")+"_atom_sites_alt.id A\n_atom_sites_alt.details\n;α source prose\nsecond line\n;\n").replace("\n",newline);var r=parse(s);var f=r.path("alternateCategories").path("atom_sites_alt").path("rows").get(0).path("fields").path("_atom_sites_alt.details");assertEquals("SEMICOLON_TEXT",f.path("lexicalForm").asText());assertEquals("α source prose"+newline+"second line",f.path("value").asText());byte[] b=s.getBytes(StandardCharsets.UTF_8);assertEquals(';',b[f.path("valueSpan").get(0).intValue()]);assertEquals(';',b[f.path("valueSpan").get(1).intValue()-1]);}
    @ParameterizedTest @ValueSource(strings={"data_test\nloop_\n_atom_site.id\n_atom_site.occupancy\n1\n","data_test\n_atom_site.id 1\n_ATOM_SITE.ID 2\n","data_test\n_atom_site.id 'bad\n","data_test\n_atom_site.id\n;bad\n","data_test\nloop_\n_atom_site.id\n_other.id\n1 2\n","data_test\nloop_\n_atom_site.id\n","data_test\n_atom_site.id 1\nloop_\n_atom_site.id\n2\n"}) void malformedSourcesNeverRepair(String text){assertThrows(java.io.IOException.class,()->parse(text));}
    @ParameterizedTest @ValueSource(strings={"ATOM 1 CA GLY","data_test\nsave_x\n","data_test\n_atom_site.id [1 2]\n","data_test\n_atom_site.id $frame\n"}) void unsupportedFormatIsDistinct(String text){assertThrows(SourceSiteMetadata.Outside.class,()->parse(text));}
    @Test void exactExplicitMembershipOnly()throws Exception{var r=parse(sites("0.1","20","A","1")+relations());var m=SourceSiteMetadata.memberships(r).orElseThrow();assertEquals(1,m.size());assertEquals("E",m.get(0).path("ensembleId").asText());assertEquals(JSON.readTree("[0]"),m.get(0).path("rowOrdinals"));}
    @Test void modelPartitionsAndNoCommonDotExpansion()throws Exception{String s=sites("0.1","20","A","1")+"2 .9 20 A 2\n3 1 20 . 1\n"+relations();var m=SourceSiteMetadata.memberships(parse(s)).orElseThrow();assertEquals(2,m.size());assertEquals(2,m.findValues("rowOrdinals").stream().mapToInt(x->x.size()).sum());}
    @ParameterizedTest @ValueSource(strings={"no-relations","dangling-alt","dangling-ens","duplicate-pair","duplicate-id","unknown-model","missing-relation-id","no-site-for-alt"}) void incompleteMembershipStaysUnknown(String kind)throws Exception{String s=sites(".5","10","A",kind.equals("unknown-model")?"?":"1");String r=relations();r=switch(kind){case "no-relations"->"";case "dangling-alt"->r.replace("E A","E C");case "dangling-ens"->r.replace("E A","F A");case "duplicate-pair"->r+"E A\n";case "duplicate-id"->r.replace("A\nB\n","A\nA\n");case "missing-relation-id"->r.replace("E A","E ?");case "no-site-for-alt"->r.replace("E A","E B");default->r;};assertTrue(SourceSiteMetadata.memberships(parse(s+r)).isEmpty());}
    @Test void proseAndUnknownFieldsRemainUninterpreted()throws Exception{String s=sites("0.5","20","A","1")+relations()+"_atom_sites_alt_ens_extra.details 'not parsed as membership'\n";var r=parse(s);assertTrue(SourceSiteMetadata.memberships(r).isPresent());var p=parse(sites(".5","20","A","1")+"_atom_sites_alt.id A\n_atom_sites_alt.unknown 'source text'\n_atom_sites_alt.details 'correlation not a protocol'\n");assertEquals("source text",p.path("alternateCategories").path("atom_sites_alt").path("rows").get(0).path("fields").path("_atom_sites_alt.unknown").path("value").asText());assertTrue(SourceSiteMetadata.memberships(p).isEmpty());}
    @Test void duplicateSourceIdsNeverMergeRows()throws Exception{var r=parse(sites("0","0","A","1")+"1 1 10 B 1\n");assertEquals(2,r.path("atomSiteRows").size());assertTrue(r.path("diagnostics").findValuesAsText("code").contains("DUPLICATE_SOURCE_ID"));}
    @Test void ordinalsRejectFractionOverflowAndWrongBlock()throws Exception{for(String n:List.of("0.5","4294967296","-1")){var p=plan();p.set("blockOrdinal",JSON.readTree(n));assertThrows(IllegalArgumentException.class,()->SourceSiteMetadata.extract(sites("0","0","A","1").getBytes(StandardCharsets.UTF_8),p,Map.of()));}var p=plan();p.put("blockName","other");assertThrows(IllegalArgumentException.class,()->SourceSiteMetadata.extract(sites("0","0","A","1").getBytes(StandardCharsets.UTF_8),p,Map.of()));}
    @Test void unknownAlternateIdentityBlocksCompleteMembership()throws Exception{var r=parse(sites(".5","20","A","1")+"2 .5 20 ? 1\n"+relations());assertTrue(SourceSiteMetadata.memberships(r).isEmpty());}
    @Test void byteExactDeterministicReplay()throws Exception{String s=sites("0","10","A","1")+relations();assertEquals(canonical(parse(s)),canonical(parse(s)));}
}
