package totah.lab.prometheus.planning;

public enum StrategyRecommendation {
    READY_WITH_EXISTING_EVIDENCE,
    READY_AFTER_MINIMAL_NEW_EVIDENCE,
    INFRASTRUCTURE_BLOCKED_ONLY,
    FUNCTIONAL_FORM_INCOMPATIBLE,
    INSUFFICIENT_VALIDATION_PATH,
    NOT_RECOMMENDED
}
