package totah.lab.prometheus.execution.quantum;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

import totah.lab.prometheus.evidence.EvidenceAcceptanceState;
import totah.lab.prometheus.evidence.EvidenceIdentity;
import totah.lab.prometheus.evidence.EvidenceProvenance;
import totah.lab.prometheus.evidence.QuantumEvidence;
import totah.lab.prometheus.execution.EvidenceExecutionException;
import totah.lab.prometheus.execution.RawArtifact;
import totah.lab.prometheus.store.GeneratedEvidenceRegistry;
import totah.lab.prometheus.store.GeneratedEvidenceRole;

/** Identity-first execution lifecycle with synchronous durable registration before success returns. */
public final class JavaNeuralQuantumRuntime {
    private final QuantumExecutionService executionService;
    private final GeneratedEvidenceRegistry registry;

    public JavaNeuralQuantumRuntime(QuantumExecutionService executionService,GeneratedEvidenceRegistry registry){
        this.executionService=Objects.requireNonNull(executionService,"executionService");
        this.registry=Objects.requireNonNull(registry,"registry");
    }

    public RuntimeResult executeOrReuse(QuantumExecutionRequest request)throws IOException,EvidenceExecutionException{
        Objects.requireNonNull(request,"request");EvidenceIdentity identity=identity(request);
        Optional<QuantumEvidence> existing=registry.reusable(identity.evidenceHash());
        if(existing.isPresent())return new RuntimeResult(Disposition.REUSE_EXISTING,existing.get(),Optional.empty());
        QuantumResult result;
        try{result=executionService.execute(request);validate(request,result);}
        catch(EvidenceExecutionException|RuntimeException e){registry.recordFailure(request.specification().checksum(),identity.evidenceHash(),e.getMessage()==null?e.getClass().getName():e.getMessage());throw e;}
        Path base=request.options().workingDirectory();List<RawArtifact> artifacts=result.artifactChecksums().entrySet().stream()
                .sorted(java.util.Map.Entry.comparingByKey()).map(e->new RawArtifact(e.getKey(),e.getValue(),"exact_quantum_result_json")).toList();
        String first=artifacts.getFirst().relativePath();String sha=artifacts.getFirst().sha256();
        List<Double> gradient=result.gradient().map(g->g.vectors().stream().flatMap(v->java.util.stream.Stream.of(v.x(),v.y(),v.z())).toList()).orElse(null);
        QuantumEvidence evidence=new QuantumEvidence(identity,new EvidenceProvenance(first,sha,result.completedAt(),List.of(),
                "generated by "+result.backendId()+"; exact-bit artifact; synchronously registered"),result.convergence(),EvidenceAcceptanceState.ACCEPTED,
                result.energy().map(QuantumResult.Energy::value),Optional.ofNullable(gradient),Optional.empty(),Optional.empty(),Optional.empty(),"validated Java neural result");
        registry.register(request.specification().checksum(),evidence,GeneratedEvidenceRole.PRIMARY,base,artifacts,
                "MISSING->AUTHORIZED->RUNNING->COMPLETED->VALIDATED->REGISTERED->REUSABLE");
        QuantumEvidence refreshed=registry.reusable(identity.evidenceHash()).orElseThrow(()->new IOException("registered evidence was not immediately reusable"));
        return new RuntimeResult(Disposition.GENERATED_NEW,refreshed,Optional.of(result));
    }

    public static EvidenceIdentity identity(QuantumExecutionRequest request){
        List<String> outputs=new ArrayList<>(request.specification().requiredOutputs());outputs.add("solverMode="+request.solverMode());
        request.requiredObservables().stream().map(Enum::name).sorted().forEach(x->outputs.add("observable="+x));outputs.sort(Comparator.naturalOrder());
        var s=request.specification();return new EvidenceIdentity(s.molecule(),request.canonicalAtomMapHash(),s.geometry(),s.formalCharge(),s.multiplicity(),s.calculationType(),s.protocol(),s.constraints(),outputs);
    }

    private static void validate(QuantumExecutionRequest request,QuantumResult result)throws EvidenceExecutionException{
        if(result.convergence()!=totah.lab.prometheus.evidence.ConvergenceStatus.CONVERGED)throw new EvidenceExecutionException("result did not converge");
        if(request.requiredObservables().contains(QuantumObservable.ABSOLUTE_ENERGY)&&(result.energy().isEmpty()||!Double.isFinite(result.energy().get().value())))throw new EvidenceExecutionException("missing/non-finite energy");
        if(request.requiredObservables().contains(QuantumObservable.CARTESIAN_GRADIENT)&&result.gradient().isEmpty())throw new EvidenceExecutionException("missing gradient");
        if(request.requiredObservables().contains(QuantumObservable.CARTESIAN_FORCE)&&result.force().isEmpty())throw new EvidenceExecutionException("missing force");
        if(result.gradient().isPresent()&&result.gradient().get().vectors().size()!=request.geometry().atoms().size())throw new EvidenceExecutionException("gradient atom-order length mismatch");
        if(result.force().isPresent()&&(!result.forceIsNegativeGradient(0.0)||result.force().get().vectors().size()!=request.geometry().atoms().size()))throw new EvidenceExecutionException("force=-gradient exact-bit invariant failed");
        if(result.artifactChecksums().isEmpty())throw new EvidenceExecutionException("successful result has no authoritative artifact");
    }

    public enum Disposition{GENERATED_NEW,REUSE_EXISTING}
    public record RuntimeResult(Disposition disposition,QuantumEvidence evidence,Optional<QuantumResult> generatedResult){public RuntimeResult{Objects.requireNonNull(disposition);Objects.requireNonNull(evidence);generatedResult=Objects.requireNonNull(generatedResult);}}
}
