package totah.lab.prometheus.variational.force;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import totah.lab.prometheus.molecular.Molecule;
import totah.lab.prometheus.neural.GeneralSlaterJastrowDirectionalEvaluator;
import totah.lab.prometheus.neural.GeneralSlaterJastrowState;
import totah.lab.prometheus.variational.GeneralMolecularSampleSource;

/** All-nucleus Cartesian differential-SWCT estimator using one fused directional graph per sample. */
public final class GeneralAnalyticDifferentialSwctForceEstimator {
    public Result evaluate(GeneralSlaterJastrowState state,GeneralMolecularSampleSource samples){Objects.requireNonNull(state);Objects.requireNonNull(samples);Molecule molecule=state.molecule();int components=3*molecule.nuclei().size();Accumulator a=new Accumulator(components);var evaluator=new GeneralSlaterJastrowDirectionalEvaluator();long start=System.nanoTime();a.peakHeap=usedHeap();samples.forEach((quadratureWeight,coordinates)->{var e=evaluator.evaluate(molecule,state.parameters(),coordinates);a.peakHeap=Math.max(a.peakHeap,usedHeap());a.stateTraversals+=e.stateTraversals();a.directionalPasses+=e.directionalAdPasses();double psi=e.value();if(!Double.isFinite(psi)||Math.abs(psi)<1e-14)return;double local=-.5*e.electronicLaplacian()/psi+e.potential(),weight=quadratureWeight*psi*psi;a.norm+=weight;a.energy+=weight*local;a.localEnergyEvaluations++;for(int nucleus=0;nucleus<molecule.nuclei().size();nucleus++)for(int axis=0;axis<3;axis++){int c=3*nucleus+axis,t=GeneralSlaterJastrowDirectionalEvaluator.total(nucleus,axis),b=GeneralSlaterJastrowDirectionalEvaluator.bare(nucleus,axis);double dLocalTotal=-.5*(e.laplacianDirectionalDerivatives()[t]*psi-e.electronicLaplacian()*e.valueDirectionalDerivatives()[t])/(psi*psi)+e.potentialDirectionalDerivatives()[t];double dLocalBare=-.5*(e.laplacianDirectionalDerivatives()[b]*psi-e.electronicLaplacian()*e.valueDirectionalDerivatives()[b])/(psi*psi)+e.potentialDirectionalDerivatives()[b];double log=e.valueDirectionalDerivatives()[t]/psi+.5*e.warpDivergence()[c],hfm=-dLocalTotal,base=hfm-2*local*log;a.base[c]+=weight*base;a.log[c]+=weight*log;a.bare[c]+=weight*-dLocalBare;}});if(!(a.norm>1e-14))throw new IllegalArgumentException("zero force-estimator norm");double energy=a.energy/a.norm;List<NuclearForce> forces=new ArrayList<>();for(int nucleus=0;nucleus<molecule.nuclei().size();nucleus++){double[] f=new double[3],bare=new double[3];for(int axis=0;axis<3;axis++){int c=3*nucleus+axis;f[axis]=a.base[c]/a.norm+2*energy*a.log[c]/a.norm;bare[axis]=a.bare[c]/a.norm;}forces.add(new NuclearForce(nucleus,f[0],f[1],f[2],bare[0],bare[1],bare[2]));}a.peakHeap=Math.max(a.peakHeap,usedHeap());return new Result(forces,energy,a.stateTraversals,a.localEnergyEvaluations,a.directionalPasses,System.nanoTime()-start,a.peakHeap,"ANALYTIC_DIFFERENTIAL_SWCT","hartree/bohr");}
    private static long usedHeap(){Runtime r=Runtime.getRuntime();return r.totalMemory()-r.freeMemory();}
    public record NuclearForce(int canonicalNucleusIndex,double fx,double fy,double fz,double bareFx,double bareFy,double bareFz){public NuclearForce{if(canonicalNucleusIndex<0||!Double.isFinite(fx)||!Double.isFinite(fy)||!Double.isFinite(fz))throw new IllegalArgumentException("invalid nuclear force");}}
    public record Result(List<NuclearForce> forces,double energyHartree,long stateTraversals,long localEnergyEvaluations,long directionalAdPasses,long wallTimeNanos,long peakHeapBytes,String estimator,String forceUnit){public Result{forces=List.copyOf(forces);}}
    private static final class Accumulator{double norm,energy;long stateTraversals,localEnergyEvaluations,directionalPasses,peakHeap;final double[] base,log,bare;Accumulator(int n){base=new double[n];log=new double[n];bare=new double[n];}}
}
