package totah.lab.daedalus.system;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.JSON;

class BatchCProvenanceEdgeTest {
    @TempDir Path temp;
    @ParameterizedTest @ValueSource(strings={"conflicting-attribution","expired-partner"}) void exactPartnerReviewCannotBeTransferred(String mode)throws Exception{
        var t=new ClPheAcceptanceTest();t.temp=temp;var s=t.sample("valid");var input=new ArrayList<>(s.inputs());var old=input.stream().filter(e->{try{return e.evidenceType().equals("athena:event-source")&&((EvidenceInterpretation)new EvidenceExchange().decodeRecord(e.readPayload())).measurements().get("proposition").equals("ATHENA.I11.SOURCE_PARTNER_ATTRIBUTION/1");}catch(Exception ex){return false;}}).findFirst().orElseThrow();
        var i=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(old.readPayload());var next=new EvidenceInterpretation(ref(ScientificReference.Kind.EVIDENCE_INTERPRETATION,"changed-partner"),i.inputs(),i.evaluator(),i.configuration(),i.subjects(),mode.equals("conflicting-attribution")?EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE:i.status(),i.measurements(),i.reasons(),i.limitations(),i.supersedes(),mode.equals("expired-partner")?i.recordedAt().plusSeconds(1):i.recordedAt());
        if(mode.equals("expired-partner"))input.remove(old);input.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"changed-partner"),"record","athena:event-source",new EvidenceExchange().encodeRecord(next),i.evaluator(),s.source().state.subject(),T,List.of()));
        assertEquals(mode.equals("expired-partner")?EvidenceInterpretation.Status.NOT_EVALUATED:EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,t.evaluate(new ClPheAcceptanceTest.Sample(s.source(),s.qualification(),input),true).status());
    }
    @Test void rawCoordinateSourcesRemainActualSources()throws Exception{var t=new ClPheAcceptanceTest();t.temp=temp;var s=t.sample("valid");var r=t.evaluate(s,true);var raw=JSON.readTree(r.measurements().get("payload"));assertEquals(JSON.valueToTree(s.source().state.sources()),raw.path("plan").path("coordinateSourceReferences"));assertTrue(s.source().state.limitations().stream().anyMatch(x->x.contains("Synthetic")));assertFalse(r.measurements().containsKey("experimentallyObserved"));}
    @Test void changedMappingCannotInheritAnExactPlanReview()throws Exception{var t=new SourceSiteMetadataAcceptanceTest();t.temp=temp;var s=t.sample("valid");var input=new ArrayList<>(s.inputs());var old=input.stream().filter(e->e.evidenceType().equals("athena:source-site-metadata-plan")).findFirst().orElseThrow();var plan=(com.fasterxml.jackson.databind.node.ObjectNode)JSON.readTree(old.readPayload());var rows=plan.withArray("correspondence");assertTrue(rows.size()>1);int first=rows.get(0).path("rowOrdinal").intValue();((com.fasterxml.jackson.databind.node.ObjectNode)rows.get(0)).put("rowOrdinal",rows.get(1).path("rowOrdinal").intValue());((com.fasterxml.jackson.databind.node.ObjectNode)rows.get(1)).put("rowOrdinal",first);input.remove(old);input.add(S1ResearchFixtures.envelope(s.state(),"changed-v18","plan",old.evidenceType(),SystemStateView.bytes(plan)));assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,t.evaluate(new SourceSiteMetadataAcceptanceTest.Sample(s.state(),s.qualification(),input),true,"").status());}
    @Test void reorderedMetadataInputsAreDeterministic()throws Exception{var t=new SourceSiteMetadataAcceptanceTest();t.temp=temp;var s=t.sample("valid");var input=new ArrayList<>(s.inputs());Collections.reverse(input);assertEquals(t.evaluate(s,true,""),t.evaluate(new SourceSiteMetadataAcceptanceTest.Sample(s.state(),s.qualification(),input),true,""));}
    @ParameterizedTest @ValueSource(strings={"status","selectedGraph","selectedComponent"}) void changedGovernedParentResultCannotProduceLineage(String mode)throws Exception{var t=new SourceFragmentLineageAcceptanceTest();t.temp=temp;var s=t.sample("valid");var input=new ArrayList<>(s.inputs());input.remove(s.parent());var old=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(s.parent().readPayload());var v=new TreeMap<>(old.measurements());if(!mode.equals("status"))v.put(mode,"{}");var next=new EvidenceInterpretation(old.reference(),old.inputs(),old.evaluator(),old.configuration(),old.subjects(),mode.equals("status")?EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE:old.status(),v,old.reasons(),old.limitations(),old.supersedes(),old.recordedAt());var e=SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"altered-parent"),"result","athena:event-source",new EvidenceExchange().encodeRecord(next),old.evaluator(),s.state().subject(),T,List.of());input.add(e);assertThrows(IllegalArgumentException.class,()->t.evaluate(new SourceFragmentLineageAcceptanceTest.Sample(s.state(),s.qualification(),input,e),true));}
    @Test void allLineageDigestsBindExactApprovedContent()throws Exception{var t=new SourceFragmentLineageAcceptanceTest();t.temp=temp;var s=t.sample("stereo");var p=JSON.readTree(t.evaluate(s,true).measurements().get("payload"));assertEquals(s.state().binding().stateSha256(),p.path("sourceStateSha256").asText());assertEquals(SystemStateView.digest(JSON.convertValue(p.path("parameters"),Object.class)),p.path("parametersSha256").asText());var digest=JSON.createObjectNode();for(var key:List.of("stateKind","sourceStateSha256","operation","selectionManifest","implementation","profile","parametersSha256","dataTables","selectedComponent","resultingGraph"))digest.set(key,p.get(key));assertEquals(SystemStateView.digest(JSON.convertValue(digest,Object.class)),p.path("resultingStateSha256").asText());assertTrue(p.path("dataTables").isEmpty());}
    @Test void metadataPlanCannotReplayAcrossSourceStates()throws Exception{var t=new SourceSiteMetadataAcceptanceTest();t.temp=temp;var s=t.sample("valid");var input=new ArrayList<>(s.inputs());var old=input.stream().filter(e->e.evidenceType().equals("athena:source-site-metadata-plan")).findFirst().orElseThrow();var p=(com.fasterxml.jackson.databind.node.ObjectNode)JSON.readTree(old.readPayload());((com.fasterxml.jackson.databind.node.ObjectNode)p.path("state").path("state")).put("id","another-source-state");input.remove(old);input.add(S1ResearchFixtures.envelope(s.state(),"other-state","plan",old.evidenceType(),SystemStateView.bytes(p)));assertThrows(IllegalArgumentException.class,()->t.evaluate(new SourceSiteMetadataAcceptanceTest.Sample(s.state(),s.qualification(),input),true,""));}
    @Test void lineageCannotTreatHistoricalParentTimeAsCurrent()throws Exception{var t=new SourceFragmentLineageAcceptanceTest();t.temp=temp;var s=t.sample("valid");var input=new ArrayList<>(s.inputs());input.remove(s.parent());var i=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(s.parent().readPayload());var next=new EvidenceInterpretation(i.reference(),i.inputs(),i.evaluator(),i.configuration(),i.subjects(),i.status(),i.measurements(),i.reasons(),i.limitations(),i.supersedes(),i.recordedAt().minusSeconds(1));var e=SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"historical-parent"),"record","athena:event-source",new EvidenceExchange().encodeRecord(next),i.evaluator(),s.state().subject(),T,List.of());input.add(e);assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,t.evaluate(new SourceFragmentLineageAcceptanceTest.Sample(s.state(),s.qualification(),input,e),true).status());}

}
