package totah.lab.daedalus.system;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.design.backend.MolecularGraph;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.gaia.structure.AtomReference;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.*;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.canonical;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.pin;

/** Hand-authored Cl/PHE states and independent synthetic source reviews. */
class ClPheAcceptanceTest {
    @TempDir Path temp;
    static final Path MANIFEST=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/cl-phe-candidate-v1/ATHENA.I11.CARBON_BOUND_CL_PHE_GEOMETRIC_CANDIDATE.rule.json");
    record Sample(MetPheSurveyAcceptanceTest.Source source,S1ResearchFixtures.Qualified qualification,List<EvidenceEnvelope> inputs) { }
    Sample sample(String variant)throws Exception {
        double x=variant.startsWith("tie")?0:Set.of("edge","angle-negative").contains(variant)?2:0.5,z=variant.equals("far")?5:variant.equals("edge")?1:variant.equals("angle-negative")?.5:3;
        if(variant.equals("distance4-theta100")){double rho=Math.cos(Math.toRadians(100))+Math.sqrt(16-Math.pow(Math.sin(Math.toRadians(100)),2));x=1-rho*Math.cos(Math.toRadians(100));z=rho*Math.sin(Math.toRadians(100));}var atoms=new ArrayList<MolecularGraph.Atom>();
        atoms.add(atom("CG",variant.equals("cl-n")?"N":"C",0,false,x,variant.equals("reverse-axis")?-2:2,z));String element=Set.of("F","Br","I").contains(variant)?variant:"Cl";var cl=atom("SD",element,variant.equals("charged")?-1:0,false,x,0,z);atoms.add(cl);var bonds=new ArrayList<MolecularGraph.Bond>(List.of(bond("CG","SD",variant.equals("double-cl")?MolecularGraph.BondOrder.DOUBLE:MolecularGraph.BondOrder.SINGLE)));var hs=new TreeMap<String,Integer>(Map.of("CG",3,"SD",variant.equals("cl-h")?1:0));
        if(variant.equals("other-ligand-halogen")){atoms.add(atom("F","F",0,false,x+3,2,z));bonds.add(bond("CG","F",MolecularGraph.BondOrder.SINGLE));hs.put("CG",2);hs.put("F",0);}
        if(variant.equals("two-cl-bonds")){atoms.add(atom("EX","C",0,false,x+2,0,z));bonds.add(bond("SD","EX",MolecularGraph.BondOrder.SINGLE));hs.put("EX",3);}
        for(int i=0;i<atoms.size();i++){var a=atoms.get(i);atoms.set(i,new MolecularGraph.Atom(a.id(),a.element(),a.isotope(),a.formalCharge(),a.explicitHydrogens(),a.aromatic(),a.stereochemistry(),a.coordinates(),variant.equals("missing-none")?Map.of():Map.of("athena.ocl.atomRadicalState/1",variant.equals("radical")&&a.id().equals("SD")?"D":"NONE")));}
        var fs=List.of(new Fixture(new MolecularGraph(atoms,bonds,Map.of("fixture","chloromethane-source")),hs),MetPheSurveyAcceptanceTest.chemical(false,3,variant.equals("tie-permuted")?"permuted":variant));var state=MetPheSurveyAcceptanceTest.state(fs,variant);var f=new MetPheSurveyAcceptanceTest.Source(state);f.manifest=RuleRegistry.decode(Files.readAllBytes(MANIFEST));
        for(int n=0;n<2;n++){var cov=coverage(state,fs.get(n));cov.set("componentReference",node(state.components().get(n).identity()));
            if(variant.equals("missing-h"))cov.path("atomState").forEach(v->((ObjectNode)v).put("hydrogenMode","UNKNOWN").putNull("implicitHydrogenCount"));
            if(variant.equals("missing-charge"))cov.path("atomState").forEach(v->((ObjectNode)v).put("chargeStatus","UNKNOWN_INCONCLUSIVE").putNull("formalCharge"));
            if(variant.equals("missing-aromaticity"))cov.path("atomState").forEach(v->((ObjectNode)v).put("aromaticityStatus","UNKNOWN_INCONCLUSIVE"));
            if(variant.equals("incomplete-graph"))cov.put("completeGraph","UNKNOWN_INCONCLUSIVE");var ce=f.add("athena:group-source-coverage",SystemStateView.bytes(cov),ref(ScientificReference.Kind.METHOD,"i11-source"));
            if(!variant.equals("missing-scope"))f.scope(ce,variant.equals("known-connection")?"KNOWN_NON_ORDINARY_CONNECTION":variant.equals("unknown-scope")?"UNKNOWN":"COMPLETE_ORDINARY_COVALENT_NO_COORDINATION",false,false);
            if(variant.equals("conflict"))f.scope(ce,"UNKNOWN",false,false);
            if(n==1&&!variant.equals("missing-pattern"))for(var def:JSON.readTree(f.manifest.parameters().get("sources").value())){var m=RuleRegistry.decode(SystemStateView.bytes(def));var collector=RuleAnalyzers.collector(m,request(state,m),BACKEND);var result=collector.analyze(state,List.of(ce,envelope(state,"athena:group-definition",JSON.readTree(m.parameters().get("definition").value()))),Map.of()).getFirst();f.add("athena:group-identities",result.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method());}
        }
        var plan=JSON.createObjectNode();plan.put("schema","athena-continuous-geometry-plan/1");plan.set("stateBinding",node(state.binding()));plan.put("coordinateUnit","ANGSTROM");plan.set("coordinateSourceReferences",node(state.sources()));var group=plan.putArray("groups").addObject();group.put("id","phe-ring");group.set("atoms",node(f.selected.subList(2,8).stream().sorted().toList()));group.set("sourceReferences",node(state.sources()));var ops=plan.putArray("operations");for(int i=2;i<8;i++){var op=ops.addObject();op.put("id","distance-"+i);op.put("kind","DISTANCE");op.set("atoms",node(List.of(f.selected.get(1),f.selected.get(i))));}
        var op=ops.addObject();op.put("id","centroid-angle");op.put("kind","POINT_PAIR_GROUP");op.set("atoms",node(List.of(f.selected.get(1),f.selected.get(variant.equals("wrong-nearest")?3:2))));op.put("groupId","phe-ring");plan.putNull("radiusAssignmentReference");plan.set("sourceReferences",node(state.sources()));plan.putArray("limitations").add("Synthetic coordinates only");f.add("athena:continuous-geometry-plan",SystemStateView.bytes(plan),ref(ScientificReference.Kind.METHOD,"i11-plan"));
        var q=S1ResearchFixtures.qualify(f.manifest,state,f.selected,temp.resolve(UUID.randomUUID().toString()),"i11");f.manifest=q.manifest();if(!variant.equals("no-scope-authority"))MetPheSurveyAcceptanceTest.qualifyScope(f,temp.resolve(UUID.randomUUID().toString()));
        if(!variant.equals("no-attribution")){
            var snapshot=f.add("athena:system-state",SystemStateView.bytes(state.snapshot()),ref(ScientificReference.Kind.METHOD,"exact-state"));var protocol=f.add("athena:source-artifact","Synthetic explicit source partner assignment protocol, no production authority".getBytes(java.nio.charset.StandardCharsets.UTF_8),ref(ScientificReference.Kind.METHOD,"i11-partner-protocol"));var original=f.add("athena:source-artifact",SystemStateView.bytes(Map.of("syntheticExplicitPartnerAssignment",List.of(state.components().get(0).identity(),state.components().get(1).identity()))),ref(ScientificReference.Kind.METHOD,"i11-original"));
            var v=new TreeMap<String,String>();v.put("proposition","ATHENA.I11.SOURCE_PARTNER_ATTRIBUTION/1");v.put("stateBinding",canonical(state.binding()));v.put("ligandComponentReference",canonical(state.components().get(0).identity()));v.put("proteinComponentReference",canonical(state.components().get(1).identity()));v.put("ligandAtoms",canonical(state.components().get(0).correspondenceAlternatives().getFirst().values().stream().sorted(Comparator.comparing(S1NitrogenAcceptanceTest::canonical)).toList()));v.put("proteinAtoms",canonical(state.components().get(1).correspondenceAlternatives().getFirst().values().stream().sorted(Comparator.comparing(S1NitrogenAcceptanceTest::canonical)).toList()));v.put("stateSnapshotPin",canonical(pin(snapshot)));v.put("sourceProtocol",canonical(pin(protocol)));v.put("originalSourcePins",canonical(List.of(pin(original))));
            var method=ref(ScientificReference.Kind.METHOD,"i11-synthetic-attribution");var status=variant.equals("outside-partner")?EvidenceInterpretation.Status.UNSUPPORTED:variant.equals("unknown-partner")?EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE:EvidenceInterpretation.Status.SUPPORTED_PRESENT;
            var i=new EvidenceInterpretation(ref(ScientificReference.Kind.EVIDENCE_INTERPRETATION,"i11-attribution"),List.of(snapshot,protocol,original).stream().map(e->new EvidenceInterpretation.Input(e.reference(),e.payloadSha256())).toList(),method,Map.of(),List.of(state.subject()),status,v,List.of("Explicit fixture partner assignment only"),List.of("synthetic, not source production authority"),Optional.empty(),totah.lab.athena.system.rules.research.ResearchGateAcceptanceTest.AT);var e=f.add("athena:event-source",new EvidenceExchange().encodeRecord(i),method);
            if(!variant.equals("no-partner-authority")){var reviewed=BatchCSourceReviewFixtures.review("ATHENA.I11.SOURCE_PARTNER_ATTRIBUTION",f.manifest,state,f.selected,temp.resolve(UUID.randomUUID().toString()),List.of(e,protocol));f.inputs.addAll(reviewed.artifacts());}
        }
        return new Sample(f,q,new ArrayList<>(f.inputs));
    }
    SystemGraphAnalyzer.Finding evaluate(Sample s,boolean current)throws Exception{var f=s.source();var input=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(f.manifest,s.qualification().request());var raw=collector.analyze(f.state,input,Map.of()).getFirst();input.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"i11"),"raw","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),f.state.subject(),T,List.of()));if(current)input.addAll(s.qualification().artifacts());var before=canonical(f.state.snapshot());var result=RuleAnalyzers.evaluator(f.manifest,s.qualification().request()).analyze(f.state,input,Map.of()).getFirst();assertEquals(before,canonical(f.state.snapshot()));return result;}
    @Test void otherLigandAtomsDoNotGeneralizeSelectedClRole()throws Exception{assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,evaluate(sample("other-ligand-halogen"),true).status());}
    @Test void explicitEligibleSelectedCandidate()throws Exception{var r=evaluate(sample("valid"),true);assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status(),r.toString());assertEquals(6,JSON.readTree(r.measurements().get("ringMemberDistancesAngstrom")).size());assertEquals(1,JSON.readTree(r.measurements().get("nearestRingAtoms")).size());assertTrue(Double.parseDouble(r.measurements().get("thetaDegrees"))<140);}
    @Test void eligibleFarIsSelectedNegativeOnly()throws Exception{assertEquals(EvidenceInterpretation.Status.ABSENT_FALSE,evaluate(sample("far"),true).status());}
    @Test void exactTieRemainsUnknown()throws Exception{var r=evaluate(sample("tie"),true);assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status());assertTrue(JSON.readTree(r.measurements().get("nearestRingAtoms")).size()>1);}
    @Test void wrongNearestCannotSupplyConvenientAngle()throws Exception{assertThrows(IllegalArgumentException.class,()->evaluate(sample("wrong-nearest"),true));}
    @ParameterizedTest @ValueSource(strings={"F","Br","I","charged","cl-h","two-cl-bonds","cl-n","double-cl","known-connection","kekule","flagged-kekule","substituted-ring","fused-ring","heteroring","mixed-isotope","outside-partner","wrong-label"}) void excludedDomainDoesNotBecomeNegative(String v)throws Exception{assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,evaluate(sample(v),true).status(),v);}
    @ParameterizedTest @ValueSource(strings={"missing-h","missing-charge","missing-aromaticity","missing-none","incomplete-graph","missing-scope","unknown-scope","conflict","missing-pattern","ambiguous","unqualified-frame","degenerate","no-attribution","unknown-partner"}) void unresolvedCasesCannotProveNegative(String v)throws Exception{assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(sample(v),true).status(),v);}
    @ParameterizedTest @ValueSource(strings={"no-partner-authority","no-scope-authority"}) void independentAuthoritiesAreRequired(String v)throws Exception{assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample(v),true).status(),v);}
    @Test void ruleApprovalDoesNotSupplyCurrentAuthority()throws Exception{assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample("valid"),false).status());}
    @Test void deterministicFocusedReplay()throws Exception{var s=sample("valid");assertEquals(evaluate(s,true),evaluate(s,true));}
    @Test void exactReviewedExampleGeometry()throws Exception{var r=evaluate(sample("distance4-theta100"),true);assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status());assertEquals(4,Double.parseDouble(r.measurements().get("distanceAngstrom")),1e-12);assertEquals(100,Double.parseDouble(r.measurements().get("thetaDegrees")),1e-12);}
    @Test void angleAloneCanExcludeCloseSelectedPair()throws Exception{assertEquals(EvidenceInterpretation.Status.ABSENT_FALSE,evaluate(sample("angle-negative"),true).status());}
    @Test void characterizationNeverReplacesCandidate()throws Exception{var face=evaluate(sample("valid"),true);var edge=evaluate(sample("edge"),true);assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,face.status());assertEquals(face.status(),edge.status());assertEquals("FACE_ON",face.measurements().get("orientationCharacterization"));assertEquals("EDGE_ON",edge.measurements().get("orientationCharacterization"));}
    @Test void carbonAxisDoesNotDefineTheta()throws Exception{var a=evaluate(sample("valid"),true);var b=evaluate(sample("reverse-axis"),true);assertEquals(a.status(),b.status());assertEquals(a.measurements().get("thetaDegrees"),b.measurements().get("thetaDegrees"));}
    @Test void exactTieIsIndependentOfSourceAtomOrder()throws Exception{var a=evaluate(sample("tie"),true);var b=evaluate(sample("tie-permuted"),true);assertEquals(a.status(),b.status());assertEquals(a.measurements().get("nearestRingAtoms"),b.measurements().get("nearestRingAtoms"));}
    @Test void reorderedIdenticalEvidenceIsIdempotent()throws Exception{var s=sample("valid");var reversed=new ArrayList<>(s.inputs());Collections.reverse(reversed);reversed.add(reversed.getFirst());assertEquals(evaluate(s,true),evaluate(new Sample(s.source(),s.qualification(),reversed),true));}
    @ParameterizedTest @ValueSource(strings={"stateBinding","ligandAtoms","proteinAtoms","sourceProtocol","ligandComponentReference"}) void changedAttributionBindingsAreRejected(String key)throws Exception{var s=sample("valid");var inputs=new ArrayList<>(s.inputs());var e=inputs.stream().filter(x->{try{return x.evidenceType().equals("athena:event-source")&&((EvidenceInterpretation)new EvidenceExchange().decodeRecord(x.readPayload())).measurements().get("proposition").equals("ATHENA.I11.SOURCE_PARTNER_ATTRIBUTION/1");}catch(Exception ex){return false;}}).findFirst().orElseThrow();var old=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(e.readPayload());var values=new TreeMap<>(old.measurements());values.put(key,key.endsWith("Atoms")?"[]":"{}");var changed=new EvidenceInterpretation(old.reference(),old.inputs(),old.evaluator(),old.configuration(),old.subjects(),old.status(),values,old.reasons(),old.limitations(),old.supersedes(),old.recordedAt());inputs.remove(e);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"i11-altered"),"attribution","athena:event-source",new EvidenceExchange().encodeRecord(changed),old.evaluator(),s.source().state.subject(),T,List.of()));assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void missingOriginalWitnessIsUnknown()throws Exception{var s=sample("valid");var inputs=new ArrayList<>(s.inputs());var e=inputs.stream().filter(x->x.method().id().equals("i11-original")).findFirst().orElseThrow();inputs.remove(e);assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),inputs),true).status());}
    @Test void absentDistanceOperationIsRejected()throws Exception{var s=sample("valid");var inputs=new ArrayList<>(s.inputs());var old=inputs.stream().filter(e->e.evidenceType().equals("athena:continuous-geometry-plan")).findFirst().orElseThrow();var plan=(ObjectNode)JSON.readTree(old.readPayload());((com.fasterxml.jackson.databind.node.ArrayNode)plan.path("operations")).remove(0);inputs.remove(old);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"i11-short"),"plan",old.evidenceType(),SystemStateView.bytes(plan),old.method(),s.source().state.subject(),T,List.of()));assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void collisionOfEvidenceIdentityIsRejected()throws Exception{var s=sample("valid");var inputs=new ArrayList<>(s.inputs());var e=inputs.getFirst();var replacement=SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"collision"),"new",e.evidenceType(),"{}".getBytes(java.nio.charset.StandardCharsets.UTF_8),e.method(),s.source().state.subject(),T,List.of());var collision=new EvidenceEnvelope(e.reference(),replacement.evidenceType(),replacement.payloadFormat(),replacement.payloadVersion(),replacement.payloadBase64(),replacement.artifactPath(),replacement.payloadSha256(),replacement.provenance(),replacement.method(),replacement.context(),replacement.subjects(),replacement.qualifications(),replacement.limitations(),replacement.recordedAt());inputs.add(collision);assertThrows(Exception.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @ParameterizedTest @ValueSource(strings={"cross-definition","wrong-angle-vertex"}) void geometryProvenanceCannotBeSubstituted(String variant)throws Exception{var s=sample("valid");var inputs=new ArrayList<>(s.inputs());if(variant.equals("wrong-angle-vertex")){var old=inputs.stream().filter(e->e.evidenceType().equals("athena:continuous-geometry-plan")).findFirst().orElseThrow();var p=(ObjectNode)JSON.readTree(old.readPayload());((ObjectNode)p.path("operations").get(6)).set("atoms",JSON.valueToTree(s.source().selected.subList(0,2)));inputs.remove(old);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"wrong-vertex"),"plan",old.evidenceType(),SystemStateView.bytes(p),old.method(),s.source().state.subject(),T,List.of()));assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}else{var collector=RuleAnalyzers.collector(s.source().manifest,s.qualification().request());var raw=collector.analyze(s.source().state,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"wrong-definition"),"raw","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),ref(ScientificReference.Kind.METHOD,"G03-not-I11"),s.source().state.subject(),T,List.of()));inputs.addAll(s.qualification().artifacts());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.evaluator(s.source().manifest,s.qualification().request()).analyze(s.source().state,inputs,Map.of()));}}
    @Test void expiredCandidateAuthorityCannotActivate()throws Exception{var s=sample("valid");var artifacts=new ArrayList<>(s.qualification().artifacts());var e=artifacts.stream().filter(x->x.evidenceType().equals("athena:rule-qualification-receipt")).findFirst().orElseThrow();var r=totah.lab.athena.system.rules.research.ResearchDocuments.decode(e.readPayload(),totah.lab.athena.system.rules.research.RuleQualificationReceipt.class);var expired=new totah.lab.athena.system.rules.research.RuleQualificationReceipt(r.schema(),r.ruleKey(),r.manifestSha256(),r.eligibility(),r.implementationReport(),r.foundationCertificate(),r.stateBinding(),r.request(),r.qualification(),r.mode(),r.evaluatedAt().plusSeconds(60),r.reasons());artifacts.remove(e);artifacts.add(S1ResearchFixtures.envelope(s.source().state,"i11-expired","receipt","athena:rule-qualification-receipt",totah.lab.athena.system.rules.research.ResearchDocuments.encode(expired)));var q=new S1ResearchFixtures.Qualified(s.qualification().manifest(),s.qualification().request(),artifacts);assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(new Sample(s.source(),q,s.inputs()),true).status());}
    public static void main(String[] args)throws Exception{var t=new ClPheAcceptanceTest();t.temp=Files.createDirectories(Path.of(args[0]));var out=new TreeMap<String,Object>();for(var variant:List.of("valid","far","tie","F","no-partner-authority","missing-h")){var r=t.evaluate(t.sample(variant),true);out.put(variant,Map.of("status",r.status(),"measurements",r.measurements()));}Files.write(Path.of(args[1]),SystemStateView.bytes(out));}
}
