package totah.lab.daedalus.system;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.design.backend.MolecularGraph;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.gaia.structure.*;
import totah.lab.gaia.chemistry.Element;
import totah.lab.gaia.graph.ResidueGraph;
import totah.lab.athena.interaction.perception.FormalChargeAssignments;
import totah.lab.gaia.geometry.Point3D;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.*;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.canonical;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.pin;
/** Independent hand-specified finite source graphs; no production chemistry or source authority. */
class GlycineHCarbonylAcceptanceTest {
    @TempDir Path temp;
    static final Path MANIFEST=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/glycine-h-carbonyl-v1/ATHENA.I04.EXPLICIT_SOURCE_H_GLYCINE_BACKBONE_CARBONYL_CANDIDATE.rule.json");
    static B01FunctionalGroupAcceptanceTest.Fixture chemical(boolean donor,double distance,String variant) {
        var h=new LinkedHashMap<String,Integer>();h.put("PRE_CM",3);h.put("PRE_C",0);h.put("PRE_O",0);h.put("N",1);h.put("CA",donor?0:2);h.put("C",0);h.put("O",0);h.put("POST_N",1);h.put("POST_CM",3);
        var bonds=new ArrayList<MolecularGraph.Bond>();for(var edge:List.of("PRE_CM PRE_C","PRE_C N","N CA","CA C","C POST_N","POST_N POST_CM")){var e=edge.split(" ");bonds.add(bond(e[0],e[1],MolecularGraph.BondOrder.SINGLE));}
        bonds.add(bond("PRE_C","PRE_O",MolecularGraph.BondOrder.DOUBLE));bonds.add(bond("C","O",MolecularGraph.BondOrder.DOUBLE));
        if(donor){h.put("HA1",0);h.put("HA2",0);bonds.add(bond("CA","HA1",MolecularGraph.BondOrder.SINGLE));bonds.add(bond("CA","HA2",MolecularGraph.BondOrder.SINGLE));}
        if(variant.equals("primary-cap")){bonds.removeIf(b->b.firstAtomId().equals("POST_N")&&b.secondAtomId().equals("POST_CM"));h.remove("POST_CM");h.put("POST_N",2);}
        if(variant.equals("tertiary-cap")){h.put("POST_CM2",3);h.put("POST_N",0);bonds.add(bond("POST_N","POST_CM2",MolecularGraph.BondOrder.SINGLE));}
        if(donor&&variant.equals("multiply-bonded-h"))bonds.add(bond("N","HA1",MolecularGraph.BondOrder.SINGLE));
        if(donor&&variant.equals("missing-h-vertex")){h.remove("HA2");bonds.removeIf(b->b.secondAtomId().equals("HA2"));}
        if(donor&&variant.equals("implicit-donor"))h.put("CA",1);
        if(donor&&variant.equals("wrong-h-link")){bonds.removeIf(b->b.secondAtomId().equals("HA1"));bonds.add(bond("N","HA1",MolecularGraph.BondOrder.SINGLE));h.put("N",0);h.put("CA",1);}
        if(donor&&variant.equals("substituted-ca")){h.put("CB",3);bonds.add(bond("CA","CB",MolecularGraph.BondOrder.SINGLE));}
        if(donor&&variant.equals("broken-acyl")){bonds.removeIf(b->b.firstAtomId().equals("PRE_C")&&b.secondAtomId().equals("PRE_O"));bonds.add(bond("PRE_C","PRE_O",MolecularGraph.BondOrder.SINGLE));h.put("PRE_C",1);h.put("PRE_O",1);}
        if(donor&&variant.equals("missing-link"))bonds.removeIf(b->b.firstAtomId().equals("PRE_C")&&b.secondAtomId().equals("N"));
        if(donor&&variant.equals("protonated-n"))h.put("N",2);
        if(variant.equals("same-component"))h.put("PRE_CM",2);
        double angle=variant.equals("relaxed")?100:variant.equals("wrong-angle")?80:130;
        var atoms=new ArrayList<MolecularGraph.Atom>();
        for(var id:h.keySet()){String e=id.startsWith("HA")?"H":id.endsWith("O")?"O":id.endsWith("N")?"N":"C";double x=atoms.size()+20,y=donor?5:10,z=0;
            if(donor&&id.equals("CA")){x=1;y=0;}
            if(donor&&id.equals("HA1")){x=0;y=0;}
            if(donor&&id.equals("HA2")){x=0;y=0;z=1;}
            if(!donor&&id.equals("O")){x=distance*Math.cos(Math.toRadians(angle));y=distance*Math.sin(Math.toRadians(angle));if(variant.equals("zero")){x=0;y=0;}}
            if(donor&&id.equals("CA")&&variant.equals("degenerate")){x=0;y=0;}
            int charge=donor&&id.equals("N")&&variant.equals("protonated-n")?1:!donor&&id.equals("O")&&variant.equals("charged-carbonyl")?1:0;
            var a=atom(id,e,charge,false,x,y,z);var props=new TreeMap<String,String>();if(!variant.equals("missing-none"))props.put("athena.ocl.atomRadicalState/1",variant.equals("radical")&&donor&&id.equals("CA")?"D":"NONE");
            atoms.add(new MolecularGraph.Atom(id,e,id.equals("HA1")&&variant.equals("deuterium")?Integer.valueOf(2):id.equals("HA1")&&variant.equals("protium")?Integer.valueOf(1):null,charge,a.explicitHydrogens(),false,a.stereochemistry(),a.coordinates(),props));}
        if(variant.equals("permuted")){Collections.reverse(atoms);Collections.reverse(bonds);}
        return new B01FunctionalGroupAcceptanceTest.Fixture(new MolecularGraph(atoms,bonds,Map.of("fixture","finite-source-glycine")),h);
    }
    static SystemStateView state(List<B01FunctionalGroupAcceptanceTest.Fixture> fs,String variant) {
        var residues=new ArrayList<Residue>();var bonds=new ArrayList<Bond>();var components=new ArrayList<SystemStateView.Component>();var charges=new TreeMap<AtomReference,Integer>();
        for(int i=0;i<fs.size();i++){var graph=fs.get(i).graph();var map=new TreeMap<String,AtomReference>();var grouped=new TreeMap<Integer,List<Atom>>();int selected=3*i+2;
            for(var a:graph.atoms()){int r=a.id().startsWith("PRE_")?selected-1:a.id().startsWith("POST_")?selected+1:selected;String name=a.id().replace("PRE_","").replace("POST_","");var ar=new AtomReference("A",r,' ',name);map.put(a.id(),ar);charges.put(ar,a.formalCharge());var xyz=a.coordinates();var atom=Atom.builder().name(name).element(Element.fromSymbol(a.element())).autoDockType(a.aromatic()?"A":a.element()).position(new Point3D(xyz.x(),xyz.y(),xyz.z())).build();grouped.computeIfAbsent(r,k->new ArrayList<>()).add(atom);if(variant.equals("duplicate-name")&&i==0&&name.equals("CA"))grouped.get(r).add(atom);}
            for(var entry:grouped.entrySet())residues.add(new Residue(entry.getKey()==selected?(variant.equals("wrong-label")?"UNK":"GLY"):"CAP",entry.getKey(),entry.getValue()));
            for(var b:graph.bonds())bonds.add(new Bond(map.get(b.firstAtomId()),map.get(b.secondAtomId()),totah.lab.gaia.chemistry.BondOrder.valueOf(b.order().name())));
            components.add(new SystemStateView.Component(ref(ScientificReference.Kind.SUBJECT,"i04-component-"+i),graph,variant.equals("ambiguous")?List.of(map,map):List.of(map),List.of("hand-authored source graph")));}
        return new SystemStateView(ref(ScientificReference.Kind.CONTEXT,variant.equals("different-state")?"i04-other-state":"i04-state"),ResidueGraph.from(new Structure(List.of(new Chain("A",residues)),bonds,ConnectivityProvenance.EXPLICIT)),components,List.of(ref(ScientificReference.Kind.SOURCE,"synthetic-i04")),Set.of(),new FormalChargeAssignments(charges),!variant.equals("unqualified-frame"),true,List.of("Synthetic coordinates; no experimental/energetic assertion"));
    }
    static class Source {
        final SystemStateView state;RuleManifest manifest;final List<EvidenceEnvelope> inputs=new ArrayList<>();final List<AtomReference> selected;int seq;
        Source(SystemStateView s)throws Exception {state=s;manifest=RuleRegistry.decode(Files.readAllBytes(MANIFEST));selected=new ArrayList<>(List.of(new AtomReference("A",2,' ',"CA"),new AtomReference("A",2,' ',"HA1"),new AtomReference("A",5,' ',"O"),new AtomReference("A",5,' ',"C")));}

        EvidenceEnvelope add(String type,byte[] bytes,ScientificReference method) {var e=SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"s1-synthetic"),"input-"+seq++,type,bytes,method,state.subject(),T,List.of("hand-authored engineering fixture; no production scope authority"));inputs.add(e);return e;}
        void scope(EvidenceEnvelope coverage,String connection,boolean wrongAtoms,boolean wrongState)throws Exception {
            var coverageComponent=JSON.readTree(coverage.readPayload()).path("componentReference");var c=state.components().stream().filter(x->JSON.valueToTree(x.identity()).equals(coverageComponent)).findFirst().orElseThrow();var protocol=add("athena:source-artifact","synthetic lossless source protocol; no real preparation assertion".getBytes(java.nio.charset.StandardCharsets.UTF_8),ref(ScientificReference.Kind.METHOD,"scope-protocol"));
            boolean nonordinary=connection.equals("KNOWN_NON_ORDINARY_CONNECTION");
            var original=add("athena:source-artifact",SystemStateView.bytes(nonordinary?Map.of("ordinaryProjection",state.snapshot(),"explicitOriginalConnection",Map.of("identity","source-dative-17","first","component-source-N:a1","second","source-Zn:external","kind","DATIVE")):state.snapshot()),ref(ScientificReference.Kind.METHOD,"original-source"));
            var values=new TreeMap<String,String>();values.put("proposition",nonordinary?"ATHENA.I03.SP3_SOURCE_SCOPE/2":"ATHENA.I03.SP3_SOURCE_SCOPE/1");values.put("stateBinding",wrongState?"{}":canonical(state.binding()));values.put("componentReference",canonical(c.identity()));values.put("atoms",canonical(wrongAtoms?List.of():c.correspondenceAlternatives().getFirst().values().stream().sorted(Comparator.comparing(S1NitrogenAcceptanceTest::canonical)).toList()));values.put("connectionCoverage",connection);values.put("electronicStateCoverage","COMPLETE_EXPLICIT_NONE");values.put("sourceProtocol",canonical(pin(protocol)));
            var method=ref(ScientificReference.Kind.METHOD,"unqualified-synthetic-scope");var i=new EvidenceInterpretation(ref(ScientificReference.Kind.EVIDENCE_INTERPRETATION,"scope-"+seq),List.of(new EvidenceInterpretation.Input(coverage.reference(),coverage.payloadSha256()),new EvidenceInterpretation.Input(protocol.reference(),protocol.payloadSha256()),new EvidenceInterpretation.Input(original.reference(),original.payloadSha256())),method,Map.of(),List.of(state.subject()),nonordinary?EvidenceInterpretation.Status.UNSUPPORTED:EvidenceInterpretation.Status.SUPPORTED_PRESENT,values,List.of(nonordinary?"Original connection source-dative-17: component-source-N:a1 -> source-Zn:external, explicitly DATIVE; exact original bytes pinned":"synthetic complete assertion"),List.of("not independently qualified"),Optional.empty(),totah.lab.athena.system.rules.research.ResearchGateAcceptanceTest.AT);
            add("athena:event-source",new EvidenceExchange().encodeRecord(i),method);
        }
    }
    static void qualifyScope(Source f,Path temp)throws Exception {
        var scopes=f.inputs.stream().filter(e->e.evidenceType().equals("athena:event-source")).toList();
        int scopeIndex=0;for(var scope:scopes){
        var old=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(scope.readPayload());
        var p=B01FunctionalGroupAcceptanceTest.JSON.readTree(old.measurements().get("sourceProtocol"));
        var source=f.inputs.stream().filter(e->e.payloadSha256().equals(p.path("sha256").asText())).findFirst().orElseThrow();
        Path protocol=Path.of("software/modules/daedalus/src/test/resources/i03-s1/synthetic-source-protocol.txt");assertArrayEquals(Files.readAllBytes(protocol),source.readPayload());
        var base=f.manifest;
        var scopeManifest=new RuleManifest("athena-rule/2","ATHENA.I03.SP3_SOURCE_SCOPE","1.0.0","SYNTHETIC_SOURCE_SCOPE",base.family(),base.tier(),"fixture.source-scope","1",SystemGraphCertificate.Status.NOT_EVALUATED,false,List.of(),base.requiredChemistry(),List.of(),base.measurementsProduced(),base.classificationStates(),base.parameters(),List.of(new RuleManifest.Source(protocol.toString(),source.payloadSha256(),"synthetic source protocol only"),new RuleManifest.Source("sha256:"+scope.payloadSha256(),scope.payloadSha256(),"Exact synthetic scope interpretation, including original source pins and actual producer identity")),List.of(),List.of("engineering source assertion only"),base.negativeCoverage());
        var q=S1ResearchFixtures.qualify(scopeManifest,f.state,f.selected,temp,"scope-authority-"+scopeIndex++,Map.of(scope.payloadSha256(),scope.readPayload()));
        f.inputs.addAll(q.artifacts());
        }
    }

    record Sample(Source source,S1ResearchFixtures.Qualified qualification,List<EvidenceEnvelope> inputs) { }
    Sample sample(double distance,String variant)throws Exception {
        var fs=List.of(chemical(true,distance,variant),chemical(false,distance,variant));var built=state(fs,variant);
        if(variant.equals("same-component")){var atoms=new ArrayList<MolecularGraph.Atom>();var bonds=new ArrayList<MolecularGraph.Bond>();var h=new TreeMap<String,Integer>();var map=new TreeMap<String,AtomReference>();
            for(int i=0;i<2;i++){String prefix=i==0?"m_":"p_";var source=fs.get(i);for(var a:source.graph().atoms()){atoms.add(new MolecularGraph.Atom(prefix+a.id(),a.element(),a.isotope(),a.formalCharge(),a.explicitHydrogens(),a.aromatic(),a.stereochemistry(),a.coordinates(),a.properties()));h.put(prefix+a.id(),source.hydrogens().get(a.id()));map.put(prefix+a.id(),built.components().get(i).correspondenceAlternatives().getFirst().get(a.id()));}for(var b:source.graph().bonds())bonds.add(bond(prefix+b.firstAtomId(),prefix+b.secondAtomId(),b.order()));}
            bonds.add(bond("m_PRE_CM","p_PRE_CM",MolecularGraph.BondOrder.SINGLE));var graph=new MolecularGraph(atoms,bonds,Map.of("fixture","finite connected source components"));var actual=new ArrayList<>(built.graph().structure().bonds());actual.add(new Bond(map.get("m_PRE_CM"),map.get("p_PRE_CM"),totah.lab.gaia.chemistry.BondOrder.SINGLE));built=new SystemStateView(built.identity(),ResidueGraph.from(new Structure(built.graph().structure().getChains(),actual,ConnectivityProvenance.EXPLICIT)),List.of(new SystemStateView.Component(ref(ScientificReference.Kind.SUBJECT,"same-component"),graph,List.of(map),List.of())),built.sources(),Set.of(),built.charges(),true,true,built.limitations());fs=List.of(new B01FunctionalGroupAcceptanceTest.Fixture(graph,h));}
        var f=new Source(built);if(variant.equals("second-h"))f.selected.set(1,new AtomReference("A",2,' ',"HA2"));var definitions=JSON.readTree(f.manifest.parameters().get("sources").value());
        for(int i=0;i<fs.size();i++){var coverage=coverage(f.state,fs.get(i));coverage.set("componentReference",node(f.state.components().get(i).identity()));
            if(variant.equals("missing-h"))coverage.path("atomState").forEach(v->((ObjectNode)v).put("hydrogenMode","UNKNOWN").putNull("implicitHydrogenCount"));
            if(variant.equals("missing-charge"))coverage.path("atomState").forEach(v->((ObjectNode)v).put("chargeStatus","UNKNOWN_INCONCLUSIVE").putNull("formalCharge"));
            if(variant.equals("missing-aromaticity"))coverage.path("atomState").forEach(v->((ObjectNode)v).put("aromaticityStatus","UNKNOWN_INCONCLUSIVE"));
            if(variant.equals("known-incompatible-h"))((ObjectNode)coverage.path("atomState").path("CA")).put("implicitHydrogenCount",4);
            if(variant.equals("incomplete-graph"))coverage.put("completeGraph","UNKNOWN_INCONCLUSIVE");
            var ce=f.add("athena:group-source-coverage",SystemStateView.bytes(coverage),ref(ScientificReference.Kind.METHOD,"i04-source"));
            if(!variant.equals("missing-scope"))f.scope(ce,variant.equals("known-connection")?"KNOWN_NON_ORDINARY_CONNECTION":variant.equals("unknown-scope")?"UNKNOWN":"COMPLETE_ORDINARY_COVALENT_NO_COORDINATION",false,false);
            if(variant.equals("conflict"))f.scope(ce,"UNKNOWN",false,false);
            if(!variant.equals("missing-pattern"))for(var def:definitions){var m=RuleRegistry.decode(SystemStateView.bytes(def));var collector=RuleAnalyzers.collector(m,request(f.state,m),BACKEND);var result=collector.analyze(f.state,List.of(ce,envelope(f.state,"athena:group-definition",JSON.readTree(m.parameters().get("definition").value()))),Map.of()).getFirst();f.add("athena:group-identities",result.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method());}
        }
        var plan=JSON.createObjectNode();plan.put("schema","athena-continuous-geometry-plan/1");plan.set("stateBinding",node(f.state.binding()));plan.put("coordinateUnit","ANGSTROM");plan.set("coordinateSourceReferences",node(f.state.sources()));plan.putArray("groups");var ops=plan.putArray("operations");var op=ops.addObject();op.put("id","distance");op.put("kind","DISTANCE");op.set("atoms",node(f.selected.subList(1,3)));op=ops.addObject();op.put("id","angle");op.put("kind","ANGLE");op.set("atoms",node(f.selected.subList(0,3)));plan.putNull("radiusAssignmentReference");plan.set("sourceReferences",node(f.state.sources()));plan.putArray("limitations").add("Synthetic exact source geometry");f.add("athena:continuous-geometry-plan",SystemStateView.bytes(plan),ref(ScientificReference.Kind.METHOD,"i04-plan"));
        var q=S1ResearchFixtures.qualify(f.manifest,f.state,f.selected,temp.resolve(UUID.randomUUID().toString()),"i04");f.manifest=q.manifest();if(!variant.equals("no-scope-authority"))qualifyScope(f,temp.resolve(UUID.randomUUID().toString()));return new Sample(f,q,new ArrayList<>(f.inputs));
    }
    List<SystemGraphAnalyzer.Finding> evaluate(Sample s,boolean current)throws Exception {var f=s.source();var before=SystemStateView.bytes(f.state.snapshot());var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(f.manifest,s.qualification().request());var raw=collector.analyze(f.state,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"i04"),"measurement","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),f.state.subject(),T,List.of()));if(current)inputs.addAll(s.qualification().artifacts());var out=RuleAnalyzers.evaluator(f.manifest,s.qualification().request()).analyze(f.state,inputs,Map.of());assertArrayEquals(before,SystemStateView.bytes(f.state.snapshot()));return out;}
    @ParameterizedTest @ValueSource(doubles={2.5,3.0,3.4}) void exactSelectedContact(double d)throws Exception {assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,evaluate(sample(d,"valid"),true).getFirst().status());}
    @Test void shortRelaxedBranchIsDistinctFromTableOnly()throws Exception {assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,evaluate(sample(2.5,"relaxed"),true).getFirst().status());assertEquals(EvidenceInterpretation.Status.ABSENT_FALSE,evaluate(sample(3.1,"relaxed"),true).getFirst().status());}
    @Test void selectedNegativeRequiresExactEligiblePair()throws Exception {assertEquals(EvidenceInterpretation.Status.ABSENT_FALSE,evaluate(sample(4,"valid"),true).getFirst().status());assertEquals(EvidenceInterpretation.Status.ABSENT_FALSE,evaluate(sample(2,"wrong-angle"),true).getFirst().status());}
    @ParameterizedTest @ValueSource(strings={"permuted","second-h","protium","primary-cap","tertiary-cap"}) void explicitTupleVariants(String v)throws Exception {assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,evaluate(sample(2,v),true).getFirst().status());}
    @Test void eachHydrogenRemainsDistinct()throws Exception {var a=evaluate(sample(2,"valid"),true).getFirst();var b=evaluate(sample(2,"second-h"),true).getFirst();assertNotEquals(a.measurements().get("tuple"),b.measurements().get("tuple"));assertEquals("EXPLICIT_SOURCE_H",a.measurements().get("geometryEvidenceKind"));assertTrue(a.measurements().get("hydrogenInterpretation").contains("no experimental-observation inference"));}
    @ParameterizedTest @ValueSource(strings={"missing-h","missing-charge","missing-aromaticity","missing-none","incomplete-graph","missing-scope","unknown-scope","conflict","ambiguous","missing-pattern","degenerate","zero","unqualified-frame","missing-h-vertex","implicit-donor","wrong-h-link"}) void unknownCannotBecomeNegative(String v)throws Exception {var r=evaluate(sample(4,v),true).getFirst();assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status(),r.toString());}
    @ParameterizedTest @ValueSource(strings={"substituted-ca","broken-acyl","protonated-n","charged-carbonyl","radical","known-connection","deuterium","wrong-label","same-component","multiply-bonded-h"}) void boundedExclusionsAreNotContactAbsence(String v)throws Exception {var r=evaluate(sample(4,v),true).getFirst();assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,r.status(),r.toString());}
    @Test void duplicateCanonicalSourceNameIsRejectedBeforeEvaluation()throws Exception {assertThrows(IllegalArgumentException.class,()->sample(2,"duplicate-name"));}
    @Test void sameIdentityChangedBytesRejected()throws Exception {var s=sample(2,"valid");var e=s.inputs().getFirst();var bytes="{}".getBytes(java.nio.charset.StandardCharsets.UTF_8);var changed=new EvidenceEnvelope(e.reference(),e.evidenceType(),e.payloadFormat(),e.payloadVersion(),Optional.of(Base64.getEncoder().encodeToString(bytes)),Optional.empty(),EvidenceExchange.sha256(bytes),e.provenance(),e.method(),e.context(),e.subjects(),e.qualifications(),e.limitations(),e.recordedAt());var inputs=new ArrayList<>(s.inputs());inputs.add(changed);assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void changedRawGeometryCannotReplay()throws Exception {var s=sample(2,"valid");var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(s.source().manifest,s.qualification().request());var raw=(ObjectNode)JSON.readTree(collector.analyze(s.source().state,inputs,Map.of()).getFirst().measurements().get("payload"));raw.put("inventedContact",true);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"i04-tamper"),"raw","athena:rule-measurements",SystemStateView.bytes(raw),collector.method(),s.source().state.subject(),T,List.of()));inputs.addAll(s.qualification().artifacts());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.evaluator(s.source().manifest,s.qualification().request()).analyze(s.source().state,inputs,Map.of()));}
    @ParameterizedTest @ValueSource(doubles={Double.NaN,Double.POSITIVE_INFINITY}) void nonfiniteSourceCoordinatesAreRejectedBeforeEvaluation(double d)throws Exception {assertThrows(IllegalArgumentException.class,()->sample(d,"valid"));}
    @Test void identicalCoordinatesInAnotherStateCannotReplay()throws Exception {var a=sample(2,"valid");var b=sample(2,"different-state");assertEquals(a.source().state.binding().coordinateSha256(),b.source().state.binding().coordinateSha256());assertNotEquals(a.source().state.binding(),b.source().state.binding());assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(b.source(),b.qualification(),a.inputs()),true));}
    @Test void changedStateCannotConsumePriorEvidence()throws Exception {var s=sample(2,"valid");var changed=sample(2.5,"valid");assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(changed.source(),changed.qualification(),s.inputs()),true));}
    @Test void absentSelectedEvidenceNeverConsumesHistoricalChemistry()throws Exception {var s=sample(2,"valid");var inputs=s.inputs().stream().filter(e->e.evidenceType().equals("athena:continuous-geometry-plan")).toList();assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),inputs),true).getFirst().status());}
    @Test void conflictingIndependentSourceFactsRemainUnknown()throws Exception {var s=sample(2,"valid");var e=s.inputs().stream().filter(x->x.evidenceType().equals("athena:group-source-coverage")).findFirst().orElseThrow();var c=(ObjectNode)JSON.readTree(e.readPayload());((ObjectNode)c.path("atomState").path("N")).put("formalCharge",1);var inputs=new ArrayList<>(s.inputs());inputs.add(envelope(s.source().state,"athena:group-source-coverage",c));assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),inputs),true).getFirst().status());}
    @Test void conflictingHydrogenAssertionsCannotEstablishEligibility()throws Exception {var s=sample(2,"valid");var e=s.inputs().stream().filter(x->x.evidenceType().equals("athena:group-source-coverage")).findFirst().orElseThrow();var c=(ObjectNode)JSON.readTree(e.readPayload());((ObjectNode)c.path("atomState").path("CA")).put("implicitHydrogenCount",4);var inputs=new ArrayList<>(s.inputs());inputs.add(envelope(s.source().state,"athena:group-source-coverage",c));assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),inputs),true).getFirst().status());}
    @Test void exactOrderedAnchorTupleCannotBeReplaced()throws Exception {var s=sample(2,"valid");var r=s.qualification().request();var atoms=new ArrayList<>(r.atoms());Collections.swap(atoms,0,1);var changed=new RuleRequest(r.state(),r.manifestKey(),r.manifestSha256(),atoms,r.first(),r.second(),r.radiusAngstrom(),r.maximumHops(),r.maximumNodes(),r.maximumCandidates());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.collector(s.source().manifest,changed).analyze(s.source().state,s.inputs(),Map.of()));}
    @Test void absentScopeAuthorityAndParentAuthorityStaySeparate()throws Exception {assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample(2,"no-scope-authority"),true).getFirst().status());assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample(2,"valid"),false).getFirst().status());}
    @Test void missingCovalentLinkIsNotSequenceAdjacency()throws Exception {assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(sample(2,"missing-link"),true).getFirst().status());}
    @Test void exactDuplicateReorderedEvidenceReplays()throws Exception {var s=sample(2,"valid");var inputs=new ArrayList<>(s.inputs());inputs.add(inputs.getFirst());Collections.reverse(inputs);assertEquals(evaluate(s,true),evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void manifestCannotSelfQualifyOrChangeThreshold()throws Exception {var n=(ObjectNode)JSON.readTree(Files.readAllBytes(MANIFEST));n.put("qualification","QUALIFIED");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));n.put("qualification","NOT_EVALUATED");((ObjectNode)n.path("parameters").path("geometry")).put("value","{}");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));}
    @Test void expiredInteractionReceiptIsNotCurrentAuthority()throws Exception {var s=sample(2,"valid");var artifacts=new ArrayList<>(s.qualification().artifacts());var e=artifacts.stream().filter(x->x.evidenceType().equals("athena:rule-qualification-receipt")).findFirst().orElseThrow();var r=totah.lab.athena.system.rules.research.ResearchDocuments.decode(e.readPayload(),totah.lab.athena.system.rules.research.RuleQualificationReceipt.class);var expired=new totah.lab.athena.system.rules.research.RuleQualificationReceipt(r.schema(),r.ruleKey(),r.manifestSha256(),r.eligibility(),r.implementationReport(),r.foundationCertificate(),r.stateBinding(),r.request(),r.qualification(),r.mode(),r.evaluatedAt().plusSeconds(60),r.reasons());artifacts.remove(e);artifacts.add(S1ResearchFixtures.envelope(s.source().state,"i04-expired","receipt","athena:rule-qualification-receipt",totah.lab.athena.system.rules.research.ResearchDocuments.encode(expired)));var q=new S1ResearchFixtures.Qualified(s.qualification().manifest(),s.qualification().request(),artifacts);assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(new Sample(s.source(),q,s.inputs()),true).getFirst().status());}
    @ParameterizedTest @ValueSource(strings={"scope-protocol","original-source"}) void missingOriginalOrPreparationProvenanceIsUnknown(String name)throws Exception {var x=sample(2,"valid");var inputs=x.inputs().stream().filter(e->!e.method().id().equals(name)).toList();assertTrue(inputs.size()<x.inputs().size());assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(x.source(),x.qualification(),inputs),true).getFirst().status());}
    @Test void proxyCannotReplaceExplicitHydrogenGeometry()throws Exception {var x=sample(2,"valid");var r=x.qualification().request();var t=new ArrayList<>(r.atoms());t.set(1,new AtomReference("A",2,' ',"N"));var changed=new RuleRequest(r.state(),r.manifestKey(),r.manifestSha256(),t,r.first(),r.second(),r.radiusAngstrom(),r.maximumHops(),r.maximumNodes(),r.maximumCandidates());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.collector(x.source().manifest,changed).analyze(x.source().state,x.inputs(),Map.of()));}
    public static void main(String[] args)throws Exception {var t=new GlycineHCarbonylAcceptanceTest();t.temp=Files.createDirectories(Path.of(args[0]));Files.write(Path.of(args[1]),SystemStateView.bytes(t.evaluate(t.sample(2,"valid"),true)));}
}
