package totah.lab.daedalus.system;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.design.backend.MolecularGraph;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.gaia.structure.*;
import totah.lab.gaia.chemistry.Element;
import totah.lab.gaia.graph.ResidueGraph;
import totah.lab.athena.interaction.perception.FormalChargeAssignments;
import totah.lab.gaia.geometry.Point3D;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.*;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.canonical;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.pin;
/** Independent hand-specified finite source graphs; no production chemistry or source authority. */
class MetPheSurveyAcceptanceTest {
    @TempDir Path temp;
    static final Path MANIFEST=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/met-phe-survey-v1/ATHENA.G03.SOURCE_MET_PHE_SURVEY_CONTACT.rule.json");
    static B01FunctionalGroupAcceptanceTest.Fixture chemical(boolean met,double distance,String variant) {
        var h=new LinkedHashMap<String,Integer>();h.put("PRE_CM",3);h.put("PRE_C",0);h.put("PRE_O",0);h.put("N",1);h.put("CA",1);h.put("C",0);h.put("O",0);h.put("CB",2);h.put("CG",met?2:0);
        if(met){h.put("SD",0);h.put("CE",3);}else for(var n:List.of("CD1","CE1","CZ","CE2","CD2"))h.put(n,1);h.put("POST_N",1);h.put("POST_CM",3);
        var bonds=new ArrayList<MolecularGraph.Bond>();for(var edge:List.of("PRE_CM PRE_C","PRE_C N","N CA","CA C","CA CB","CB CG","C POST_N","POST_N POST_CM")){var e=edge.split(" ");bonds.add(bond(e[0],e[1],MolecularGraph.BondOrder.SINGLE));}
        bonds.add(bond("PRE_C","PRE_O",MolecularGraph.BondOrder.DOUBLE));bonds.add(bond("C","O",MolecularGraph.BondOrder.DOUBLE));
        var ring=List.of("CG","CD1","CE1","CZ","CE2","CD2");
        if(met){bonds.add(bond("CG","SD",MolecularGraph.BondOrder.SINGLE));bonds.add(bond("SD","CE",MolecularGraph.BondOrder.SINGLE));}else for(int i=0;i<6;i++)bonds.add(bond(ring.get(i),ring.get((i+1)%6),MolecularGraph.BondOrder.AROMATIC));
        if(met&&variant.equals("missing-link")){bonds.removeIf(b->Set.of(b.firstAtomId(),b.secondAtomId()).equals(Set.of("N","PRE_C")));h.put("N",2);h.put("PRE_C",1);}
        if(met&&variant.equals("extra-sulfur")){h.put("EX",3);bonds.add(bond("SD","EX",MolecularGraph.BondOrder.SINGLE));}
        if(!met&&variant.equals("substituted-ring")){h.put("EX",3);h.put("CZ",0);bonds.add(bond("CZ","EX",MolecularGraph.BondOrder.SINGLE));}
        if(met&&variant.equals("sulfoxide")){h.put("OX",0);bonds.add(bond("SD","OX",MolecularGraph.BondOrder.DOUBLE));}
        if(met&&variant.equals("thiol")){bonds.removeIf(b->Set.of(b.firstAtomId(),b.secondAtomId()).equals(Set.of("SD","CE")));bonds.add(bond("CB","CE",MolecularGraph.BondOrder.SINGLE));h.put("SD",1);h.put("CB",1);}
        if(met&&variant.equals("explicit-h")){h.put("H",0);h.put("CE",2);bonds.add(bond("CE","H",MolecularGraph.BondOrder.SINGLE));}
        if(variant.equals("same-component"))h.put("PRE_CM",2);
        var atoms=new ArrayList<MolecularGraph.Atom>();double[][] xy={{1,0},{.5,1},{-.5,1},{-1,0},{-.5,-1},{.5,-1}};
        for(var id:h.keySet()){String e=id.equals("H")?"H":id.equals("OX")?"O":id.equals("SD")?(variant.equals("sulfur-lookalike")?"O":"S"):id.endsWith("O")?"O":id.endsWith("N")?"N":!met&&id.equals("CZ")&&variant.equals("heteroring")?"N":"C";int index=ring.indexOf(id);boolean aromatic=!met&&index>=0;double x=atoms.size()+20,y=0,z=0;
            if(aromatic){x=xy[index][0];y=xy[index][1];if(variant.equals("degenerate"))y=0;}
            if(met&&id.equals("SD")){x=variant.equals("coplanar")?distance:0;z=variant.equals("coplanar")?0:distance;}
            if(met&&id.equals("CG")){x=variant.equals("unused-angle-degenerate")?0:-1;z=distance;}
            if(variant.equals("zero")&&met&&id.equals("SD")){x=0;z=0;}
            int charge=met&&id.equals("SD")&&variant.equals("charged")?1:0;
            var a=atom(id,e,charge,aromatic,x,y,z);var props=new TreeMap<String,String>();if(!variant.equals("missing-none"))props.put("athena.ocl.atomRadicalState/1",variant.equals("radical")&&met&&id.equals("SD")?"D":"NONE");
            Integer isotope=aromatic&&(variant.equals("uniform-isotope")||variant.equals("mixed-isotope")&&id.equals("CZ"))?13:null;
            atoms.add(new MolecularGraph.Atom(id,e,isotope,charge,a.explicitHydrogens(),aromatic,a.stereochemistry(),a.coordinates(),props));}
        if(variant.equals("permuted")){Collections.reverse(atoms);Collections.reverse(bonds);}
        return new B01FunctionalGroupAcceptanceTest.Fixture(new MolecularGraph(atoms,bonds,Map.of("fixture",met?"finite-met-amide":"finite-phe-amide")),h);
    }
    static SystemStateView state(List<B01FunctionalGroupAcceptanceTest.Fixture> fs,String variant) {
        var residues=new ArrayList<Residue>();var bonds=new ArrayList<Bond>();var components=new ArrayList<SystemStateView.Component>();var charges=new TreeMap<AtomReference,Integer>();
        for(int i=0;i<fs.size();i++){var graph=fs.get(i).graph();var map=new TreeMap<String,AtomReference>();var grouped=new TreeMap<Integer,List<Atom>>();int selected=3*i+2;
            for(var a:graph.atoms()){int r=a.id().startsWith("PRE_")?selected-1:a.id().startsWith("POST_")?selected+1:selected;String name=a.id().replace("PRE_","").replace("POST_","");var ar=new AtomReference("A",r,' ',name);map.put(a.id(),ar);charges.put(ar,a.formalCharge());var xyz=a.coordinates();var atom=Atom.builder().name(name).element(Element.fromSymbol(a.element())).autoDockType(a.aromatic()?"A":a.element()).position(new Point3D(xyz.x(),xyz.y(),xyz.z())).build();grouped.computeIfAbsent(r,k->new ArrayList<>()).add(atom);if(variant.equals("duplicate-name")&&i==0&&name.equals("SD"))grouped.get(r).add(atom);}
            for(var entry:grouped.entrySet())residues.add(new Residue(entry.getKey()==selected?(variant.equals("wrong-label")?"UNK":i==0?"MET":"PHE"):"CAP",entry.getKey(),entry.getValue()));
            for(var b:graph.bonds())bonds.add(new Bond(map.get(b.firstAtomId()),map.get(b.secondAtomId()),totah.lab.gaia.chemistry.BondOrder.valueOf(b.order().name())));
            components.add(new SystemStateView.Component(ref(ScientificReference.Kind.SUBJECT,"g03-component-"+i),graph,variant.equals("ambiguous")?List.of(map,map):List.of(map),List.of("hand-authored source graph")));}
        return new SystemStateView(ref(ScientificReference.Kind.CONTEXT,"g03-state"),ResidueGraph.from(new Structure(List.of(new Chain("A",residues)),bonds,ConnectivityProvenance.EXPLICIT)),components,List.of(ref(ScientificReference.Kind.SOURCE,"synthetic-g03")),Set.of(),new FormalChargeAssignments(charges),!variant.equals("unqualified-frame"),true,List.of("Synthetic coordinates; no experimental/energetic assertion"));
    }
    static class Source {
        final SystemStateView state;RuleManifest manifest;final List<EvidenceEnvelope> inputs=new ArrayList<>();final List<AtomReference> selected;int seq;
        Source(SystemStateView s)throws Exception {state=s;manifest=RuleRegistry.decode(Files.readAllBytes(MANIFEST));selected=new ArrayList<>();selected.add(new AtomReference("A",2,' ',"CG"));selected.add(new AtomReference("A",2,' ',"SD"));for(var n:List.of("CG","CD1","CE1","CZ","CE2","CD2"))selected.add(new AtomReference("A",5,' ',n));}
        EvidenceEnvelope add(String type,byte[] bytes,ScientificReference method) {var e=SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"s1-synthetic"),"input-"+seq++,type,bytes,method,state.subject(),T,List.of("hand-authored engineering fixture; no production scope authority"));inputs.add(e);return e;}
        void scope(EvidenceEnvelope coverage,String connection,boolean wrongAtoms,boolean wrongState)throws Exception {
            var coverageComponent=JSON.readTree(coverage.readPayload()).path("componentReference");var c=state.components().stream().filter(x->JSON.valueToTree(x.identity()).equals(coverageComponent)).findFirst().orElseThrow();var protocol=add("athena:source-artifact","synthetic lossless source protocol; no real preparation assertion".getBytes(java.nio.charset.StandardCharsets.UTF_8),ref(ScientificReference.Kind.METHOD,"scope-protocol"));
            boolean nonordinary=connection.equals("KNOWN_NON_ORDINARY_CONNECTION");
            var original=add("athena:source-artifact",SystemStateView.bytes(nonordinary?Map.of("ordinaryProjection",state.snapshot(),"explicitOriginalConnection",Map.of("identity","source-dative-17","first","component-source-N:a1","second","source-Zn:external","kind","DATIVE")):state.snapshot()),ref(ScientificReference.Kind.METHOD,"original-source"));
            var values=new TreeMap<String,String>();values.put("proposition",nonordinary?"ATHENA.I03.SP3_SOURCE_SCOPE/2":"ATHENA.I03.SP3_SOURCE_SCOPE/1");values.put("stateBinding",wrongState?"{}":canonical(state.binding()));values.put("componentReference",canonical(c.identity()));values.put("atoms",canonical(wrongAtoms?List.of():c.correspondenceAlternatives().getFirst().values().stream().sorted(Comparator.comparing(S1NitrogenAcceptanceTest::canonical)).toList()));values.put("connectionCoverage",connection);values.put("electronicStateCoverage","COMPLETE_EXPLICIT_NONE");values.put("sourceProtocol",canonical(pin(protocol)));
            var method=ref(ScientificReference.Kind.METHOD,"unqualified-synthetic-scope");var i=new EvidenceInterpretation(ref(ScientificReference.Kind.EVIDENCE_INTERPRETATION,"scope-"+seq),List.of(new EvidenceInterpretation.Input(coverage.reference(),coverage.payloadSha256()),new EvidenceInterpretation.Input(protocol.reference(),protocol.payloadSha256()),new EvidenceInterpretation.Input(original.reference(),original.payloadSha256())),method,Map.of(),List.of(state.subject()),nonordinary?EvidenceInterpretation.Status.UNSUPPORTED:EvidenceInterpretation.Status.SUPPORTED_PRESENT,values,List.of(nonordinary?"Original connection source-dative-17: component-source-N:a1 -> source-Zn:external, explicitly DATIVE; exact original bytes pinned":"synthetic complete assertion"),List.of("not independently qualified"),Optional.empty(),totah.lab.athena.system.rules.research.ResearchGateAcceptanceTest.AT);
            add("athena:event-source",new EvidenceExchange().encodeRecord(i),method);
        }
    }
    static void qualifyScope(Source f,Path temp)throws Exception {
        var scopes=f.inputs.stream().filter(e->e.evidenceType().equals("athena:event-source")).toList();
        int scopeIndex=0;for(var scope:scopes){
        var old=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(scope.readPayload());
        var p=B01FunctionalGroupAcceptanceTest.JSON.readTree(old.measurements().get("sourceProtocol"));
        var source=f.inputs.stream().filter(e->e.payloadSha256().equals(p.path("sha256").asText())).findFirst().orElseThrow();
        Path protocol=Path.of("software/modules/daedalus/src/test/resources/i03-s1/synthetic-source-protocol.txt");assertArrayEquals(Files.readAllBytes(protocol),source.readPayload());
        var base=f.manifest;
        var scopeManifest=new RuleManifest("athena-rule/2","ATHENA.I03.SP3_SOURCE_SCOPE","1.0.0","SYNTHETIC_SOURCE_SCOPE",base.family(),base.tier(),"fixture.source-scope","1",SystemGraphCertificate.Status.NOT_EVALUATED,false,List.of(),base.requiredChemistry(),List.of(),base.measurementsProduced(),base.classificationStates(),base.parameters(),List.of(new RuleManifest.Source(protocol.toString(),source.payloadSha256(),"synthetic source protocol only"),new RuleManifest.Source("sha256:"+scope.payloadSha256(),scope.payloadSha256(),"Exact synthetic scope interpretation, including original source pins and actual producer identity")),List.of(),List.of("engineering source assertion only"),base.negativeCoverage());
        var q=S1ResearchFixtures.qualify(scopeManifest,f.state,f.selected,temp,"scope-authority-"+scopeIndex++,Map.of(scope.payloadSha256(),scope.readPayload()));
        f.inputs.addAll(q.artifacts());
        }
    }

    record Sample(Source source,S1ResearchFixtures.Qualified qualification,List<EvidenceEnvelope> inputs) { }
    Sample sample(double distance,String variant)throws Exception {
        var fs=List.of(chemical(true,distance,variant),chemical(false,distance,variant));var built=state(fs,variant);
        if(variant.equals("same-component")){var atoms=new ArrayList<MolecularGraph.Atom>();var bonds=new ArrayList<MolecularGraph.Bond>();var h=new TreeMap<String,Integer>();var map=new TreeMap<String,AtomReference>();
            for(int i=0;i<2;i++){String prefix=i==0?"m_":"p_";var source=fs.get(i);for(var a:source.graph().atoms()){atoms.add(new MolecularGraph.Atom(prefix+a.id(),a.element(),a.isotope(),a.formalCharge(),a.explicitHydrogens(),a.aromatic(),a.stereochemistry(),a.coordinates(),a.properties()));h.put(prefix+a.id(),source.hydrogens().get(a.id()));map.put(prefix+a.id(),built.components().get(i).correspondenceAlternatives().getFirst().get(a.id()));}for(var b:source.graph().bonds())bonds.add(bond(prefix+b.firstAtomId(),prefix+b.secondAtomId(),b.order()));}
            bonds.add(bond("m_PRE_CM","p_PRE_CM",MolecularGraph.BondOrder.SINGLE));var graph=new MolecularGraph(atoms,bonds,Map.of("fixture","finite connected source components"));var actual=new ArrayList<>(built.graph().structure().bonds());actual.add(new Bond(map.get("m_PRE_CM"),map.get("p_PRE_CM"),totah.lab.gaia.chemistry.BondOrder.SINGLE));built=new SystemStateView(built.identity(),ResidueGraph.from(new Structure(built.graph().structure().getChains(),actual,ConnectivityProvenance.EXPLICIT)),List.of(new SystemStateView.Component(ref(ScientificReference.Kind.SUBJECT,"same-component"),graph,List.of(map),List.of())),built.sources(),Set.of(),built.charges(),true,true,built.limitations());fs=List.of(new B01FunctionalGroupAcceptanceTest.Fixture(graph,h));}
        var f=new Source(built);var definitions=JSON.readTree(f.manifest.parameters().get("sources").value());
        for(int i=0;i<fs.size();i++){var coverage=coverage(f.state,fs.get(i));coverage.set("componentReference",node(f.state.components().get(i).identity()));
            if(variant.equals("missing-h"))coverage.path("atomState").forEach(v->((ObjectNode)v).put("hydrogenMode","UNKNOWN").putNull("implicitHydrogenCount"));
            if(variant.equals("missing-charge"))coverage.path("atomState").forEach(v->((ObjectNode)v).put("chargeStatus","UNKNOWN_INCONCLUSIVE").putNull("formalCharge"));
            if(variant.equals("missing-aromaticity"))coverage.path("atomState").forEach(v->((ObjectNode)v).put("aromaticityStatus","UNKNOWN_INCONCLUSIVE"));
            if(variant.equals("known-incompatible-h"))((ObjectNode)coverage.path("atomState").path("CG")).put("implicitHydrogenCount",4);
            if(variant.equals("incomplete-graph"))coverage.put("completeGraph","UNKNOWN_INCONCLUSIVE");
            var ce=f.add("athena:group-source-coverage",SystemStateView.bytes(coverage),ref(ScientificReference.Kind.METHOD,"g03-source"));
            if(!variant.equals("missing-scope"))f.scope(ce,variant.equals("known-connection")?"KNOWN_NON_ORDINARY_CONNECTION":variant.equals("unknown-scope")?"UNKNOWN":"COMPLETE_ORDINARY_COVALENT_NO_COORDINATION",false,false);
            if(variant.equals("conflict"))f.scope(ce,"UNKNOWN",false,false);
            if(!variant.equals("missing-pattern"))for(var def:definitions){var m=RuleRegistry.decode(SystemStateView.bytes(def));var collector=RuleAnalyzers.collector(m,request(f.state,m),BACKEND);var result=collector.analyze(f.state,List.of(ce,envelope(f.state,"athena:group-definition",JSON.readTree(m.parameters().get("definition").value()))),Map.of()).getFirst();f.add("athena:group-identities",result.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method());}
        }
        var plan=JSON.createObjectNode();plan.put("schema","athena-continuous-geometry-plan/1");plan.set("stateBinding",node(f.state.binding()));plan.put("coordinateUnit","ANGSTROM");plan.set("coordinateSourceReferences",node(f.state.sources()));var group=plan.putArray("groups").addObject();group.put("id","phe-ring");group.set("atoms",node(f.selected.subList(2,8).stream().sorted().toList()));group.set("sourceReferences",node(f.state.sources()));var op=plan.putArray("operations").addObject();op.put("id","selected");op.put("kind","POINT_PAIR_GROUP");op.set("atoms",node(f.selected.subList(0,2)));op.put("groupId","phe-ring");plan.putNull("radiusAssignmentReference");plan.set("sourceReferences",node(f.state.sources()));plan.putArray("limitations").add("Synthetic exact source geometry");f.add("athena:continuous-geometry-plan",SystemStateView.bytes(plan),ref(ScientificReference.Kind.METHOD,"g03-plan"));
        var q=S1ResearchFixtures.qualify(f.manifest,f.state,f.selected,temp.resolve(UUID.randomUUID().toString()),"g03");f.manifest=q.manifest();if(!variant.equals("no-scope-authority"))qualifyScope(f,temp.resolve(UUID.randomUUID().toString()));return new Sample(f,q,new ArrayList<>(f.inputs));
    }
    List<SystemGraphAnalyzer.Finding> evaluate(Sample s,boolean current)throws Exception {var f=s.source();var before=SystemStateView.bytes(f.state.snapshot());var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(f.manifest,s.qualification().request());var raw=collector.analyze(f.state,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"g03"),"measurement","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),f.state.subject(),T,List.of()));if(current)inputs.addAll(s.qualification().artifacts());var out=RuleAnalyzers.evaluator(f.manifest,s.qualification().request()).analyze(f.state,inputs,Map.of());assertArrayEquals(before,SystemStateView.bytes(f.state.snapshot()));return out;}
    @ParameterizedTest @ValueSource(doubles={3,5,7}) void exactSelectedContact(double d)throws Exception {assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,evaluate(sample(d,"valid"),true).getFirst().status());}
    @Test void selectedNegativeRequiresExactEligiblePair()throws Exception {assertEquals(EvidenceInterpretation.Status.ABSENT_FALSE,evaluate(sample(Math.nextUp(7.0),"valid"),true).getFirst().status());}
    @ParameterizedTest @ValueSource(strings={"coplanar","unused-angle-degenerate","uniform-isotope","permuted","same-component"}) void diagnosticOrRepresentationVariationDoesNotAddCriterion(String v)throws Exception {assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,evaluate(sample(5,v),true).getFirst().status());}
    @ParameterizedTest @ValueSource(strings={"missing-h","missing-charge","missing-aromaticity","missing-none","incomplete-graph","missing-scope","unknown-scope","conflict","ambiguous","missing-pattern","wrong-label","degenerate","zero","unqualified-frame"}) void unknownCannotBecomeNegative(String v)throws Exception {var r=evaluate(sample(8,v),true).getFirst();assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status(),r.toString());}
    @ParameterizedTest @ValueSource(strings={"known-incompatible-h","charged","radical","known-connection","substituted-ring","extra-sulfur","mixed-isotope","sulfoxide","thiol","explicit-h","sulfur-lookalike","heteroring"}) void boundedExclusionsAreNotContactAbsence(String v)throws Exception {var r=evaluate(sample(8,v),true).getFirst();assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,r.status(),r.toString());}
    @Test void duplicateCanonicalSourceNameIsRejectedBeforeEvaluation()throws Exception {assertThrows(IllegalArgumentException.class,()->sample(5,"duplicate-name"));}
    @Test void sameIdentityChangedBytesRejected()throws Exception {var s=sample(5,"valid");var e=s.inputs().getFirst();var bytes="{}".getBytes(java.nio.charset.StandardCharsets.UTF_8);var changed=new EvidenceEnvelope(e.reference(),e.evidenceType(),e.payloadFormat(),e.payloadVersion(),Optional.of(Base64.getEncoder().encodeToString(bytes)),Optional.empty(),EvidenceExchange.sha256(bytes),e.provenance(),e.method(),e.context(),e.subjects(),e.qualifications(),e.limitations(),e.recordedAt());var inputs=new ArrayList<>(s.inputs());inputs.add(changed);assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void changedRawGeometryCannotReplay()throws Exception {var s=sample(5,"valid");var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(s.source().manifest,s.qualification().request());var raw=(ObjectNode)JSON.readTree(collector.analyze(s.source().state,inputs,Map.of()).getFirst().measurements().get("payload"));raw.put("inventedContact",true);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"g03-tamper"),"raw","athena:rule-measurements",SystemStateView.bytes(raw),collector.method(),s.source().state.subject(),T,List.of()));inputs.addAll(s.qualification().artifacts());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.evaluator(s.source().manifest,s.qualification().request()).analyze(s.source().state,inputs,Map.of()));}
    @Test void changedStateCannotConsumePriorEvidence()throws Exception {var s=sample(5,"valid");var changed=sample(6,"valid");assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(changed.source(),changed.qualification(),s.inputs()),true));}
    @Test void absentSelectedEvidenceNeverConsumesHistoricalChemistry()throws Exception {var s=sample(5,"valid");var inputs=s.inputs().stream().filter(e->e.evidenceType().equals("athena:continuous-geometry-plan")).toList();assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),inputs),true).getFirst().status());}
    @Test void conflictingIndependentSourceFactsRemainUnknown()throws Exception {var s=sample(5,"valid");var e=s.inputs().stream().filter(x->x.evidenceType().equals("athena:group-source-coverage")).findFirst().orElseThrow();var c=(ObjectNode)JSON.readTree(e.readPayload());((ObjectNode)c.path("atomState").path("SD")).put("formalCharge",1);var inputs=new ArrayList<>(s.inputs());inputs.add(envelope(s.source().state,"athena:group-source-coverage",c));assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),inputs),true).getFirst().status());}
    @Test void conflictingHydrogenAssertionsCannotEstablishEligibility()throws Exception {var s=sample(5,"valid");var e=s.inputs().stream().filter(x->x.evidenceType().equals("athena:group-source-coverage")).findFirst().orElseThrow();var c=(ObjectNode)JSON.readTree(e.readPayload());((ObjectNode)c.path("atomState").path("CG")).put("implicitHydrogenCount",4);var inputs=new ArrayList<>(s.inputs());inputs.add(envelope(s.source().state,"athena:group-source-coverage",c));assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),inputs),true).getFirst().status());}
    @Test void exactOrderedAnchorTupleCannotBeReplaced()throws Exception {var s=sample(5,"valid");var r=s.qualification().request();var atoms=new ArrayList<>(r.atoms());Collections.swap(atoms,0,1);var changed=new RuleRequest(r.state(),r.manifestKey(),r.manifestSha256(),atoms,r.first(),r.second(),r.radiusAngstrom(),r.maximumHops(),r.maximumNodes(),r.maximumCandidates());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.collector(s.source().manifest,changed).analyze(s.source().state,s.inputs(),Map.of()));}
    @Test void absentScopeAuthorityAndParentAuthorityStaySeparate()throws Exception {assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample(5,"no-scope-authority"),true).getFirst().status());assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample(5,"valid"),false).getFirst().status());}
    @Test void missingCovalentLinkIsNotSequenceAdjacency()throws Exception {assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(sample(5,"missing-link"),true).getFirst().status());}
    @Test void exactDuplicateReorderedEvidenceReplays()throws Exception {var s=sample(5,"valid");var inputs=new ArrayList<>(s.inputs());inputs.add(inputs.getFirst());Collections.reverse(inputs);assertEquals(evaluate(s,true),evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void manifestCannotSelfQualifyOrChangeThreshold()throws Exception {var n=(ObjectNode)JSON.readTree(Files.readAllBytes(MANIFEST));n.put("qualification","QUALIFIED");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));n.put("qualification","NOT_EVALUATED");((ObjectNode)n.path("parameters").path("maximumDistanceAngstrom")).put("value","8");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));}
    @Test void expiredInteractionReceiptIsNotCurrentAuthority()throws Exception {var s=sample(5,"valid");var artifacts=new ArrayList<>(s.qualification().artifacts());var e=artifacts.stream().filter(x->x.evidenceType().equals("athena:rule-qualification-receipt")).findFirst().orElseThrow();var r=totah.lab.athena.system.rules.research.ResearchDocuments.decode(e.readPayload(),totah.lab.athena.system.rules.research.RuleQualificationReceipt.class);var expired=new totah.lab.athena.system.rules.research.RuleQualificationReceipt(r.schema(),r.ruleKey(),r.manifestSha256(),r.eligibility(),r.implementationReport(),r.foundationCertificate(),r.stateBinding(),r.request(),r.qualification(),r.mode(),r.evaluatedAt().plusSeconds(60),r.reasons());artifacts.remove(e);artifacts.add(S1ResearchFixtures.envelope(s.source().state,"g03-expired","receipt","athena:rule-qualification-receipt",totah.lab.athena.system.rules.research.ResearchDocuments.encode(expired)));var q=new S1ResearchFixtures.Qualified(s.qualification().manifest(),s.qualification().request(),artifacts);assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(new Sample(s.source(),q,s.inputs()),true).getFirst().status());}
    public static void main(String[] args)throws Exception {var t=new MetPheSurveyAcceptanceTest();t.temp=Files.createDirectories(Path.of(args[0]));Files.write(Path.of(args[1]),SystemStateView.bytes(t.evaluate(t.sample(5,"valid"),true)));}
}
