package totah.lab.daedalus.system;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import java.nio.file.*;
import java.util.*;
import com.fasterxml.jackson.databind.node.*;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.JSON;
import static totah.lab.mnemosyne.EvidenceInterpretation.Status.*;
class OrderedSignAcceptanceTest {
 @TempDir Path temp;
 @ParameterizedTest @ValueSource(strings={"SER","THR","VAL"})
 void exactReferenceRows(String id)throws Exception {var w=new OrderedSignFixtures(id);w.bind();w.qualify(temp,true);var result=w.evaluate();assertEquals(SUPPORTED_PRESENT,result.status(),result.toString());var p=JSON.readTree(result.measurements().get("payload"));assertEquals(id.equals("THR")?2:1,p.path("rows").size());for(var row:p.path("rows")){assertEquals(4,row.path("atomTuple").size());assertTrue(Set.of("MATCHES_REFERENCE_SIGN","OPPOSES_REFERENCE_SIGN").contains(row.path("comparison").asText()));assertEquals(row.path("sourceRow").path("volumeSign").asText().toUpperCase(),row.path("referenceSign").asText());assertEquals("ANGSTROM_CUBED",row.path("volume").path("unit").asText());}if(id.equals("SER"))assertEquals("OPPOSES_REFERENCE_SIGN",p.path("rows").get(0).path("comparison").asText(),"Source L identity does not force coordinate sign match");String dest=System.getProperty("v08.replay");if(dest!=null)Files.writeString(Path.of(dest+"-"+id+".json"),result.measurements().get("payload"));}
 @ParameterizedTest(name="{0}") @ValueSource(strings={"UNSUPPORTED:GLY","UNSUPPORTED:D-SER","UNSUPPORTED:allo-THR","UNSUPPORTED:deprotonated","UNKNOWN_INCONCLUSIVE:charge","UNKNOWN_INCONCLUSIVE:stereo","UNKNOWN_INCONCLUSIVE:coverage","UNKNOWN_INCONCLUSIVE:coherence","UNKNOWN_INCONCLUSIVE:zero","SUPPORTED_PRESENT:tiny","SUPPORTED_PRESENT:reflected","NOT_EVALUATED:no-rule","NOT_EVALUATED:no-source","NOT_EVALUATED:expired-rule","NOT_EVALUATED:expired-source","NOT_EVALUATED:budget","REJECT:tuple-order","REJECT:invented-comparison","REJECT:volume-bits","REJECT:definition","REJECT:extra-field","UNKNOWN_INCONCLUSIVE:missing-reference"})
 void boundaries(String spec)throws Exception{String expected=spec.split(":")[0],name=spec.split(":")[1],id=name.equals("GLY")?"GLY":name.equals("allo-THR")?"THR":"SER";var xyz=new HashMap<String,double[]>();if(name.equals("zero"))xyz.put("2_CB",new double[]{1,1,0});if(name.equals("tiny"))xyz.put("2_CB",new double[]{1,0,1e-200});if(name.equals("reflected"))xyz.put("2_CB",new double[]{1,0,-1});var w=new OrderedSignFixtures(id,name.equals("deprotonated")?name:"valid",xyz);var f=w.f;String before=S1NitrogenAcceptanceTest.canonical(f.state.binding());var stereo=(ObjectNode)f.facts.get("stereochemistry").path("residues").get(1);if(name.equals("D-SER"))stereo.put("alpha","D");if(name.equals("allo-THR"))stereo.put("beta","OTHER");if(name.equals("stereo"))stereo.put("alpha","UNKNOWN");if(name.equals("charge"))((ObjectNode)f.facts.get("identityState").path("residues").get(1).path("atoms").get(0)).putNull("formalCharge");if(name.equals("coverage"))f.binding.put("sourceScope","UNKNOWN");if(name.equals("coherence"))f.facts.get("coherence").put("correlation","UNRESOLVED");w.bind();w.qualify(temp,!name.equals("no-source"));if(name.equals("no-rule"))f.inputs.removeIf(e->e.evidenceType().equals("athena:rule-qualification-receipt")&&e.reference().id().startsWith("rv-main/"));if(name.startsWith("expired"))CbetaAcceptanceTest.expire(f,name.equals("expired-rule")?"rv-main/":"rv-source/");if(name.equals("budget"))f.request=new RuleRequest(f.request.state(),f.request.manifestKey(),f.request.manifestSha256(),f.request.atoms(),f.request.first(),f.request.second(),.1,0,1,1);if(name.equals("missing-reference")){String sha=totah.lab.mnemosyne.EvidenceExchange.sha256(Files.readAllBytes(OrderedSignFixtures.RES.resolve("s__SER.cif")));f.inputs.removeIf(e->e.payloadSha256().equals(sha));}
  if(expected.equals("REJECT")){var collector=RuleAnalyzers.collector(f.manifest,f.request);var p=(ObjectNode)JSON.readTree(collector.analyze(f.state,f.inputs,Map.of()).getFirst().measurements().get("payload"));var row=(ObjectNode)p.path("rows").get(0);switch(name){case "tuple-order"->{var a=(ArrayNode)row.get("atomTuple");var x=a.get(1);a.set(1,a.get(2));a.set(2,x);}case "invented-comparison"->row.put("comparison","MATCHES_REFERENCE_SIGN");case "volume-bits"->((ObjectNode)row.get("volume")).put("binary64Hex","0000000000000000");case "definition"->p.put("definitionSha256","0".repeat(64));default->p.put("sourceQualified",true);}f.add("athena:rule-measurements",SystemStateView.bytes(p),collector.method());assertThrows(Exception.class,()->RuleAnalyzers.evaluator(f.manifest,f.request).analyze(f.state,f.inputs,Map.of()));return;}
  var result=w.evaluate();assertEquals(totah.lab.mnemosyne.EvidenceInterpretation.Status.valueOf(expected),result.status(),spec+result);assertEquals(before,S1NitrogenAcceptanceTest.canonical(f.state.binding()));if(name.equals("zero")){var row=JSON.readTree(result.measurements().get("payload")).path("rows").get(0);assertEquals(0.,row.path("volume").path("value").doubleValue());assertEquals("SUPPORTED_PRESENT",row.path("volume").path("status").asText());assertTrue(row.path("comparison").isNull());}
 }
}
