package totah.lab.daedalus.system;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.JSON;
import static totah.lab.daedalus.system.ResidueValidationFixtures.node;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.ref;
import static totah.lab.athena.system.rules.research.ResearchGateAcceptanceTest.AT;
import static totah.lab.mnemosyne.EvidenceInterpretation.Status.*;
final class RestraintFixtures {
 static final String ID="ATHENA.V07.MONOMER_LIBRARY_STV_INTERNAL_HEAVY_RESTRAINT_DEVIATION";
 static final String FACT="ATHENA.V07.TRANS_PROFILE_APPLICABILITY_SOURCE_FACT";
 static final Path RES=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/restraint-deviation-v1");
 static final List<String> ROLES=List.of("N","CA","C","O","CB","OG","OG1","CG1","CG2");
 final ResidueValidationFixtures f;final String id;ObjectNode binding,fact;EvidenceEnvelope bindingEnvelope;final Map<String,EvidenceEnvelope> refs=new TreeMap<>();final List<EvidenceEnvelope> profileWitnesses=new ArrayList<>();
 RestraintFixtures(String id)throws Exception{this(id,"valid",Map.of());}
 RestraintFixtures(String id,String variant,Map<String,double[]> xyz)throws Exception{this.id=id;f=new ResidueValidationFixtures(id,true,variant,xyz);f.manifest=RuleRegistry.decode(Files.readAllBytes(RES.resolve(ID+".rule.json")));}
 void prepare()throws Exception {
  f.bindingEnvelope=f.add("athena:residue-context-binding",f.binding);for(var e:f.facts.entrySet())f.witness(e.getKey(),e.getValue());
  for(var s:JSON.readTree(Files.readAllBytes(RES.resolve("SOURCES.json"))))refs.put(s.path("file").asText(),f.add("athena:source-artifact",Files.readAllBytes(RES.resolve(s.path("file").asText())),ref(ScientificReference.Kind.METHOD,"pinned-v07-reference")));
  var profile=JSON.createObjectNode();var original=JSON.readTree(Files.readAllBytes(RES.resolve("REFERENCE_PROFILE.json")));profile.put("identity",original.path("profile").asText());for(var k:List.of("repository","commit","centralModifications","hydrogenRestraints","numericProfile"))profile.set(k,original.get(k.equals("centralModifications")?"centralReferenceModifications":k));profile.set("profileManifest",node(pin(refs.get("REFERENCE_PROFILE.json"))));profile.set("referenceRows",node(pin(refs.get("REFERENCE_ROWS.json"))));
  for(var key:List.of("sourceArtifacts","licenseArtifacts")){var pins=new ArrayList<Object>();for(var spec:original.path(key.equals("sourceArtifacts")?"artifacts":"licenseArtifacts")){String path=spec.path("path").asText();pins.add(pin(refs.get(path.substring(path.lastIndexOf('/')+1))));}profile.set(key,node(pins.stream().sorted(Comparator.comparing(S1NitrogenAcceptanceTest::canonical)).toList()));}
  binding=JSON.createObjectNode();binding.put("schema","athena-restraint-source-reference-binding/1");binding.put("definition",ID+"/1");binding.set("stateBinding",node(f.state.binding()));binding.set("contextBinding",node(pin(f.bindingEnvelope)));binding.set("centralResidue",f.binding.path("central").get("residue"));if(Set.of("SER","THR","VAL").contains(id))binding.put("candidateIdentity",id);else binding.putNull("candidateIdentity");binding.set("referenceProfile",profile);binding.set("preparationReferences",f.binding.get("preparationReferences"));binding.putArray("limitations").add("Synthetic source profile; not production authority");
  var links=binding.putArray("linkBindings");for(int i=0;i<2;i++){var l=links.addObject();l.put("direction",i==0?"INCOMING":"OUTGOING");l.set("from",f.binding.path(i==0?"previous":"central").path("roles").get("C"));l.set("to",f.binding.path(i==0?"central":"next").path("roles").get("N"));l.put("referenceLink","TRANS");l.put("centralComponent",i==0?2:1);l.set("sourceLocations",node(f.locations()));}
  var atoms=binding.putArray("atomCorrespondence");for(var role:ROLES){var a=atoms.addObject();a.put("role",role);var source=f.binding.path("central").path("roles").get(role);a.set("source",source);JsonNode coord=JSON.nullNode();for(var aa:f.binding.path("central").path("atoms"))if(aa.path("source").equals(source))coord=aa.get("coordinate");a.set("coordinate",coord);}
  fact=JSON.createObjectNode();fact.set("centralResidue",binding.get("centralResidue"));fact.set("referenceProfile",profile);fact.set("centralModifications",profile.get("centralModifications"));fact.put("sourceStateDescription","Independent synthetic source-specific TRANS applicability");fact.set("sourceEvidence",node(List.of(pin(f.original))));fact.putArray("reasons").add("Hand authored synthetic review");var lf=fact.putArray("linkFacts");for(var l:links){var x=(ObjectNode)l.deepCopy();x.put("applicability","APPLICABLE");x.set("applicabilityEvidence",node(List.of(pin(f.original))));x.put("rationale","Synthetic exact graph/context profile review, not a geometry assignment");lf.add(x);}
 }
 void bind()throws Exception {
  bindingEnvelope=f.add("athena:restraint-source-reference-binding",binding);witness(fact);
  var selected=new TreeSet<totah.lab.gaia.structure.AtomReference>();for(var a:binding.path("atomCorrespondence"))if(!a.path("coordinate").isNull())selected.add(JSON.treeToValue(a.get("coordinate"),totah.lab.gaia.structure.AtomReference.class));
  f.request=new RuleRequest(f.state.binding(),f.manifest.key(),RuleRegistry.digest(f.manifest),List.copyOf(selected),List.of(ResidueValidationFixtures.residue(2)),List.of(),.1,0,10000,10000);
  var plan=JSON.createObjectNode();plan.put("schema","athena-continuous-geometry-plan/1");plan.set("stateBinding",node(f.state.binding()));plan.put("coordinateUnit","ANGSTROM");plan.set("coordinateSourceReferences",node(f.state.sources()));plan.putArray("groups");var ops=plan.putArray("operations");
  for(var row:JSON.readTree(Files.readAllBytes(RES.resolve("REFERENCE_ROWS.json"))).path("rows"))if(row.path("residue").asText().equals(id)){var tuple=new ArrayList<JsonNode>();for(var role:row.path("orderedRoles"))for(var a:binding.path("atomCorrespondence"))if(a.path("role").equals(role)&&!a.path("coordinate").isNull())tuple.add(a.get("coordinate"));if(tuple.size()==row.path("orderedRoles").size()){var op=ops.addObject();op.set("id",row.get("rowId"));op.put("kind",row.path("kind").asText().equals("BOND")?"DISTANCE":"ANGLE");op.set("atoms",node(tuple));}}
  plan.putNull("radiusAssignmentReference");plan.set("sourceReferences",node(f.state.sources()));plan.putArray("limitations").add("Synthetic geometry");var pe=f.add("athena:continuous-geometry-plan",plan);var gm=RuleRegistry.decode(f.manifest.parameters().get("geometry").value().getBytes(java.nio.charset.StandardCharsets.UTF_8));var gr=new RuleRequest(f.state.binding(),gm.key(),RuleRegistry.digest(gm),f.request.atoms(),List.of(),List.of(),.1,0,10000,10000);var collector=RuleAnalyzers.collector(gm,gr);var raw=collector.analyze(f.state,List.of(pe),Map.of()).getFirst();f.add("athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method());
 }
 void witness(JsonNode fact)throws Exception {
  var deps=new ArrayList<EvidenceEnvelope>(refs.values());deps.addAll(List.of(f.original,f.protocol,f.coverageEnvelope,f.bindingEnvelope,bindingEnvelope));deps.addAll(f.witnessEnvelopes);
  var v=new TreeMap<String,String>();v.put("proposition",FACT+"/1");v.put("stateBinding",canonical(f.state.binding()));v.put("contextBinding",canonical(pin(f.bindingEnvelope)));v.put("sourceReferenceBinding",canonical(pin(bindingEnvelope)));v.put("factValues",canonical(fact));v.put("sourceProtocol",canonical(pin(f.protocol)));v.put("sourceLocations",canonical(f.locations()));v.put("preparationReferences",canonical(f.binding.get("preparationReferences")));
  var method=ref(ScientificReference.Kind.METHOD,"synthetic-v07-profile");var i=new EvidenceInterpretation(ref(ScientificReference.Kind.EVIDENCE_INTERPRETATION,"v07-profile-"+profileWitnesses.size()),deps.stream().map(e->new EvidenceInterpretation.Input(e.reference(),e.payloadSha256())).toList(),method,Map.of(),List.of(f.state.subject()),SUPPORTED_PRESENT,v,List.of("Synthetic independent profile review"),List.of("Not production"),Optional.empty(),AT);profileWitnesses.add(f.add("athena:event-source",new EvidenceExchange().encodeRecord(i),method));
 }
 void qualify(Path temp,boolean source,boolean profile)throws Exception {
  f.qualify(temp,source);if(!profile)return;var src=new ArrayList<RuleManifest.Source>();var bytes=new TreeMap<String,byte[]>();for(var witness:profileWitnesses){bytes.put(witness.payloadSha256(),witness.readPayload());var w=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(witness.readPayload());for(var dep:w.inputs()){var e=f.inputs.stream().filter(x->x.reference().equals(dep.reference())&&x.payloadSha256().equals(dep.sha256())).findFirst().orElseThrow();bytes.put(e.payloadSha256(),e.readPayload());}}for(var e:bytes.entrySet())src.add(new RuleManifest.Source("sha256:"+e.getKey(),e.getKey(),"Exact synthetic V07 profile review"));
  var m=f.manifest;var sm=new RuleManifest("athena-rule/2",FACT,"1.0.0","SYNTHETIC_TRANS_SOURCE",m.family(),m.tier(),"fixture.trans-source","1",SystemGraphCertificate.Status.NOT_EVALUATED,false,List.of(),m.requiredChemistry(),List.of(),m.measurementsProduced(),m.classificationStates(),m.parameters(),src,List.of(),List.of("Not production authority"),m.negativeCoverage());f.inputs.addAll(ResidueValidationFixtures.qualify(sm,f.state,f.request.atoms(),f.request.first(),temp,"v07-profile",bytes).artifacts());
 }
 SystemGraphAnalyzer.Finding evaluate()throws Exception {var inputs=new ArrayList<>(f.inputs);var collector=RuleAnalyzers.collector(f.manifest,f.request);var raw=collector.analyze(f.state,inputs,Map.of()).getFirst();if(raw.measurements().containsKey("payload"))inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"v07-collected"),"measurement","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),f.state.subject(),AT,List.of("Synthetic only")));return RuleAnalyzers.evaluator(f.manifest,f.request).analyze(f.state,inputs,Map.of()).getFirst();}
}
