package totah.lab.daedalus.system;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.design.backend.MolecularGraph;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.gaia.structure.AtomReference;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.*;

/** All query tolerances and review receipts here are synthetic engineering inputs only. */
class SelectedPharmacophoreAcceptanceTest {
    @TempDir Path temp;
    static final Path MANIFEST=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/selected-pharmacophore-v1/ATHENA.N08.SELECTED_THREE_CARBONYL_TEMPLATE_RMSD.rule.json");
    record Sample(S1NitrogenAcceptanceTest.Fixture source,S1ResearchFixtures.Qualified qualification,ObjectNode template,ObjectNode plan,List<EvidenceEnvelope> inputs) { }
    Sample sample(String variant,double bound)throws Exception {
        var atoms=new ArrayList<MolecularGraph.Atom>();var bonds=new ArrayList<MolecularGraph.Bond>();var h=new TreeMap<String,Integer>();double[][] xyz={{0,0,0},{4,0,0},{0,3,0}};
        if(variant.equals("collinear-source"))xyz[2]=new double[]{8,0,0};if(variant.equals("coincident-source"))xyz[2]=xyz[0];
        for(int i=0;i<3;i++) {var p=xyz[i];atoms.add(atom("o"+i,"O",0,false,p[0],p[1],p[2]));atoms.add(atom("c"+i,"C",0,false,p[0],p[1],p[2]+1.2));bonds.add(bond("c"+i,"o"+i,variant.equals("wrong-role")&&i==2?MolecularGraph.BondOrder.SINGLE:MolecularGraph.BondOrder.DOUBLE));h.put("o"+i,variant.equals("wrong-role")&&i==2?1:0);h.put("c"+i,i==1?0:1);if(variant.equals("wrong-role")&&i==2)h.put("c"+i,2);if(i>0)bonds.add(bond("c"+(i-1),"c"+i,MolecularGraph.BondOrder.SINGLE));}
        var fixtures=new ArrayList<Fixture>();fixtures.add(new Fixture(new MolecularGraph(atoms,bonds,Map.of()),h));if(variant.equals("component-mixing")){fixtures.clear();for(int i=0;i<3;i++)fixtures.add(new Fixture(new MolecularGraph(atoms.subList(2*i,2*i+2),List.of(bond("c"+i,"o"+i,MolecularGraph.BondOrder.DOUBLE)),Map.of()),Map.of("c"+i,2,"o"+i,0)));}
        var f=new S1NitrogenAcceptanceTest.Fixture(Set.of("missing-none","missing-h","missing-scope","unknown-scope","ambiguous","conflict").contains(variant)?variant:"primary",fixtures);
        if(Set.of("missing-charge","missing-aromaticity","incomplete-graph").contains(variant)) {
            var old=f.coverages.getFirst();var c=(ObjectNode)JSON.readTree(old.readPayload());var fact=(ObjectNode)c.path("atomState").path("o0");
            if(variant.equals("missing-charge"))fact.put("chargeStatus","UNKNOWN_INCONCLUSIVE").putNull("formalCharge");
            if(variant.equals("missing-aromaticity"))fact.put("aromaticityStatus","UNKNOWN_INCONCLUSIVE");
            if(variant.equals("incomplete-graph"))c.put("completeGraph","UNKNOWN_INCONCLUSIVE");
            f.inputs.remove(old);var fresh=f.add("athena:group-source-coverage",SystemStateView.bytes(c),old.method());f.coverages.set(0,fresh);f.inputs.removeIf(e->e.evidenceType().equals("athena:event-source"));f.scope(fresh,"COMPLETE_ORDINARY_COVALENT_NO_COORDINATION",false,false);
        }
        f.inputs.removeIf(e->e.evidenceType().equals("athena:group-identities"));f.manifest=RuleRegistry.decode(Files.readAllBytes(MANIFEST));
        var role=RuleRegistry.decode(SystemStateView.bytes(JSON.readTree(f.manifest.parameters().get("sources").value()).path("ATHENA.PERCEPTION.ACCEPTOR.CARBONYL_O")));var collector=RuleAnalyzers.collector(role,B01FunctionalGroupAcceptanceTest.request(f.state,role),BACKEND);
        for(var coverage:f.coverages){var finding=collector.analyze(f.state,List.of(coverage,envelope(f.state,"athena:group-definition",JSON.readTree(role.parameters().get("definition").value()))),Map.of()).getFirst();f.add("athena:group-identities",finding.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method());}
        var map=new TreeMap<String,AtomReference>();for(var c:f.state.components())map.putAll(c.correspondenceAlternatives().getFirst());var tuple=new ArrayList<AtomReference>();for(int i=0;i<3;i++){tuple.add(map.get("o"+i));tuple.add(map.get("c"+i));}if(variant.equals("swapped-anchors"))Collections.swap(tuple,0,1);
        var template=JSON.createObjectNode();template.put("schema","athena-selected-pharmacophore-template/1").put("templateId","synthetic-engineering-query/1").put("coordinateUnit","angstrom").put("maximumRmsdAngstrom",bound);
        var points=template.putArray("points");double[][] target={{0,0,0},{4,0,0},{0,3,0}};if(variant.equals("different-shape"))target[2]=new double[]{0,8,0};if(variant.equals("collinear-query"))target[2]=new double[]{8,0,0};if(variant.equals("coincident-query"))target[2]=target[0];
        for(int i=0;i<3;i++){var p=points.addObject().put("featureId","feature-"+i).put("requiredRole","ATHENA.PERCEPTION.ACCEPTOR.CARBONYL_O");double[] c=target[i];p.putObject("coordinates").put("x",variant.equals("transformed")?10-c[1]:c[0]).put("y",variant.equals("transformed")?20+c[0]:c[1]).put("z",variant.equals("transformed")?30:c[2]);}
        template.set("sourceReferences",JSON.valueToTree(List.of(ref(ScientificReference.Kind.SOURCE,"synthetic-query-source"))));template.set("sourceProtocol",JSON.valueToTree(ref(ScientificReference.Kind.METHOD,"synthetic-query-protocol")));template.putArray("limitations").add("Synthetic query only; no production threshold or authority.");
        var te=envelope(f.state,"athena:selected-pharmacophore-template",template);var mn=(ObjectNode)JSON.valueToTree(f.manifest);if(!variant.equals("unbound"))((ObjectNode)mn.path("parameters").path("templateSha256")).put("value",te.payloadSha256());f.manifest=RuleRegistry.decode(SystemStateView.bytes(mn));
        var q=S1ResearchFixtures.qualify(f.manifest,f.state,tuple,temp.resolve(UUID.randomUUID().toString()),"n08");f.manifest=q.manifest();if(!variant.equals("no-scope-authority"))S1QualifiedProducerTest.qualifyScope(f,temp.resolve(UUID.randomUUID().toString()));
        var plan=ContinuousGeometryAcceptanceTest.plan(f.state);for(int i=0;i<3;i++)ContinuousGeometryAcceptanceTest.op(plan,"DISTANCE",tuple.get(2*i),tuple.get(2*((i+1)%3)));
        var inputs=new ArrayList<>(f.inputs);inputs.add(envelope(f.state,"athena:continuous-geometry-plan",plan));if(!variant.equals("missing-template"))inputs.add(te);return new Sample(f,q,template,plan,inputs);
    }
    SystemGraphAnalyzer.Finding evaluate(Sample s,boolean current)throws Exception {
        var f=s.source();var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(f.manifest,s.qualification().request());var raw=collector.analyze(f.state,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"n08"),"measurement","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),f.state.subject(),T,List.of()));if(current)inputs.addAll(s.qualification().artifacts());return RuleAnalyzers.evaluator(f.manifest,s.qualification().request()).analyze(f.state,inputs,Map.of()).getFirst();
    }
    Sample withTemplate(Sample s,ObjectNode t)throws Exception {var inputs=new ArrayList<>(s.inputs());inputs.removeIf(e->e.evidenceType().equals("athena:selected-pharmacophore-template"));inputs.add(envelope(s.source().state,"athena:selected-pharmacophore-template",t));return new Sample(s.source(),s.qualification(),t,s.plan(),inputs);}
    @ParameterizedTest @ValueSource(strings={"valid","transformed"}) void identicalAndRigidlyTransformedQuery(String variant)throws Exception {var r=evaluate(sample(variant,1e-10),true);assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status(),r.toString());assertEquals("QUERY_TEMPLATE",r.measurements().get("templateGeometryKind"));assertEquals("OBSERVED_SOURCE_COORDINATES",r.measurements().get("sourceGeometryKind"));}
    @Test void eligibleDifferentShapeIsOnlySelectedNegative()throws Exception {var r=evaluate(sample("different-shape",0.1),true);assertEquals(EvidenceInterpretation.Status.ABSENT_FALSE,r.status(),r.toString());assertTrue(Double.parseDouble(r.measurements().get("rmsdAngstrom"))>0.1);}
    @Test void exactComputedBoundaryAndAdjacentBounds()throws Exception {double rmsd=Double.parseDouble(evaluate(sample("different-shape",10),true).measurements().get("rmsdAngstrom"));for(double b:new double[]{Math.nextDown(rmsd),rmsd,Math.nextUp(rmsd)})assertEquals(b<rmsd?EvidenceInterpretation.Status.ABSENT_FALSE:EvidenceInterpretation.Status.SUPPORTED_PRESENT,evaluate(sample("different-shape",b),true).status());}
    @Test void explicitZeroBoundHasNoEpsilon()throws Exception {var r=evaluate(sample("valid",0),true);double rmsd=Double.parseDouble(r.measurements().get("rmsdAngstrom"));assertEquals(rmsd<=0?EvidenceInterpretation.Status.SUPPORTED_PRESENT:EvidenceInterpretation.Status.ABSENT_FALSE,r.status());assertEquals("0.0",r.measurements().get("maximumRmsdAngstrom"));}
    @ParameterizedTest @ValueSource(strings={"missing-bound","negative-bound","string-bound","nonfinite-bound","missing-point","duplicate-id","wrong-query-role","extra-field","empty-source","missing-protocol","nonfinite-point","unversioned-id"}) void malformedQueriesRejected(String variant)throws Exception {var s=sample("valid",0.1);var t=s.template().deepCopy();switch(variant){case "unversioned-id"->t.put("templateId","unversioned");case "missing-bound"->t.remove("maximumRmsdAngstrom");case "negative-bound"->t.put("maximumRmsdAngstrom",-1);case "string-bound"->t.put("maximumRmsdAngstrom","0.1");case "nonfinite-bound"->t.put("maximumRmsdAngstrom",Double.NaN);case "missing-point"->((com.fasterxml.jackson.databind.node.ArrayNode)t.path("points")).remove(2);case "duplicate-id"->((ObjectNode)t.path("points").get(2)).put("featureId","feature-0");case "wrong-query-role"->((ObjectNode)t.path("points").get(2)).put("requiredRole","ANY_ACCEPTOR");case "extra-field"->t.put("inferHydrogen",true);case "empty-source"->t.putArray("sourceReferences");case "missing-protocol"->t.remove("sourceProtocol");case "nonfinite-point"->((ObjectNode)t.path("points").get(0).path("coordinates")).put("x",Double.POSITIVE_INFINITY);}assertThrows(Exception.class,()->evaluate(withTemplate(s,t),true));}
    @ParameterizedTest @ValueSource(strings={"missing-charge","missing-aromaticity","incomplete-graph","missing-none","missing-h","missing-scope","unknown-scope","ambiguous","conflict","collinear-source","coincident-source","collinear-query","coincident-query"}) void unresolvedAndDegenerateCannotBecomeNegative(String variant)throws Exception {var r=evaluate(sample(variant,0.1),true);assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status(),r.toString());assertFalse(r.measurements().containsKey("rmsdAngstrom"));}
    @ParameterizedTest @ValueSource(strings={"wrong-role","swapped-anchors","component-mixing"}) void excludedRolesNotQueryNegatives(String variant)throws Exception {var r=evaluate(sample(variant,0.1),true);assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,r.status(),r.toString());}
    @ParameterizedTest @ValueSource(strings={"unbound","missing-template","no-scope-authority"}) void noDefaultOrBorrowedAuthority(String variant)throws Exception {assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample(variant,0.1),true).status());}
    @Test void noCurrentAuthority()throws Exception {assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample("valid",0.1),false).status());}
    @ParameterizedTest @ValueSource(strings={"bound","query-coordinate","query-protocol","query-source","template-id"}) void exactTemplateBytesCannotBorrowReview(String variant)throws Exception {var s=sample("valid",0.1);var t=s.template().deepCopy();switch(variant){case "bound"->t.put("maximumRmsdAngstrom",100);case "query-coordinate"->((ObjectNode)t.path("points").get(0).path("coordinates")).put("x",50);case "query-protocol"->t.set("sourceProtocol",JSON.valueToTree(ref(ScientificReference.Kind.METHOD,"other")));case "query-source"->t.set("sourceReferences",JSON.valueToTree(List.of(ref(ScientificReference.Kind.SOURCE,"other"))));case "template-id"->t.put("templateId","other/1");}assertThrows(IllegalArgumentException.class,()->evaluate(withTemplate(s,t),true));}
    @Test void duplicatesAndReorderingAreIdempotent()throws Exception {var s=sample("valid",0.1);var r=evaluate(s,true);var inputs=new ArrayList<>(s.inputs());inputs.add(inputs.getFirst());Collections.reverse(inputs);assertEquals(r,evaluate(new Sample(s.source(),s.qualification(),s.template(),s.plan(),inputs),true));}
    @Test void originalSourcesAndDefinitionsCannotBeBroadened()throws Exception {var n=(ObjectNode)JSON.readTree(Files.readAllBytes(MANIFEST));((ObjectNode)n.path("parameters").path("sources")).put("value","{}");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));}
    @Test void noQualificationFlagCanSelfCertify()throws Exception {var n=(ObjectNode)JSON.readTree(Files.readAllBytes(MANIFEST));n.put("qualification","QUALIFIED");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));}
    @ParameterizedTest @ValueSource(strings={"missing-source-feature","duplicate-source","alternate-correspondence"}) void exactSourceCorrespondenceRequired(String variant)throws Exception {
        var s=sample("valid",0.1);var r=s.qualification().request();var atoms=new ArrayList<>(r.atoms());if(variant.equals("missing-source-feature"))atoms.removeLast();if(variant.equals("duplicate-source"))atoms.set(4,atoms.getFirst());if(variant.equals("alternate-correspondence")){Collections.swap(atoms,0,2);Collections.swap(atoms,1,3);}
        var changed=new RuleRequest(r.state(),r.manifestKey(),r.manifestSha256(),atoms,r.first(),r.second(),r.radiusAngstrom(),r.maximumHops(),r.maximumNodes(),r.maximumCandidates());var q=new S1ResearchFixtures.Qualified(s.qualification().manifest(),changed,s.qualification().artifacts());assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),q,s.template(),s.plan(),s.inputs()),true));
    }
    @Test void conflictingSourceFactsCannotBecomeNegative()throws Exception {var s=sample("valid",0.1);var c=(ObjectNode)JSON.readTree(s.source().coverages.getFirst().readPayload());((ObjectNode)c.path("atomState").path("o0")).put("formalCharge",1);var inputs=new ArrayList<>(s.inputs());inputs.add(envelope(s.source().state,"athena:group-source-coverage",c));assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),s.template(),s.plan(),inputs),true).status());}
    @Test void missingRoleEvidenceCannotBecomeNegative()throws Exception {var s=sample("valid",0.1);var inputs=new ArrayList<>(s.inputs());inputs.removeIf(e->e.evidenceType().equals("athena:group-identities"));assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),s.template(),s.plan(),inputs),true).status());}
    @Test void measurementReplayCannotBeRelabeled()throws Exception {var s=sample("valid",0.1);var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(s.source().manifest,s.qualification().request());var raw=(ObjectNode)JSON.readTree(collector.analyze(s.source().state,inputs,Map.of()).getFirst().measurements().get("payload"));((ObjectNode)raw.path("operations").get(0).path("quantities").path("distanceAngstrom")).put("value",99);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"n08"),"measurement","athena:rule-measurements",SystemStateView.bytes(raw),collector.method(),s.source().state.subject(),T,List.of()));inputs.addAll(s.qualification().artifacts());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.evaluator(s.source().manifest,s.qualification().request()).analyze(s.source().state,inputs,Map.of()));}
    @Test void changedBytesUnderSameIdentityAreRejected()throws Exception {var s=sample("valid",0.1);var first=s.inputs().getFirst();var replacement=new EvidenceEnvelope(first.reference(),first.evidenceType(),first.payloadFormat(),first.payloadVersion(),Optional.of(Base64.getEncoder().encodeToString("{}".getBytes())),Optional.empty(),EvidenceExchange.sha256("{}".getBytes()),first.provenance(),first.method(),first.context(),first.subjects(),first.qualifications(),first.limitations(),first.recordedAt());var inputs=new ArrayList<>(s.inputs());inputs.add(replacement);assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),s.template(),s.plan(),inputs),true));}
    @Test void expiredQueryReceiptCannotAuthorize()throws Exception {var s=sample("valid",0.1);var artifacts=new ArrayList<>(s.qualification().artifacts());var e=artifacts.stream().filter(x->x.evidenceType().equals("athena:rule-qualification-receipt")).findFirst().orElseThrow();var r=totah.lab.athena.system.rules.research.ResearchDocuments.decode(e.readPayload(),totah.lab.athena.system.rules.research.RuleQualificationReceipt.class);var expired=new totah.lab.athena.system.rules.research.RuleQualificationReceipt(r.schema(),r.ruleKey(),r.manifestSha256(),r.eligibility(),r.implementationReport(),r.foundationCertificate(),r.stateBinding(),r.request(),r.qualification(),r.mode(),r.evaluatedAt().plusSeconds(60),r.reasons());artifacts.remove(e);artifacts.add(S1ResearchFixtures.envelope(s.source().state,"n08-expired","receipt","athena:rule-qualification-receipt",totah.lab.athena.system.rules.research.ResearchDocuments.encode(expired)));var q=new S1ResearchFixtures.Qualified(s.qualification().manifest(),s.qualification().request(),artifacts);assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(new Sample(s.source(),q,s.template(),s.plan(),s.inputs()),true).status());}
    @ParameterizedTest @ValueSource(strings={"unqualified-frame","changed-state"}) void stateAndFrameCannotBorrowSourceGeometry(String variant)throws Exception {
        var s=sample("valid",0.1);var old=s.source().state;var state=new SystemStateView(variant.equals("changed-state")?ref(ScientificReference.Kind.SUBJECT,"changed-source-state"):old.identity(),old.graph(),old.components(),old.sources(),Set.of(),old.charges(),!variant.equals("unqualified-frame"),true,List.of("changed source binding"));var r=s.qualification().request();var request=new RuleRequest(state.binding(),r.manifestKey(),r.manifestSha256(),r.atoms(),r.first(),r.second(),r.radiusAngstrom(),r.maximumHops(),r.maximumNodes(),r.maximumCandidates());assertThrows(Exception.class,()->RuleAnalyzers.collector(s.source().manifest,request).analyze(state,s.inputs(),Map.of()));
    }
    public static void main(String[] args)throws Exception {var t=new SelectedPharmacophoreAcceptanceTest();t.temp=Files.createDirectories(Path.of(args[0]));Files.write(Path.of(args[1]),SystemStateView.bytes(t.evaluate(t.sample("valid",0.1),true)));}
}
