package totah.lab.daedalus.system;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.JSON;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.canonical;

class SourceFragmentLineageAcceptanceTest {
    @TempDir Path temp;
    static final Path MANIFEST=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/source-fragment-lineage-v1/ATHENA.A08.SOURCE_FRAGMENT_PARENT_LINEAGE.rule.json");
    record Sample(SystemStateView state,S1ResearchFixtures.Qualified qualification,List<EvidenceEnvelope> inputs,EvidenceEnvelope parent) { }
    Sample sample(String variant)throws Exception{
        var old=new SourceFragmentParentAcceptanceTest();old.temp=Files.createDirectories(temp.resolve(UUID.randomUUID().toString()));var base=old.sample(variant);var s=base.source().state;var inputs=new ArrayList<>(base.inputs());inputs.addAll(base.qualification().artifacts());
        var snapshot=S1ResearchFixtures.envelope(s,"a08-lineage-original","snapshot","athena:system-state",SystemStateView.bytes(s.snapshot()));inputs.add(snapshot);var collector=RuleAnalyzers.collector(base.source().manifest,base.qualification().request());var raw=collector.analyze(s,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"a08-lineage-original"),"raw","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),s.subject(),T,List.of()));
        var evaluator=RuleAnalyzers.evaluator(base.source().manifest,base.qualification().request());var found=evaluator.analyze(s,inputs,Map.of()).getFirst();var exchange=new EvidenceExchange();var pins=new ArrayList<EvidenceInterpretation.Input>();for(var e:inputs)pins.add(new EvidenceInterpretation.Input(e.reference(),exchange.contentDigest(e)));
        var interpretation=new EvidenceInterpretation(ref(ScientificReference.Kind.EVIDENCE_INTERPRETATION,"original-fragment-result"),pins,evaluator.method(),Map.of(),found.subjects(),found.status(),found.measurements(),found.reasons(),found.limitations(),Optional.empty(),totah.lab.athena.system.rules.research.ResearchGateAcceptanceTest.AT);
        var parent=SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"a08-lineage-parent"),"interpretation","athena:event-source",exchange.encodeRecord(interpretation),evaluator.method(),s.subject(),T,List.of("Exact synthetic governed selection, not production authority"));inputs.add(parent);
        var q=S1ResearchFixtures.qualify(RuleRegistry.decode(Files.readAllBytes(MANIFEST)),s,List.of(),temp.resolve(UUID.randomUUID().toString()),"a08-lineage");return new Sample(s,q,inputs,parent);
    }
    SystemGraphAnalyzer.Finding evaluate(Sample s,boolean current)throws Exception{var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(s.qualification().manifest(),s.qualification().request());var raw=collector.analyze(s.state(),inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"a08-lineage"),"raw","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),s.state().subject(),T,List.of()));if(current)inputs.addAll(s.qualification().artifacts());String before=canonical(s.state().snapshot());var result=RuleAnalyzers.evaluator(s.qualification().manifest(),s.qualification().request()).analyze(s.state(),inputs,Map.of()).getFirst();assertEquals(before,canonical(s.state().snapshot()));return result;}
    @ParameterizedTest @ValueSource(strings={"valid","reverse","single","charged","inorganic","stereo"}) void exactSourceAndDerivedViewStaySeparate(String variant)throws Exception{var s=sample(variant);var r=evaluate(s,true);assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status(),r.toString());var p=JSON.readTree(r.measurements().get("payload"));assertEquals("DERIVED",p.path("stateKind").asText());assertEquals("FRAGMENT_PARENT",p.path("operation").asText());var c=s.state().components().stream().max(Comparator.comparingInt(x->x.chemistry().atoms().size())).orElseThrow();assertEquals(JSON.valueToTree(c.chemistry()),p.path("resultingGraph"));assertEquals(c.chemistry().atoms().size(),p.path("atomLineage").size());assertEquals(c.chemistry().bonds().size(),p.path("bondLineage").size());assertEquals(s.state().components().size()-1,p.path("excludedSourceComponents").size());assertEquals(s.state().atoms().size()-c.chemistry().atoms().size(),p.path("changes").path("removedFromDerivedView").size());for(var k:List.of("addedAtoms","addedBonds","changedAtoms","changedBonds","changedCoordinates"))assertTrue(p.path("changes").path(k).isEmpty());assertEquals(s.parent().payloadSha256(),p.path("parentInterpretation").path("sha256").asText());assertFalse(r.measurements().containsKey("chemicalEquivalence"));}
    @ParameterizedTest @ValueSource(strings={"tie","missing-charge","missing-aromaticity","incomplete-graph","missing-h","missing-none","missing-scope","unknown-scope","conflict","ambiguous","disconnected"}) void unresolvedParentDoesNotFallBack(String variant)throws Exception{var r=evaluate(sample(variant),true);assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status());assertFalse(r.measurements().containsKey("stateKind"));assertFalse(r.measurements().containsKey("resultingStateSha256"));}
    @ParameterizedTest @ValueSource(strings={"explicit-h","known-connection"}) void originalExcludedDomainIsUnchanged(String variant)throws Exception{assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,evaluate(sample(variant),true).status());}
    @Test void bothAuthoritiesRemainIndependent()throws Exception{assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample("valid"),false).status());assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample("no-scope-authority"),true).status());}
    @Test void missingParentIsUnknown()throws Exception{var s=sample("valid");var inputs=new ArrayList<>(s.inputs());inputs.remove(s.parent());assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.state(),s.qualification(),inputs,s.parent()),true).status());}
    @ParameterizedTest @ValueSource(strings={"sourceStateSha256","resultingStateSha256","parametersSha256","operation","resultingGraph","atomLineage","bondLineage","excludedSourceComponents","changes"}) void alteredPayloadCannotReplay(String field)throws Exception{var s=sample("valid");var p=(ObjectNode)JSON.readTree(evaluate(s,true).measurements().get("payload"));p.put(field,"altered");var inputs=new ArrayList<>(s.inputs());inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"a08-mutated"),"payload","athena:source-fragment-parent-lineage",SystemStateView.bytes(p),RuleAnalyzers.evaluator(s.qualification().manifest(),s.qualification().request()).method(),s.state().subject(),T,List.of()));assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.state(),s.qualification(),inputs,s.parent()),true));}
    @ParameterizedTest @ValueSource(strings={"NORMALIZATION","CHARGE_PARENT","TAUTOMER_PARENT","STEREO_PARENT","ISOTOPE_PARENT","SUPER_PARENT"}) void otherOperationsHaveNoApprovedManifest(String operation)throws Exception{var m=(ObjectNode)JSON.readTree(Files.readAllBytes(MANIFEST));m.put("ruleId","ATHENA.A08."+operation);assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(m)));}
    @Test void exactReplayIsDeterministic()throws Exception{var s=sample("valid");assertEquals(evaluate(s,true),evaluate(s,true));}
    @Test void originalDependencyMissingStaysUnknown()throws Exception{var s=sample("valid");var inputs=new ArrayList<>(s.inputs());inputs.removeIf(e->e.evidenceType().equals("athena:system-state"));assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.state(),s.qualification(),inputs,s.parent()),true).status());}
    @Test void originalEnvelopeMetadataChangeCannotReplay()throws Exception{var s=sample("valid");var inputs=new ArrayList<>(s.inputs());var old=inputs.stream().filter(e->e.evidenceType().equals("athena:system-state")).findFirst().orElseThrow();inputs.remove(old);inputs.add(new EvidenceEnvelope(old.reference(),old.evidenceType(),old.payloadFormat(),old.payloadVersion(),old.payloadBase64(),old.artifactPath(),old.payloadSha256(),old.provenance(),old.method(),old.context(),old.subjects(),old.qualifications(),List.of("changed provenance limitation"),old.recordedAt()));assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.state(),s.qualification(),inputs,s.parent()),true));}
    public static void main(String[] args)throws Exception{var t=new SourceFragmentLineageAcceptanceTest();t.temp=Files.createDirectories(Path.of(args[0]));var out=new TreeMap<String,Object>();for(var v:List.of("valid","charged","stereo","tie","explicit-h")){var r=t.evaluate(t.sample(v),true);out.put(v,Map.of("status",r.status(),"measurements",r.measurements()));}Files.write(Path.of(args[1]),SystemStateView.bytes(out));}
}
