package totah.lab.daedalus.system;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.JSON;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.canonical;
import static totah.lab.daedalus.system.S1NitrogenAcceptanceTest.pin;

class SourceSiteMetadataAcceptanceTest {
    @TempDir Path temp;
    static final Path MANIFEST=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/source-site-metadata-v1/ATHENA.V18.MMCIF_SOURCE_SITE_METADATA.rule.json");
    record Sample(SystemStateView state,S1ResearchFixtures.Qualified qualification,List<EvidenceEnvelope> inputs) { }
    Sample sample(String variant)throws Exception{
        var f=new S1NitrogenAcceptanceTest.Fixture("primary");var state=f.state;var input=new ArrayList<EvidenceEnvelope>();var text=new StringBuilder("data_test\nloop_\n_atom_site.id\n_atom_site.occupancy\n_atom_site.B_iso_or_equiv\n_atom_site.label_alt_id\n_atom_site.pdbx_PDB_model_num\n");var atoms=state.atoms().keySet().stream().sorted().toList();for(int i=0;i<atoms.size();i++)text.append(i).append(" ").append(variant.equals("missing-values")?"? . ? ?":"0.50 20.00 A 1").append('\n');if(variant.equals("unselected-source-row"))text.append("999 . . B 1\n");if(variant.equals("excess-source-rows"))for(int i=0;i<10001;i++)text.append(1000+i).append(" . . B 1\n");
        if(!variant.equals("no-relations"))text.append("_atom_sites_alt.id A\n_atom_sites_alt_ens.id E\nloop_\n_atom_sites_alt_gen.ens_id\n_atom_sites_alt_gen.alt_id\nE ").append(variant.equals("dangling")?"B":"A").append('\n');
        var source=S1ResearchFixtures.envelope(state,"v18-original","cif","athena:source-artifact",text.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));var protocol=S1ResearchFixtures.envelope(state,"v18-protocol","protocol","athena:source-artifact","Synthetic explicit source-row mapping protocol; no production authority".getBytes(java.nio.charset.StandardCharsets.UTF_8));input.add(source);input.add(protocol);
        var p=JSON.createObjectNode();p.put("schema","athena-source-site-metadata-plan/1");p.put("definition","ATHENA.V18.MMCIF_SOURCE_SITE_METADATA/1");p.set("state",JSON.valueToTree(state.binding()));p.set("source",JSON.valueToTree(pin(source)));p.set("sourceProtocol",JSON.valueToTree(pin(protocol)));p.put("blockOrdinal",0);p.put("blockName","test");var map=p.putArray("correspondence");for(int i=0;i<atoms.size();i++){if(variant.equals("missing-mapping")&&i==0)continue;var row=map.addObject();row.put("rowOrdinal",variant.equals("collision")?0:i);row.set("atom",JSON.valueToTree(atoms.get(i)));}if(variant.equals("fractional"))((ObjectNode)map.get(0)).put("rowOrdinal",0.5);if(variant.equals("overflow"))((ObjectNode)map.get(0)).put("rowOrdinal",4294967296L);
        var pe=S1ResearchFixtures.envelope(state,"v18-plan","plan","athena:source-site-metadata-plan",SystemStateView.bytes(p));input.add(pe);var q=S1ResearchFixtures.qualify(RuleRegistry.decode(Files.readAllBytes(MANIFEST)),state,List.of(),temp.resolve(UUID.randomUUID().toString()),"v18");
        if(!variant.equals("no-mapping-authority"))input.addAll(BatchCSourceReviewFixtures.review("ATHENA.V18.MMCIF_SOURCE_SITE_METADATA.SOURCE_MAPPING",q.manifest(),state,List.of(),temp.resolve(UUID.randomUUID().toString()),List.of(pe,protocol)).artifacts());return new Sample(state,q,input);
    }
    SystemGraphAnalyzer.Finding evaluate(Sample s,boolean current,String corruption)throws Exception{
        var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(s.qualification().manifest(),s.qualification().request());var raw=collector.analyze(s.state(),inputs,Map.of()).getFirst();var node=(ObjectNode)JSON.readTree(raw.measurements().get("payload"));if(corruption.equals("span"))((ObjectNode)node.path("atomSiteRows").get(0).path("fields").path("_atom_site.occupancy")).putArray("valueSpan").add(0).add(1);if(corruption.equals("value"))((ObjectNode)node.path("atomSiteRows").get(0).path("fields").path("_atom_site.occupancy")).put("value","1.0");
        if(!corruption.equals("missing-report"))inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"v18"),"raw","athena:source-site-metadata",SystemStateView.bytes(node),collector.method(),s.state().subject(),T,List.of()));if(current)inputs.addAll(s.qualification().artifacts());var before=canonical(s.state().snapshot());var r=RuleAnalyzers.evaluator(s.qualification().manifest(),s.qualification().request()).analyze(s.state(),inputs,Map.of()).getFirst();assertEquals(before,canonical(s.state().snapshot()));return r;
    }
    @Test void explicitSourceMetadataAndMembership()throws Exception{var r=evaluate(sample("valid"),true,"");assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status(),r.toString());assertEquals("COMPLETE_FOR_SELECTED_BLOCK",r.measurements().get("metadataCoverage"));assertEquals("EXPLICIT_MEMBERSHIP_RESOLVED",r.measurements().get("ensembleResolution"));}
    @ParameterizedTest @ValueSource(strings={"missing-values","no-relations","dangling"}) void MetadataCoverageDoesNotCertifyAvailableValuesOrEnsembles(String v)throws Exception{var r=evaluate(sample(v),true,"");assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status());assertEquals("COMPLETE_FOR_SELECTED_BLOCK",r.measurements().get("metadataCoverage"));assertEquals("UNKNOWN",r.measurements().get("ensembleResolution"));assertFalse(r.measurements().containsKey("chemicalCompleteness"));}
    @Test void unselectedSourceRowsAreNotInsertedIntoState()throws Exception{var s=sample("unselected-source-row");var r=evaluate(s,true,"");assertEquals(s.state().atoms().size()+1,JSON.readTree(r.measurements().get("payload")).path("atomSiteRows").size());assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status());}
    @Test void missingMappingIsUnknownNotSourceDefault()throws Exception{assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(sample("missing-mapping"),true,"").status());}
    @ParameterizedTest @ValueSource(strings={"collision","fractional","overflow"}) void invalidOrdinalMappingFailsClosed(String v)throws Exception{assertThrows(IllegalArgumentException.class,()->evaluate(sample(v),true,""));}
    @Test void independentExactMappingAuthorityRequired()throws Exception{assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample("no-mapping-authority"),true,"").status());assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample("valid"),false,"").status());}
    @ParameterizedTest @ValueSource(strings={"span","value"}) void changedReportCannotReplay(String field)throws Exception{assertThrows(IllegalArgumentException.class,()->evaluate(sample("valid"),true,field));}
    @Test void missingReportCannotProveMetadataCoverage()throws Exception{assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(sample("valid"),true,"missing-report").status());}
    @Test void deterministicFocusedReplay()throws Exception{var s=sample("valid");assertEquals(evaluate(s,true,""),evaluate(s,true,""));}
    @ParameterizedTest @ValueSource(strings={"source","protocol"}) void absentOriginalArtifactCannotBeReconstructed(String kind)throws Exception{var s=sample("valid");var input=new ArrayList<>(s.inputs());var plan=input.stream().filter(e->e.evidenceType().equals("athena:source-site-metadata-plan")).findFirst().orElseThrow();var n=JSON.readTree(plan.readPayload());var pin=n.path(kind.equals("source")?"source":"sourceProtocol");input.removeIf(e->JSON.valueToTree(e.reference()).equals(pin.path("reference")));input.addAll(s.qualification().artifacts());var result=RuleAnalyzers.evaluator(s.qualification().manifest(),s.qualification().request()).analyze(s.state(),input,Map.of()).getFirst();assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,result.status());}
    @Test void sourceByteChangeCannotReuseOldPlan()throws Exception{var s=sample("valid");var input=new ArrayList<>(s.inputs());var original=input.stream().filter(e->e.reference().id().equals("v18-original/cif")).findFirst().orElseThrow();var altered=SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"v18-original"),"cif",original.evidenceType(),"data_test\n_atom_site.id changed\n".getBytes(java.nio.charset.StandardCharsets.UTF_8),original.method(),s.state().subject(),T,List.of());input.remove(original);input.add(altered);assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.state(),s.qualification(),input),true,""));}
    @Test void explicitPlanConflictIsUnknown()throws Exception{var s=sample("valid");var input=new ArrayList<>(s.inputs());var plan=input.stream().filter(e->e.evidenceType().equals("athena:source-site-metadata-plan")).findFirst().orElseThrow();input.add(S1ResearchFixtures.envelope(s.state(),"v18-other","plan",plan.evidenceType(),plan.readPayload()));var result=RuleAnalyzers.collector(s.qualification().manifest(),s.qualification().request()).analyze(s.state(),input,Map.of()).getFirst();assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,result.status());}
    @Test void boundedCoverageCannotBecomeCompleteAfterTruncation()throws Exception{var result=evaluate(sample("excess-source-rows"),true,"");assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,result.status());assertEquals("UNKNOWN",result.measurements().get("metadataCoverage"));}

    public static void main(String[] args)throws Exception{var t=new SourceSiteMetadataAcceptanceTest();t.temp=Files.createDirectories(Path.of(args[0]));var out=new TreeMap<String,Object>();for(var v:List.of("valid","missing-values","no-relations","missing-mapping","no-mapping-authority")){var r=t.evaluate(t.sample(v),true,"");out.put(v,Map.of("status",r.status(),"measurements",r.measurements()));}Files.write(Path.of(args[1]),SystemStateView.bytes(out));}
}
