package totah.lab.daedalus.system;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.design.backend.MolecularGraph;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.*;

/** Synthetic source-component policies; selection is never a salt or chemical-validity assertion. */
class SourceFragmentParentAcceptanceTest {
    @TempDir Path temp;
    static final Path MANIFEST=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/source-fragment-parent-v1/ATHENA.A08.UNIQUE_LARGEST_HEAVY_SOURCE_COMPONENT.rule.json");
    record Sample(S1NitrogenAcceptanceTest.Fixture source,S1ResearchFixtures.Qualified qualification,List<EvidenceEnvelope> inputs) { }
    static Fixture carbonChain(int size,String tag,boolean charged,boolean stereo) {
        var atoms=new ArrayList<MolecularGraph.Atom>();var bonds=new ArrayList<MolecularGraph.Bond>();var h=new TreeMap<String,Integer>();
        for(int i=0;i<size;i++){var a=atom("a"+i,charged&&i==size-1?"N":"C",charged&&i==size-1?1:0,false,i,0,0);if(stereo&&i==1)a=new MolecularGraph.Atom(a.id(),a.element(),13,a.formalCharge(),a.explicitHydrogens(),a.aromatic(),"PARITY_1",a.coordinates(),Map.of("source-note","retain opaque source metadata"));atoms.add(a);h.put(a.id(),size==1?4:i==0||i==size-1?3:2);if(i>0)bonds.add(bond("a"+(i-1),a.id(),MolecularGraph.BondOrder.SINGLE));}
        if(stereo){atoms.add(atom("oh","O",0,false,1,1,0));bonds.add(bond("a1","oh",MolecularGraph.BondOrder.SINGLE));h.put("a1",1);h.put("oh",1);}
        return new Fixture(new MolecularGraph(atoms,bonds,Map.of("source-tag",tag)),h);
    }
    Sample sample(String variant)throws Exception {
        var small=carbonChain(2,"small",false,false);var large=carbonChain(variant.equals("stereo")?4:3,"large",variant.equals("charged"),variant.equals("stereo"));
        if(variant.equals("inorganic"))large=new Fixture(new MolecularGraph(List.of(atom("s","S",0,false,0,0,0),atom("o1","O",0,false,1,0,0),atom("o2","O",0,false,-1,0,0)),List.of(bond("s","o1",MolecularGraph.BondOrder.DOUBLE),bond("s","o2",MolecularGraph.BondOrder.DOUBLE)),Map.of("source-tag","inorganic")),Map.of("s",0,"o1",0,"o2",0));
        if(variant.equals("explicit-h")){var atoms=new ArrayList<>(large.graph().atoms());atoms.add(atom("h","H",0,false,0,1,0));var bonds=new ArrayList<>(large.graph().bonds());bonds.add(bond("a0","h",MolecularGraph.BondOrder.SINGLE));var hs=new TreeMap<>(large.hydrogens());hs.put("a0",2);hs.put("h",0);large=new Fixture(new MolecularGraph(atoms,bonds,large.graph().properties()),hs);}
        if(variant.equals("disconnected"))large=new Fixture(new MolecularGraph(large.graph().atoms(),List.of(),large.graph().properties()),large.hydrogens());
        var supplied=variant.equals("single")?List.of(large):variant.equals("reverse")?List.of(large,small):variant.equals("tie")?List.of(small,carbonChain(2,"different-tied",true,false)):List.of(small,large);
        var f=new S1NitrogenAcceptanceTest.Fixture(Set.of("missing-h","missing-none","missing-scope","unknown-scope","conflict","ambiguous","known-connection").contains(variant)?variant:"primary",supplied);f.inputs.removeIf(e->e.evidenceType().equals("athena:group-identities"));
        if(variant.equals("known-connection"))for(var scope:f.inputs.stream().filter(e->e.evidenceType().equals("athena:event-source")).toList()) {
            var i=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(scope.readPayload());var old=f.inputs.stream().filter(e->e.reference().equals(i.inputs().get(2).reference())).findFirst().orElseThrow();var original=(ObjectNode)JSON.readTree(old.readPayload());((ObjectNode)original.path("explicitOriginalConnection")).put("first","component-source-C:a0");f.inputs.remove(old);var fresh=f.add("athena:source-artifact",SystemStateView.bytes(original),old.method());var deps=new ArrayList<>(i.inputs());deps.set(2,new EvidenceInterpretation.Input(fresh.reference(),fresh.payloadSha256()));var next=new EvidenceInterpretation(i.reference(),deps,i.evaluator(),i.configuration(),i.subjects(),i.status(),i.measurements(),List.of("Exact source-dative-17: component-source-C:a0 -> source-Zn:external, source DATIVE; no covalent conversion"),i.limitations(),i.supersedes(),i.recordedAt());f.inputs.remove(scope);f.add("athena:event-source",new EvidenceExchange().encodeRecord(next),next.evaluator());
        }
        if(Set.of("missing-charge","missing-aromaticity","incomplete-graph").contains(variant)) {
            var old=f.coverages.getFirst();var c=(ObjectNode)JSON.readTree(old.readPayload());var fact=(ObjectNode)c.path("atomState").path("a0");if(variant.equals("missing-charge"))fact.put("chargeStatus","UNKNOWN_INCONCLUSIVE").putNull("formalCharge");if(variant.equals("missing-aromaticity"))fact.put("aromaticityStatus","UNKNOWN_INCONCLUSIVE");if(variant.equals("incomplete-graph"))c.put("completeGraph","UNKNOWN_INCONCLUSIVE");
            f.inputs.remove(old);var fresh=f.add("athena:group-source-coverage",SystemStateView.bytes(c),old.method());f.coverages.set(0,fresh);f.inputs.removeIf(e->e.evidenceType().equals("athena:event-source"));for(var coverage:f.coverages)f.scope(coverage,"COMPLETE_ORDINARY_COVALENT_NO_COORDINATION",false,false);
        }
        f.manifest=RuleRegistry.decode(Files.readAllBytes(MANIFEST));var q=S1ResearchFixtures.qualify(f.manifest,f.state,List.of(),temp.resolve(UUID.randomUUID().toString()),"a08");f.manifest=q.manifest();if(!variant.equals("no-scope-authority"))S1QualifiedProducerTest.qualifyScope(f,temp.resolve(UUID.randomUUID().toString()));return new Sample(f,q,new ArrayList<>(f.inputs));
    }
    SystemGraphAnalyzer.Finding evaluate(Sample s,boolean current)throws Exception {
        var f=s.source();byte[] original=SystemStateView.bytes(f.state.snapshot());var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(f.manifest,s.qualification().request());var raw=collector.analyze(f.state,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"a08"),"measurement","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),f.state.subject(),T,List.of()));if(current)inputs.addAll(s.qualification().artifacts());var result=RuleAnalyzers.evaluator(f.manifest,s.qualification().request()).analyze(f.state,inputs,Map.of()).getFirst();assertArrayEquals(original,SystemStateView.bytes(f.state.snapshot()));return result;
    }
    @ParameterizedTest @ValueSource(strings={"valid","reverse","single","charged","inorganic","stereo"}) void uniqueParentPreservesExactGraphAndIdentityLineage(String variant)throws Exception {
        var s=sample(variant);var r=evaluate(s,true);assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status(),r.toString());var expected=s.source().state.components().stream().max(Comparator.comparingInt(c->c.chemistry().atoms().size())).orElseThrow();assertEquals(JSON.valueToTree(expected.chemistry()),JSON.readTree(r.measurements().get("selectedGraph")));assertArrayEquals(SystemStateView.bytes(expected.chemistry()),r.measurements().get("selectedGraph").getBytes(java.nio.charset.StandardCharsets.UTF_8));assertEquals(JSON.valueToTree(expected.correspondenceAlternatives().getFirst()),JSON.readTree(r.measurements().get("atomLineage")));assertEquals(expected.chemistry().bonds().size(),JSON.readTree(r.measurements().get("bondLineage")).size());assertEquals(s.source().state.components().size()-1,JSON.readTree(r.measurements().get("retainedOtherComponents")).size());if(variant.equals("charged"))assertEquals(1,expected.chemistry().atoms().getLast().formalCharge());if(variant.equals("inorganic"))assertEquals("inorganic",expected.chemistry().properties().get("source-tag"));
    }
    @Test void tiedComponentsNeverUseChargeOrStringTieBreak()throws Exception {var r=evaluate(sample("tie"),true);assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status(),r.toString());assertFalse(r.measurements().containsKey("selectedGraph"));assertEquals(2,JSON.readTree(r.measurements().get("maximalComponents")).size());}
    @ParameterizedTest @ValueSource(strings={"explicit-h","known-connection"}) void excludedSourcesAreNotSilentlyProjected(String variant)throws Exception {assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,evaluate(sample(variant),true).status());}
    @ParameterizedTest @ValueSource(strings={"missing-charge","missing-aromaticity","incomplete-graph","missing-h","missing-none","missing-scope","unknown-scope","conflict","ambiguous","disconnected"}) void missingAndConflictingSourceCannotSelectConvenientParent(String variant)throws Exception {var r=evaluate(sample(variant),true);assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status(),r.toString());assertFalse(r.measurements().containsKey("selectedGraph"));}
    @Test void sourceScopeAuthorityIsIndependent()throws Exception {assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(sample("no-scope-authority"),true).status());}
    @Test void noCurrentAuthority()throws Exception {var r=evaluate(sample("valid"),false);assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,r.status());assertTrue(r.measurements().containsKey("sourceComponentInventory"));assertFalse(r.measurements().containsKey("selectedGraph"));}
    @Test void duplicateAndReorderedEvidenceIsIdempotent()throws Exception {var s=sample("valid");var r=evaluate(s,true);var inputs=new ArrayList<>(s.inputs());inputs.add(inputs.getFirst());Collections.reverse(inputs);assertEquals(r,evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void conflictingCoverageCannotRemoveSmallerCandidate()throws Exception {var s=sample("valid");var c=(ObjectNode)JSON.readTree(s.source().coverages.getFirst().readPayload());((ObjectNode)c.path("atomState").path("a0")).put("formalCharge",1);var inputs=new ArrayList<>(s.inputs());inputs.add(envelope(s.source().state,"athena:group-source-coverage",c));assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),inputs),true).status());}
    @Test void noProductionFlagOrAlternativeTiePolicy()throws Exception {var n=(ObjectNode)JSON.readTree(Files.readAllBytes(MANIFEST));n.put("qualification","QUALIFIED");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));n.put("qualification","NOT_EVALUATED");((ObjectNode)n.path("parameters").path("selectionPolicy")).put("value","PREFER_ORGANIC");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));}
    @Test void inheritedSourceIsNotImplicitlyConsumed()throws Exception {var s=sample("valid");assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,evaluate(new Sample(s.source(),s.qualification(),List.of()),true).status());}
    @Test void changedBytesUnderSameIdentityRejected()throws Exception {var s=sample("valid");var first=s.inputs().getFirst();var replacement=new EvidenceEnvelope(first.reference(),first.evidenceType(),first.payloadFormat(),first.payloadVersion(),Optional.of(Base64.getEncoder().encodeToString("{}".getBytes())),Optional.empty(),EvidenceExchange.sha256("{}".getBytes()),first.provenance(),first.method(),first.context(),first.subjects(),first.qualifications(),first.limitations(),first.recordedAt());var inputs=new ArrayList<>(s.inputs());inputs.add(replacement);assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @ParameterizedTest @ValueSource(strings={"omitted-component","overlap","missing-map","duplicate-component-id"}) void entireSourceUniverseMustBeCompleteAndDisjoint(String variant)throws Exception {
        var s=sample("valid");var old=s.source().state;var components=new ArrayList<>(old.components());var c=components.getLast();var map=new TreeMap<>(c.correspondenceAlternatives().getFirst());
        if(variant.equals("omitted-component"))components.removeFirst();else{if(variant.equals("missing-map"))map.remove("a0");if(variant.equals("overlap"))map.put("a0",components.getFirst().correspondenceAlternatives().getFirst().get("a0"));components.set(1,new SystemStateView.Component(variant.equals("duplicate-component-id")?components.getFirst().identity():c.identity(),c.chemistry(),List.of(map),c.limitations()));}
        var state=new SystemStateView(old.identity(),old.graph(),components,old.sources(),Set.of(),old.charges(),true,true,List.of("synthetic invalid candidate universe"));var q=S1ResearchFixtures.qualify(RuleRegistry.decode(Files.readAllBytes(MANIFEST)),state,List.of(),temp.resolve(UUID.randomUUID().toString()),"a08-invalid");var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(q.manifest(),q.request());var raw=collector.analyze(state,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"a08-invalid"),"measurement","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),state.subject(),T,List.of()));inputs.addAll(q.artifacts());var result=RuleAnalyzers.evaluator(q.manifest(),q.request()).analyze(state,inputs,Map.of()).getFirst();assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,result.status(),result.toString());assertFalse(result.measurements().containsKey("selectedGraph"));
    }
    @ParameterizedTest @ValueSource(strings={"dummy","atom-stereo","bond-stereo"}) void unrepresentedSourceFeaturesAreNotSilentlyDiscarded(String variant)throws Exception {
        var s=sample("valid");var old=s.source().state;var components=new ArrayList<>(old.components());var c=components.getFirst();var atoms=new ArrayList<>(c.chemistry().atoms());var bonds=new ArrayList<>(c.chemistry().bonds());var a=atoms.getFirst();
        if(variant.equals("bond-stereo")){var b=bonds.getFirst();bonds.set(0,new MolecularGraph.Bond(b.id(),b.firstAtomId(),b.secondAtomId(),b.order(),b.aromatic(),"UNREPRESENTED_SOURCE_STEREO",b.properties()));}
        else atoms.set(0,new MolecularGraph.Atom(a.id(),variant.equals("dummy")?"*":a.element(),a.isotope(),a.formalCharge(),a.explicitHydrogens(),a.aromatic(),variant.equals("atom-stereo")?"UNREPRESENTED_SOURCE_STEREO":a.stereochemistry(),a.coordinates(),a.properties()));
        components.set(0,new SystemStateView.Component(c.identity(),new MolecularGraph(atoms,bonds,c.chemistry().properties()),c.correspondenceAlternatives(),c.limitations()));var state=new SystemStateView(old.identity(),old.graph(),components,old.sources(),Set.of(),old.charges(),true,true,List.of("synthetic unsupported source representation"));
        var q=S1ResearchFixtures.qualify(RuleRegistry.decode(Files.readAllBytes(MANIFEST)),state,List.of(),temp.resolve(UUID.randomUUID().toString()),"a08-representation");var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(q.manifest(),q.request());var raw=collector.analyze(state,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"a08-representation"),"measurement","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),state.subject(),T,List.of()));inputs.addAll(q.artifacts());var r=RuleAnalyzers.evaluator(q.manifest(),q.request()).analyze(state,inputs,Map.of()).getFirst();assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,r.status(),r.toString());assertFalse(r.measurements().containsKey("selectedGraph"));
    }
    @Test void changedRawSourceSnapshotCannotReplay()throws Exception {var s=sample("valid");var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(s.source().manifest,s.qualification().request());var raw=(ObjectNode)JSON.readTree(collector.analyze(s.source().state,inputs,Map.of()).getFirst().measurements().get("payload"));raw.put("inventedParent",true);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"a08-changed"),"measurement","athena:rule-measurements",SystemStateView.bytes(raw),collector.method(),s.source().state.subject(),T,List.of()));inputs.addAll(s.qualification().artifacts());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.evaluator(s.source().manifest,s.qualification().request()).analyze(s.source().state,inputs,Map.of()));}
    @Test void expiredParentAuthorityCannotSelect()throws Exception {var s=sample("valid");var artifacts=new ArrayList<>(s.qualification().artifacts());var e=artifacts.stream().filter(x->x.evidenceType().equals("athena:rule-qualification-receipt")).findFirst().orElseThrow();var r=totah.lab.athena.system.rules.research.ResearchDocuments.decode(e.readPayload(),totah.lab.athena.system.rules.research.RuleQualificationReceipt.class);var expired=new totah.lab.athena.system.rules.research.RuleQualificationReceipt(r.schema(),r.ruleKey(),r.manifestSha256(),r.eligibility(),r.implementationReport(),r.foundationCertificate(),r.stateBinding(),r.request(),r.qualification(),r.mode(),r.evaluatedAt().plusSeconds(60),r.reasons());artifacts.remove(e);artifacts.add(S1ResearchFixtures.envelope(s.source().state,"a08-expired","receipt","athena:rule-qualification-receipt",totah.lab.athena.system.rules.research.ResearchDocuments.encode(expired)));var q=new S1ResearchFixtures.Qualified(s.qualification().manifest(),s.qualification().request(),artifacts);assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,evaluate(new Sample(s.source(),q,s.inputs()),true).status());}
    public static void main(String[] args)throws Exception {var t=new SourceFragmentParentAcceptanceTest();t.temp=Files.createDirectories(Path.of(args[0]));Files.write(Path.of(args[1]),SystemStateView.bytes(t.evaluate(t.sample("valid"),true)));}
}
