package totah.lab.daedalus.system;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import totah.lab.athena.design.backend.MolecularGraph;
import totah.lab.athena.system.*;
import totah.lab.athena.system.rules.*;
import totah.lab.athena.system.rules.research.*;
import totah.lab.mnemosyne.*;
import java.nio.file.*;
import java.util.*;
import java.util.stream.Stream;
import static org.junit.jupiter.api.Assertions.*;
import static totah.lab.daedalus.system.AthenaScientificRulesAcceptanceTest.*;
import static totah.lab.daedalus.system.B01FunctionalGroupAcceptanceTest.*;

/** Independent synthetic source patterns and engineering authority, never zinc-binding observations. */
class ZnSourceFeatureAcceptanceTest {
    @TempDir Path temp;
    static final Path MANIFEST=Path.of("software/modules/athena/src/main/resources/totah/lab/athena/system/rules/zn-source-features-v1/ATHENA.P07.RDKIT_ZNBINDER_SOURCE_FEATURES_NEUTRAL_HEAVY.rule.json");
    static final Path FIXTURES=Path.of("software/modules/daedalus/src/test/resources/p07-source-features/fixtures.json");
    record Sample(S1NitrogenAcceptanceTest.Fixture source,S1ResearchFixtures.Qualified qualification,List<EvidenceEnvelope> inputs) { }
    static JsonNode row(String name)throws Exception {for(var r:JSON.readTree(Files.readAllBytes(FIXTURES)).path("cases"))if(r.path("id").asText().equals(name))return r;throw new IllegalArgumentException(name);}
    static Fixture chemical(String name,String variant)throws Exception {
        var r=row(name);var atoms=new ArrayList<MolecularGraph.Atom>();var bonds=new ArrayList<MolecularGraph.Bond>();var h=new TreeMap<String,Integer>();
        for(var v:r.path("atoms")){String id=v.path("id").asText();var a=atom(id,v.path("element").asText(),v.path("charge").asInt(),v.path("aromatic").asBoolean(),atoms.size(),0,0);var props=new TreeMap<String,String>();if(!variant.equals("missing-none"))props.put("athena.ocl.atomRadicalState/1",variant.equals("radical")&&atoms.isEmpty()?"D":"NONE");atoms.add(new MolecularGraph.Atom(a.id(),a.element(),a.isotope(),a.formalCharge(),a.explicitHydrogens(),a.aromatic(),a.stereochemistry(),a.coordinates(),props));h.put(id,v.path("hydrogens").asInt());}
        for(var b:r.path("bonds"))bonds.add(bond("a"+b.path("first").asInt(),"a"+b.path("second").asInt(),MolecularGraph.BondOrder.valueOf(b.path("order").asText())));
        if(variant.equals("permuted")){Collections.reverse(atoms);Collections.reverse(bonds);}
        return new Fixture(new MolecularGraph(atoms,bonds,Map.of("fixture",name,"source","synthetic RDKit2026.03.4 reference annotations; not production source")),h);
    }
    Sample sample(String name,String variant)throws Exception {
        var f=new S1NitrogenAcceptanceTest.Fixture(Set.of("missing-none","radical").contains(variant)?"missing-none":variant.equals("ambiguous")?"ambiguous":"primary",List.of(chemical(name,variant)));f.inputs.removeIf(e->Set.of("athena:group-identities","athena:event-source","athena:group-source-coverage").contains(e.evidenceType()));
        var coverage=(ObjectNode)JSON.readTree(f.coverages.getFirst().readPayload());coverage.putArray("limitations").add("Synthetic independent RDKit2026.03.4 H/state annotations; no actual source observation or production authority");
        if(variant.equals("missing-h"))coverage.path("atomState").forEach(v->((ObjectNode)v).put("hydrogenMode","UNKNOWN").putNull("implicitHydrogenCount"));
        if(variant.equals("missing-charge"))((ObjectNode)coverage.path("atomState").path("a0")).put("chargeStatus","UNKNOWN_INCONCLUSIVE").putNull("formalCharge");
        if(variant.equals("missing-aromaticity"))((ObjectNode)coverage.path("atomState").path("a0")).put("aromaticityStatus","UNKNOWN_INCONCLUSIVE");
        if(variant.equals("incomplete-graph"))coverage.put("completeGraph","UNKNOWN_INCONCLUSIVE");
        if(variant.equals("contradictory-h"))((ObjectNode)coverage.path("atomState").path("a0")).put("implicitHydrogenCount",0);
        var ce=f.add("athena:group-source-coverage",SystemStateView.bytes(coverage),ref(ScientificReference.Kind.METHOD,"p07-synthetic-source"));f.coverages.clear();f.coverages.add(ce);
        if(!variant.equals("missing-scope"))f.scope(ce,variant.equals("known-connection")?"KNOWN_NON_ORDINARY_CONNECTION":variant.equals("unknown-scope")?"UNKNOWN":"COMPLETE_ORDINARY_COVALENT_NO_COORDINATION",false,false);if(variant.equals("conflict"))f.scope(ce,"UNKNOWN",false,false);
        f.manifest=RuleRegistry.decode(Files.readAllBytes(MANIFEST));var sources=JSON.readTree(f.manifest.parameters().get("sources").value());
        for(var fields=sources.fields();fields.hasNext();) {var entry=fields.next();if(variant.equals("missing-branch")&&entry.getKey().endsWith("ZNBINDER6_H1"))continue;var m=RuleRegistry.decode(SystemStateView.bytes(entry.getValue()));var collector=RuleAnalyzers.collector(m,request(f.state,m),BACKEND);var result=collector.analyze(f.state,List.of(ce,envelope(f.state,"athena:group-definition",JSON.readTree(m.parameters().get("definition").value()))),Map.of()).getFirst();f.add("athena:group-identities",result.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method());}
        var selected=f.state.components().getFirst().correspondenceAlternatives().getFirst().values().stream().sorted().toList();if(variant.equals("partial-selection"))selected=selected.subList(0,selected.size()-1);
        var q=S1ResearchFixtures.qualify(f.manifest,f.state,selected,temp.resolve(UUID.randomUUID().toString()),"p07");f.manifest=q.manifest();if(!variant.equals("no-scope-authority"))S1QualifiedProducerTest.qualifyScope(f,temp.resolve(UUID.randomUUID().toString()));return new Sample(f,q,new ArrayList<>(f.inputs));
    }
    List<SystemGraphAnalyzer.Finding> evaluate(Sample s,boolean current)throws Exception {
        var f=s.source();var before=SystemStateView.bytes(f.state.snapshot());var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(f.manifest,s.qualification().request());var raw=collector.analyze(f.state,inputs,Map.of()).getFirst();inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"p07"),"measurement","athena:rule-measurements",raw.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),f.state.subject(),T,List.of()));if(current)inputs.addAll(s.qualification().artifacts());var out=RuleAnalyzers.evaluator(f.manifest,s.qualification().request()).analyze(f.state,inputs,Map.of());assertArrayEquals(before,SystemStateView.bytes(f.state.snapshot()));return out;
    }
    @TestFactory Stream<DynamicTest> independentReferencePanel()throws Exception {var names=new ArrayList<String>();JSON.readTree(Files.readAllBytes(FIXTURES)).path("cases").forEach(r->names.add(r.path("id").asText()));return names.stream().map(name->DynamicTest.dynamicTest(name,()->{var expected=row(name);var result=evaluate(sample(name,"valid"),true);assertEquals(6,result.size());for(var r:result){if(!expected.path("admitted").asBoolean())assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,r.status(),name+":"+r);else {int count=expected.path("expectedOriginalFeatureCounts").path(r.measurements().get("originalFeatureName")).asInt();assertEquals(count==0?EvidenceInterpretation.Status.ABSENT_FALSE:EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.status(),name+":"+r);assertEquals(count,JSON.readTree(r.measurements().get("sourceFeatureOccurrences")).size(),name+":"+r.id());assertEquals("true",r.measurements().get("countExhaustive"));}}}));}
    @ParameterizedTest @ValueSource(strings={"missing-h","missing-charge","missing-aromaticity","incomplete-graph","contradictory-h","missing-none","missing-scope","unknown-scope","conflict","ambiguous","partial-selection"}) void unresolvedEvidenceNeverSuppliesFeatureTruth(String variant)throws Exception {for(var r:evaluate(sample("carboxylic_acid",variant),true))assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status(),variant+":"+r);}
    @Test void branchUnionRetainsBothOverlappingWitnesses()throws Exception {var r=evaluate(sample("phosphoryl_C_H1_overlap","valid"),true).stream().filter(x->x.id().equals("ZnBinder6")).findFirst().orElseThrow();var nodes=JSON.readTree(r.measurements().get("sourceFeatureOccurrences"));assertEquals(1,nodes.size());assertEquals(2,nodes.elements().next().path("branches").size());}
    @Test void missingOneOrBranchCannotProveNegative()throws Exception {var r=evaluate(sample("alkane_negative","missing-branch"),true);assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.stream().filter(x->x.id().equals("ZnBinder6")).findFirst().orElseThrow().status());assertEquals(EvidenceInterpretation.Status.ABSENT_FALSE,r.getFirst().status());}
    @Test void distinctOriginalNamesStaySeparate()throws Exception {var r=evaluate(sample("carbonyl_methylene_thiol","valid"),true);assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.get(0).status());assertEquals(EvidenceInterpretation.Status.SUPPORTED_PRESENT,r.get(1).status());assertNotEquals(r.get(0).id(),r.get(1).id());}
    @Test void distinctTargetSetsSharingSulfurAreRetained()throws Exception {var r=evaluate(sample("shared_terminal_sulfur","valid"),true).stream().filter(x->x.id().equals("ZnBinder2")).findFirst().orElseThrow();assertEquals(2,JSON.readTree(r.measurements().get("sourceFeatureOccurrences")).size());}
    @ParameterizedTest @ValueSource(strings={"radical","known-connection"}) void excludedSourceIsNotEligibility(String variant)throws Exception {for(var r:evaluate(sample(variant.equals("known-connection")?"amine":"thiol",variant),true))assertEquals(EvidenceInterpretation.Status.UNSUPPORTED,r.status(),r.toString());}
    @Test void featureAndScopeAuthorityRemainIndependent()throws Exception {for(var r:evaluate(sample("thiol","no-scope-authority"),true))assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,r.status());for(var r:evaluate(sample("thiol","valid"),false))assertEquals(EvidenceInterpretation.Status.NOT_EVALUATED,r.status());}
    @Test void duplicateReorderedInputsAreIdentical()throws Exception {var s=sample("phosphoryl_C_H1_overlap","valid");var inputs=new ArrayList<>(s.inputs());inputs.add(inputs.getFirst());Collections.reverse(inputs);assertEquals(evaluate(s,true),evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void sourceAtomOrderPreservesFeatureMembership()throws Exception {var a=evaluate(sample("shared_terminal_sulfur","valid"),true);var b=evaluate(sample("shared_terminal_sulfur","permuted"),true);for(int i=0;i<6;i++){assertEquals(a.get(i).status(),b.get(i).status());var first=new TreeSet<String>();var second=new TreeSet<String>();JSON.readTree(a.get(i).measurements().get("sourceFeatureOccurrences")).fieldNames().forEachRemaining(first::add);JSON.readTree(b.get(i).measurements().get("sourceFeatureOccurrences")).fieldNames().forEachRemaining(second::add);assertEquals(first,second);}}
    @Test void changedQueryAndSelfQualificationAreRejected()throws Exception {var n=(ObjectNode)JSON.readTree(Files.readAllBytes(MANIFEST));n.put("qualification","QUALIFIED");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));n.put("qualification","NOT_EVALUATED");((ObjectNode)n.path("parameters").path("features")).put("value","{}");assertThrows(java.io.IOException.class,()->RuleRegistry.decode(SystemStateView.bytes(n)));}
    @Test void inheritedSourceIsNotConsumed()throws Exception {var s=sample("thiol","valid");for(var r:evaluate(new Sample(s.source(),s.qualification(),List.of()),true))assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status());}
    @Test void conflictingCoverageRemainsUnknown()throws Exception {var s=sample("thiol","valid");var coverage=(ObjectNode)JSON.readTree(s.source().coverages.getFirst().readPayload());((ObjectNode)coverage.path("atomState").path("a0")).put("formalCharge",1);var inputs=new ArrayList<>(s.inputs());inputs.add(envelope(s.source().state,"athena:group-source-coverage",coverage));for(var r:evaluate(new Sample(s.source(),s.qualification(),inputs),true))assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status());}
    @Test void sameIdentityChangedBytesRejected()throws Exception {var s=sample("thiol","valid");var e=s.inputs().getFirst();var bytes="{}".getBytes(java.nio.charset.StandardCharsets.UTF_8);var changed=new EvidenceEnvelope(e.reference(),e.evidenceType(),e.payloadFormat(),e.payloadVersion(),Optional.of(Base64.getEncoder().encodeToString(bytes)),Optional.empty(),EvidenceExchange.sha256(bytes),e.provenance(),e.method(),e.context(),e.subjects(),e.qualifications(),e.limitations(),e.recordedAt());var inputs=new ArrayList<>(s.inputs());inputs.add(changed);assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void changedBranchWitnessCannotReplay()throws Exception {var s=sample("thiol","valid");var inputs=new ArrayList<>(s.inputs());var e=inputs.stream().filter(x->x.evidenceType().equals("athena:group-identities")).findFirst().orElseThrow();var n=(ObjectNode)JSON.readTree(e.readPayload());((ObjectNode)n.path("definition")).put("query","[*]");inputs.remove(e);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"p07-tamper"),"changed-branch",e.evidenceType(),SystemStateView.bytes(n),e.method(),s.source().state.subject(),T,List.of()));assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),s.qualification(),inputs),true));}
    @Test void changedRawSnapshotCannotReplay()throws Exception {var s=sample("thiol","valid");var inputs=new ArrayList<>(s.inputs());var collector=RuleAnalyzers.collector(s.source().manifest,s.qualification().request());var raw=(ObjectNode)JSON.readTree(collector.analyze(s.source().state,inputs,Map.of()).getFirst().measurements().get("payload"));raw.put("inventedFeature",true);inputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"p07-tamper"),"raw","athena:rule-measurements",SystemStateView.bytes(raw),collector.method(),s.source().state.subject(),T,List.of()));inputs.addAll(s.qualification().artifacts());assertThrows(IllegalArgumentException.class,()->RuleAnalyzers.evaluator(s.source().manifest,s.qualification().request()).analyze(s.source().state,inputs,Map.of()));}
    @Test void enumerationBudgetDoesNotInventExhaustiveCount()throws Exception {
        var s=sample("shared_terminal_sulfur","valid");var old=s.qualification().request();var request=new RuleRequest(old.state(),old.manifestKey(),old.manifestSha256(),old.atoms(),old.first(),old.second(),old.radiusAngstrom(),old.maximumHops(),old.maximumNodes(),1);var artifacts=new ArrayList<>(s.qualification().artifacts());var receiptEnvelope=artifacts.stream().filter(e->e.evidenceType().equals("athena:rule-qualification-receipt")).findFirst().orElseThrow();var receipt=ResearchDocuments.decode(receiptEnvelope.readPayload(),RuleQualificationReceipt.class);var byHash=new HashMap<String,byte[]>();for(var e:artifacts)byHash.put(e.payloadSha256(),e.readPayload());byHash.put(EvidenceExchange.sha256(SystemStateView.bytes(request)),SystemStateView.bytes(request));
        ResearchArtifactReader reader=pin->byHash.get(pin.sha256()).clone();var contextEnvelope=artifacts.stream().filter(e->e.evidenceType().equals("athena:rule-policy-context")).findFirst().orElseThrow();var renewed=RuleQualification.qualify(s.source().manifest,ResearchDocuments.decode(reader.read(receipt.eligibility()),ResearchEligibility.class),ResearchDocuments.decode(reader.read(receipt.implementationReport()),RuleImplementationQualificationV2.class),ResearchDocuments.decode(reader.read(receipt.foundationCertificate()),SystemGraphCertificate.class),s.source().state,request,ResearchDocuments.decode(contextEnvelope.readPayload(),RulePolicyContext.class),reader,receipt.evaluatedAt());
        artifacts.remove(receiptEnvelope);artifacts.add(S1ResearchFixtures.envelope(s.source().state,"p07-budget","request","athena:source-artifact",SystemStateView.bytes(request)));artifacts.add(S1ResearchFixtures.envelope(s.source().state,"p07-budget","receipt","athena:rule-qualification-receipt",ResearchDocuments.encode(renewed)));var q=new S1ResearchFixtures.Qualified(s.source().manifest,request,artifacts);assertThrows(IllegalArgumentException.class,()->evaluate(new Sample(s.source(),q,s.inputs()),true));var limitedInputs=new ArrayList<>(s.inputs());limitedInputs.removeIf(e->e.evidenceType().equals("athena:group-identities"));var sources=JSON.readTree(s.source().manifest.parameters().get("sources").value());for(var entry=sources.fields();entry.hasNext();){var m=RuleRegistry.decode(SystemStateView.bytes(entry.next().getValue()));var sr=new RuleRequest(request.state(),m.key(),RuleRegistry.digest(m),List.of(),List.of(),List.of(),request.radiusAngstrom(),request.maximumHops(),request.maximumNodes(),request.maximumCandidates());var collector=RuleAnalyzers.collector(m,sr,BACKEND);var finding=collector.analyze(s.source().state,List.of(s.source().coverages.getFirst(),envelope(s.source().state,"athena:group-definition",JSON.readTree(m.parameters().get("definition").value()))),Map.of()).getFirst();limitedInputs.add(SystemQualificationPipeline.envelope(ref(ScientificReference.Kind.ACTIVITY,"p07-budget"),m.ruleId(),"athena:group-identities",finding.measurements().get("payload").getBytes(java.nio.charset.StandardCharsets.UTF_8),collector.method(),s.source().state.subject(),T,List.of()));}var r=evaluate(new Sample(s.source(),q,limitedInputs),true).stream().filter(x->x.id().equals("ZnBinder2")).findFirst().orElseThrow();assertEquals(EvidenceInterpretation.Status.UNKNOWN_INCONCLUSIVE,r.status());assertEquals("false",r.measurements().get("countExhaustive"));assertEquals(2,JSON.readTree(r.measurements().get("sourceFeatureOccurrences")).size());
    }
    @Test void symmetricQueryAlternativesInsideOneUnionAreRetained()throws Exception {var r=evaluate(sample("cyclic_phosphoryl_symmetry","valid"),true).stream().filter(x->x.id().equals("ZnBinder6")).findFirst().orElseThrow();var nodes=JSON.readTree(r.measurements().get("sourceFeatureOccurrences"));assertEquals(1,nodes.size());var branches=nodes.elements().next().path("branches");assertEquals(1,branches.size());assertEquals(2,branches.elements().next().path("sourceOccurrence").path("roleCorrespondenceAlternatives").size());}
    public static void main(String[] args)throws Exception {var t=new ZnSourceFeatureAcceptanceTest();t.temp=Files.createDirectories(Path.of(args[0]));Files.write(Path.of(args[1]),SystemStateView.bytes(t.evaluate(t.sample("phosphoryl_C_H1_overlap","valid"),true)));}
}
