package totah.lab.athena.system.rules;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import totah.lab.athena.system.*;
import totah.lab.gaia.structure.*;
import totah.lab.mnemosyne.*;
import java.io.IOException;
import java.util.*;
import static totah.lab.athena.system.rules.EventPayload.*;
import static totah.lab.mnemosyne.EvidenceInterpretation.Status.*;

/** Bounded V08 ordered numerical sign; chemical stereochemistry remains an independent source fact. */
final class OrderedChiralSignRules {
    static final String ID="ATHENA.V08.STV_ORDERED_CHIRAL_SIGN_JAVA21";
    static final String PROFILE="ATHENA.JAVA21.ORDERED_BINARY64_TRIPLE_PRODUCT/1";
    private OrderedChiralSignRules() { }
    record Row(String residue,String id,List<String> tuple,String sign,String file) { }
    static final List<Row> ROWS=List.of(new Row("SER","chir_1",List.of("CA","N","C","CB"),"POSITIVE","s__SER.cif"),new Row("THR","chir_1",List.of("CA","N","C","CB"),"POSITIVE","t__THR.cif"),new Row("THR","chir_2",List.of("CB","OG1","CA","CG2"),"NEGATIVE","t__THR.cif"),new Row("VAL","chir_1",List.of("CA","N","C","CB"),"POSITIVE","v__VAL.cif"));
    static byte[] resource(String name)throws IOException{try(var in=OrderedChiralSignRules.class.getResourceAsStream("/totah/lab/athena/system/rules/ordered-chiral-sign-v1/"+name)){if(in==null)throw new IOException("V08 reference absent "+name);return in.readAllBytes();}}
    static void validate(RuleManifest m){require(Set.of("athena-rule/2","athena-rule/3").contains(m.schema())&&m.ruleId().equals(ID)&&m.version().equals("1.0.0")&&m.profile().equals("ATHENA_ORDERED_CHIRAL_SIGN_V1")&&m.implementationId().equals("athena.ordered-chiral-sign")&&m.implementationVersion().equals("1")&&m.qualification()==SystemGraphCertificate.Status.NOT_EVALUATED&&m.family()==RuleManifest.Family.VALIDATOR&&m.requiredCapabilities().isEmpty(),"Exact V08 manifest");try{var original=JSON.readTree(resource(ID+".rule.json"));for(var k:List.of("parameters","requiredChemistry","requiredGeometry","measurementsProduced","negativeCoverage","scientificSources","limitations"))require(JSON.valueToTree(m).get(k).equals(original.get(k)),"V08 definition changed: "+k);}catch(IOException e){throw new IllegalArgumentException("V08 source unavailable",e);}}
    static ScientificReference method(RuleManifest m,boolean evaluate){return new ScientificReference(ScientificReference.Kind.METHOD,"athena.ordered-chiral-sign",m.key()+(evaluate?"/evaluate":"/collect"),RuleRegistry.digest(m));}
    static SystemGraphAnalyzer analyzer(RuleManifest m,RuleRequest r,boolean evaluate){validate(m);return new SystemGraphAnalyzer(){
        public ScientificReference method(){return OrderedChiralSignRules.method(m,evaluate);}
        public Set<SystemGraphCertificate.Capability> requires(){return Set.of();}
        public Set<SystemGraphCertificate.Capability> qualifies(){return Set.of();}
        public Set<String> evidenceTypes(){return Set.of("athena:residue-context-binding","athena:group-source-coverage","athena:rule-measurements","athena:event-source","athena:source-artifact","athena:rule-manifest","athena:rule-policy-context","athena:rule-qualification-receipt","athena:rule-research-eligibility","athena:rule-implementation-qualification","athena:system-binding","athena:system-certificate","athena:rule-request","athena:system-state");}
        public List<Finding> analyze(SystemStateView state,List<EvidenceEnvelope> supplied,Map<String,String> config)throws Exception {
            require(state.binding().equals(r.state())&&r.manifestKey().equals(m.key())&&r.manifestSha256().equals(RuleRegistry.digest(m))&&r.first().size()==1&&r.second().isEmpty(),"V08 selected source request");var inputs=index(supplied);var bindings=inputs.values().stream().filter(e->e.evidenceType().equals("athena:residue-context-binding")).toList();if(bindings.isEmpty())return List.of(finding(state,NOT_EVALUATED,null,"Missing source context"));require(bindings.size()==1,"One V08 context");var context=bindings.getFirst();var c=ResidueContextSource.check(state,context,inputs);require(ResidueContextSource.residue(c.binding().path("central").path("residue")).equals(r.first().getFirst()),"Central request identity");String identity=c.identity("central");var selected=ROWS.stream().filter(x->x.residue().equals(identity)).toList();var tuples=new ArrayList<List<AtomReference>>();var union=new TreeSet<AtomReference>();
            for(var row:selected){var tuple=new ArrayList<AtomReference>();for(var role:row.tuple()){var a=c.coordinate("central",role);if(a!=null){tuple.add(a);union.add(a);}}require(new HashSet<>(tuple).size()==tuple.size(),"Distinct V08 atoms");tuples.add(tuple.size()==4?List.copyOf(tuple):List.of());}require(r.atoms().equals(List.copyOf(union)),"Exact V08 tuple union");
            var p=JSON.createObjectNode();p.put("schema","athena-ordered-chiral-sign-measurements/1");p.put("definition",ID+"/1");p.put("definitionSha256",RuleRegistry.digest(m));p.set("stateBinding",JSON.valueToTree(state.binding()));p.put("requestSha256",hash(r));p.set("contextBinding",JSON.valueToTree(pin(context)));p.set("centralResidue",c.binding().path("central").path("residue"));p.put("sourceAdmissionStatus",NOT_EVALUATED.name());p.set("sourceFactStatuses",JSON.valueToTree(c.statuses()));p.put("authorityStatus",NOT_EVALUATED.name());var consumed=new TreeMap<String,Object>();for(var e:c.consumed())consumed.put(canonical(pin(e)),pin(e));
            byte[] specBytes=resource("SOURCES.json");require(EvidenceExchange.sha256(specBytes).equals("a15155f05d8482941dead20c80c3ab046e5bd62e9af0018f0097db372284d593"),"V08 source manifest digest");boolean complete=true;var artifacts=new TreeMap<String,Object>();var byFile=new HashMap<String,Object>();
            for(var spec:JSON.readTree(specBytes)){String file=spec.path("file").asText(),sha=spec.path("sha256").asText();require(EvidenceExchange.sha256(resource(file)).equals(sha),"Changed V08 packaged source");var matches=inputs.values().stream().filter(e->e.evidenceType().equals("athena:source-artifact")&&e.payloadSha256().equals(sha)).toList();Object pin;if(matches.isEmpty()){complete=false;pin=Map.of("reference",new ScientificReference(ScientificReference.Kind.EVIDENCE_ENVELOPE,"athena.ordered-sign.required",file,sha),"sha256",sha);}else{pin=pin(matches.getFirst());consumed.put(canonical(pin),pin);}artifacts.put(canonical(pin),pin);byFile.put(file,pin);}
            var profile=p.putObject("referenceProfile");profile.put("repository","MonomerLibrary/monomers");profile.put("commit","1c97ea23a7df06373ed01cd7c3156a1f8e9b27e3");profile.put("numericProfile",PROFILE);profile.set("artifacts",JSON.valueToTree(artifacts.values()));var rows=p.putArray("rows");
            for(int i=0;i<selected.size();i++){var row=selected.get(i);var n=rows.addObject();n.put("rowId",row.residue()+"."+row.id());n.set("atomTuple",JSON.valueToTree(tuples.get(i)));n.put("referenceSign",row.sign());var source=n.putObject("sourceRow");source.set("artifact",JSON.valueToTree(byFile.get(row.file())));source.put("dataBlock","comp_"+row.residue());source.put("category","_chem_comp_chir");source.put("chiralityId",row.id());source.put("center",row.tuple().getFirst());source.set("orderedLigands",JSON.valueToTree(row.tuple().subList(1,4)));source.put("volumeSign",row.sign().toLowerCase(Locale.ROOT));value(n,NOT_EVALUATED,null);n.putArray("reasons");}
            p.put("assessmentStatus",NOT_EVALUATED.name());p.set("sourcePins",JSON.valueToTree(consumed.values()));p.set("reasons",JSON.valueToTree(new TreeSet<>(c.reasons())));p.set("limitations",JSON.valueToTree(m.limitations()));if(!evaluate)return List.of(finding(state,SUPPORTED_PRESENT,p,"Bound ordered source tuples only"));
            var prior=inputs.values().stream().filter(e->e.evidenceType().equals("athena:rule-measurements")&&e.method().equals(OrderedChiralSignRules.method(m,false))).toList();require(prior.size()==1&&canonical(read(prior.getFirst())).equals(canonical(p)),"Exact V08 collected replay");var time=r.maximumNodes()>=union.size()&&r.maximumCandidates()>=selected.size()?S1Qualification.current(m,state,r,inputs):Optional.<java.time.Instant>empty();boolean auth=time.isPresent()&&ResidueContextSource.authorized(c,state,inputs,time.get());var admission=auth?c.status():NOT_EVALUATED;if(admission==SUPPORTED_PRESENT)admission=ResidueValidationRules.rotamerDomain(c,identity);if(admission==SUPPORTED_PRESENT)for(var sr:c.facts().get("identityState").path("residues"))if(sr.path("residue").equals(c.binding().path("central").path("residue")))admission=RestraintDeviationRules.isotopeDomain(sr.path("atoms"));p.put("sourceAdmissionStatus",admission.name());p.put("authorityStatus",auth?SUPPORTED_PRESENT.name():NOT_EVALUATED.name());var base=admission;if(base==SUPPORTED_PRESENT&&!complete)base=UNKNOWN_INCONCLUSIVE;var statuses=new ArrayList<EvidenceInterpretation.Status>();
            for(int i=0;i<selected.size();i++){var n=(ObjectNode)rows.get(i);var status=base;Double v=null;if(status==SUPPORTED_PRESENT){if(tuples.get(i).size()!=4)status=UNKNOWN_INCONCLUSIVE;else{double[][] xyz=new double[4][3];for(int j=0;j<4;j++){var x=state.atoms().get(tuples.get(i).get(j)).getPosition();xyz[j]=new double[]{x.x(),x.y(),x.z()};}v=OrderedChiralSign.volume(xyz);if(v==null||v==0)status=UNKNOWN_INCONCLUSIVE;}}value(n,status,v);if(v!=null&&v!=0)n.put("comparison",OrderedChiralSign.sign(v).equals(selected.get(i).sign())?"MATCHES_REFERENCE_SIGN":"OPPOSES_REFERENCE_SIGN");if(status!=SUPPORTED_PRESENT)((com.fasterxml.jackson.databind.node.ArrayNode)n.get("reasons")).add("Exact source/authority and defined nonzero ordered numerical volume required");statuses.add(status);}
            var status=base==SUPPORTED_PRESENT?(statuses.isEmpty()?UNKNOWN_INCONCLUSIVE:ResidueContextSource.combine(statuses)):base;p.put("assessmentStatus",status.name());for(var e:inputs.values())consumed.put(canonical(pin(e)),pin(e));p.set("sourcePins",JSON.valueToTree(consumed.values()));return List.of(finding(state,status,p,"Ordered numerical sign comparison only; no chemistry reassignment"));
        }
        private Finding finding(SystemStateView s,EvidenceInterpretation.Status status,ObjectNode p,String why){return new Finding(evaluate?"evaluate":"collect",List.of(s.subject()),status,p==null?Map.of():Map.of("payload",canonical(p)),List.of(why),m.limitations());}
    };}
    private static void value(ObjectNode n,EvidenceInterpretation.Status status,Double v){var q=n.putObject("volume");q.put("status",v==null?status.name():SUPPORTED_PRESENT.name());q.put("unit","ANGSTROM_CUBED");if(v==null){q.putNull("value");q.putNull("binary64Hex");n.putNull("numericalSign");}else{q.put("value",v);q.put("binary64Hex",ResidueReferenceTables.bits(v));n.put("numericalSign",OrderedChiralSign.sign(v));}n.putNull("comparison");n.put("assessmentStatus",status.name());}
}
