package totah.lab.athena.system.rules;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import totah.lab.athena.system.*;
import totah.lab.gaia.structure.*;
import totah.lab.mnemosyne.*;
import java.io.IOException;
import java.util.*;
import static totah.lab.athena.system.rules.EventPayload.*;
import static totah.lab.mnemosyne.EvidenceInterpretation.Status.*;

/** Finite V07 restraint comparison. Residuals are not an outlier or energetic classification. */
final class RestraintDeviationRules {
    static final String ID="ATHENA.V07.MONOMER_LIBRARY_STV_INTERNAL_HEAVY_RESTRAINT_DEVIATION";
    private RestraintDeviationRules() { }
    static void validate(RuleManifest m) {
        require(Set.of("athena-rule/2","athena-rule/3").contains(m.schema())&&m.ruleId().equals(ID)&&m.version().equals("1.0.0")&&m.profile().equals("ATHENA_RESTRAINT_DEVIATION_V1")&&m.implementationId().equals("athena.restraint-deviation")&&m.implementationVersion().equals("1")&&m.qualification()==SystemGraphCertificate.Status.NOT_EVALUATED&&m.family()==RuleManifest.Family.VALIDATOR&&m.requiredCapabilities().isEmpty(),"Exact V07 manifest");
        try{var original=JSON.readTree(RestraintSource.resource(ID+".rule.json"));for(var k:List.of("parameters","requiredChemistry","requiredGeometry","measurementsProduced","negativeCoverage","scientificSources","limitations"))require(JSON.valueToTree(m).get(k).equals(original.get(k)),"V07 definition changed: "+k);}catch(IOException e){throw new IllegalArgumentException("V07 definition unavailable",e);}
    }
    static ScientificReference method(RuleManifest m,boolean evaluation){return new ScientificReference(ScientificReference.Kind.METHOD,"athena.restraint-deviation",m.key()+(evaluation?"/evaluate":"/collect"),RuleRegistry.digest(m));}
    static double[] residual(double x,double target,double esd){if(!Double.isFinite(x)||!Double.isFinite(target)||!Double.isFinite(esd)||esd<=0)return null;double delta=x-target;double normalized=delta/esd;return Double.isFinite(delta)&&Double.isFinite(normalized)?new double[]{delta,normalized}:null;}
    static EvidenceInterpretation.Status isotopeDomain(JsonNode atoms){boolean explicit=false;for(var a:atoms){if(a.path("isotopeStatus").asText().equals("UNKNOWN"))return UNKNOWN_INCONCLUSIVE;if(a.path("isotopeStatus").asText().equals("EXPLICIT"))explicit=true;}return explicit?UNSUPPORTED:SUPPORTED_PRESENT;}
    static SystemGraphAnalyzer analyzer(RuleManifest m,RuleRequest r,boolean evaluate) {
        validate(m);return new SystemGraphAnalyzer(){
            public ScientificReference method(){return RestraintDeviationRules.method(m,evaluate);}
            public Set<SystemGraphCertificate.Capability> requires(){return Set.of();}
            public Set<SystemGraphCertificate.Capability> qualifies(){return Set.of();}
            public Set<String> evidenceTypes(){return Set.of("athena:restraint-source-reference-binding","athena:residue-context-binding","athena:group-source-coverage","athena:continuous-geometry-plan","athena:rule-measurements","athena:event-source","athena:source-artifact","athena:rule-manifest","athena:rule-policy-context","athena:rule-qualification-receipt","athena:rule-research-eligibility","athena:rule-implementation-qualification","athena:system-binding","athena:system-certificate","athena:rule-request","athena:system-state");}
            public List<Finding> analyze(SystemStateView state,List<EvidenceEnvelope> supplied,Map<String,String> config)throws Exception {
                require(state.binding().equals(r.state())&&r.manifestKey().equals(m.key())&&r.manifestSha256().equals(RuleRegistry.digest(m))&&r.first().size()==1&&r.second().isEmpty(),"Exact selected central V07 request");
                var inputs=index(supplied);var contexts=ofType(inputs,"athena:residue-context-binding");var bindings=ofType(inputs,"athena:restraint-source-reference-binding");
                if(contexts.isEmpty()||bindings.isEmpty())return List.of(finding(state,NOT_EVALUATED,null,"Exact source/reference binding absent"));require(contexts.size()==1&&bindings.size()==1,"One selected context and reference binding");
                var context=contexts.getFirst();var binding=bindings.getFirst();var c=ResidueContextSource.check(state,context,inputs);var a=RestraintSource.check(state,binding,context,c,inputs);
                require(ResidueContextSource.residue(c.binding().path("central").path("residue")).equals(r.first().getFirst()),"Central request identity");
                var rows=new ArrayList<JsonNode>();String identity=c.identity("central");for(var row:RestraintSource.rows())if(row.path("residue").asText().equals(identity))rows.add(row);
                var tuples=new LinkedHashMap<String,List<AtomReference>>();var sourceTuples=new HashMap<String,List<JsonNode>>();var selected=new TreeSet<AtomReference>();
                for(var row:rows){String id=row.path("rowId").asText();var atoms=new ArrayList<AtomReference>();var sources=new ArrayList<JsonNode>();for(var role:row.path("orderedRoles")){var x=c.coordinate("central",role.asText());if(x!=null){atoms.add(x);selected.add(x);}var source=c.binding().path("central").path("roles").get(role.asText());if(source!=null&&!source.isNull())sources.add(source);}tuples.put(id,atoms.size()==row.path("orderedRoles").size()?List.copyOf(atoms):List.of());sourceTuples.put(id,sources.size()==row.path("orderedRoles").size()?List.copyOf(sources):List.of());}
                if(rows.isEmpty())for(var role:RestraintSource.ROLES){var x=c.coordinate("central",role);if(x!=null)selected.add(x);}
                require(r.atoms().equals(List.copyOf(selected)),"Exact selected heavy-atom union");
                var p=JSON.createObjectNode();p.put("schema","athena-restraint-deviation-measurements/1");p.put("definition",ID+"/1");p.put("definitionSha256",RuleRegistry.digest(m));p.set("stateBinding",JSON.valueToTree(state.binding()));p.put("requestSha256",hash(r));p.set("contextBinding",JSON.valueToTree(pin(context)));p.set("sourceReferenceBinding",JSON.valueToTree(pin(binding)));p.set("centralResidue",c.binding().path("central").path("residue"));p.put("sourceAdmissionStatus",NOT_EVALUATED.name());p.set("sourceFactStatuses",JSON.valueToTree(c.statuses()));p.set("referenceProfile",a.binding().get("referenceProfile"));p.put("referenceStatus",a.referenceStatus().name());
                var app=p.putObject("profileApplicability");app.put("incoming",a.links().get("incoming").name());app.put("outgoing",a.links().get("outgoing").name());app.put("status",a.applicability().name());app.set("witnesses",JSON.valueToTree(a.witnesses().stream().map(EventPayload::pin).sorted(Comparator.comparing(EventPayload::canonical)).toList()));
                var authority=p.putObject("authority");for(var k:List.of("definition","residueSource","profileSource","status"))authority.put(k,NOT_EVALUATED.name());
                var values=geometry(state,m,r,inputs,rows,tuples,p);var ids=rows.stream().map(x->x.path("rowId").asText()).toList();var coverage=p.putObject("rowCoverage");coverage.set("expectedRowIds",JSON.valueToTree(ids));coverage.set("emittedRowIds",JSON.valueToTree(ids));coverage.putArray("evaluatedRowIds");coverage.put("status",rows.isEmpty()?(identity==null?UNKNOWN_INCONCLUSIVE:UNSUPPORTED).name():SUPPORTED_PRESENT.name());
                var results=p.putArray("rows");for(var row:rows){String id=row.path("rowId").asText(),unit=row.path("unit").asText();var n=results.addObject();n.put("rowId",id);n.set("kind",row.get("kind"));n.set("orderedRoles",row.get("orderedRoles"));n.set("sourceAtoms",JSON.valueToTree(sourceTuples.get(id)));n.set("coordinateAtoms",JSON.valueToTree(tuples.get(id)));
                    var ref=n.putObject("reference");ref.set("table",a.binding().path("referenceProfile").get("referenceRows"));ref.put("rowId",id);var chain=ref.putArray("provenanceChain");for(var origin:row.path("provenanceChain")){var copy=origin.deepCopy();String sha=origin.path("artifact").path("sha256").asText();JsonNode rp=null;for(var ap:a.binding().path("referenceProfile").path("sourceArtifacts"))if(ap.path("sha256").asText().equals(sha))rp=ap;require(rp!=null,"Original reference pin inventory");((ObjectNode)copy).set("artifact",rp);chain.add(copy);}
                    ref.set("targetDecimal",row.get("targetDecimal"));ref.set("esdDecimal",row.get("esdDecimal"));quantity(ref,"target",a.referenceStatus(),a.referenceStatus()==SUPPORTED_PRESENT?Double.parseDouble(row.path("targetDecimal").asText()):null,unit);quantity(ref,"esd",a.referenceStatus(),a.referenceStatus()==SUPPORTED_PRESENT?Double.parseDouble(row.path("esdDecimal").asText()):null,unit);
                    if(tuples.get(id).isEmpty()||p.path("geometry").path("plan").isNull())n.putNull("geometryOperationId");else n.put("geometryOperationId",id);Double value=values.get(id);quantity(n,"measurement",value==null?UNKNOWN_INCONCLUSIVE:SUPPORTED_PRESENT,value,unit);quantity(n,"signedResidual",NOT_EVALUATED,null,unit);quantity(n,"restraintNormalizedResidual",NOT_EVALUATED,null,"DIMENSIONLESS");n.put("assessmentStatus",NOT_EVALUATED.name());n.putArray("reasons");}
                p.put("assessmentStatus",NOT_EVALUATED.name());p.set("reasons",JSON.valueToTree(new TreeSet<>(c.reasons())));p.set("limitations",JSON.valueToTree(m.limitations()));collectionPins(p,inputs,c,a,binding);
                if(!evaluate)return List.of(finding(state,SUPPORTED_PRESENT,p,"Raw geometry and reference inventory only; no applicable comparison"));
                var prior=inputs.values().stream().filter(e->e.evidenceType().equals("athena:rule-measurements")&&e.method().equals(RestraintDeviationRules.method(m,false))).toList();require(prior.size()==1,"Exact collected V07 payload required");
                // The collector is not an input of its own payload. Exclude it for exact replay comparison.
                require(canonical(read(prior.getFirst())).equals(canonical(p)),"V07 collected payload replay mismatch");
                boolean budget=r.maximumNodes()>=selected.size()&&r.maximumCandidates()>=rows.size();var at=budget?S1Qualification.current(m,state,r,inputs):Optional.<java.time.Instant>empty();boolean ruleAuth=at.isPresent();boolean sourceAuth=ruleAuth&&ResidueContextSource.authorized(c,state,inputs,at.get());boolean profileAuth=ruleAuth&&RestraintSource.authorized(a,state,inputs,at.get());
                authority.put("definition",ruleAuth?SUPPORTED_PRESENT.name():NOT_EVALUATED.name());authority.put("residueSource",sourceAuth?SUPPORTED_PRESENT.name():NOT_EVALUATED.name());authority.put("profileSource",profileAuth?SUPPORTED_PRESENT.name():NOT_EVALUATED.name());boolean all=ruleAuth&&sourceAuth&&profileAuth;authority.put("status",all?SUPPORTED_PRESENT.name():NOT_EVALUATED.name());
                var admission=c.status();if(admission==SUPPORTED_PRESENT)admission=ResidueValidationRules.rotamerDomain(c,identity);if(admission==SUPPORTED_PRESENT)for(var sr:c.facts().get("identityState").path("residues"))if(sr.path("residue").equals(c.binding().path("central").path("residue")))admission=isotopeDomain(sr.path("atoms"));admission=ResidueContextSource.combine(List.of(admission,a.correspondenceStatus()));p.put("sourceAdmissionStatus",sourceAuth?admission.name():NOT_EVALUATED.name());
                var base=!all?NOT_EVALUATED:ResidueContextSource.combine(List.of(admission,a.applicability()));if(base==SUPPORTED_PRESENT&&a.referenceStatus()!=SUPPORTED_PRESENT)base=UNKNOWN_INCONCLUSIVE;
                var rowStatuses=new ArrayList<EvidenceInterpretation.Status>();for(var node:results){var n=(ObjectNode)node;String id=n.path("rowId").asText(),unit=n.path("measurement").path("unit").asText();var status=base;double[] value=null;
                    if(status==SUPPORTED_PRESENT){if(values.get(id)==null)status=UNKNOWN_INCONCLUSIVE;else{value=residual(values.get(id),Double.parseDouble(n.path("reference").path("targetDecimal").asText()),Double.parseDouble(n.path("reference").path("esdDecimal").asText()));if(value==null)status=UNKNOWN_INCONCLUSIVE;}}
                    quantity(n,"signedResidual",status,value==null?null:value[0],unit);quantity(n,"restraintNormalizedResidual",status,value==null?null:value[1],"DIMENSIONLESS");n.put("assessmentStatus",status.name());if(status==SUPPORTED_PRESENT)((com.fasterxml.jackson.databind.node.ArrayNode)coverage.get("evaluatedRowIds")).add(id);else ((com.fasterxml.jackson.databind.node.ArrayNode)n.get("reasons")).add("Exact admission, applicability, current authority, reference and defined geometry required");rowStatuses.add(status);
                }
                var finalStatus=base==SUPPORTED_PRESENT?(rows.isEmpty()?UNKNOWN_INCONCLUSIVE:ResidueContextSource.combine(rowStatuses)):base;p.put("assessmentStatus",finalStatus.name());if(finalStatus!=SUPPORTED_PRESENT)((com.fasterxml.jackson.databind.node.ArrayNode)p.get("reasons")).add("No statistical classification or substitute authority; incomplete selected comparison");pins(p,inputs);return List.of(finding(state,finalStatus,p,"Continuous selected restraint deviations only"));
            }
            private Finding finding(SystemStateView s,EvidenceInterpretation.Status status,ObjectNode p,String why){return new Finding(evaluate?"evaluate":"collect",List.of(s.subject()),status,p==null?Map.of():Map.of("payload",canonical(p)),List.of(why),m.limitations());}
        };
    }
    private static void collectionPins(ObjectNode p,Map<String,EvidenceEnvelope> inputs,ResidueContextSource.Checked c,RestraintSource.Checked a,EvidenceEnvelope binding)throws Exception {
        var consumed=new TreeMap<String,Object>();for(var e:c.consumed())consumed.put(canonical(pin(e)),pin(e));consumed.put(canonical(pin(binding)),pin(binding));
        for(var e:a.witnesses()){consumed.put(canonical(pin(e)),pin(e));var w=(EvidenceInterpretation)new EvidenceExchange().decodeRecord(e.readPayload());for(var d:w.inputs()){var pp=JSON.valueToTree(Map.of("reference",d.reference(),"sha256",d.sha256()));if(inputs.values().stream().anyMatch(x->canonical(pin(x)).equals(canonical(pp))))consumed.put(canonical(pp),pp);}}
        collectPins(a.binding().get("referenceProfile"),inputs,consumed);collectPins(p.get("geometry"),inputs,consumed);p.set("sourcePins",JSON.valueToTree(consumed.values()));
    }
    private static void collectPins(JsonNode n,Map<String,EvidenceEnvelope> inputs,Map<String,Object> consumed){if(n.isObject()&&n.has("reference")&&n.has("sha256")){if(inputs.values().stream().anyMatch(e->canonical(pin(e)).equals(canonical(n))))consumed.put(canonical(n),n);}else if(n.isContainerNode())for(var child:n)collectPins(child,inputs,consumed);}
    private static List<EvidenceEnvelope> ofType(Map<String,EvidenceEnvelope> inputs,String type){return inputs.values().stream().filter(e->e.evidenceType().equals(type)).toList();}
    private static void pins(ObjectNode p,Map<String,EvidenceEnvelope> inputs){var pins=new TreeMap<String,Object>();for(var e:inputs.values())pins.put(canonical(pin(e)),pin(e));p.set("sourcePins",JSON.valueToTree(pins.values()));}
    private static void quantity(ObjectNode n,String key,EvidenceInterpretation.Status status,Double v,String unit){var q=n.putObject(key);q.put("status",status.name());q.put("unit",unit);if(v==null){q.putNull("value");q.putNull("binary64Hex");}else{q.put("value",v);q.put("binary64Hex",ResidueReferenceTables.bits(v));}}
    private static Map<String,Double> geometry(SystemStateView s,RuleManifest m,RuleRequest r,Map<String,EvidenceEnvelope> inputs,List<JsonNode> rows,Map<String,List<AtomReference>> tuples,ObjectNode p)throws Exception {
        var out=p.putObject("geometry");out.putNull("plan");out.putNull("rawMeasurements");var plans=ofType(inputs,"athena:continuous-geometry-plan");require(plans.size()<=1,"One V07 geometry plan");var values=new HashMap<String,Double>();if(plans.isEmpty())return values;
        var plan=plans.getFirst();var n=read(plan);var complete=rows.stream().filter(x->!tuples.get(x.path("rowId").asText()).isEmpty()).toList();require(n.path("groups").isArray()&&n.path("groups").isEmpty()&&n.path("radiusAssignmentReference").isNull()&&n.path("operations").isArray()&&n.path("operations").size()==complete.size(),"Exact V07 geometry plan");
        for(int i=0;i<complete.size();i++){var row=complete.get(i);var op=n.path("operations").get(i);require(op.path("id").equals(row.get("rowId"))&&op.path("kind").asText().equals(row.path("kind").asText().equals("BOND")?"DISTANCE":"ANGLE")&&op.path("atoms").equals(JSON.valueToTree(tuples.get(row.path("rowId").asText()))),"Exact reference-row geometry tuple/order");}
        var gm=RuleRegistry.decode(SystemStateView.bytes(HbondCandidateRules.parameter(m,"geometry")));var gr=new RuleRequest(s.binding(),gm.key(),RuleRegistry.digest(gm),r.atoms(),List.of(),List.of(),r.radiusAngstrom(),0,r.maximumNodes(),r.maximumCandidates());var collector=RuleAnalyzers.collector(gm,gr);var raw=JSON.readTree(collector.analyze(s,List.of(plan),Map.of()).getFirst().measurements().get("payload"));
        var originals=inputs.values().stream().filter(e->e.evidenceType().equals("athena:rule-measurements")&&e.method().equals(collector.method())).toList();require(originals.size()==1&&canonical(read(originals.getFirst())).equals(canonical(raw)),"Exact raw Athena geometry replay");out.set("plan",JSON.valueToTree(pin(plan)));out.set("rawMeasurements",JSON.valueToTree(pin(originals.getFirst())));
        for(int i=0;i<complete.size();i++){var row=complete.get(i);Double v=HalogenCarbonylRules.value(raw.path("operations"),i,row.path("kind").asText().equals("BOND")?"distanceAngstrom":"angleDegrees");if(v!=null&&Double.isFinite(v))values.put(row.path("rowId").asText(),v);}return values;
    }
}
