import { useApiQuery } from '../../api/hooks'

interface Report { generatedAt: string; sources: Record<string, unknown>[]; evidence: Record<string, unknown>[]; implicatedFeatures: Record<string, unknown>[]; computationalRuns: Record<string, unknown>[]; focusClashSummary: Record<string, unknown>[]; focusClashes: Record<string, unknown>[]; flexibleRnaSummary: Record<string, unknown>[]; rnaSelectivityContrasts: Record<string, unknown>[]; rnaSelectivityResidues: Record<string, unknown>[]; longRnaFragments: Record<string, unknown>[]; longRnaSummary: Record<string, unknown>[]; klf4FinalValidation: Record<string, unknown>[]; reproducibilityArtifacts: Record<string, unknown>[]; unansweredQuestions: string[] }
const text = (value: unknown) => value == null ? '—' : String(value)
const label = (value: unknown) => text(value).replaceAll('_', ' ')
const verdictClass = (value: unknown) => text(value).includes('DIRECT') ? 'direct' : text(value).includes('INDIRECT') ? 'indirect' : 'context'

export function Mettl7EvidenceReportPage() {
  const { data, loading, error } = useApiQuery<Report>('/api/reports/mettl7-rna-activator')
  if (loading) return <article className="dcmb-report"><p>Loading evidence audit…</p></article>
  if (error || !data) return <article className="dcmb-report"><h1>METTL7 evidence audit</h1><p role="alert">{error instanceof Error ? error.message : 'Report unavailable.'}</p></article>
  const residues = data.implicatedFeatures.filter((row) => row.feature_type !== 'RNA_SITE')
  const rnaSites = data.implicatedFeatures.filter((row) => row.feature_type === 'RNA_SITE')
  const focusPositions = [...new Set(data.focusClashSummary.map((row) => Number(row.residue_number)))].sort((a, b) => a - b)
  const clashAt = (enzyme: string, position: number) => data.focusClashSummary.find((row) => row.enzyme === enzyme && Number(row.residue_number) === position)

  return <article className="dcmb-report mettl7-evidence-report">
    <header className="dcmb-report-hero mettl7-hero"><div><p className="dcmb-kicker">Saved primary-evidence audit · live PostgreSQL record</p><h1>METTL7 RNA mechanism</h1><p className="dcmb-lede">What is directly established for METTL7A and METTL7B, where the m7G–m6A conflict remains open, and what netarsudil actually does.</p></div><div className="dcmb-gate-stack"><span className="dcmb-gate mettl7-direct">7A m7G · DIRECT</span><span className="dcmb-gate mettl7-class">7B m6A · SUBSTRATE CLASS</span><span className="dcmb-gate insufficient">Netarsudil activation · UNPROVEN</span></div></header>

    <section className="dcmb-callout"><strong>Hard conclusion</strong><p>Purified METTL7A transfers d3-methyl to defined KLF4 and NFKBIA RNA as internal m7G. Purified METTL7B generates m6A on heterogeneous poly(A) RNA. BMP2 and FILIP1L are strong cellular assignments, but neither is yet a purified, site-defined reaction.</p></section>

    <section className="dcmb-section"><div className="dcmb-section-heading"><p>Evidence ladder</p><h2>Claims separated by experimental strength</h2></div><div className="mettl7-evidence-grid">{data.evidence.map((row) => <article className="mettl7-evidence-card" key={text(row.evidence_key)}><div className="mettl7-card-top"><span>{text(row.enzyme)}</span><span className={`mettl7-verdict ${verdictClass(row.evidence_level)}`}>{label(row.evidence_level)}</span></div><h3>{text(row.modification ?? row.activity)}</h3><p className="mettl7-substrate">{text(row.substrate_rna)}</p><p>{text(row.conclusion)}</p><dl><div><dt>Purified protein</dt><dd>{row.purified_protein === true ? 'YES' : 'NO'}</dd></div><div><dt>Defined substrate</dt><dd>{row.defined_substrate === true ? 'YES' : 'NO'}</dd></div><div className="wide"><dt>Site / motif</dt><dd>{text(row.site_or_motif)}</dd></div></dl></article>)}</div></section>

    <section className="dcmb-section mettl7-contrast"><div className="dcmb-section-heading"><p>Apparent contradiction</p><h2>METTL7A: m7G versus m6A</h2></div><div className="mettl7-contrast-grid"><div><span>Direct chemistry</span><strong>KLF4 / NFKBIA → internal m7G</strong><p>Purified HA-METTL7A, defined transcripts, d3-SAM and LC-MS/MS product detection.</p></div><div><span>Cellular mechanism</span><strong>BMP2 → proposed m6A</strong><p>RIP, MeRIP, perturbation and site-mutant reporters—but no equivalent purified transfer assay.</p></div></div><p className="mettl7-contrast-note">Dual specificity remains possible, not demonstrated. Recruitment of another writer or a required cellular complex remains viable.</p></section>

    <section className="dcmb-section"><div className="dcmb-section-heading"><p>Structure mapping</p><h2>Residues, SAM and paralog differences</h2></div><div className="mettl7-feature-list">{residues.map((row) => <div key={text(row.feature_key)}><span className="mettl7-residue">{text(row.residue_label)}</span><div><strong>{label(row.feature_type)}</strong><p>{text(row.implication)}</p></div><small>Structure {text(row.structure_id)} · pocket {text(row.pocket_id)}</small></div>)}</div><p className="dcmb-footnote">D98, L145 and D200 are conserved and SAM-facing in the retained A/B models. Published netarsudil contacts therefore do not themselves explain B selectivity.</p></section>

    <section className="dcmb-section dcmb-pocket-section mettl7-pocket-section"><div className="dcmb-section-heading"><p>Existing pocket database</p><h2>Mapped context</h2></div><div className="dcmb-pocket-stat"><strong>1,520.177 Å³</strong><span>METTL7A · pocket 32</span></div><div className="dcmb-pocket-stat"><strong>1,687.094 Å³</strong><span>METTL7B · pocket 3</span></div><div className="dcmb-pocket-stat"><strong>{rnaSites.length}</strong><span>RNA constraints mapped</span></div><p>Volumes and identifiers come from existing chosen-pocket records; they are structural context, not biochemical evidence.</p></section>

    <section className="dcmb-section mettl7-computation"><div className="dcmb-section-heading"><p>Persisted computational evidence</p><h2>RNA catalytic feasibility · clash decomposition</h2></div><div className="dcmb-dynamics-grid"><div><strong>12</strong><span>matched A/B probes</span></div><div><strong>554</strong><span>residue rows in PostgreSQL</span></div><div><strong>60</strong><span>flexible refinements</span></div><div><strong>18</strong><span>both catalytic windows retained</span></div></div><p className="dcmb-footnote">Inputs remain local catalytic-feasibility probes—not docking poses or binding models. Severe-clash dimensions are preserved independently from geometry, contacts and HADDOCK terms.</p></section>

    <section className="dcmb-section"><div className="dcmb-section-heading"><p>Reciprocal positions</p><h2>Aggregate severe clashes by residue</h2></div><div className="mettl7-clash-grid">{focusPositions.map((position) => { const a = clashAt('METTL7A', position); const b = clashAt('METTL7B', position); return <article key={position}><span>{position}</span><h3>{text(a?.residue_name)} / {text(b?.residue_name)}</h3><div><strong>{text(a?.severe_atom_pairs ?? 0)}</strong><small>METTL7A</small><strong>{text(b?.severe_atom_pairs ?? 0)}</strong><small>METTL7B</small></div></article> })}</div><p className="dcmb-footnote">Counts are protein–RNA heavy-atom pairs below 1.8 Å summed across six sequence-matched probes. They are steric decompositions, not binding energies.</p></section>

    <section className="dcmb-section"><div className="dcmb-section-heading"><p>HADDOCK3 2026.8.0 pilot</p><h2>Flexible RNA restraint retention</h2></div><div className="mettl7-flex-list">{data.flexibleRnaSummary.map((row) => <div key={`${text(row.enzyme)}-${text(row.site_id)}`}><span>{text(row.enzyme)}</span><strong>{label(row.site_id)}</strong><div><b>{text(row.catalytic_window_models)} / {text(row.refined_models)}</b><small>distance + angle retained</small></div><div><b>{text(row.minimum_severe_clashes)}</b><small>minimum severe clashes</small></div></div>)}</div><p className="dcmb-footnote">HADDOCK scores are retained in the database for run provenance only and are not interpreted as affinity.</p></section>

    <section className="dcmb-section mettl7-contrast"><div className="dcmb-section-heading"><p>Reciprocal-mutation causal pilot</p><h2>Ligand/RNA selectivity coupling</h2></div><div className="dcmb-callout"><strong>Expansion gate: NOT MET</strong><p>No reciprocal mutation produced a reproducible bidirectional A↔B RNA-accommodation shift. Position 199 has a one-sided KLF4 signal in METTL7A, but METTL7B G199F does not reverse it.</p></div><div className="mettl7-flex-list">{data.rnaSelectivityContrasts.map((row) => <div key={`${text(row.enzyme)}-${text(row.mutation)}-${text(row.site_id)}`}><span>{text(row.enzyme)} · {text(row.mutation)}</span><strong>{label(row.site_id)}</strong><div><b>{Number(row.delta_both_windows).toFixed(3)}</b><small>Δ both windows</small></div><div><b>{text(row.conformers_positive)}/{text(row.conformers_negative)}/{text(row.conformers_unchanged)}</b><small>conformer + / − / 0</small></div></div>)}</div><p className="dcmb-footnote">324 retained refinements · 54 paired contrasts · 3 starting RNA conformers. Δ is mutant minus matched WT. Distance, angle, deformation, clashes, contacts, restraint energy and HADDOCK components remain separate in PostgreSQL and the downloadable tables.</p></section>

    <section className="dcmb-section"><div className="dcmb-section-heading"><p>Causal classification</p><h2>What the reciprocal test supports</h2></div><div className="mettl7-contrast-grid"><div><span>Positions 43 and 199</span><strong>LIGAND_ONLY_SELECTIVITY</strong><p>Strong ligand evidence; no reproducible two-way RNA reversal. A F199G→KLF4 is a one-sided substrate-specific RNA signal.</p></div><div><span>Position 232</span><strong>STRUCTURAL_CONTEXT</strong><p>Not RNA-mutated because the primary set failed the expansion gate; current confidence is low.</p></div></div><p className="mettl7-contrast-note">The double swaps are non-additive and substrate/metric-dependent. Neither can be called uniformly synergistic or antagonistic.</p></section>

    <section className="dcmb-section mettl7-contrast"><div className="dcmb-section-heading"><p>Final longer-RNA validation</p><h2>Computational RNA-interface route closed</h2></div><div className="dcmb-callout"><strong>Terminal bilateral gate: NOT MET</strong><p>Three physically screened KLF4 conformers were tested with distributed 40-nt flexibility and soft SAM geometry. The predefined requirement was ≥5 admissible models from ≥3 conformers in both arms. No residues or networks were nominated.</p></div><div className="mettl7-flex-list">{data.klf4FinalValidation.map((row) => <div key={text(row.enzyme)}><span>{text(row.enzyme)}</span><strong>KLF4 final validation</strong><div><b>{text(row.admissible_models)} / {text(row.retained_models)}</b><small>admissible models</small></div><div><b>{text(row.admissible_conformers)} / 3</b><small>conformers represented</small></div></div>)}</div><div className="mettl7-feature-list">{data.longRnaFragments.map((row) => <div key={text(row.rna_key)}><span className="mettl7-residue">{text(row.rna_key)}</span><div><strong>{text(row.target_site)} · {text(row.transcript_accession)}</strong><p>{text(row.sequence)}</p></div><small>{label(row.status)}</small></div>)}</div><p className="dcmb-footnote">METTL7A: 0 admissible models/0 conformers. METTL7B: 1/1. Stop further computational METTL7–RNA docking until new nucleotide mapping, cross-linking, footprinting or interface-mutation evidence constrains the search.</p></section>

    <section className="dcmb-section"><div className="dcmb-section-heading"><p>Reproducibility</p><h2>Reports, scripts and retained data</h2></div><div className="mettl7-artifact-list">{data.reproducibilityArtifacts.map((row) => <a key={text(row.artifact_key)} href={`/api/reports/mettl7-rna-activator/artifacts/${encodeURIComponent(text(row.artifact_key))}`} target="_blank" rel="noreferrer"><span>{label(row.artifact_type)}</span><strong>{text(row.artifact_key)}</strong><p>{text(row.description)}</p><code>{text(row.repository_path)}</code></a>)}</div><p className="dcmb-footnote">All paths resolve inside the Totah Lab repository. Database rows retain the report, protocol classification and exact reproduction entry points.</p></section>

    <section className="dcmb-section dcmb-dynamics mettl7-activator"><div className="dcmb-section-heading"><p>Activator audit</p><h2>Netarsudil evidence chain</h2></div><div className="dcmb-dynamics-grid"><div><strong>−11.494</strong><span>Glide score</span></div><div><strong>9.53 mM</strong><span>reported SPR KD</span></div><div><strong>0.1 µM</strong><span>mRNA induction EC50</span></div><div><strong>0</strong><span>purified activation curves</span></div></div><p>The EC50 measures induction of METTL7B expression, not catalytic activation. Classification: direct SPR binder plus cellular expression inducer plus METTL7B-dependent pharmacology.</p></section>

    <section className="dcmb-section"><div className="dcmb-section-heading"><p>Information gaps</p><h2>Questions that change the mechanism</h2></div><div className="dcmb-answer-list">{data.unansweredQuestions.map((question, index) => <div key={question}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{question}</h3></div></div>)}</div></section>
    <footer className="dcmb-report-footer"><strong>Next action gate</strong><p>Do not launch generic docking. First recover or reproduce the published netarsudil pose and test static compatibility with validated SAM-bound A/B structures. Best wet-lab discriminator: isotope-resolved purified-enzyme reactions on defined RNA sites.</p><small>Generated {new Date(data.generatedAt).toLocaleString()} from {data.sources.length} curated primary sources.</small></footer>
  </article>
}
