rcsb.entry=https://data.rcsb.org/rest/v1/core/entry/
rcsb.search=https://search.rcsb.org/rcsbsearch/v2/query
rcsb.download=https://files.rcsb.org/download/
rcsb.ligand=https://files.rcsb.org/ligands/view/
uniprot.entry=https://rest.uniprot.org/uniprotkb/
uniprot.stream=https://rest.uniprot.org/uniprotkb/stream
alphafold.files=https://alphafold.ebi.ac.uk/files/
biohub.base=https://biohub.ai
