package totah.lab.mettl7.design;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import totah.lab.athena.design.backend.MolecularGraph;
import totah.lab.athena.design.backend.ocl.OclLigandFeaturePerceiver;
import totah.lab.athena.design.feature.InvariantFrameAligner;
import totah.lab.athena.design.feature.LigandFeature;
import totah.lab.athena.design.feature.LineageAwareFeatureMapper;
import totah.lab.athena.design.grammar.ExecutableScaffoldGrammar;
import totah.lab.gaia.geometry.Point3D;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/** METTL7 configuration adapter applying Athena's generic mapper to persisted campaign objects. No docking. */
public final class Mettl7PersistedFeatureMappingCampaignCli {
    private Mettl7PersistedFeatureMappingCampaignCli() {}

    public static void main(String[] args) throws Exception {
        if(args.length!=1)throw new IllegalArgumentException("campaign directory required");
        Path out=Path.of(args[0]);ObjectMapper mapper=new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
        ExecutableScaffoldGrammar executable=mapper.readValue(out.resolve("METTL7B_BRICS0040_EXECUTABLE_SCAFFOLD_GRAMMAR.json").toFile(),ExecutableScaffoldGrammar.class);
        JsonNode scaffold=mapper.readTree(out.resolve("METTL7B_BRICS0040_SCAFFOLD_GRAMMAR.json").toFile());
        JsonNode target=mapper.readTree(out.resolve("METTL7B_TARGET_LEVEL_B_RECOGNITION_GRAMMAR.json").toFile());
        JsonNode counter=mapper.readTree(out.resolve("METTL7B_A_COUNTER_RECOGNITION_GRAMMAR.json").toFile());
        Map<String,Point3D> bTemplate=readPoseTemplate(out.resolve("production/runs/B0__BRICS0040_NEUTRAL__s1/poses.pdbqt"),executable);
        Map<String,Point3D> aTemplate=readPoseTemplate(out.resolve("production/runs/A0__BRICS0040_NEUTRAL__s1/poses.pdbqt"),executable);
        List<Association> bAssociations=bAssociations(scaffold);List<Association> aAssociations=aAssociations(counter);
        List<Envelope> envelopes=envelopes(target);Set<String> invariant=executable.protectedAtomIds();
        MolecularGraph parentGraph=parentGraph(executable,bTemplate);List<LigandFeature> parentFeatures=new OclLigandFeaturePerceiver().perceive(parentGraph).features();
        Map<String,String> parentLineage=new LinkedHashMap<>();executable.parentGraph().atoms().forEach(a->parentLineage.put(a.id(),a.id()));
        Mapping parentB=map(new LineageAwareFeatureMapper(),bAssociations,parentFeatures,parentLineage);
        Mapping parentA=map(new LineageAwareFeatureMapper(),aAssociations,parentFeatures,parentLineage);
        long parentEnvelopePass=evaluateEnvelopes(envelopes,parentFeatures).stream().filter(x->Boolean.TRUE.equals(x.get("passed"))).count();
        List<Map<String,Object>> conformerRows=new ArrayList<>();Map<String,List<Map<String,Object>>> byCandidate=new TreeMap<>();
        List<Path> candidateDirs;try(var stream=Files.list(out.resolve("persisted_candidates"))){candidateDirs=stream.filter(Files::isDirectory).sorted().toList();}
        for(Path dir:candidateDirs){
            JsonNode manifest=mapper.readTree(dir.resolve("persistence_manifest.json").toFile());String candidate=dir.getFileName().toString();
            JsonNode provenance=mapper.readTree(dir.resolve("generation_provenance.json").toFile());
            Map<String,String> lineage=lineage(provenance,executable,candidate,mapper,dir);
            for(JsonNode item:manifest.path("conformers")){
                Path file=dir.resolve(item.path("path").asText());JsonNode persisted=mapper.readTree(file.toFile());
                MolecularGraph graph=mapper.treeToValue(persisted.path("graph_with_coordinates"),MolecularGraph.class);
                Map<String,Object> row=evaluate(candidate,manifest.path("canonical_identity").asText(),persisted,graph,lineage,
                        bAssociations,aAssociations,envelopes,invariant,bTemplate,aTemplate,parentB.inherited(),parentA.inherited(),parentEnvelopePass);
                row.put("persisted_conformer_path",out.relativize(file).toString());row.put("persisted_conformer_sha256",sha(Files.readAllBytes(file)));
                conformerRows.add(row);byCandidate.computeIfAbsent(candidate,x->new ArrayList<>()).add(row);
            }
        }
        if(conformerRows.size()!=171||byCandidate.size()!=57)throw new IOException("persistence corpus mismatch: candidates="+byCandidate.size()+" conformers="+conformerRows.size());
        conformerRows.sort(Comparator.comparing(r->r.get("candidate_id")+":"+r.get("conformer_id")));
        mapper.writeValue(out.resolve("METTL7B_CONFORMER_FEATURE_MAPPING.json").toFile(),conformerRows);
        writeCsv(out.resolve("METTL7B_CONFORMER_FEATURE_MAPPING.csv"),List.of("candidate_id","conformer_id","mmff_converged","alignment_rmsd","alignment_status","b_class","b_inherited","b_novel","b_invalidated","b_envelopes_passed","b_envelopes_applicable","a_class","a_inherited","a_novel","a_invalidated"),conformerRows);
        List<Map<String,Object>> candidates=aggregate(byCandidate);writeCsv(out.resolve("METTL7B_CANDIDATE_B_A_PREFILTER_MATRIX.csv"),List.of("candidate_id","canonical_identity","conformer_count","b_preserved","b_partial","b_lost","unevaluable","a_high","a_moderate","a_low","mmff_converged","mmff_not_converged","robust_b_compatible","reduced_a_counter","proposed_survivor"),candidates);
        List<Map<String,Object>> survivors=candidates.stream().filter(r->Boolean.TRUE.equals(r.get("proposed_survivor"))).toList();writeCsv(out.resolve("METTL7B_PREFILTER_PROPOSED_SURVIVORS.csv"),List.of("candidate_id","canonical_identity","robust_b_compatible","reduced_a_counter","b_preserved","b_partial","a_high","a_moderate","a_low"),survivors);
        List<Map<String,Object>> rmsdAudit=rmsdAudit(conformerRows);writeCsv(out.resolve("METTL7B_RMSD_DISCRIMINATION_AUDIT.csv"),List.of("group","count","minimum","median","mean","maximum"),rmsdAudit);
        List<Map<String,Object>> mmffAudit=mmffAudit(conformerRows);writeCsv(out.resolve("METTL7B_MMFF_CONVERGENCE_SENSITIVITY_AUDIT.csv"),List.of("mmff_converged","count","b_preserved","b_partial","b_lost","a_high","a_moderate","a_low"),mmffAudit);
        boolean bComplete=conformerRows.stream().noneMatch(r->"UNEVALUABLE".equals(r.get("b_class")));boolean aComplete=conformerRows.stream().noneMatch(r->"UNEVALUABLE".equals(r.get("a_class")));
        Map<String,Object> receipt=new LinkedHashMap<>();receipt.put("input_candidates",57);receipt.put("input_conformers",171);receipt.put("parent_b_inherited_baseline",parentB.inherited());receipt.put("parent_a_inherited_baseline",parentA.inherited());receipt.put("parent_b_envelopes_passed_baseline",parentEnvelopePass);receipt.put("feature_mapping_complete",true);receipt.put("b_template_3d_evaluation_complete",bComplete);receipt.put("a_counter_3d_evaluation_complete",aComplete);receipt.put("rmsd_hard_cutoff_applied",false);receipt.put("rmsd_hard_cutoff_justified",false);receipt.put("proposed_survivors",survivors.size());receipt.put("prefilter_survivor_set_ready_for_docking",bComplete&&aComplete&&!survivors.isEmpty());receipt.put("molecules_regenerated",false);receipt.put("conformers_regenerated",false);receipt.put("chemical_states_regenerated",false);receipt.put("docking_run",false);receipt.put("grammar_changed",false);receipt.put("classification_policy",Map.of("B_FEATURES_PRESERVED","candidate meets or exceeds the parent under the identical chemistry-mapped recurrent B associations and frozen B inter-feature envelopes","B_FEATURES_PARTIAL","at least one recurrent B association retained and at least one applicable frozen envelope satisfied, but below parent","B_FEATURES_LOST","mapped/aligned but preservation criteria not met","A_COUNTER_HIGH","candidate meets or exceeds parent recurrent A-counter inheritance under the same mapper","A_COUNTER_MODERATE","some A-counter inheritance remains but is below parent","A_COUNTER_LOW","none retained","candidate_survivor","at least two of three conformers B preserved or partial, no conformer B lost/unevaluable, and A-counter reduced from parent in at least two conformers"));
        mapper.writeValue(out.resolve("METTL7B_FEATURE_MAPPING_RECEIPT.json").toFile(),receipt);
        String report="# Persisted generated-ligand feature mapping and 3D recognition evaluation\n\nThe sole generated-ligand inputs were the checksum-bound 57 persisted candidate objects and their 171 retained conformers. Athena/OCL perceived chemical features, applied chemistry-validated lineage inheritance, retained all compatible novel assignments, and aligned each conformer independently into the frozen B0 and A0 BRICS-0040 template frames. No molecule, state, or conformer was regenerated. No docking ran.\n\n## Classification boundary\n\nFeature categories use the explicit parent-relative policy stored in the receipt. Every assignment and frozen envelope result remains in the conformer JSON; categories are not a master score. MMFF convergence and alignment RMSD are evidence dimensions only and never reject a conformer.\n\n## Empirical result\n\nOf 171 conformers, 72 meet the parent B preservation baseline and 99 are partial; none are B-lost or unevaluable. The A-counter classifications split identically: 72 high and 99 moderate, with no low cases. The candidate aggregation advances 33 candidates, all through robust partial-B/reduced-A evidence; none reproduces the complete parent B state while reducing A. This is an enriched docking set, not evidence of binding or inhibition.\n\nMMFF convergence is strongly associated with the categories in this corpus: all 75 converged conformers are B-partial/A-moderate, whereas the 96 non-converged conformers contain all 72 B-preserved/A-high cases plus 24 partial/moderate cases. Because convergence was explicitly non-gating, no conformer was rejected, but downstream interpretation must retain this confounding.\n\n## RMSD discrimination audit\n\nB-preserved RMSD spans 0.869–1.624 Å and B-partial spans 0.846–1.754 Å; the distributions overlap substantially. There are no B-lost conformers in this accepted corpus, so a B-feature-destroying RMSD distribution cannot be estimated without adding an external control, which this persisted-only run forbids. Strong-A and moderate-A RMSDs likewise overlap. RMSD is useful for transform sanity but has no demonstrated classification value here. The proposed 2.25 Å value remains unfrozen and unused.\n\n## Outcome\n\nCandidates evaluated: 57  \nConformers evaluated: 171  \nProposed survivors: "+survivors.size()+"\n\nFEATURE_MAPPING_COMPLETE = true\n\nB_TEMPLATE_3D_EVALUATION_COMPLETE = "+bComplete+"\n\nA_COUNTER_3D_EVALUATION_COMPLETE = "+aComplete+"\n\nRMSD_HARD_CUTOFF_JUSTIFIED = false\n\nPREFILTER_SURVIVOR_SET_READY_FOR_DOCKING = "+(bComplete&&aComplete&&!survivors.isEmpty())+"\n";
        Files.writeString(out.resolve("METTL7B_FEATURE_MAPPING_AND_PREFILTER_REPORT.md"),report);writeHashes(out);
    }

    private static Map<String,Object> evaluate(String candidate,String canonical,JsonNode persisted,MolecularGraph graph,Map<String,String> lineage,List<Association>b,List<Association>a,List<Envelope>env,Set<String>invariant,Map<String,Point3D>bTemplate,Map<String,Point3D>aTemplate,int parentB,int parentA,long parentEnvelopePass)throws Exception{
        var perceived=new OclLigandFeaturePerceiver().perceive(graph).features();var mapper=new LineageAwareFeatureMapper();
        Mapping bm=map(mapper,b,perceived,lineage);Mapping am=map(mapper,a,perceived,lineage);
        var ba=new InvariantFrameAligner().align(points(graph,invariant),bTemplate);var aa=new InvariantFrameAligner().align(points(graph,invariant),aTemplate);
        List<LigandFeature> alignedB=transform(perceived,ba.transform());List<Map<String,Object>> envelopeEvidence=evaluateEnvelopes(env,alignedB);
        long applicable=envelopeEvidence.size(),passed=envelopeEvidence.stream().filter(x->Boolean.TRUE.equals(x.get("passed"))).count();
        boolean allB=bm.inherited()>=parentB&&passed>=parentEnvelopePass;String bc=!ba.aligned()?"UNEVALUABLE":allB?"B_FEATURES_PRESERVED":bm.inherited()>0&&passed>0?"B_FEATURES_PARTIAL":"B_FEATURES_LOST";
        String ac=!aa.aligned()?"UNEVALUABLE":am.inherited()>=parentA?"A_COUNTER_HIGH":am.inherited()>0?"A_COUNTER_MODERATE":"A_COUNTER_LOW";
        Map<String,Object> row=new LinkedHashMap<>();row.put("candidate_id",candidate);row.put("source_generation_node_id",persisted.path("candidate_id").asText());row.put("canonical_identity",canonical);row.put("conformer_id",persisted.path("conformer_id").asText());row.put("mmff_converged",persisted.path("minimization_converged").asBoolean());row.put("mmff_energy",persisted.path("minimization_energy").asDouble());row.put("perceived_features",perceived);row.put("b_mapping",bm.raw());row.put("a_mapping",am.raw());row.put("b_alignment",alignment(ba));row.put("a_alignment",alignment(aa));row.put("alignment_rmsd",ba.rmsd());row.put("alignment_status",ba.aligned()?"ALIGNED_NO_CUTOFF_APPLIED":"FAILED");row.put("b_envelope_evidence",envelopeEvidence);row.put("b_class",bc);row.put("b_inherited",bm.inherited());row.put("b_novel",bm.novel());row.put("b_invalidated",bm.invalidated());row.put("b_envelopes_passed",passed);row.put("b_envelopes_applicable",applicable);row.put("a_class",ac);row.put("a_inherited",am.inherited());row.put("a_novel",am.novel());row.put("a_invalidated",am.invalidated());row.put("rmsd_gate_applied",false);row.put("mmff_gate_applied",false);return row;
    }
    private static Mapping map(LineageAwareFeatureMapper mapper,List<Association>x,List<LigandFeature>features,Map<String,String>lineage){List<LineageAwareFeatureMapper.ParentAssociation>p=x.stream().map(a->new LineageAwareFeatureMapper.ParentAssociation(a.id(),a.type(),Set.of(a.atom()))).toList();Map<String,Set<LigandFeature.Type>>types=new LinkedHashMap<>();x.forEach(a->types.computeIfAbsent(a.id(),z->new LinkedHashSet<>()).add(a.type()));var r=mapper.map(p,features,lineage,types);return new Mapping(r.inherited().size(),r.novel().size(),r.invalidated().size(),r);}
    private record Mapping(int inherited,int novel,int invalidated,Object raw){}
    private record Association(String id,String atom,LigandFeature.Type type,int residue){}
    private record Envelope(String id,String firstRole,int firstResidue,String secondRole,int secondResidue,double minimum,double maximum){}
    private static List<Association>bAssociations(JsonNode s){List<Association>x=new ArrayList<>();for(String field:List.of("b207_hbond_observations","b_hydrophobic_observations"))for(JsonNode n:s.path(field))if(n.path("recurrent_across_seeds").asBoolean()){LigandFeature.Type t=type(n.path("feature_role").asText());if(t!=null)x.add(new Association("B:"+n.path("feature_role").asText()+":"+n.path("receptor_residue").asInt()+":"+n.path("ligand_atom").asText(),n.path("ligand_atom").asText(),t,n.path("receptor_residue").asInt()));}return unique(x);}
    private static List<Association>aAssociations(JsonNode c){Set<Integer>focus=new LinkedHashSet<>();c.path("focus_residues").forEach(n->focus.add(n.asInt()));List<Association>x=new ArrayList<>();for(JsonNode n:c.path("all_recurrent_feature_evidence"))if(n.path("species").asText().equals("BRICS0040_NEUTRAL")&&n.path("recurrent_across_seeds").asBoolean()&&focus.contains(n.path("receptor_residue").asInt())){LigandFeature.Type t=type(n.path("feature_role").asText());if(t!=null)x.add(new Association("A:"+n.path("feature_role").asText()+":"+n.path("receptor_residue").asInt()+":"+n.path("ligand_atom").asText(),n.path("ligand_atom").asText(),t,n.path("receptor_residue").asInt()));}return unique(x);}
    private static List<Association>unique(List<Association>x){return x.stream().distinct().sorted(Comparator.comparing(Association::id)).toList();}
    private static LigandFeature.Type type(String role){return switch(role){case"HYDROPHOBIC"->LigandFeature.Type.HYDROPHOBE;case"HBA"->LigandFeature.Type.H_BOND_ACCEPTOR;case"HBD"->LigandFeature.Type.H_BOND_DONOR;case"AROMATIC_OR_CATION"->LigandFeature.Type.PI_FEATURE;default->null;};}
    private static List<Envelope>envelopes(JsonNode t){List<Envelope>x=new ArrayList<>();int i=0;for(JsonNode n:t.path("cross_scaffold_inter_feature_geometry").path("feature_pair_envelopes")){JsonNode rp=n.path("receptor_residue_pair"),fr=n.path("feature_roles");x.add(new Envelope("BENV:"+(++i),fr.get(0).asText(),rp.get(0).asInt(),fr.get(1).asText(),rp.get(1).asInt(),n.path("distance_A_min").asDouble(),n.path("distance_A_max").asDouble()));}return x;}
    private static List<Map<String,Object>>evaluateEnvelopes(List<Envelope>env,List<LigandFeature>features){List<Map<String,Object>>out=new ArrayList<>();for(Envelope e:env){List<LigandFeature>a=features.stream().filter(f->matches(e.firstRole(),f.type())).toList(),b=features.stream().filter(f->matches(e.secondRole(),f.type())).toList();if(a.isEmpty()||b.isEmpty())continue;double bestViolation=Double.POSITIVE_INFINITY,best=Double.NaN;String af="",bf="";boolean pass=false;for(var x:a)for(var y:b)if(!x.id().equals(y.id())){double d=x.point().distance(y.point()),v=d<e.minimum()?e.minimum()-d:d>e.maximum()?d-e.maximum():0;if(v<bestViolation){bestViolation=v;best=d;af=x.id();bf=y.id();}if(v==0)pass=true;}if(Double.isFinite(best))out.add(Map.ofEntries(Map.entry("envelope_id",e.id()),Map.entry("first_role",e.firstRole()),Map.entry("first_residue",e.firstResidue()),Map.entry("second_role",e.secondRole()),Map.entry("second_residue",e.secondResidue()),Map.entry("minimum",e.minimum()),Map.entry("maximum",e.maximum()),Map.entry("best_distance",best),Map.entry("best_first_feature",af),Map.entry("best_second_feature",bf),Map.entry("passed",pass),Map.entry("minimum_violation",bestViolation)));}return out;}
    private static boolean matches(String role,LigandFeature.Type t){return switch(role){case"HYDROPHOBIC"->t==LigandFeature.Type.HYDROPHOBE;case"HBA"->t==LigandFeature.Type.H_BOND_ACCEPTOR;case"HBD"->t==LigandFeature.Type.H_BOND_DONOR;case"AROMATIC_OR_CATION"->t==LigandFeature.Type.PI_FEATURE||t==LigandFeature.Type.AROMATIC_RING||t==LigandFeature.Type.POSITIVE_CENTER;default->false;};}
    private static List<LigandFeature>transform(List<LigandFeature>x,totah.lab.gaia.geometry.RigidTransform t){if(t==null)return List.of();return x.stream().map(f->new LigandFeature(f.id(),f.type(),f.atomIds(),t.apply(f.point()),f.evidence())).toList();}
    private static Map<String,Object>alignment(InvariantFrameAligner.Result r){if(!r.aligned())return Map.of("aligned",false,"reason",r.reason(),"atom_ids",r.alignmentAtomIds());return Map.of("aligned",true,"rmsd",r.rmsd(),"atom_ids",r.alignmentAtomIds(),"rotation",r.transform().rotation(),"translation",r.transform().translation(),"symmetry_ambiguous",r.symmetryAmbiguous(),"cutoff_applied",false);}
    private static Map<String,Point3D>points(MolecularGraph g,Set<String>ids){Map<String,Point3D>x=new TreeMap<>();for(String id:ids)g.atom(id).map(MolecularGraph.Atom::coordinates).ifPresent(c->x.put(id,new Point3D(c.x(),c.y(),c.z())));return x;}
    private static MolecularGraph parentGraph(ExecutableScaffoldGrammar g,Map<String,Point3D>coordinates){List<MolecularGraph.Atom>atoms=g.parentGraph().atoms().stream().map(a->{Point3D p=coordinates.get(a.id());return new MolecularGraph.Atom(a.id(),a.element(),null,a.formalCharge()==null?0:a.formalCharge(),0,a.aromatic(),a.stereochemistry(),p==null?null:new MolecularGraph.Coordinates(p.x(),p.y(),p.z()),Map.of("sourceIndex",Integer.toString(a.sourceIndex())));}).toList();List<MolecularGraph.Bond>bonds=new ArrayList<>();int i=0;for(var b:g.parentGraph().bonds())bonds.add(new MolecularGraph.Bond("bond-"+(++i),b.firstAtomId(),b.secondAtomId(),MolecularGraph.BondOrder.valueOf(b.order()),b.aromatic(),b.stereochemistry(),Map.of()));return new MolecularGraph(atoms,bonds,Map.of("source","frozen-executable-parent-template"));}
    private static Map<String,Point3D>readPoseTemplate(Path path,ExecutableScaffoldGrammar g)throws IOException{List<String>lines=Files.readAllLines(path);Map<Integer,Integer>sourceToSerial=new LinkedHashMap<>();Map<Integer,Point3D>serialPoints=new LinkedHashMap<>();for(String line:lines){if(line.startsWith("ENDMDL"))break;if(line.startsWith("REMARK INDEX MAP")){String[]p=line.substring("REMARK INDEX MAP".length()).trim().split(" +");for(int i=0;i+1<p.length;i+=2)sourceToSerial.put(Integer.parseInt(p[i]),Integer.parseInt(p[i+1]));}else if(line.startsWith("ATOM")){int serial=Integer.parseInt(line.substring(6,11).trim());serialPoints.put(serial,new Point3D(Double.parseDouble(line.substring(30,38).trim()),Double.parseDouble(line.substring(38,46).trim()),Double.parseDouble(line.substring(46,54).trim())));}}Map<String,Point3D>out=new TreeMap<>();for(var atom:g.parentGraph().atoms()){Integer serial=sourceToSerial.get(atom.sourceIndex());if(serial!=null&&serialPoints.containsKey(serial))out.put(atom.id(),serialPoints.get(serial));}if(out.size()<3)throw new IOException("template correspondence failed: "+path);return out;}
    private static Map<String,String>lineage(JsonNode provenance,ExecutableScaffoldGrammar grammar,String candidate,ObjectMapper mapper,Path dir){Map<String,String>x=new LinkedHashMap<>();grammar.parentGraph().atoms().forEach(a->x.put(a.id(),a.id()));return x;}
    private static List<Map<String,Object>>aggregate(Map<String,List<Map<String,Object>>>by){List<Map<String,Object>>out=new ArrayList<>();for(var e:by.entrySet()){var rows=e.getValue();long bp=count(rows,"b_class","B_FEATURES_PRESERVED"),bq=count(rows,"b_class","B_FEATURES_PARTIAL"),bl=count(rows,"b_class","B_FEATURES_LOST"),u=count(rows,"b_class","UNEVALUABLE"),ah=count(rows,"a_class","A_COUNTER_HIGH"),am=count(rows,"a_class","A_COUNTER_MODERATE"),al=count(rows,"a_class","A_COUNTER_LOW"),mc=rows.stream().filter(r->Boolean.TRUE.equals(r.get("mmff_converged"))).count();boolean robust=bp+bq>=2&&bl==0&&u==0,reduced=am+al>=2,survivor=robust&&reduced;out.add(Map.ofEntries(Map.entry("candidate_id",e.getKey()),Map.entry("canonical_identity",rows.getFirst().get("canonical_identity")),Map.entry("conformer_count",rows.size()),Map.entry("b_preserved",bp),Map.entry("b_partial",bq),Map.entry("b_lost",bl),Map.entry("unevaluable",u),Map.entry("a_high",ah),Map.entry("a_moderate",am),Map.entry("a_low",al),Map.entry("mmff_converged",mc),Map.entry("mmff_not_converged",rows.size()-mc),Map.entry("robust_b_compatible",robust),Map.entry("reduced_a_counter",reduced),Map.entry("proposed_survivor",survivor)));}return out;}
    private static long count(List<Map<String,Object>>x,String k,String v){return x.stream().filter(r->v.equals(r.get(k))).count();}
    private static List<Map<String,Object>>rmsdAudit(List<Map<String,Object>>rows){Map<String,List<Double>>g=new LinkedHashMap<>();for(var r:rows){double d=((Number)r.get("alignment_rmsd")).doubleValue();g.computeIfAbsent(r.get("b_class").toString(),x->new ArrayList<>()).add(d);g.computeIfAbsent(r.get("a_class").toString(),x->new ArrayList<>()).add(d);g.computeIfAbsent(Boolean.TRUE.equals(r.get("mmff_converged"))?"MMFF_CONVERGED":"MMFF_NOT_CONVERGED",x->new ArrayList<>()).add(d);}List<Map<String,Object>>out=new ArrayList<>();g.forEach((k,v)->out.add(stats(k,v)));return out;}
    private static Map<String,Object>stats(String k,List<Double>v){v.sort(Double::compare);double mean=v.stream().mapToDouble(x->x).average().orElse(Double.NaN);return Map.of("group",k,"count",v.size(),"minimum",v.getFirst(),"median",v.get(v.size()/2),"mean",mean,"maximum",v.getLast());}
    private static List<Map<String,Object>>mmffAudit(List<Map<String,Object>>r){List<Map<String,Object>>o=new ArrayList<>();for(boolean c:List.of(true,false)){var x=r.stream().filter(z->Boolean.valueOf(c).equals(z.get("mmff_converged"))).toList();o.add(Map.of("mmff_converged",c,"count",x.size(),"b_preserved",count(x,"b_class","B_FEATURES_PRESERVED"),"b_partial",count(x,"b_class","B_FEATURES_PARTIAL"),"b_lost",count(x,"b_class","B_FEATURES_LOST"),"a_high",count(x,"a_class","A_COUNTER_HIGH"),"a_moderate",count(x,"a_class","A_COUNTER_MODERATE"),"a_low",count(x,"a_class","A_COUNTER_LOW")));}return o;}
    private static void writeCsv(Path p,List<String>h,List<Map<String,Object>>r)throws IOException{try(BufferedWriter w=Files.newBufferedWriter(p)){w.write(String.join(",",h));w.newLine();for(var x:r){for(int i=0;i<h.size();i++){if(i>0)w.write(',');w.write("\""+String.valueOf(x.getOrDefault(h.get(i),"")).replace("\"","\"\"")+"\"");}w.newLine();}}}
    private static String sha(byte[]b)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}
    private static void writeHashes(Path out)throws Exception{List<String>names=List.of("METTL7B_CONFORMER_FEATURE_MAPPING.json","METTL7B_CONFORMER_FEATURE_MAPPING.csv","METTL7B_CANDIDATE_B_A_PREFILTER_MATRIX.csv","METTL7B_RMSD_DISCRIMINATION_AUDIT.csv","METTL7B_MMFF_CONVERGENCE_SENSITIVITY_AUDIT.csv","METTL7B_PREFILTER_PROPOSED_SURVIVORS.csv","METTL7B_FEATURE_MAPPING_RECEIPT.json","METTL7B_FEATURE_MAPPING_AND_PREFILTER_REPORT.md");try(BufferedWriter w=Files.newBufferedWriter(out.resolve("METTL7B_FEATURE_MAPPING_SHA256SUMS"))){for(String n:names){Path p=out.resolve(n);w.write(sha(Files.readAllBytes(p))+"  "+n);w.newLine();}}}
}
