<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>totah.lab</groupId>
        <artifactId>totah-lab</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>daedalus</artifactId>

    <dependencies>
        <dependency>
            <groupId>totah.lab</groupId>
            <artifactId>gaia</artifactId>
        </dependency>
        <dependency>
            <groupId>totah.lab</groupId>
            <artifactId>hermes</artifactId>
        </dependency>
        <dependency>
            <groupId>totah.lab</groupId>
            <artifactId>euclid</artifactId>
        </dependency>
        <dependency>
            <groupId>totah.lab</groupId>
            <artifactId>hephaestus</artifactId>
        </dependency>
        <dependency>
            <groupId>totah.lab</groupId>
            <artifactId>athena</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>totah.lab</groupId>
            <artifactId>shared-resources</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.biojava</groupId>
            <artifactId>biojava-structure</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-slf4j2-impl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.7</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
