<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>totah.lab</groupId>
    <artifactId>totah-lab</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>daedalus</module>
        <module>euclid</module>
        <module>gaia</module>
        <module>athena</module>
        <module>proteus</module>
        <module>hermes</module>
        <module>hephaestus</module>
        <module>prometheus</module>
    </modules>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <lombok.version>1.18.46</lombok.version>
        <spring-boot.version>3.4.13</spring-boot.version>
        <org.biojava.version>7.2.5</org.biojava.version>
        <assertj.version>3.27.7</assertj.version>
        <junit.version>5.13.4</junit.version>
        <openpdf.version>2.0.4</openpdf.version>
        <apache-poi.version>5.5.1</apache-poi.version>
        <spring-ai.version>1.0.9</spring-ai.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.biojava</groupId>
                <artifactId>biojava-structure</artifactId>
                <version>${org.biojava.version}</version>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.github.librepdf</groupId>
                <artifactId>openpdf</artifactId>
                <version>${openpdf.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${apache-poi.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>shared-resources</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>lab-report</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>daedalus</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>gaia</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>athena</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>hermes</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>hephaestus</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>euclid</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>proteus</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>totah.lab</groupId>
                <artifactId>prometheus</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Lombok Configuration -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <version>${spring-boot.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.20.0</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-junit-jupiter</artifactId>
                <version>5.20.0</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>${spring-boot.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
