from pathlib import Path
import json
root=Path(__file__).resolve().parent
rows=[
('V13','CaBLAM','DATA_DOMAIN_SELECTION_REQUIRED',3,'Five-residue coherent source topology -> exact pseudo-dihedrals/angles -> selected complete contours -> native interpolation and thresholds','Only a motif sample was acquired. It is not an outlier distribution. Full contour set is publicly located, but context domain and complete high-dimensional evaluator/admission closure are unapproved.',None,'Select a bounded backbone context and exact complete outlier/CA grid set; acquire and oracle-pin that set before implementation.'),
('V14','RNA sugar pucker / suites','DISTINCT_PROTOCOL_CHOICES_REQUIRED',3,'RNA ribose/base/phosphate exact state -> source-linked coherent atom tuples -> either pucker geometry or seven-angle suite profile','Pucker and suite are different protocols. Pucker source performs distance-based bond selection; Athena cannot inherit it as source topology. Suitename C/Python differ near cutoffs; cluster/options/runtime and terminal/modified-state handling need explicit selection.',None,'Choose one exact pucker or suite profile; no combined universal RNA validator. Reuse geometry only after RNA source-admission is reviewed.'),
('I15','Complete metal coordination geometry','SOURCE_COMPLETENESS_CONTRACT_REQUIRED',4,'Explicit Zn/donor identities -> independently supported complete first shell including water/symmetry/competing ligands -> selected geometry model','Four nearby donors establish neither first-shell admission nor completeness. No exact authoritative shell protocol/producer selected. Pairwise P07 proximity and I15 carbonyl geometry are not complete-sphere qualification.',None,'Require a specific independently reviewed shell authority, treatment of bidentate/competing/water/symmetry states and chosen geometry comparison; no proximity-inferred closure.'),
('I17','Serious clash classification','COMPLETE_NAMED_PROTOCOL_REQUIRED',4,'Exact H preparation/convention -> radii -> nonbonded/exclusion/DA/altloc/water policy -> overlap -> selected protocol category','Probe/MolProbity >0.4 A is inseparable from its full parameter system. No complete named runtime/parameter/preparation protocol selected. Existing I16 continuous gap cannot establish a serious clash.',None,'Pin one full Probe-compatible protocol and independent oracle fixtures, including exclusions. Until then retain continuous I16 only.'),
('V19','Diffraction / refinement validation','NATIVE_VS_EXTERNAL_REPORT_DECISION',5,'Experimental data + model/state binding + refinement conventions -> native metric OR attributed report ingestion','Official XML sample acquired, but no native structure-factor/uncertainty/free-flag/evaluator closure. Report preservation already exists; parsing a number does not qualify native validation.',None,'Choose explicitly native reproduction versus bounded attributed report extraction; external report scope would not close native metrics.'),
('V20','Local X-ray map/model fit','NATIVE_VS_EXTERNAL_REPORT_DECISION',5,'Observed data/map coefficients -> frame/model alignment/scaling/masks -> exact local statistic','Official report sample is not a pinned map construction/fit protocol. Raw experimental data and exact map/scaling/selection semantics are missing.',None,'Same consolidated external-report/native decision as V19; no invented density-fit score.'),
('V21','NMR ensemble/shift/restraint validation','NATIVE_VS_EXTERNAL_REPORT_DECISION',5,'Raw shifts/restraints and assignments -> ambiguity/units/model ensemble -> named evaluation protocol','Official report sample exists; raw experimental assignments/restraints and complete selected algorithm/protocol do not. Coordinate ensemble similarity is not experimental validation.',None,'Choose report extraction or native experimental protocol; retain ambiguous/missing assignments explicitly.'),
('V22','EM map and map/model fit','NATIVE_VS_EXTERNAL_REPORT_DECISION',5,'Map/half-map/mask source identity -> sampling/frame/alignment -> selected map-only or map-model metric','Official report sample exists; full raw map/half-map/mask protocol and FSC/Q-score conventions not selected. Author-reported and validator-calculated values must remain separate.',None,'Choose report extraction or native map metric as one bounded existing-row contract.'),
('V17','Mogul empirical ligand geometry','EXTERNAL_LICENSED_ACCESS_BLOCKED',6,'Authorized exact Mogul/CSD library+runtime -> chemical-fragment applicability/sample coverage -> named empirical statistic','Public documentation is available, but authorized versioned empirical library/runtime access is unverified. Public single structures cannot substitute for the distribution.',None,'Obtain authorized library/runtime/version and usage constraints. No code or invented substitute while access is absent.')]
av=json.loads((root.parent/'foundation-v2-review-20261008/EXTERNAL_DATA_AVAILABILITY.json').read_text());lookup={r['id']:r for r in av['rows']} if 'rows' in av else {r['id']:r for r in av['entries']}
entries=[]
for id,title,status,priority,deps,blocker,review,action in rows:
 entries.append({'capabilityId':id,'title':title,'campaignStatus':status,'priorityGroup':priority,'dependencyChain':deps,'exactRemainingBlocker':blocker,'nextAction':action,'decisionPackage':review,'alreadyLocatedEvidence':lookup.get(id,{}).get('evidence',[]),'implementedInThisCampaign':False,'qualified':False})
assert len(entries)==9
j={'schema':'foundation-v2-existing-rule-closure/1','scope':'Only existing 96-capability rows; no V09/V10 expansion or new families','unfinishedRowsWithoutQualifiedScientificDomain':[r['capabilityId'] for r in entries],'entries':entries,'qualifiedRowResiduals':[{'capabilityId':'G06','definition':'ATHENA.G06.SAM_CATECHOLATE_NAC_2018_SUMMARY/1','status':'BLOCKED_SOURCE_ADMISSION','blocker':'Metal-associated catecholate state and complete source connection/coordination admission remain unresolved; water-tetrel leaf cannot supply them.','implementationAuthorized':False}],'notReopened':['V09 domain','V10 domain','G05 alternate SAM/SAH/Tyr/Trp domains','I04 broader donor domains','broader G03 domains'],'closureCriteria':'Each selected bounded contract has focused acceptance, deterministic replay and one affected Tier2 batch; unresolved choices/access remain explicitly blocked, never reported qualified. Tier3 only at v2 seal.'}
(root/'REMAINING_V2.json').write_text(json.dumps(j,indent=2)+'\n')
