package totah.lab.hephaestus.validation;

public enum ValidationCode {
    NULL_VALUE, EMPTY_STRUCTURE, EMPTY_CHAIN, EMPTY_RESIDUE,
    DUPLICATE_CHAIN_ID, DUPLICATE_RESIDUE_IDENTITY, DUPLICATE_ATOM_IDENTITY,
    NONFINITE_COORDINATE, NONFINITE_CHARGE, MISSING_AD4_TYPE,
    MISSING_TOPOLOGY, TOPOLOGY_ATOM_COUNT_MISMATCH, TOPOLOGY_INDEX_INVALID,
    MISSING_CHARGE_ASSIGNMENT, CHARGE_ATOM_COUNT_MISMATCH, CHARGE_INDEX_INVALID,
    MISSING_ATOM_TYPE_ASSIGNMENT, ATOM_TYPE_COUNT_MISMATCH, ATOM_TYPE_INDEX_INVALID,
    DUPLICATE_CANONICAL_ASSIGNMENT, STALE_ATOM_INDEX, ATOM_REFERENCE_MISMATCH,
    FLEXIBILITY_RESIDUE_MISSING, FLEXIBILITY_ANCHOR_INVALID,
    FLEXIBILITY_FRAGMENT_INVALID, FLEXIBILITY_BOND_INVALID,
    FLEXIBILITY_GRAPH_CYCLIC, FLEXIBILITY_GRAPH_DISCONNECTED,
    FLEXIBILITY_ATOM_DUPLICATE, FLEXIBILITY_PARTITION_INCOMPLETE,
    MISSING_PREPARATION_REPORT, REPORT_STATE_MISMATCH, METADATA_INCONSISTENT,
    MUTATION_TARGET_MISSING, MUTATION_WILD_TYPE_MISMATCH,
    MUTATION_BACKBONE_INCOMPLETE, MUTATION_ALT_LOC_PRESENT,
    MUTATION_EXPLICIT_COVALENT_BOND, MUTATION_AMBIGUOUS_COVALENT_TOPOLOGY,
    MUTATION_TEMPLATE_MISSING, MUTATION_GEOMETRY_INVALID
}
