-- Source-coordinate observations and versioned component-pocket geometry.

ALTER TABLE docking.assembly_component_occurrence
    ADD COLUMN IF NOT EXISTS category varchar(30),
    ADD COLUMN IF NOT EXISTS atom_count integer,
    ADD COLUMN IF NOT EXISTS heavy_atom_count integer;

CREATE TABLE IF NOT EXISTS docking.assembly_component_atom (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id bigint NOT NULL
        REFERENCES docking.assembly_component_occurrence(id) ON DELETE CASCADE,
    source_atom_id varchar(40) NOT NULL,
    atom_name varchar(20) NOT NULL,
    element varchar(5) NOT NULL,
    x double precision NOT NULL,
    y double precision NOT NULL,
    z double precision NOT NULL,
    occupancy double precision,
    b_factor double precision,
    formal_charge integer,
    alternate_location varchar(10),
    CONSTRAINT assembly_component_atom_unique
        UNIQUE (occurrence_id, source_atom_id)
);

CREATE TABLE IF NOT EXISTS docking.assembly_pocket_atom (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pocket_id bigint NOT NULL REFERENCES docking.assembly_pocket(id)
        ON DELETE CASCADE,
    source_atom_id varchar(40) NOT NULL,
    atom_name varchar(20) NOT NULL,
    element varchar(5) NOT NULL,
    auth_asym_id varchar(30) NOT NULL,
    residue_number integer NOT NULL,
    insertion_code varchar(10),
    residue_name varchar(20),
    x double precision NOT NULL,
    y double precision NOT NULL,
    z double precision NOT NULL,
    CONSTRAINT assembly_pocket_atom_unique
        UNIQUE (pocket_id, source_atom_id)
);

CREATE TABLE IF NOT EXISTS docking.component_pocket_annotation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id bigint NOT NULL
        REFERENCES docking.assembly_component_occurrence(id) ON DELETE CASCADE,
    pocket_id bigint NOT NULL REFERENCES docking.assembly_pocket(id)
        ON DELETE CASCADE,
    relationship_class varchar(30) NOT NULL,
    minimum_pocket_atom_distance double precision,
    minimum_alpha_sphere_center_distance double precision,
    minimum_alpha_sphere_surface_distance double precision,
    component_centroid_pocket_centroid_distance double precision,
    heavy_atoms_inside_sphere_cloud integer NOT NULL,
    heavy_atoms_near_sphere_cloud integer NOT NULL,
    heavy_atom_inside_fraction double precision NOT NULL,
    heavy_atom_near_fraction double precision NOT NULL,
    contacting_pocket_residues integer NOT NULL,
    method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    thresholds jsonb NOT NULL,
    run_token uuid NOT NULL,
    evaluated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT component_pocket_annotation_unique
        UNIQUE (occurrence_id, pocket_id),
    CONSTRAINT component_pocket_relationship_check CHECK
        (relationship_class IN ('OCCUPIES_POCKET', 'CONTACTS_POCKET',
                                'NEAR_POCKET', 'NOT_ASSOCIATED')),
    CONSTRAINT component_pocket_fraction_check CHECK
        (heavy_atom_inside_fraction BETWEEN 0 AND 1
         AND heavy_atom_near_fraction BETWEEN 0 AND 1)
);

ALTER TABLE docking.component_pocket_annotation
    ADD COLUMN IF NOT EXISTS run_token uuid;
UPDATE docking.component_pocket_annotation
SET run_token = gen_random_uuid()
WHERE run_token IS NULL;
ALTER TABLE docking.component_pocket_annotation
    ALTER COLUMN run_token SET NOT NULL;

CREATE INDEX IF NOT EXISTS component_atom_occurrence_idx
    ON docking.assembly_component_atom(occurrence_id);
CREATE INDEX IF NOT EXISTS pocket_atom_pocket_idx
    ON docking.assembly_pocket_atom(pocket_id);
CREATE INDEX IF NOT EXISTS component_pocket_class_idx
    ON docking.component_pocket_annotation(relationship_class);
