-- Pairwise experimental-target correspondence, separate from docking receptor cache.

CREATE TABLE IF NOT EXISTS docking.experimental_target_sequence (
    target_id bigint PRIMARY KEY REFERENCES public.targets(id) ON DELETE CASCADE,
    uniprot_accession varchar(255) NOT NULL,
    sequence text NOT NULL,
    sequence_sha256 char(64) NOT NULL,
    origin varchar(30) NOT NULL,
    method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    source_uri text NOT NULL,
    retrieved_at timestamptz NOT NULL,
    CHECK (origin='SOURCE_REPORTED'),
    CHECK (length(sequence)>0)
);

CREATE TABLE IF NOT EXISTS docking.experimental_target_sequence_source (
    target_id bigint NOT NULL REFERENCES docking.experimental_target_sequence(target_id)
        ON DELETE CASCADE,
    artifact_id bigint NOT NULL REFERENCES docking.assembly_artifact(id)
        ON DELETE RESTRICT,
    PRIMARY KEY (target_id,artifact_id)
);

CREATE TABLE IF NOT EXISTS docking.experimental_target_sequence_evaluation (
    target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE CASCADE,
    artifact_id bigint NOT NULL REFERENCES docking.assembly_artifact(id)
        ON DELETE RESTRICT,
    evaluation_status varchar(30) NOT NULL,
    availability varchar(30) NOT NULL,
    error text,
    method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    evaluated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(target_id,artifact_id),
    CHECK(evaluation_status IN ('EVALUATED','FAILED')),
    CHECK(availability IN ('EVIDENCE_PRESENT','NO_EVIDENCE','FAILED'))
);

CREATE TABLE IF NOT EXISTS docking.experimental_target_alignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE CASCADE,
    candidate_target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE CASCADE,
    identity double precision NOT NULL,
    query_coverage double precision NOT NULL,
    candidate_coverage double precision NOT NULL,
    aligned_pair_count integer NOT NULL,
    evaluation_status varchar(30) NOT NULL,
    correspondence_status varchar(30) NOT NULL,
    method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    identity_threshold double precision NOT NULL,
    coverage_threshold double precision NOT NULL,
    evaluated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(query_target_id,candidate_target_id,method_version),
    CHECK(query_target_id<candidate_target_id),
    CHECK(evaluation_status IN ('EVALUATED','FAILED')),
    CHECK(correspondence_status IN ('ACCEPTED','LOW_CONFIDENCE','FAILED'))
);

CREATE TABLE IF NOT EXISTS docking.experimental_target_alignment_pair (
    alignment_id bigint NOT NULL REFERENCES docking.experimental_target_alignment(id)
        ON DELETE CASCADE,
    query_uniprot_position integer NOT NULL,
    candidate_uniprot_position integer NOT NULL,
    query_residue char(1) NOT NULL,
    candidate_residue char(1) NOT NULL,
    substitution_score integer NOT NULL,
    query_direct_contact boolean NOT NULL,
    candidate_direct_contact boolean NOT NULL,
    query_near_shell boolean NOT NULL,
    candidate_near_shell boolean NOT NULL,
    PRIMARY KEY(alignment_id,query_uniprot_position,candidate_uniprot_position)
);

CREATE INDEX IF NOT EXISTS experimental_target_alignment_query_idx
    ON docking.experimental_target_alignment(query_target_id);
CREATE INDEX IF NOT EXISTS experimental_target_alignment_candidate_idx
    ON docking.experimental_target_alignment(candidate_target_id);
