-- Additive, ligand-centred canonical experimental binding-site layer.

CREATE TABLE IF NOT EXISTS docking.experimental_binding_site (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id bigint NOT NULL REFERENCES docking.assembly_component_occurrence(id)
        ON DELETE CASCADE,
    site_number integer NOT NULL,
    localization_status varchar(20) NOT NULL,
    ligand_centroid_x double precision NOT NULL,
    ligand_centroid_y double precision NOT NULL,
    ligand_centroid_z double precision NOT NULL,
    contributing_pocket_count integer NOT NULL,
    direct_contact_residue_count integer NOT NULL,
    near_shell_residue_count integer NOT NULL,
    covered_ligand_atom_count integer NOT NULL,
    contacted_ligand_atom_count integer NOT NULL,
    method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    grouping_rule jsonb NOT NULL,
    run_token uuid NOT NULL,
    evaluated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (occurrence_id,site_number),
    CHECK (localization_status IN ('STRONG','WEAK'))
);

CREATE TABLE IF NOT EXISTS docking.experimental_binding_site_candidate (
    occurrence_id bigint NOT NULL REFERENCES docking.assembly_component_occurrence(id)
        ON DELETE CASCADE,
    pocket_id bigint NOT NULL REFERENCES docking.assembly_pocket(id) ON DELETE CASCADE,
    site_id bigint REFERENCES docking.experimental_binding_site(id) ON DELETE CASCADE,
    disposition varchar(20) NOT NULL,
    PRIMARY KEY (occurrence_id,pocket_id),
    CHECK (disposition IN ('CONTRIBUTING','INCIDENTAL')),
    CHECK ((disposition='CONTRIBUTING' AND site_id IS NOT NULL)
        OR (disposition='INCIDENTAL' AND site_id IS NULL))
);

CREATE TABLE IF NOT EXISTS docking.experimental_binding_site_residue (
    site_id bigint NOT NULL REFERENCES docking.experimental_binding_site(id)
        ON DELETE CASCADE,
    auth_asym_id varchar(30) NOT NULL,
    residue_number integer NOT NULL,
    insertion_code varchar(10) NOT NULL DEFAULT '',
    residue_name varchar(20) NOT NULL,
    distance_band varchar(20) NOT NULL,
    PRIMARY KEY (site_id,auth_asym_id,residue_number,insertion_code,distance_band),
    CHECK (distance_band IN ('DIRECT','NEAR_SHELL'))
);

CREATE TABLE IF NOT EXISTS docking.experimental_binding_site_target (
    site_id bigint NOT NULL REFERENCES docking.experimental_binding_site(id)
        ON DELETE CASCADE,
    target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE RESTRICT,
    PRIMARY KEY (site_id,target_id)
);

CREATE TABLE IF NOT EXISTS docking.experimental_binding_site_chain (
    site_id bigint NOT NULL REFERENCES docking.experimental_binding_site(id)
        ON DELETE CASCADE,
    auth_asym_id varchar(30) NOT NULL,
    PRIMARY KEY (site_id,auth_asym_id)
);

CREATE TABLE IF NOT EXISTS docking.experimental_binding_site_ligand_atom (
    site_id bigint NOT NULL REFERENCES docking.experimental_binding_site(id)
        ON DELETE CASCADE,
    source_atom_id varchar(40) NOT NULL,
    evidence_type varchar(20) NOT NULL,
    PRIMARY KEY (site_id,source_atom_id,evidence_type),
    CHECK (evidence_type IN ('SPHERE_COVERED','PROTEIN_CONTACT'))
);

CREATE TABLE IF NOT EXISTS docking.experimental_binding_site_pocket_pair (
    occurrence_id bigint NOT NULL REFERENCES docking.assembly_component_occurrence(id)
        ON DELETE CASCADE,
    first_pocket_id bigint NOT NULL REFERENCES docking.assembly_pocket(id)
        ON DELETE CASCADE,
    second_pocket_id bigint NOT NULL REFERENCES docking.assembly_pocket(id)
        ON DELETE CASCADE,
    shared_residues integer NOT NULL,
    residue_jaccard double precision NOT NULL,
    minimum_sphere_surface_gap double precision,
    pocket_centroid_distance double precision NOT NULL,
    shared_covered_ligand_atoms integer NOT NULL,
    covered_ligand_atom_jaccard double precision NOT NULL,
    shared_contacted_ligand_atoms integer NOT NULL,
    contacted_ligand_atom_jaccard double precision NOT NULL,
    minimum_engaged_ligand_atom_distance double precision,
    same_chain_context boolean NOT NULL,
    same_human_target_context boolean NOT NULL,
    same_physical_site boolean NOT NULL,
    method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    PRIMARY KEY (occurrence_id,first_pocket_id,second_pocket_id),
    CHECK (first_pocket_id < second_pocket_id)
);

CREATE INDEX IF NOT EXISTS experimental_site_occurrence_idx
    ON docking.experimental_binding_site(occurrence_id);
CREATE INDEX IF NOT EXISTS experimental_site_target_idx
    ON docking.experimental_binding_site_target(target_id);
