-- Additive coordinate-owned persistence for experimental biological assemblies.
-- Legacy docking.structure/pocket tables remain unchanged.

CREATE TABLE IF NOT EXISTS docking.experimental_assembly (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pdb_id varchar(4) NOT NULL,
    assembly_id varchar(20) NOT NULL,
    experimental_method varchar(100),
    resolution_angstrom double precision,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT experimental_assembly_identity_unique
        UNIQUE (pdb_id, assembly_id)
);

CREATE TABLE IF NOT EXISTS docking.assembly_artifact (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_id bigint NOT NULL REFERENCES docking.experimental_assembly(id)
        ON DELETE CASCADE,
    artifact_type varchar(30) NOT NULL,
    filename varchar(255) NOT NULL,
    storage_location text NOT NULL,
    sha256 char(64),
    producer varchar(100),
    producer_version varchar(100),
    command_line text,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT assembly_artifact_location_unique
        UNIQUE (assembly_id, artifact_type, storage_location)
);

CREATE TABLE IF NOT EXISTS docking.assembly_polymer_entity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_id bigint NOT NULL REFERENCES docking.experimental_assembly(id)
        ON DELETE CASCADE,
    source_entity_id varchar(30) NOT NULL,
    description text,
    CONSTRAINT assembly_polymer_entity_unique
        UNIQUE (assembly_id, source_entity_id)
);

CREATE TABLE IF NOT EXISTS docking.assembly_polymer_chain (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polymer_entity_id bigint NOT NULL
        REFERENCES docking.assembly_polymer_entity(id) ON DELETE CASCADE,
    label_asym_id varchar(30) NOT NULL,
    auth_asym_id varchar(30),
    model_number integer NOT NULL DEFAULT 1,
    CONSTRAINT assembly_polymer_chain_unique
        UNIQUE (polymer_entity_id, label_asym_id, model_number)
);

CREATE TABLE IF NOT EXISTS docking.assembly_polymer_target (
    polymer_entity_id bigint NOT NULL
        REFERENCES docking.assembly_polymer_entity(id) ON DELETE CASCADE,
    target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE RESTRICT,
    uniprot_accession varchar(255) NOT NULL,
    mapping_provenance varchar(100) NOT NULL,
    is_human boolean,
    PRIMARY KEY (polymer_entity_id, target_id)
);

CREATE TABLE IF NOT EXISTS docking.assembly_target (
    assembly_id bigint NOT NULL REFERENCES docking.experimental_assembly(id)
        ON DELETE CASCADE,
    target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE RESTRICT,
    association_provenance varchar(100) NOT NULL,
    PRIMARY KEY (assembly_id, target_id)
);

CREATE TABLE IF NOT EXISTS docking.assembly_component_occurrence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_id bigint NOT NULL REFERENCES docking.experimental_assembly(id)
        ON DELETE CASCADE,
    component_id varchar(20) NOT NULL,
    label_asym_id varchar(30) NOT NULL,
    auth_asym_id varchar(30),
    auth_sequence_id varchar(30),
    insertion_code varchar(10),
    alternate_location varchar(10),
    model_number integer NOT NULL DEFAULT 1,
    CONSTRAINT assembly_component_occurrence_unique UNIQUE NULLS NOT DISTINCT
        (assembly_id, component_id, label_asym_id, auth_sequence_id,
         insertion_code, alternate_location, model_number)
);

CREATE TABLE IF NOT EXISTS docking.assembly_pocket (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_id bigint NOT NULL REFERENCES docking.experimental_assembly(id)
        ON DELETE CASCADE,
    artifact_id bigint NOT NULL REFERENCES docking.assembly_artifact(id)
        ON DELETE RESTRICT,
    pocket_number integer NOT NULL,
    fpocket_rank integer NOT NULL,
    score double precision,
    druggability_score double precision,
    volume double precision,
    descriptors jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT assembly_pocket_identity_unique
        UNIQUE (assembly_id, pocket_number),
    CONSTRAINT assembly_pocket_reported_rank CHECK (fpocket_rank = pocket_number)
);

CREATE TABLE IF NOT EXISTS docking.assembly_pocket_residue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pocket_id bigint NOT NULL REFERENCES docking.assembly_pocket(id)
        ON DELETE CASCADE,
    auth_asym_id varchar(30) NOT NULL,
    residue_number integer NOT NULL,
    insertion_code varchar(10),
    CONSTRAINT assembly_pocket_residue_unique UNIQUE NULLS NOT DISTINCT
        (pocket_id, auth_asym_id, residue_number, insertion_code)
);

CREATE TABLE IF NOT EXISTS docking.assembly_pocket_alpha_sphere (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pocket_id bigint NOT NULL REFERENCES docking.assembly_pocket(id)
        ON DELETE CASCADE,
    sphere_number bigint NOT NULL,
    x double precision NOT NULL,
    y double precision NOT NULL,
    z double precision NOT NULL,
    radius double precision NOT NULL,
    CONSTRAINT assembly_pocket_alpha_sphere_unique
        UNIQUE (pocket_id, sphere_number)
);

CREATE TABLE IF NOT EXISTS docking.assembly_pocket_target (
    pocket_id bigint NOT NULL REFERENCES docking.assembly_pocket(id)
        ON DELETE CASCADE,
    target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE RESTRICT,
    supporting_residue_count integer NOT NULL,
    association_method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    PRIMARY KEY (pocket_id, target_id),
    CONSTRAINT assembly_pocket_target_support_positive
        CHECK (supporting_residue_count > 0)
);

CREATE INDEX IF NOT EXISTS assembly_chain_auth_idx
    ON docking.assembly_polymer_chain(auth_asym_id);
CREATE INDEX IF NOT EXISTS assembly_pocket_residue_chain_idx
    ON docking.assembly_pocket_residue(auth_asym_id);
CREATE INDEX IF NOT EXISTS assembly_pocket_target_target_idx
    ON docking.assembly_pocket_target(target_id);
