-- Additive source-provenanced residue correspondence for experimental sites.

CREATE TABLE IF NOT EXISTS docking.assembly_residue_mapping_evaluation (
    assembly_id bigint NOT NULL
        REFERENCES docking.experimental_assembly(id) ON DELETE CASCADE,
    target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE RESTRICT,
    entry_artifact_id bigint
        REFERENCES docking.assembly_artifact(id) ON DELETE RESTRICT,
    evaluation_status varchar(30) NOT NULL,
    method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    error text,
    evaluated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (assembly_id, target_id),
    CONSTRAINT assembly_residue_mapping_evaluation_status_check CHECK
        (evaluation_status IN ('EVALUATED', 'NOT_EVALUATED',
         'NOT_APPLICABLE', 'FAILED')),
    CONSTRAINT assembly_residue_mapping_evaluation_error_check CHECK
        ((evaluation_status = 'FAILED' AND error IS NOT NULL)
         OR evaluation_status <> 'FAILED')
);

CREATE TABLE IF NOT EXISTS docking.assembly_residue_uniprot_mapping (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_id bigint NOT NULL
        REFERENCES docking.experimental_assembly(id) ON DELETE CASCADE,
    polymer_chain_id bigint
        REFERENCES docking.assembly_polymer_chain(id) ON DELETE CASCADE,
    target_id bigint NOT NULL REFERENCES public.targets(id) ON DELETE RESTRICT,
    source_artifact_id bigint NOT NULL
        REFERENCES docking.assembly_artifact(id) ON DELETE RESTRICT,
    entity_id varchar(30),
    label_asym_id varchar(30),
    auth_asym_id varchar(30) NOT NULL,
    label_sequence_id integer,
    auth_sequence_id varchar(30) NOT NULL,
    residue_number_source varchar(30) NOT NULL,
    insertion_code varchar(10) NOT NULL DEFAULT '',
    structure_residue_name varchar(10),
    uniprot_accession varchar(255) NOT NULL,
    uniprot_position integer,
    uniprot_residue_name varchar(10),
    coordinate_status varchar(30) NOT NULL,
    mapping_outcome varchar(30) NOT NULL,
    difference_details text,
    origin varchar(30) NOT NULL,
    method varchar(100) NOT NULL,
    method_version varchar(50) NOT NULL,
    CONSTRAINT assembly_residue_uniprot_mapping_unique UNIQUE
        (assembly_id, target_id, auth_asym_id, auth_sequence_id,
         insertion_code),
    CONSTRAINT assembly_residue_mapping_coordinate_status_check CHECK
        (coordinate_status IN ('RESOLVED', 'UNRESOLVED', 'UNKNOWN')),
    CONSTRAINT assembly_residue_mapping_number_source_check CHECK
        (residue_number_source IN ('AUTH_SEQ_NUM', 'PDB_SEQ_NUM', 'UNKNOWN')),
    CONSTRAINT assembly_residue_mapping_outcome_check CHECK
        (mapping_outcome IN ('MATCH', 'SUBSTITUTION', 'MODIFIED',
         'UNKNOWN', 'NOT_MAPPED', 'AMBIGUOUS')),
    CONSTRAINT assembly_residue_mapping_origin_check CHECK
        (origin IN ('SOURCE_REPORTED', 'SOURCE_OBSERVED', 'DERIVED')),
    CONSTRAINT assembly_residue_mapping_position_positive CHECK
        (uniprot_position IS NULL OR uniprot_position > 0)
);

CREATE INDEX IF NOT EXISTS assembly_residue_mapping_uniprot_idx
    ON docking.assembly_residue_uniprot_mapping
       (uniprot_accession, uniprot_position);
CREATE INDEX IF NOT EXISTS assembly_residue_mapping_structure_idx
    ON docking.assembly_residue_uniprot_mapping
       (assembly_id, auth_asym_id, auth_sequence_id, insertion_code);
