BEGIN;

-- Protein-level sequence-alignment cache for sequence-seeded pocket
-- alignment. One row per ordered receptor pair and algorithm version:
-- the direction is meaningful (query -> candidate pairs), the reverse
-- direction is a separate row. Computed by Athena's
-- NeedlemanWunschSequenceAligner (match +2, mismatch -1, gap -2) from
-- the receptors' structure artifacts and persisted by
-- ProteinSequenceAlignmentService on first use; algorithm_version
-- stamps the row so stale rows can be detected after an aligner
-- change (1 = Needleman-Wunsch v1).
CREATE TABLE IF NOT EXISTS docking.protein_sequence_alignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_receptor_id BIGINT NOT NULL,
    candidate_receptor_id BIGINT NOT NULL,
    identity DOUBLE PRECISION NOT NULL,
    algorithm_version INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT protein_sequence_alignment_pair_unique
        UNIQUE (query_receptor_id, candidate_receptor_id,
                algorithm_version)
);

-- Aligned (non-gapped) residue pairs of one cached alignment, in no
-- particular order; the aligner consumes them as a mapping.
CREATE TABLE IF NOT EXISTS docking.protein_sequence_alignment_pair (
    alignment_id BIGINT NOT NULL
        REFERENCES docking.protein_sequence_alignment (id)
        ON DELETE CASCADE,
    query_residue_number INTEGER NOT NULL,
    candidate_residue_number INTEGER NOT NULL,
    query_residue_name VARCHAR(3),
    candidate_residue_name VARCHAR(3),

    CONSTRAINT protein_sequence_alignment_row_unique
        UNIQUE (alignment_id, query_residue_number,
                candidate_residue_number)
);

COMMIT;
