BEGIN;

CREATE UNIQUE INDEX IF NOT EXISTS residue_structure_id_id_uk
    ON docking.residue (structure_id, id);

CREATE TABLE IF NOT EXISTS docking.residue_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id BIGINT NOT NULL,
    residue_id BIGINT NOT NULL,
    artifact_id BIGINT NOT NULL,
    analysis_type VARCHAR(64) NOT NULL,
    score DOUBLE PRECISION,
    rank INTEGER,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT residue_analysis_rank_check
        CHECK (rank IS NULL OR rank > 0),

    CONSTRAINT residue_analysis_residue_fk
        FOREIGN KEY (structure_id, residue_id)
        REFERENCES docking.residue (structure_id, id)
        ON DELETE CASCADE,

    CONSTRAINT residue_analysis_artifact_fk
        FOREIGN KEY (artifact_id)
        REFERENCES docking.artifacts (id)
        ON DELETE RESTRICT,

    CONSTRAINT residue_analysis_identity_unique
        UNIQUE (
            structure_id,
            residue_id,
            artifact_id,
            analysis_type
        )
);

CREATE INDEX IF NOT EXISTS residue_analysis_structure_type_idx
    ON docking.residue_analysis (structure_id, analysis_type);

CREATE INDEX IF NOT EXISTS residue_analysis_structure_type_score_idx
    ON docking.residue_analysis (
        structure_id,
        analysis_type,
        score DESC
    );

CREATE INDEX IF NOT EXISTS residue_analysis_artifact_idx
    ON docking.residue_analysis (artifact_id);

COMMENT ON TABLE docking.residue_analysis IS
    'Artifact-backed computed evidence for a residue in a specific structure.';

COMMENT ON COLUMN docking.residue_analysis.analysis_type IS
    'Stable discriminator for the analysis, such as ESMC_CONSTRAINT.';

COMMENT ON COLUMN docking.residue_analysis.score IS
    'Primary sortable value for the analysis type.';

COMMENT ON COLUMN docking.residue_analysis.metrics IS
    'Analysis-specific values that do not justify schema changes.';

COMMIT;
