package totah.lab.hermes.file.pdbqt.validation;

public enum PdbqtValidationCode {
    NULL_INPUT, FILE_EMPTY, UNSUPPORTED_RECORD, MALFORMED_RECORD,
    INVALID_SERIAL, DUPLICATE_SERIAL, INVALID_COORDINATE, INVALID_CHARGE,
    MISSING_AD4_TYPE, DUPLICATE_ATOM, MISSING_ATOM, PARTITION_INCOMPLETE,
    DUPLICATE_FRAGMENT, UNKNOWN_FRAGMENT, INVALID_ANCHOR,
    ROOT_UNBALANCED, BRANCH_UNBALANCED, BRANCH_REFERENCE_MISSING,
    BRANCH_GRAPH_CYCLIC, TORSDOF_MISMATCH, RIGID_FLEXIBLE_OVERLAP
}
