package totah.lab.prometheus.variational.force;

import static org.junit.jupiter.api.Assertions.*;
import java.util.List;
import org.junit.jupiter.api.Test;
import totah.lab.prometheus.molecular.*;
import totah.lab.prometheus.neural.GeneralSlaterJastrowState;
import totah.lab.prometheus.variational.GeneralMolecularSampleSource;
import totah.lab.prometheus.variational.QuantumCoordinates;
import totah.lab.prometheus.variational.SpinProjection;

final class GeneralAnalyticDifferentialSwctForceEstimatorTest {
    @Test void allCartesianComponentsMatchIndependentCentralDifference(){Fixture f=fixture(false,false);var analytic=new GeneralAnalyticDifferentialSwctForceEstimator().evaluate(f.state,f.source);var numerical=new GeneralMolecularSwctFiniteDifferenceOracle().evaluate(f.state,f.source,1e-5);assertEquals(2,analytic.forces().size());for(int a=0;a<2;a++){assertEquals(numerical.forces().get(a).fx(),analytic.forces().get(a).fx(),2e-7);assertEquals(numerical.forces().get(a).fy(),analytic.forces().get(a).fy(),2e-7);assertEquals(numerical.forces().get(a).fz(),analytic.forces().get(a).fz(),2e-7);}assertEquals(16,analytic.stateTraversals());assertEquals(16,analytic.localEnergyEvaluations());assertEquals(16,analytic.directionalAdPasses());assertEquals(192,numerical.stateTraversals());assertEquals("hartree/bohr",analytic.forceUnit());}
    @Test void isolatedDiatomicObeysTranslationTorqueAndTransverseSymmetry(){Fixture f=fixture(false,false);var r=new GeneralAnalyticDifferentialSwctForceEstimator().evaluate(f.state,f.source);var a=r.forces().get(0);var b=r.forces().get(1);assertEquals(0,a.fx()+b.fx(),2e-12,"sum fx");assertEquals(0,a.fy()+b.fy(),2e-12,"sum fy");assertEquals(0,a.fz()+b.fz(),2e-12,"sum fz");assertEquals(0,a.fx(),2e-12,"a fx");assertEquals(0,a.fy(),2e-12,"a fy");assertEquals(0,b.fx(),2e-12,"b fx");assertEquals(0,b.fy(),2e-12,"b fy");}
    @Test void equivalentNuclearPermutationAndRotationTransformCanonicalVector(){var normal=new GeneralAnalyticDifferentialSwctForceEstimator().evaluate(fixture(false,false).state,fixture(false,false).source);Fixture permuted=fixture(true,false);var swapped=new GeneralAnalyticDifferentialSwctForceEstimator().evaluate(permuted.state,permuted.source);assertEquals(normal.forces().get(0).fz(),swapped.forces().get(1).fz(),2e-12);assertEquals(normal.forces().get(1).fz(),swapped.forces().get(0).fz(),2e-12);Fixture rotated=fixture(false,true);var rr=new GeneralAnalyticDifferentialSwctForceEstimator().evaluate(rotated.state,rotated.source);assertEquals(normal.forces().get(0).fz(),rr.forces().get(0).fx(),2e-12);assertEquals(normal.forces().get(1).fz(),rr.forces().get(1).fx(),2e-12);}
    @Test void deterministicReplayIsBitwiseAndSingleNucleusForceIsZero(){Fixture f=fixture(false,false);var estimator=new GeneralAnalyticDifferentialSwctForceEstimator();var a=estimator.evaluate(f.state,f.source);var b=estimator.evaluate(f.state,f.source);for(int i=0;i<2;i++){assertEquals(Double.doubleToRawLongBits(a.forces().get(i).fx()),Double.doubleToRawLongBits(b.forces().get(i).fx()));assertEquals(Double.doubleToRawLongBits(a.forces().get(i).fy()),Double.doubleToRawLongBits(b.forces().get(i).fy()));assertEquals(Double.doubleToRawLongBits(a.forces().get(i).fz()),Double.doubleToRawLongBits(b.forces().get(i).fz()));}Molecule h=new Molecule("H",List.of(n(0,0,0,0)),new MolecularCharge(0),new ElectronCount(1),new SpinSector(1,0,2));var hs=GeneralSlaterJastrowState.cuspInitialized(h);GeneralMolecularSampleSource source=c->c.accept(1,new QuantumCoordinates(List.of(new QuantumCoordinates.ParticleCoordinate(0,.7,.2,-.1,SpinProjection.ALPHA))));var hf=estimator.evaluate(hs,source).forces().getFirst();assertEquals(0,hf.fx(),0);assertEquals(0,hf.fy(),0);assertEquals(0,hf.fz(),0);}
    private static Fixture fixture(boolean swapNuclei,boolean rotate){double r=.7;List<NuclearCenter> nuclei=swapNuclei?List.of(n(0,0,0,r),n(1,0,0,-r)):List.of(n(0,0,0,-r),n(1,0,0,r));if(rotate)nuclei=nuclei.stream().map(x->{var p=x.position();return n(x.orderedIndex(),p.z(),0,0);}).toList();Molecule molecule=new Molecule("H2-force",nuclei,new MolecularCharge(0),new ElectronCount(2),new SpinSector(1,1,1));List<double[]> base=List.of(new double[]{.35,.20,.40,-.45,-.15,-.30},new double[]{-.35,-.20,-.40,.45,.15,.30},new double[]{.60,-.25,-.10,-.55,.30,.15},new double[]{-.60,.25,.10,.55,-.30,-.15});List<QuantumCoordinates> points=new java.util.ArrayList<>();for(double[] v:base)for(int turn=0;turn<4;turn++){double angle=turn*Math.PI/2,c=Math.cos(angle),s=Math.sin(angle);double x1=c*v[0]-s*v[1],y1=s*v[0]+c*v[1],x2=c*v[3]-s*v[4],y2=s*v[3]+c*v[4];points.add(q(x1,y1,v[2],x2,y2,v[5],rotate));}GeneralMolecularSampleSource source=consumer->{for(var p:points)consumer.accept(1,p);};return new Fixture(GeneralSlaterJastrowState.cuspInitialized(molecule),source);}
    private static NuclearCenter n(int i,double x,double y,double z){return new NuclearCenter(i,"H",new NuclearCharge(1),new CartesianPosition(x,y,z,LengthUnit.BOHR));}
    private static QuantumCoordinates q(double x1,double y1,double z1,double x2,double y2,double z2,boolean rotate){if(rotate)return q(z1,y1,-x1,z2,y2,-x2,false);return new QuantumCoordinates(List.of(new QuantumCoordinates.ParticleCoordinate(0,x1,y1,z1,SpinProjection.ALPHA),new QuantumCoordinates.ParticleCoordinate(1,x2,y2,z2,SpinProjection.BETA)));}
    private record Fixture(GeneralSlaterJastrowState state,GeneralMolecularSampleSource source){}
}
